### ISSUE TITLE
Complete Code Coverage for View Models

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1001]
The Talawa code base needs to be 100% reliable. This means we need to have We 100% unittest code coverage. This is a parent issue for all View Model unittest issues.

We will be creating one issue per related file with the expectation that widgets referenced in these files must also have unittests.
- We'll only assign the child issues. 
- Please comment on one of the child issues for assignment.
- Only one child issue will be assigned to a person at any one time.

Parent Issue:
- https://github.com/PalisadoesFoundation/talawa/issues/1124

Child Issues:
- https://github.com/PalisadoesFoundation/talawa/issues/1002
- https://github.com/PalisadoesFoundation/talawa/issues/1003
- https://github.com/PalisadoesFoundation/talawa/issues/1023
- https://github.com/PalisadoesFoundation/talawa/issues/1018
- https://github.com/PalisadoesFoundation/talawa/issues/1119

**Comment by M-A-D-A-R-A** [comment]
Hey , I would like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment]
@M-A-D-A-R-A We'll only assign the child issues. Please comment on one of the child issues for assignment. Only one child issue will be assigned to a person at any one time.

**Comment by palisadoes** [comment]
All child issues are closed.
