### ISSUE TITLE
Complete Code Coverage for Pre-Auth View Models

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1002]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage. This is a parent issue for all Pre-Auth View Model unittest issues.

We will be creating one issue per related file with the expectation that widgets referenced in these files must also have unittests.
- We'll only assign the child issues. 
- Please comment on one of the child issues for assignment.
- Only one child issue will be assigned to a person at any one time.

**Note:** 5 additional points will be assigned to any potential internship applicants who completes all the child issues.

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1001

Child Issues:
- https://github.com/PalisadoesFoundation/talawa/issues/1004
- https://github.com/PalisadoesFoundation/talawa/issues/1005
- https://github.com/PalisadoesFoundation/talawa/issues/1006
- https://github.com/PalisadoesFoundation/talawa/issues/1007
- https://github.com/PalisadoesFoundation/talawa/issues/1008

**Comment by CyberWake** [comment]
@palisadoes please assign this one to me. I'll like to work on it.

**Comment by palisadoes** [comment]
@CyberWake please work on the individual issues for assignment. One at at time. We want to make sure everyone gets a chance.
