### ISSUE TITLE
Unittests for signup_details_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1006]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/signup_details_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by ahluwaliatikant** [comment]
@palisadoes I would like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment]
@ahluwaliatikant Why is it that your tests do not import [signup_details_view_model.dart](https://github.com/PalisadoesFoundation/talawa/blob/develop/lib/view_model/pre_auth_view_models/signup_details_view_model.dart)?

The [Code Coverage report](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/view_model/pre_auth_view_models/signup_details_view_model.dart) shows that the methods, classes and functions in the file have no coverage at all.

I'm going to reopen this issue. It has not been completed correctly.

**Comment by ahluwaliatikant** [comment]
@palisadoes Actually I used mockito's code generation to generate mocks for the class and then used stubbing to test those functions.
If some mentor could point out whatever is wrong and help me a bit, I am willing to learn and make the necessary changes.

**Comment by ahluwaliatikant** [comment]
@palisadoes Basically, I need someone to just help me understand how to test functions that interact with the API.
The approach I followed was to create mocks for them and then use stubbing.

**Comment by palisadoes** [comment]
Please ask Rutvik Chandla @rutvik11062000 on Slack. He should be able to guide you.

**Comment by RandyKdev** [comment]
Hi @palisadoes, I would like to work on this issue.

**Comment by palisadoes** [comment]
@RandyKdev Please get the code coverage on this file up to 100%. The PR shows only 92%. 

- https://app.codecov.io/gh/PalisadoesFoundation/talawa/compare/1219/changes

I'm reopening this issue. Thanks for the work, only a little more to go.

**Comment by RandyKdev** [comment]
@palisadoes The current code coverage for this file, `signup_details_view_model.dart` is 100%. Here is the link

https://app.codecov.io/gh/PalisadoesFoundation/talawa/compare/1290/changes

**Comment by palisadoes** [comment]
Thanks. Closing. Please take a look at any of the other view_model tests. We have almost completed them all.

**Comment by RandyKdev** [comment]
Ok, I will.
