### ISSUE TITLE
Unittests for login_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1007]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/login_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by nirala96** [comment]
I am willing to work on this issue. Can you pls assign me?

**Comment by palisadoes** [comment]
Reassigning it's been over 3 weeks.

**Comment by guptapriyanshu7** [comment]
@palisadoes I would like to work on this.

**Comment by palisadoes** [comment]
Reopening as the tests do not cover the new Firebase functionality. Coverage is low

**Comment by ALIRAZA17** [comment]
@palisadoes I would like to work on this. Please assign.

**Comment by palisadoes** [comment]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ALIRAZA17** [comment]
@noman2002 can you please assign this issue to me?

**Comment by noman2002** [comment]
@ALIRAZA17 Assigned you 2 issues. Please work on them and try to get the coverage to 100%. Thank you.

**Comment by noman2002** [comment]
@ALIRAZA17 Any progress on this one ?

**Comment by ALIRAZA17** [comment]
@noman2002 on it!!

**Comment by droy312** [comment]
Can I work on this issue?

**Comment by noman2002** [comment]
@droy312 Any update ?

**Comment by droy312** [comment]
Yes working in it. Submitted a PR related to another issue. Waiting for it's merge.

**Comment by palisadoes** [comment]
Unassigning due to inactivity. We need to give others a chance.

**Comment by chiragtyagi2003** [comment]
@Olatade Some tests are already present in the file.

**Comment by chiragtyagi2003** [comment]
@Olatade I have added some new tests, kindly review.

**Comment by palisadoes** [comment]
Unassigning due to inactivity
