### ISSUE TITLE
Unittests for set_url_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1008]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
pre_auth_view_models/set_url_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1002

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/pre_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by guptapriyanshu7** [comment]
@palisadoes I would like to work on this.
