### ISSUE TITLE
Unittests for organization_feed_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1009]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/feed_view_models/organization_feed_view_model.dart
```

This file can be found in the `lib/view_model` directory

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by guptapriyanshu7** [comment]
@palisadoes I would like to work on this.

**Comment by palisadoes** [comment]
Reopening as the code coverage for this file has fallen

**Comment by Aankirz** [comment]
Hey @palisadoes sir I would like to work in this issue, can u pls assign it to me?

**Comment by noman2002** [comment]
@Aankirz Any update ?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by ilakshaygupt** [comment]
Can you please assign me this issue ?

**Comment by Yousef-Rabia** [comment]
@palisadoes I would like to work on this.

**Comment by Cioppolo14** [comment]
@Yousef-Rabia I have assigned you.  Please tag me or another assigner, instead of palisadoes for future assignment requests.
