### ISSUE TITLE
Unittests for create_event_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1010]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/event_view_models/create_event_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1023

**Comment by ahluwaliatikant** [comment]
@palisadoes Please assign this issue to me.

**Comment by palisadoes** [comment]
- This isn't complete the [file shows only 31% code coverage](https://app.codecov.io/gh/PalisadoesFoundation/talawa) instead of 100%
- Reopening
