### ISSUE TITLE
Unittests for explore_events_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1011]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/event_view_models/explore_events_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1023
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/event_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by ItsAdityaKSingh** [comment]
@palisadoes Should I try resolving this?

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by ItsAdityaKSingh** [comment]
Yes, I would like to work on this. I started learning about tests but then got involved in academics and other projects and couldn't catch up. So, if you wish, you could unassign, but I would try to complete it and make a PR as soon as possible.

**Comment by ahluwaliatikant** [comment]
@palisadoes I would like to work on this. Please assign it to me.
