### ISSUE TITLE
Unittests for edit_event_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1012]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/event_view_models/edit_event_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1023
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/event_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by BolisettySujith** [comment]
I would like to work on this issue, can u pls assign it to me?

**Comment by palisadoes** [comment]
@BolisettySujith Are you still working on this?

**Comment by BolisettySujith** [comment]
Yes, I will make one PR as soon as possible.

**Comment by palisadoes** [comment]
Are you still working on this? It's been over a month

**Comment by guptapriyanshu7** [comment]
@palisadoes please assign me to this.
