### ISSUE TITLE
Unittests for edit_profile_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1013]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/profile_view_models/edit_profile_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1023
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/profile_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by rahuldadz** [comment]
Please assign this issue to me !

**Comment by palisadoes** [comment]
@rahuldadz Are you still working on this?

**Comment by guptapriyanshu7** [comment]
@palisadoes I would like to work on this.

**Comment by Cioppolo14** [comment]
Closing this issue as coverage is now 100%.
