### ISSUE TITLE
Unittests for profile_page_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1014]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/profile_view_models/profile_page_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue:
- https://github.com/PalisadoesFoundation/talawa/issues/1023
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/profile_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by AvneetSingh2001** [comment]
I would like to work on this. Kindly Assign me.

**Comment by palisadoes** [comment]
@AvneetSingh2001 Are you still working on this?

**Comment by AvneetSingh2001** [comment]
yes @palisadoes , i am on it.

**Comment by ItsAdityaKSingh** [comment]
@AvneetSingh2001 Are you working on this issue?

**Comment by palisadoes** [comment]
Are you still working on this? It's been over a month.

**Comment by palisadoes** [comment]
Unassigning as it's been over a month.

**Comment by palisadoes** [comment]
@ItsAdityaKSingh Do you still want to work on this?

**Comment by ItsAdityaKSingh** [comment]
@palisadoes, I would like to resolve my assigned issue first and then move on to the others. I'll convey it so. Thanks for asking :)

**Comment by ahluwaliatikant** [comment]
@palisadoes, I would like to work on this. Please assign it to me.

**Comment by palisadoes** [comment]
@ahluwaliatikant  Are you still working on this?

**Comment by ahluwaliatikant** [comment]
Yes Sir @palisadoes . Got stuck at a test for one of the functions. Will try to fix that and raise a PR soon.
