### ISSUE TITLE
Unittests for lru_cache.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1015]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/chat_view_models/lru_cache.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

**Comment by nishnatadebnath** [comment]
Please assign this to me.

**Comment by nishnatadebnath** [comment]
@CyberWake I have some doubt regarding the logic used for the `/after_auth_view_models/chat_view_models/lru_cache.dart
`.
So while testing it I found out that we are initializing the LRUChatListCache  using the following constructer.

`  LRUChatListCache() {
    cache = <String, ChatListNode>{};

    head = ChatListNode();

    tail = ChatListNode();

    head.next = tail;

    tail.prev = head;
  }
`
So now my doubt is shouldn't we initialise the `head and tail` pointing to the same `chatListNode` at first addition of a chat,again if there is no chat we shouldn't be having those initializations and `head and tail` should point to `null`.

**Comment by nishnatadebnath** [comment]
@palisadoes  the `lru_cache.dart` code logic is bugged ,can I make changes to the code so that it works properly along with the unit testing?

**Comment by palisadoes** [comment]
Yes

**Comment by palisadoes** [comment]
@nishnatadebnath Are you still working on this?

**Comment by nishnatadebnath** [comment]
Yes . Sorry for the delay @palisadoes , shifting to college hostel I will complete it by 24 hr.
