### ISSUE TITLE
Unittests for direct_chat_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1016]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/chat_view_models/direct_chat_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

**Comment by SriramPatibanda** [comment]
I'm willing to work on this issue. Please assign this to me if possible.

**Comment by palisadoes** [comment]
@SriramPatibanda Are you still working on this?

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda Are you still working on this?

Yes, I've almost completed writing the test. I was blocked at a place and I'm trying to figure out the solution for it.
