### ISSUE TITLE
Unittests for progress_dialog_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1019]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/progress_dialog_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018

**Comment by SriramPatibanda** [comment]
@palisadoes I want to work on this issue. Can you please assign this to me?
