### ISSUE TITLE
Table calendar not working 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#102]
![Capture](https://user-images.githubusercontent.com/55004621/110757702-b1c00980-8271-11eb-877c-b3cd31c37635.JPG)
as you can see the table calendar is not working i would like to work on it along with the change in the UI

**Comment by sumitra19jha** [comment]
Hi @yasharth291 
This issue has already been addressed #89

**Comment by yasharth291** [comment]
oh ok
