### ISSUE TITLE
Unittests for like_button_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1020]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/like_button_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by saraljain12** [comment]
Hey, I am ready to take on this kindly tell me more about it and assign it to me

**Comment by palisadoes** [comment]
Thanks @saraljain12. This is an important task. We need to get our code test coverage to be much better. 

1. Check this link on [how to create Flutter Unit Tests](https://docs.flutter.dev/cookbook/testing/unit/introduction) for more details. 
1. Put your tests in the [test/](https://github.com/PalisadoesFoundation/talawa/tree/develop/test) directory. Check the files there for examples on how to proceed.
1. Contact @CyberWake, @rutvik11062000 and/or @sumitra19jha for guidance. They will have suggestions on the directory structure to use and more

**Comment by CyberWake** [comment]
Let me know is you need some help dm me on slack if needed.

**Comment by saraljain12** [comment]
Thanks, sure. Kindly give me the slack link
and also  demo organization for logging in to app

**Comment by CyberWake** [comment]
@Ritik Kumar Srivastava my user name or find by my mail ritikfbd@gmail.com

**Comment by aashimawadhwa** [comment]
> Let me know is you need some help dm me on slack if needed.

can u provide me the link of slack channel ?

**Comment by palisadoes** [comment]
> > Let me know is you need some help dm me on slack if needed.
> 
> can u provide me the link of slack channel ?

http://slack.palisadoes.org/

**Comment by palisadoes** [comment]
@saraljain12 Are you still working on this?

**Comment by palisadoes** [comment]
- The code coverage report only shows [68% code coverage for this file](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models). We need 100%
- Reopening

**Comment by ahluwaliatikant** [comment]
@palisadoes, I would like to work on this. Please assign it to me.
