### ISSUE TITLE
Unittests for custom_drawer_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1021]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/custom_drawer_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by nishnatadebnath** [comment]
According to some of the test done in the project,most of them are performing widget testing ,so for this one also we have to check if all the widgets are working as required,or unit testing is something completely different?

**Comment by palisadoes** [comment]
Any widgets referenced in this file, that don't already have unittests, must also have unittests done.

**Comment by nishnatadebnath** [comment]
Ya I will get the unit tests done but overall I will have to get the wdiget for the custom_drawer also tested for widget testing ,Right?

**Comment by palisadoes** [comment]
Yes

**Comment by nishnatadebnath** [comment]
Can I take up this issue?

**Comment by palisadoes** [comment]
- This file shows only [80% code coverage in the reporting.](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models) We need 100%
- Reopening

**Comment by architsangal** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
@architsangal Are you still working on this?

**Comment by architsangal** [comment]
Yeah. I had university exams, so I had to take a break.

**Comment by palisadoes** [comment]
@architsangal Are you still working on this?

**Comment by architsangal** [comment]
I think we can close this issue. For 'custom_drawer_view_model.dart' code coverage 100%.

**Comment by palisadoes** [comment]
We need to get the coverage to 100%

**Comment by nidhin29** [comment]
@noman2002 Sir,can I work on this issue
