### ISSUE TITLE
Unittests for comments_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1022]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/comments_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by Simran1604** [comment]
I am willing to work on this issue. Can you pls assign me?

**Comment by palisadoes** [comment]
@Simran1604 are you still working on this?

**Comment by Simran1604** [comment]
Yes, Sir, my college re-opened suddenly for physical classes so got caught up with that. I Will solve this issue soon.

**Comment by palisadoes** [comment]
- [This file shows 0% code coverage in the reporting](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models). We need to get to 100%
- Reopening.

**Comment by ahluwaliatikant** [comment]
@palisadoes, I would like to work on this issue. Please assign it to me.
