### ISSUE TITLE
[Enhancement] Not proper comments to understand the code

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#103]
I would like to work on it and make the project look more readable along with the changes in UI can you please assign me this

**Comment by yasharth291** [comment]
can you please assign me this

**Comment by yasharth291** [comment]
@heyjordn @jordanliu

**Comment by DeltaHarbinger** [comment]
Hey @yasharth291, for this issue, will you be focused on adding comments to already existing code? Please clarify before I assign this to you

**Comment by yasharth291** [comment]
yeah 
i will add comments

**Comment by DeltaHarbinger** [comment]
Alright, go ahead. But be sure to pull the most recent version of master before working
