### ISSUE TITLE
[Terminological error]  Misplaced description in `set_url_page_test.dart`

### ISSUE THREAD

**Issue by Simran1604** [PalisadoesFoundation/talawa#1031]
**Describe the bug**
While checking out the test files, I found a bug. Here it is "Testing if login button works" while it should be for the signup button.
**To Reproduce**

1. Open test/widget_tests/pre_auth_screens/set_url_page_test.dart
2. find the bug in lines 277 and 488

**Screenshots**
![Screenshot (120)](https://user-images.githubusercontent.com/72657303/145249384-76583da1-1c24-4266-95bd-3b0c7c859657.jpg)

**Additional details**
I would like to work on the issue @palisadoes pls assign me.

**Comment by palisadoes** [comment]
@Simran1604 Is the fix, just changing the text on line 488?

**Comment by Simran1604** [comment]
Yes

**Comment by palisadoes** [comment]
OK
