### ISSUE TITLE
first-interaction action check fails due to deprecated workflow event

### ISSUE THREAD

**Issue by SriramPatibanda** [PalisadoesFoundation/talawa#1036]
**Describe the bug**
The first time interaction GitHub action doesn't work.

**To Reproduce**

When a user submits a PR for the first time in talawa, the first interaction action fails.

**Expected behavior**
The GitHub action checks must pass on pull request from a new contributor

**Actual behavior**
The GitHub action checks fail due to lack of required permissions.

**Screenshots**
N.A.

**Proposed Solution**
GitHub has solved this issue. Reference : https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

In the workflows, one simply needs to change the  the event from ```pull_request ``` to ```pull_request_target```.

**Comment by palisadoes** [comment]
@SriramPatibanda This has worked for other first time contributors for months, including PRs this week. This page doesn't specifically identify first time contributors. Are you sure of this bug?

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda This has worked for other first time contributors for months, including PRs this week. This page doesn't specifically identify first time contributors. Are you sure of this bug?

Yes @palisadoes , I'm sure that ```pull_request``` event doesn't work when secrets are being used. Even the other PR's by first time contributors are failing due to this example, #996, you can check them yourself.

**Comment by sumitra19jha** [comment]
@palisadoes I also noticed the pull request workflow for first time contributor do have some issues. @SriramPatibanda Do you want to work on this?

**Comment by SriramPatibanda** [comment]
> @palisadoes I also noticed the pull request workflow for first time contributor do have some issues. @SriramPatibanda Do you want to work on this?

Would love to

**Comment by sumitra19jha** [comment]
Also please change the title of this issue, and make it more meaningful

**Comment by SriramPatibanda** [comment]
@sumitra19jha , I would like to bring to your notice that some actions checks were failing for this PR that I sent: #1034. When I checked the issue, I understood that there are 8 files where imports were done that weren't required. (both material and cupertino packages were imported) and that's the reason, linting errors were shown. As Peter asked me to check why the checks weren't passing and solve them, I had done the required. So, should I think I've to fix the files for this PR itself so that all the actions pass for the PR, or would you first review and merge #1034 so that it gets fixed.

**Comment by sumitra19jha** [comment]
Can you share the Snap of failed Workflow?

**Comment by SriramPatibanda** [comment]
> Can you share the Snap of failed Workflow?

![Screenshot_20211210-234507.png](https://user-images.githubusercontent.com/56649197/145622142-d66b180a-3ccb-41b3-a75f-575d58daf7b4.png)

**Comment by sumitra19jha** [comment]
Great!!! This will be resolved then while merging those PRs. I think there is one more issue with the Greetings, please look into that also.

**Comment by SriramPatibanda** [comment]
> Great!!! This will be resolved then while merging those PRs. I think there is one more issue with the Greetings, please look into that also.

Apart from ```pull_request``` event deprecation, there is some other issue you mean?

**Comment by palisadoes** [comment]
@SriramPatibanda  Your PR fixed the first time PR run issue, however we are failing actions as the `flutter analyze --no-pub` is failing. Please run `flutter analyze --no-pub` on the code base, fix the linting problem and submit a PR under this issue

**Comment by palisadoes** [comment]
I just realized that we need to merge this PR first, which I failed to do. I'll see  who can approve it.

- https://github.com/PalisadoesFoundation/talawa/pull/1034
