### ISSUE TITLE
Parts of the app can't be accessed in some devices as they touch operating system interfaces

### ISSUE THREAD

**Issue by SriramPatibanda** [PalisadoesFoundation/talawa#1038]
**Describe the bug**

The buttons and content at the boundaries of the app in select language screen can't be accessed as they touch operating system interfaces. 

**To Reproduce**

Opening the app in devices without a notch display reproduces this behavior.

**Expected behavior**
The whole interface of the app must be within the phone boundaries(SafeArea) so that every button is accessible. 

**Actual behavior**
The app's content at the boundaries of the device can't be accessed.

**Screenshots**
![Screenshot_20211213-130225](https://user-images.githubusercontent.com/56649197/145771489-32101871-79c5-4d7f-b7af-c2b636c97c97.png)

**Additional details**
N.A.

**Comment by SriramPatibanda** [comment]
Though Padding was given using SizeConfig, it's not getting initialized sometimes and this problem is faced in the Select Language page especially. I think wrapping the Scaffold with SafeArea must be a more preferable and recommended solution for this problem.

**Comment by CyberWake** [comment]
@SriramPatibanda can you tell in which scenarios do the sizeConfig is not initialized. Because that is strange this will make the whole application's UI crumble up.

**Comment by SriramPatibanda** [comment]
> @SriramPatibanda can you tell in which scenarios do the sizeConfig is not initialized. Because that is strange this will make the whole application's UI crumble up.

I'm not able to reproduce this bug again, but suddenly sometimes size config didn't get initialised and that's when I had faced this issue. And after navigating to the next page or hot reloading it, it was getting initialised.

**Comment by CyberWake** [comment]
Share a demo of the happening since this isn't possible AFAIK. And wrapping widgets in safe area for no sake doesn't make sense. Would be better if you could exactly tell the scenario.
