### ISSUE TITLE
No Response for non-existing Url

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#104]
### Description
No response from snackbar in case of non-existing(non-registered) url.
The exception has not been handled properly.

![Screenshot 2021-03-11 at 1 55 41 PM](https://user-images.githubusercontent.com/35868598/110758707-d36dc080-8272-11eb-91c1-4ad853a498fb.png)

### Steps to produce the Issue:
1. Open App.
2. Type any non-existing URL of your choice.
3. The Input will be accepted and now you are asked for signup/login.
4. Select any option and press signup/login button.
5. Error will be displayed.

**Comment by sumitra19jha** [comment]
I would like to work on this issue.
https://user-images.githubusercontent.com/35868598/110759341-82aa9780-8273-11eb-9212-0d5e4afcbc58.mp4

**Comment by sumitra19jha** [comment]
https://user-images.githubusercontent.com/35868598/110759604-cdc4aa80-8273-11eb-8a2b-faf7eb33aa9b.mp4

**Comment by DeltaHarbinger** [comment]
Hey @sumitra19jha, you can go ahead and work on this issue

**Comment by sumitra19jha** [comment]
Sure @DeltaHarbinger

**Comment by sumitra19jha** [comment]
Issue has been fixed in PR #335 @DeltaHarbinger

**Comment by sumitra19jha** [comment]
@DeltaHarbinger I created a PR for resolving this issue. Please give it a look and share your feedback.
