### ISSUE TITLE
Fix Deprectated `social_share` Plugin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1042]
**Describe the bug**
The plugin `social_share` uses a deprecated version of the Android embedding. We get the error below when the `flutter pub get` command is run.

**To Reproduce**
```
$ flutter pub get
Running "flutter pub get" in talawa...                           2,340ms
The plugin `social_share` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will
remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Expected behavior**
No error

**Actual behavior**
See message above

**Screenshots**
N/A

**Additional details**
N/A

**Comment by AvneetSingh2001** [comment]
Please assign this to me.

**Comment by SriramPatibanda** [comment]
This is actually a third party package and we can't fix the issues ourselves, the package owners must do it from their side. But a new version of this package is available. Using the latest version might solve the problem.

**Comment by AvneetSingh2001** [comment]
yes, they have updated the version yesterday only, and using that solves this problem.
