### ISSUE TITLE
Language picker colors

### ISSUE THREAD

**Issue by hridaypradhan** [PalisadoesFoundation/talawa#1048]
When a language is selected, the name remains greyed out and that doesn't convey
the selection very well, especially against the selection box that appears around it, which is also grey. 

![Screenshot_20211218-173754.jpg](https://user-images.githubusercontent.com/37269407/146640447-b148e9f6-5f51-4533-9fd2-eeb74cceaf81.jpg)

**Comment by palisadoes** [comment]
@hridaypradhan That's a good observation. Do you want to work on this?

**Comment by hridaypradhan** [comment]
> @hridaypradhan That's a good observation. Do you want to work on this?

Yes, I'd like to work on it, could you please assign it to me? Also, what should I include in the issue description to make it more comprehensive?

**Comment by palisadoes** [comment]
@hridaypradhan What you have in the body of the issue is sufficient.

**Comment by ayush-mahawar26** [comment]
Is this Issue fixed ? I would like to work on this.

**Comment by hridaypradhan** [comment]
> Is this Issue fixed ? I would like to work on this. 

Not yet, I'm working on it

**Comment by ayush-mahawar26** [comment]
@hridaypradhan OK not a probelem , im was just asking because I figured it out , how to do

https://user-images.githubusercontent.com/65828946/146674115-577e46fd-100c-4f18-a094-33650bc87308.mp4

**Comment by palisadoes** [comment]
@ayush-mahawar26 Make sure that it works with:
- All languages. Ask @sumitra19jha  for guidance.
- Dark and light mode (without using hard coded values on the screens) Investigate the MVVM Provider model. Ask @CyberWake and @rutvik11062000 for guidance.

**Comment by palisadoes** [comment]
@ayush-mahawar26 Please create a PR to fix this after you talk with the contributors mentioned previously.

**Comment by nishnatadebnath** [comment]
@palisadoes @hridaypradhan Please close this issue ,PR #1067  fixes this issue.

**Comment by palisadoes** [comment]
@nishnatadebnath I don't think so. This issue is about changing the color of the text that is highlighted to a more visible color. The other PR was about adjusting the font size so that all the text stays in a fixed position as you scroll through the languages.

**Comment by nishnatadebnath** [comment]
@palisadoes My bad I thought both of them are solved in a single PR

**Comment by ayush-mahawar26** [comment]
@palisadoes @nishnatadebnath  can I get the issue to fix ? I fixed it , just need to Generate PR . If u assign it to me .

**Comment by palisadoes** [comment]
@hridaypradhan  Are you still working on this? I'll assign it to @ayush-mahawar26 if a PR isn't submitted in 24 hours. It's overdue.

**Comment by ayush-mahawar26** [comment]
@palisadoes btw which color should i choose , when language is selected ?? white aur any other ?

**Comment by palisadoes** [comment]
> @palisadoes btw which color should i choose , when language is selected ?? white aur any other ?

A contrasting color that is in keeping with the design. Remember there is dark and light mode and it will need to use a variable value defined as part of the provider package. White/grey depending on the background should work, but it needs to be a variable in provider, not hard coded.

**Comment by palisadoes** [comment]
@ayush-mahawar26 I've assigned it to you. We need to get our code coverage up, so also address the issue the testing of this screen view.

**Comment by hridaypradhan** [comment]
I'm very sorry about the delay,  @ayush-mahawar26 please go ahead if you've already solved the issue.

**Comment by Literal-Eval** [comment]
Kindly close the issues when fixed.
