### ISSUE TITLE
SignUp error in mobile app(Code of 2020-Q4 branch)

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#105]
**Issue Description:**
In the registration screen when the user tries to sign up an error is thrown. Sometimes the app stops responding. 

**Identified Errors**
There are two errors being thrown : one is a render overflow error and other is a `Unhandled Failure FormatException` .

**Screenshot**

https://user-images.githubusercontent.com/56952811/110758592-b0431100-8272-11eb-9959-8e1ca77e8839.mp4

**Willing to work on it?**
Yes. I am looking into the error and will open a PR shortly.

**Comment by CoderMayhem** [comment]
@jordanliu is this branch linked to a functioning backend? I am not able to determine if the sign up error is due to app code or backend error.

**Comment by DeltaHarbinger** [comment]
Hey @CoderMayhem, PR #151 made major fixes to master. Furthermore, another PR (#106) was merged fixing this issue. We are sorry that we didn't assign this to you as you were the first one to bring it up, but we will be more careful to assign issues to the appropriate person in the future
