### ISSUE TITLE
Text font size difference on Language Selection screen.

### ISSUE THREAD

**Issue by Literal-Eval** [PalisadoesFoundation/talawa#1050]
![2021_12_20_20_34_12](https://user-images.githubusercontent.com/62198564/146789351-3fa99785-f6d5-4cae-8c00-5572d9bd13bb.gif)

Selecting different languages on the language selection screen causes the list view to shift a bit due to difference in sizes of fonts of different languages.

**Comment by palisadoes** [comment]
@Literal-Eval do you want to work on this issue?

**Comment by Literal-Eval** [comment]
> @Literal-Eval do you want to work on this issue?

Sure. Actually I've resolved it in my machine. Was looking for approval. 😌
