### ISSUE TITLE
Automatic Test Coverage Not Executing Against `lcov.info`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1068]
**Describe the bug**

1. GitHub action for code coverage should fail, but it passes. It may not be activated in the action.
1. This used to work before.

Earlier today we added the `coverage/` directory where the `lcov.info` file generated by the `flutter test --coverage` command and used by the `genhtml` to give the human readable output is located. We doubt that this is the cause of the issue, as it was failing earlier. This possibility should be included in your troubleshooting.

**_NOTE_** Upgrade to the latest version of `very_good_coverage` in the GitHub action

**To Reproduce**

1. Run the following commands in sequence on your CLI (Make sure you have installed the `lcov` package first.
    ```
    flutter test --coverage
    genhtml coverage/lcov.info -o coverage
    ``` 
1. You will see in the penultimate line of the `genhtml` command output that the coverage is 30%.
1.  Take a look at the [GitHub actions pull request file](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml). 
    1. You will see that the `VeryGoodOpenSource/very_good_coverage` code coverage plugin that we are using has a `min_coverage` value of 32. 
1.  If you [examine one of the latest pull request GitHub actions output](https://github.com/PalisadoesFoundation/talawa/runs/4602376197?check_suite_focus=true).   
    1. You will see that the `codebase testing` section with `flutter test --coverage` runs. We assume the `lcov.info` file is created. 
    1. Then you will see that the `Report code coverage` section runs, but:
    1.  The value of 32 > 30, so the action should fail. It does not.

**Expected behavior**
GitHub action for code coverage should fail.

**Actual behavior**
GitHub action for code coverage passes.

**Screenshots**

This is a reproduction of what you should expect from the CLI with 30% coverage.

```
$ flutter test --coverage
$ genhtml coverage/lcov.info -o coverage
Reading data file coverage/lcov.info
Resolved relative source file path "lib/main.dart" with CWD to "/home/peter/GitHub/talawa/lib/main.dart".
Found 117 entries.
Found common filename prefix "/home/peter/GitHub/talawa"
Writing .css and .png files.
Generating output.
Processing file lib/splash_screen.dart
Processing file lib/router.dart
...
...
...
Processing file lib/widgets/video_widget.dart
Processing file lib/widgets/custom_progress_dialog.dart
Processing file lib/widgets/event_search_delegate.dart
Writing directory view page.
Overall coverage rate:
  lines......: 30.1% (1820 of 6052 lines)
  functions..: no data found

```

**Additional details**
None

**Comment by nishnatadebnath** [comment]
Please assign this to me.

**Comment by palisadoes** [comment]
I updated the original text about the GitHub Actions file and the GitHub actions execution provide a better description of the issue.

**Comment by palisadoes** [comment]
@nishnatadebnath Closed by accident. Reopened.
