### ISSUE TITLE
event_card sharp corners

### ISSUE THREAD

**Issue by Pavel401** [PalisadoesFoundation/talawa#1077]
**Describe the bug**
The event_card's rectangle with sharp edges are not looking good with the UI. These cards take high cognitive effort to visually process the UI by the user. Users can appreciate the aesthetic beauty of rounded corners on the UI.

**To Reproduce**

1.Navigation Bar > Events >Explore Events > My Events

**Expected behavior**

 Rounded corners are not only easier for our eyes to process, but they also make information easier to process for the user. There’s no doubt that rounded corners are appealing.

**Actual behavior**
In the present UI, the rectangle with sharp edges cards is not looking good with the rounded buttons and rounded bottom sheets UI.
**Screenshots**
Sharp corners |  Rounded Corners
:-------------------------:|:-------------------------:
![WhatsApp Image 2021-12-23 at 9 45 48 PM](https://user-images.githubusercontent.com/47685150/147271798-42b438e7-8f98-4691-9a1c-f9b6896aa2dc.jpeg) | ![WhatsApp Image 2021-12-23 at 9 45 47 PM](https://user-images.githubusercontent.com/47685150/147271810-fbfc372e-9ee6-4c2c-b709-ad8016153444.jpeg)

**Comment by Pavel401** [comment]
Please assign me the issue, I want to work on this.

**Comment by palisadoes** [comment]
It's assigned

**Comment by palisadoes** [comment]
Closing. Fixed in:
- https://github.com/PalisadoesFoundation/talawa/pull/1076
