### ISSUE TITLE
Not all paths return a String in controllers/auth_controllers login function

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#108]
I would like to work on this.

**Comment by DeltaHarbinger** [comment]
Hey @Swayam221, can you give a better example, or a screenshot of this issue so that we can understand it better before assigning it to you?

**Comment by Swayam221** [comment]
@DeltaHarbinger this issue was actually opened for the old master branch. Since that branch is now  updated, this issue can be closed.
