### ISSUE TITLE
Testing: Event Registration

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1085]
Create unittests for this pull request:

- https://github.com/PalisadoesFoundation/talawa/pull/965

Contact @utkarshshendge for details

**Comment by Shubham-Godambe** [comment]
Hey is this still an issue? If yes ,then can you please describe it.

**Comment by palisadoes** [comment]
This can be closed

**Comment by Shubham-Godambe** [comment]
ok fine. Can you assign any good first issue to me ,as I am a beginner to open source
