### ISSUE TITLE
Fix : Switches of ``Keep Registerable`` overflow in Add Event and Edit Event pages

### ISSUE THREAD

**Issue by BolisettySujith** [PalisadoesFoundation/talawa#1088]
In the Add Event and Edit Event pages, `Keep Public` and `Keep Registerable` are aligned in a Row, because of that the switch for `Keep Registerable` is overflowing,  sometimes the switch is not sliding properly when tapped on it.

<table>
      <tr>
       <td><img src="https://user-images.githubusercontent.com/73323807/147628347-c2669da1-ade1-4f7d-855b-15347c43ada9.png"></td>
       <td><img src="https://user-images.githubusercontent.com/73323807/147628343-9c86b74b-68cf-487e-9b85-008069dc137e.png"></td>
      </tr>
  </table>

I want to work on this issue, Please Assign it to me.

**Comment by ItsAdityaKSingh** [comment]
@BolisettySujith Are you still working on resolving this?

**Comment by BolisettySujith** [comment]
Yes, I have solved the issue, now I was working on testing some widgets to include in the PR. As my End Sem Exams are going I was a bit busy in that. I will make a PR asap.

**Comment by RandyKdev** [comment]
Good day @ItsAdityaKSingh, If nobody is working on this I would like to have a go at it. Thanks
