### ISSUE TITLE
Confusion regarding a line of code

### ISSUE THREAD

**Issue by Literal-Eval** [PalisadoesFoundation/talawa#1089]
While writing test for custom_alert_dialog.dart, I came across a piece of code which I think might me wrong.

widgets/custom_alert_dialog.dart -> line 31
![code](https://user-images.githubusercontent.com/62198564/147636877-ce157ea0-83cb-4b30-8c5a-38ba0aab047a.png)

I think it should execute secondaryButtonTap.
So the code should be onTap: () => secondaryButtonTap(): navigationService.pop()

Or am I missing something ? Please clarify.

**Comment by CyberWake** [comment]
The piece of code written over is perfect. If you see the custom alert dialog there are two buttons one for the positive response and the other for a negative so on a negative response the dialog should pop definitely whereas when there is some more logic to be added like after the negative response if something has to be done in the caller state than the secondaryButtonTap function is needed to be called with the logic to close the dialog. 
Whereas if there is nothing to be done then you need not pass this function since it is nullable and if this case goes true then automatically navigationService.pop() statement is executed.
Provided that ```onTap: () => secondaryButtonTap(): navigationService.pop()``` this is a invalid dart syntax

**Comment by CyberWake** [comment]
Let me know if your doubt is cleared if so please close the issue or we can discuss more on slack

**Comment by Literal-Eval** [comment]
Yeah I get that, and that's why I asked where in the file is secondaryButtonTap called ? Nowhere I guess. So I thought this was it's place (for obvious) reasons.

And about syntax, I wrote just a pseudo-code, like if secondaryButtonTap is defined, call it, otherwise pop. That's not dart, I know. :)

So the question remains, where is secondaryButtonTap supposed to be called ?

**Comment by Literal-Eval** [comment]
I think this is the required behavior.

![navigator](https://user-images.githubusercontent.com/62198564/147652881-49002162-539d-4daa-a3f9-4c68c73c02b9.png)

**Comment by Literal-Eval** [comment]
If someone can help in this, I have to write tests for this file.

**Comment by CyberWake** [comment]
> I think this is the required behavior.
> 
> ![navigator](https://user-images.githubusercontent.com/62198564/147652881-49002162-539d-4daa-a3f9-4c68c73c02b9.png)

using this would be a more prone method since this will require not to write the dialog closing logic making it less robust. If there needs to be a logic or a negative response and the method is passed for the same then closing logic should also be handled explicitly.

**Comment by Literal-Eval** [comment]
So what's the solution ? The method needs to be called somewhere (which isn't being done). Or it doesn't ?

**Comment by CyberWake** [comment]
if the function is passed than dialog closing logic should be handled explicitly in the method passed else is the method isn't passed then nothing needs to be done.

**Comment by Literal-Eval** [comment]
So basically there should be no else block, only the if block. Right ?

> I think this is the required behavior.
> 
> ![navigator](https://user-images.githubusercontent.com/62198564/147652881-49002162-539d-4daa-a3f9-4c68c73c02b9.png)

**Comment by CyberWake** [comment]
there is no change needed.

**Comment by Literal-Eval** [comment]
Okay. Fine.
