### ISSUE TITLE
Switching from the login to the signup page while typing causes renderflex overflow (2020-Q4 branch)

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#109]
https://user-images.githubusercontent.com/68892315/110801103-e39d9400-82a2-11eb-8d15-b79accccdd8c.mp4

Notice the black and yellow lines near the keyboard, just as the witch is made.
![Films   TV 11-03-2021 19_52_25](https://user-images.githubusercontent.com/68892315/110801597-6aeb0780-82a3-11eb-92e9-5280a460f67e.png)

I would like to work on this issue. @jordanliu please assign it to me.

**Comment by adithyaakrishna** [comment]
@Swayam221 Its the same on iOS too, and on different devices the overflow also changed
![image](https://user-images.githubusercontent.com/23498248/110802173-f369a800-82a3-11eb-9ef3-62aaab10b223.png)

**Comment by Swayam221** [comment]
@adithyaakrishna thanks for mentioning. I am working on it.

**Comment by yasharth291** [comment]
we should use `Media.Query( ) `  for the same

**Comment by yasharth291** [comment]
or we can use padding and margins according to the screen size

**Comment by Swayam221** [comment]
For now I have wrapped it in a single child scroll view widget. 😅

**Comment by yasharth291** [comment]
yeah but it will not work for the longer phones with other aspect rartios

**Comment by Swayam221** [comment]
The overflow is actually being caused by the keyboard remaining open, if the keyboard is dismissed, the widget doesn't cause this error. If i use MediaQuery to set the container height, it might still cause the same problem with a lesser overflow but might not solve the problem. So, i guess scrollview is better?

**Comment by droy312** [comment]
When keyboard is open user this to know the height of the keyboard `MediaQuery.of(context).viewInsets.bottom`.
Make a container with height equals Device Height - Keyboard Height and add the `Create Account` button and the Logo inside this container.
Wrap this container with a `SingleChildScrollView` widget.
Hope this helps.

**Comment by Swayam221** [comment]
@droy312 Thankyou for the suggestion. The presence of the keyboard with the mainscreen() widget is actually a bug which will be solved by a PR related to issue #112 .

**Comment by AbdulMalikDev** [comment]
Wrapping the Row widget in a FittedBox solved the issue for me. Good thing i searched whether this issue was already created before posting a new one as mentioned in the guidelines.

**Comment by Swayam221** [comment]
@heyjordn Please review #113

**Comment by Swayam221** [comment]
@heyjordn  I am closing this issue since the PR #113 has been merged.
