### ISSUE TITLE
app crashes when image is picked via camera(post section)

### ISSUE THREAD

**Issue by rakshitkamboj** [PalisadoesFoundation/talawa#1090]
Whenever we try add an image to a new post via camera after capturing the image and clicking the tick button the app crashes.

How to generate this bug :
1. Go to Post section
2. Click on camera icon 
3. Capture the image
4. Click tick button

Here is the video attached of the bug

https://user-images.githubusercontent.com/69065683/147690711-ece21211-9c35-4915-8338-aeeba18bec72.mp4

Solution :
Instead of using image_picker package we can use edge detection package for capturing image via camera.
Edge detection package have a built in cropping feature which will avoid height and width issue of captured image.
Here's the link of package [https://pub.dev/packages/edge_detection](url).

I am willing to work on this issue.
Please assign this to me.
Thank you.

**Comment by palisadoes** [comment]
@rakshitkamboj 

- What's the existing package that's being used for image processing?
- Why can't that package be fixed or updated to not crash?
- Can the existing package do cropping? If so, why not use that instead?

**Comment by rakshitkamboj** [comment]
@palisadoes 
1. Image_picker is the existing package for image processing.

2. After surfing the internet I found out that the app isn't crashing it's being terminated by the OS to free memory, because while the image picker activity is active the Flutter application is technically a background app, and thus subject to collection by the OS when there is memory pressure.
So, I think this bug will vary from device to device. 

3. No, the existing package i.e. image_picker does not support cropping of image.

Conclusion:
I can try working on getting the existing solution to not crash but I think there will not be any proper solution for that.
So, I would suggest better to change the package to make the app bug free.
Thank you.

**Comment by palisadoes** [comment]
@rakshitkamboj Thanks for the clarification. Let's focus on a solution that:

- doesn't crash or have the memory issue mentioned
- optionally allows cropping of the image prior to upload. The auto-cropping of your original suggestion isn't necessary, simple cropping is preferred.
- is historically well supported with many installations

**Comment by rakshitkamboj** [comment]
@palisadoes 
Sure, as soon as I get a solution which meet all the above requirements then I will ping it here only.
Thank you.

**Comment by nishnatadebnath** [comment]
https://user-images.githubusercontent.com/53905682/147847822-0e77cf32-7a7c-417c-a215-33169cfee094.mp4

This is working fine with me did you check that all the permission are allowed in app settings.

**Comment by palisadoes** [comment]
@rakshitkamboj 
- Have you tried testing on both the emulator and your Android / iOS device? In which case is it failing?

As it is failing because of low memory resources, it implies an OS issue versus the app.

**Comment by rutvik11062000** [comment]
@rakshitkamboj As according @nishnatadebnath and running on my personal device and emulator don't show the effect you mentioned in the video, please try reinstalling the app and give the permission when asked.

If issue doesn't persist its better to close this.

**Comment by rakshitkamboj** [comment]
@palisadoes previously I tried running the app in android at that it was causing the bug (don't know the true reason behind that ) but after reinstalling the app camera feature is working perfectly fine.

@nishnatadebnath @rutvik11062000 Thank you for your contribution in this issue.
