### ISSUE TITLE
Generalize visibility package usage

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#1093]
### Currently there are 2 package that have the same functionality (i.e. to alter/change a widget based on the position of it on the screen).

1. _visibility_detector_
2. _inview_notifier_list_

### **Issues:**
a. As of the current implementation the values of inview_notifier_list are passing down the widget but is never used.
b. Another is calculating "inview" (i.e. variable of indicating the play/pause state) should be done on more parameters rather than just fraction percentage > 0.5, 
<p>
<img width="350" alt="image" src="https://user-images.githubusercontent.com/47498552/147852446-9126e671-d438-40e2-acce-d3bb4b565628.png">

<img width="186" alt="image" src="https://user-images.githubusercontent.com/47498552/147852407-325526a4-3ac5-4e2e-a723-6ef8841daf1a.png">
</p>

### **TODO**
a. **Resolve ambiguity of using package:**
<p>
<img width="309" alt="image" src="https://user-images.githubusercontent.com/47498552/147852675-432e6b11-6f23-42d1-a89b-a8ef1b612ec4.png">
<img width="177" alt="image" src="https://user-images.githubusercontent.com/47498552/147852679-7c593628-6759-41ca-ae6b-0d7586870899.png">
</p>
 Considering factual difference like the publisher, likes, other packages dependency, I'm proposing to remove the _inview_notifier_list_ from the implementation and make _visibility_detector_ the primary package to do the job. 

b. **Implementing more generalize code of widget detection.**
Abstraction like "base_view" (file exists in project) should be made so that code reusability should be there while using similar function for other pages.
These altering widget / trigger some function based on the position will be use in many future implementation.
E.g. function to let the server know which portion of the chats are seen by the user.

More suggestions / approaches regarding this topic are welcome below 👇 and is open for anyone to work on the action list🎯.

**Comment by palisadoes** [comment]
Thanks @rutvik11062000, your suggestion is a good approach. The fewer dependencies the better.

**Comment by nishnatadebnath** [comment]
Only problem with using _visibility_detector_ in place of _inview_notifier_list is the fact that visibilty detector has only visible fraction which can be used to tell if an widget is visible in the view or not.So if more than two widgets wrapped under _visibility_detector_  might callback simultaneusly if boths visibility_fraction is more than than the threshold we have provided .

**Comment by rutvik11062000** [comment]
@nishnatadebnath I think it can be solved by giving many thoughts to it, one can be having only one video controller  on feed page, also regarding the playback of videos the current timestamp should be cached locally so that when it resume it starts from where it is paused.

Anyone who is interested can take this issue. We need to build a reliable video auto playback system.

**Comment by nishnatadebnath** [comment]
So the initial work to be done is to remove the `_inview_notifier_list_` which is used in the post feed with visibility_detector.And then try to generalize the widget so that we can use it for other purpose and refactoring.

**Comment by rutvik11062000** [comment]
Yes this would be good.

**Comment by nishnatadebnath** [comment]
How am I supposed to cache the position ,should an mapped list do with key of the video and the current position stored and can be acessed through locators or there is some definitive approach used in this project which I might not know.

**Comment by nishnatadebnath** [comment]
Please don't close this issue as the above pull request solves only  part A of the issue.
