### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1097]
**Describe the bug**
The current UI for dark mode is not appealing or does not showcase the important parts of the app. The Circular loading button can be improved. On the Chats screen, the tab color has a different green than the one used all over the app. From the onboarding screen to various Page titles and content, it can be improved with typical and custom talawa colors! 

**To Reproduce**

1. Open App in Dark Mode
2. See the onboarding screen for the first time
3. Switch between Screens to see dull UI

**Expected behavior**
A clear UI theme and colors could be used, highlighting the main parts and titles with brighter shades.

**Actual behavior**
The UI was dull and unappealing for a user.

**Screenshots**
<img src="https://user-images.githubusercontent.com/69353350/147921499-3f1b14ed-9a6f-45f1-9c87-251a58881173.png" height="500"/> <img src="https://user-images.githubusercontent.com/69353350/147921477-9e0bdedd-bdaa-4fe5-bbbd-c2577cba76fe.png" height="500"/> <img src="https://user-images.githubusercontent.com/69353350/147921666-9e27eed2-f06a-49e1-8dc4-f047e89a1e8b.png" height="500"/> 
<img src="https://user-images.githubusercontent.com/69353350/147921683-98571350-189d-46e3-bac9-97b379b67374.png" height="500"/> <img width="217" alt="Screenshot 2022-01-03 at 3 34 26 PM" src="https://user-images.githubusercontent.com/69353350/147922738-1a753b2f-9036-460a-a512-c670ea81a1b9.png">

**Additional details**
The UIs need to be consistent with App's overall color scheme and look appealing and noticeable.

**Comment by ItsAdityaKSingh** [comment]
@palisadoes I would like to work on this issue and improve the UI for the better!

**Comment by palisadoes** [comment]
@rutvik11062000 What do you think? I'd greatly prefer changes to meet your design specification.

**Comment by palisadoes** [comment]
@ItsAdityaKSingh We have raised our code coverage percentage to 34%, so you'll need to add tests to this issue for the PRs to be approved.

**Comment by ItsAdityaKSingh** [comment]
> @ItsAdityaKSingh We have raised our code coverage percentage to 34%, so you'll need to add tests to this issue for the PRs to be approved.

So, basically, will I need to write tests first for the particular widgets or UI components I want to change?

**Comment by palisadoes** [comment]
Yes

**Comment by ItsAdityaKSingh** [comment]
Ok. Could you help me by guiding me in a direction to start writing tests, like from which widget or function should I start unit testing so as to be able to resolve this issue?

**Comment by palisadoes** [comment]
@ItsAdityaKSingh  
- [You can find widget test examples here](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/widget_tests/widgets). 
- [Our View Model tests can be found here](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/view_model_tests)

Please review them to get an idea on how to proceed. 
- Any code you submit must be tested.
- If your code uses any widget, then you must ensure that the widget in question has a test too.

This should give you an idea of how to proceed.

**Comment by ItsAdityaKSingh** [comment]
> @ItsAdityaKSingh
> 
> * [You can find widget test examples here](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/widget_tests/widgets).
> * [Our View Model tests can be found here](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/view_model_tests)
> 
> This should give you an idea of how to proceed on widgets and other code.
> 
> * Any code you submit must be tested.
> * If your code uses any widget, then you must ensure that the widget in question has a test too.

Sure. Thanks a ton!
