### ISSUE TITLE
Introduce working of Invite to org option!

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1098]
**Is your feature request related to a problem? Please describe.**
The app should be able to utilize the invite option to invite others to our orgs.
<img src="https://user-images.githubusercontent.com/69353350/147922561-74f69f92-fa58-470a-8e8e-d79a2d63907b.png" height="500"/>

**Describe the solution you'd like**
Functioning of Invite button in the profile section.

**Describe alternatives you've considered**
If inviting to orgs is not possible, we could at least help invite people to use talawa app.

**Approach to be followed (optional)**
We can create dynamic links for inviting friends by sharing links and org/app details.

**Comment by palisadoes** [comment]
@ItsAdityaKSingh We have raised our code coverage percentage to 34%, so you'll need to add tests to this issue for the PRs to be approved.

**Comment by palisadoes** [comment]
@ItsAdityaKSingh 

- The first step would be to invite people already enrolled in the Talawa App. Inviting external persons should be another issue.
- The already enrolled person should get some kind of notification in Talawa that this has been done.
- We would need to have provisions for restrictions:
   - Some organizations may only want administrators to have this privilege
   - Others may only want certain people to have this privilege
   - Others would allow everyone 

This will require changes to the API. I think we'll need to split this up into several issues, one for each of the use cases stated above. The first would be to figure out a way to do this where everyone has the privilege.

How do you plan to proceed?

**Comment by ItsAdityaKSingh** [comment]
Thanks for the insights! It's a really great plan you have laid out here. What I thought about proceeding was to first of all invite external persons to join talawa and be a part of the organization I am sending an invite from. But if you want to proceed with already joined members of talawa, then that would be a nice option too. It could grow gradually with the additional restrictions and features as you mentioned. 
**So, if possible I would like to begin with notifying already joined members about this invite in a notifications section as well as with a general notification from the app.**

From this, we could also attach a new feature, that of a notification page with a banner on AppBar leading to it. It can have invites, activities, important dates' notifiers, etc. 
Your views on this @palisadoes ?

**Comment by palisadoes** [comment]
What backend do you plan to use to implement the notifications?

**Comment by ItsAdityaKSingh** [comment]
> What backend do you plan to use to implement the notifications?

I could use Firebase Could Messaging to send push notifications to targeted users.

**Comment by palisadoes** [comment]
- Would that require the Palisadoes Foundation to have a Firebase account, and/or would that be the responsibility of the Talawa end user's organization?
- If it is the Talawa organization, how will the Firebase authentication data be sent to the app?

We need to make the push functionality account the responsibility of the Talawa end user's organization to reduce the need for us to be called and/or billed for every new organization that signs up.

**Comment by ItsAdityaKSingh** [comment]
Yes, it requires a firebase account. I am not that experienced in terms of the backend to give the best solution :(  
So any better suggestions you would like to put or discuss? I would need to do some research on this.

**Comment by palisadoes** [comment]
Please research this with the requirements I posted previously. This has been a recurring issue that needs to be addressed. The end user organization needs to have the Firebase account shared between the app and the API, or the push notifications have to be managed solely by the App <-> API connection.

Chat functionality depends on figuring out the right approach to this too.

**Comment by ItsAdityaKSingh** [comment]
Sure sir, I would try to do the needful along with writing tests for changes I requested in UI.

**Comment by palisadoes** [comment]
@ItsAdityaKSingh please contact @sumitra19jha on Slack before proceeding. He has extensive experience with the backend API will have advice that would be useful. When you have a strategy on how to proceed we can continue the discussion here.

**Comment by ItsAdityaKSingh** [comment]
Thanks a lot! I would be glad to learn from him and try to implement this feature :)
