### ISSUE TITLE
Establishing a new branch with code refactored to current Stable version of Flutter. (2.0.1)

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#110]
I would like mentors to refactor the code of the app to new stable and supported version of flutter (2.0.1). So that people can work on the Bug fixing that will be. **Because fixing bug and creating issues on outdated version of flutter won't matter as some of them would be fixed when we migrate to newer verion.** I suggest to @heyjordn ,that it would be better that we create separate branch for this with refactored and migrated code.

**Comment by jordanliu** [comment]
Hey @i-anuragmishra, please see #111
