### ISSUE TITLE
Code Stability

### ISSUE THREAD

**Issue by jordanliu** [PalisadoesFoundation/talawa#111]
Currently, talawa's codebase is unstable. We're actively working on it to be stable enough for contributions, we're aiming to have it stable by Saturday - March 13.

We appreciate all the feedback and effort to contribute!

**Comment by Saibaba-Alapati** [comment]
Files missing. Pod install fails and android emulator clean exit

**Comment by yasharth291** [comment]
Some of the Widgets which are deprecated should be changed and i really really want to contribute for the same. Could you please assign me the same.

**Comment by pr4nshul** [comment]
![Screenshot (186)](https://user-images.githubusercontent.com/51524156/111026014-fed8e280-840d-11eb-9786-2c4dbbdf8df8.png)

While trying to the run the code on my device , I faced the following issue. In addition to that alot of red line indicating errors in the code showed up even after I ran pub get. Can someone help me out?
As you can see below:

![Screenshot (187)](https://user-images.githubusercontent.com/51524156/111026022-0dbf9500-840e-11eb-9b9a-add7c39c7425.png)

**Comment by yasharth291** [comment]
run the second branch Q4-2020

**Comment by DeltaHarbinger** [comment]
Hey @pr4nshul, the master branch should be able to be built on any device now. No need to use the Q4 branch anymore
