### ISSUE TITLE
User Interface of Chat Screen

### ISSUE THREAD

**Issue by rakshitkamboj** [PalisadoesFoundation/talawa#1110]
Willing to contribute to this project by adding a chat screen for direct chat page.

Here's the User Interface of the chat screen:

![chat-screen](https://user-images.githubusercontent.com/69065683/148799401-561a6d89-1bdd-4f04-95a9-1d50108df4a4.png)

Or If there is other Interface available then I am ready to develop that too.
Thankyou.

**Comment by palisadoes** [comment]
We are evaluating scalable ways implement chat with the API. Details will come in a week or so. Hold on.
