### ISSUE TITLE
Add option to increase or decrease font size

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1111]
**Is your feature request related to a problem? Please describe.**
There is no option in settings to increase/decrease font size in the app.

**Describe the solution you'd like**
Adding a sizing option wherein one can change the overall font size of the app.

**Additional context**

Right now only 2 optional settings is provided:

<img src="https://user-images.githubusercontent.com/69353350/148901324-7480f021-2134-4668-9010-b6d7a171b122.png" height="500"/>

**Comment by palisadoes** [comment]
This is an interesting idea, however it's best handled by the Android system font settings. This will add a lot of code to the app that is available elsewhere.

We should focus on ensuring that the app adjusts its screens appropriately when this parameter is adjusted.

**Comment by palisadoes** [comment]
I'm going to close this issue for the reasons stated previously.

**Comment by ItsAdityaKSingh** [comment]
Sure! So could we possibly pursue this feature later or not implement it at all?

**Comment by palisadoes** [comment]
No, we need to focus on major areas of improvement as [outlined in our documentation site](https://palisadoesfoundation.github.io/talawa-docs/docs/internships/internship-ideas).
