### ISSUE TITLE
Unittests for event_card_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1118]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
widgets_view_models/event_card_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1018
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/widgets_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by M-A-D-A-R-A** [comment]
As of now, the Code in `widgets_view_models/event_card_view_model.dart` is commented ou by @utkarshshendge. Do we need to first code the `event_card_view_model.dart` and then write the test for it?

**Comment by palisadoes** [comment]
You are right. I'll close this issue. Please work on another issue. We should remove `widgets_view_models/event_card_view_model.dart` from the code base.

**Comment by palisadoes** [comment]
I reopened the issue. We need to have event registration implemented.  If you can implement event registration using this uncommented code, then include the test for it in the PR. You can create an issue for event registration functionality too and link both issues in the same PR.
