### ISSUE TITLE
Keybaord doesnt dismiss automatically when navigating to a different page

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#112]
https://user-images.githubusercontent.com/68892315/110814673-adb2dc80-82af-11eb-9d8d-7840e37fc2be.mp4

we can see that the keyboard remains open and doesn't dismiss.
I would like to work on this.

**Comment by droy312** [comment]
When `sign up` button is pressed user `FocusScope.of(context).unfocus()` to dismiss keyboard programmatically.

User `SingleChildScrollView` in Create Account page because there is an overflow error when the keyboard appears.

**Comment by yasharth291** [comment]
#113  this pull request has completed it.

**Comment by Swayam221** [comment]
@yasharth291 @droy312  #113 only fixes the renderflow error. This issue is for a different bug. Thankyou for suggestions!😄

**Comment by pr4nshul** [comment]
I opened a similar issue, 30 min back and closed it as it was a duplicate to this one. I would like to work on this, I want to know this though, does this issue persist only on the signup and login page or throughout the application.

**Comment by yasharth291** [comment]
its resolved @pr4nshul  see the pull request #141

**Comment by Swayam221** [comment]
@heyjordn please review #141

**Comment by Swayam221** [comment]
@DeltaHarbinger @jordanliu Please review #160 which fixes this issue.
