### ISSUE TITLE
Unittests for theme_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1120]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
theme_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1119
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by umang-sinha** [comment]
hey I am working on this. Please assign it to me

**Comment by palisadoes** [comment]
Please see the updated criteria in the comments

**Comment by ahluwaliatikant** [comment]
Hey @umang-sinha, are you still working on this?
