### ISSUE TITLE
Unittests for main_screen_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1121]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
main_screen_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1119
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by patrickwitter** [comment]
I would like to tackle this issue

**Comment by palisadoes** [comment]
Please see updated criteria in the comments

**Comment by palisadoes** [comment]
Reopening as the code coverage for this file isn't 100%
- https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/view_model/main_screen_view_model.dart

**Comment by architsangal** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
Reopening as the code coverage is under 70%

**Comment by DevanshuB211** [comment]
@palisadoes @noman2002 please assign this issue to me

**Comment by noman2002** [comment]
@DevanshuB211 Any progress ?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Manik2708** [comment]
@palisadoes @noman2002 can you assign this issue to me?

**Comment by Manik2708** [comment]
@noman2002 @palisadoes The tests are already written for this file and code coverage is close to 97% but there is a problem. Please correct me if I am wrong, these tests are appearing to be Pseudo in nature (I mean to say these tests are covering lines but not matching the actual code), I am not sure about this so I want to get it cleared. This file aims to give user an app tour so there are Targets, which I don't know whether should be tested or not (they are very high in number and would led to high amount of Boilerplate code in the test). I have made the test coverage to 100% but still doubtful of it's effectiveness. I request the maintainers to recheck the currently written tests and let me know if I can fix it. Or should I move with these tests making it's coverage 100%.

**Comment by Manik2708** [comment]
Please close this issue as it is completed @palisadoes
