### ISSUE TITLE
Unittests for lang_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1122]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lang_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1119
### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by ahluwaliatikant** [comment]
@palisadoes, I would like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment]
Please see updated criteria in the comments
