### ISSUE TITLE
Unittests for base_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1123]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
base_view_model.dart
```

This file can be found in the `lib/view_model` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1119

**Comment by patrickwitter** [comment]
@palisadoes Good day, I would like to tackle this issue
