### ISSUE TITLE
Complete Code Coverage for Widgets

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1125]
The Talawa code base needs to be 100% reliable. This means we need to have We 100% unittest code coverage. This is a parent issue for all View Model unittest issues.

We will be creating one issue per related file with the expectation that widgets referenced in these files must also have unittests.
- We'll only assign the child issues. 
- Please comment on one of the child issues for assignment.
- Only one child issue will be assigned to a person at any one time.

Parent Issue:
- https://github.com/PalisadoesFoundation/talawa/issues/1124

Child Issues:
- https://github.com/PalisadoesFoundation/talawa/issues/1126
- https://github.com/PalisadoesFoundation/talawa/issues/1127
- https://github.com/PalisadoesFoundation/talawa/issues/1128
- https://github.com/PalisadoesFoundation/talawa/issues/1129
- https://github.com/PalisadoesFoundation/talawa/issues/1130
- https://github.com/PalisadoesFoundation/talawa/issues/1131
- https://github.com/PalisadoesFoundation/talawa/issues/1132
- https://github.com/PalisadoesFoundation/talawa/issues/1133
- https://github.com/PalisadoesFoundation/talawa/issues/1134
- https://github.com/PalisadoesFoundation/talawa/issues/1135
- https://github.com/PalisadoesFoundation/talawa/issues/1136
- https://github.com/PalisadoesFoundation/talawa/issues/1137
- https://github.com/PalisadoesFoundation/talawa/issues/1138
- https://github.com/PalisadoesFoundation/talawa/issues/1139
- https://github.com/PalisadoesFoundation/talawa/issues/1140
- https://github.com/PalisadoesFoundation/talawa/issues/1141
- https://github.com/PalisadoesFoundation/talawa/issues/1142
- https://github.com/PalisadoesFoundation/talawa/issues/1173
- https://github.com/PalisadoesFoundation/talawa/issues/1174
- https://github.com/PalisadoesFoundation/talawa/issues/1175
- https://github.com/PalisadoesFoundation/talawa/issues/1176
- https://github.com/PalisadoesFoundation/talawa/issues/1177
- https://github.com/PalisadoesFoundation/talawa/issues/1178
- https://github.com/PalisadoesFoundation/talawa/issues/1179
- https://github.com/PalisadoesFoundation/talawa/issues/1293
- https://github.com/PalisadoesFoundation/talawa/issues/1294
- #1396 
- #1397

**Comment by Adiii1436** [comment]
Hello @palisadoes ! I want to work on https://github.com/PalisadoesFoundation/talawa/issues/1127 . Please assign this issue to me.

**Comment by palisadoes** [comment]
@Adiii1436 You need to comment on the issue directly or else you cannot be assigned
