### ISSUE TITLE
Unittests for widget event_search_delegate.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1133]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
event_search_delegate.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by guptapriyanshu7** [comment]
I want to work on this one @palisadoes .

**Comment by palisadoes** [comment]
- [The code coverage report shows 94% coverage](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets). We need to get to 100%.
- Reopening

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 please assign me this issue
