### ISSUE TITLE
Unittests for widget from_palisadoes.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1134]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
from_palisadoes.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

**Comment by guptapriyanshu7** [comment]
Hey @palisadoes, can I work on this one?
