### ISSUE TITLE
Unittests for widget post_list_widget.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1138]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
post_list_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

**Comment by patrickwitter** [comment]
@palisadoes  Good day, I would like to tackle this issue.
