### ISSUE TITLE
Unittests for widget signup_progress_indicator.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1140]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
signup_progress_indicator.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

**Comment by guptapriyanshu7** [comment]
Can I take this up?
