### ISSUE TITLE
Unittests for widget video_widget.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1142]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
video_widget.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- No functionality must be removed to achieve this goal

**Comment by architsangal** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by architsangal** [comment]
No. I am working on other issues for now.

**Comment by iamworrell** [comment]
can you assign this issue to me?

**Comment by shatanikmahanty** [comment]
Hey @palisadoes is @iamworrell still working on this? If not, can you please assign me this

**Comment by palisadoes** [comment]
@shatanikmahanty Do you still want to work on this?

**Comment by shatanikmahanty** [comment]
I am facing an issue with testing future builder widget, I was trying to find documentation on that but couldn't find proper ones that fit these use cases. If someone wants to collaborate with me for this so that I can workout the problems with future builder, then I can still put up a PR. Please wait for 1 more week, until then if I can't find a solution, I will unassign myself

**Comment by palisadoes** [comment]
@shatanikmahanty  Please contact @TheHazeEffect (Troy Anderson) on slack. He may be able to assist.

**Comment by noman2002** [comment]
@shatanikmahanty Any update ?

**Comment by shatanikmahanty** [comment]
Hi @noman2002, as @palisadoes instructed I contacted Troy Anderson on Slack. I am currently awaiting a reply from his end.

**Comment by palisadoes** [comment]
@TheHazeEffect please provide feedback
