### ISSUE TITLE
Password validator only shows invalid password on signup screen

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#1145]
**Describe the bug**
Password validator on signup detail page only show invalid password in every condition.
Example: when the password is too short, when the password doesn't have Capital letters, when the password doesn't have special character.

**To Reproduce**

1. Select Language
2. Verify org url
3. Click on signup
4. Select Organization and click next
5. Enter password and see the unexpected behavior.

**Expected behavior**
It should show "password is too short" when the length of password is short.
It should show "password doesn't contain special character" when a special character is not there.
It should show "password doesn't contain at least one capital/small letter" when it is not there is password.

**Actual behavior**
It only shows "invalid password" for every case.

**Screenshots**
<img src="https://user-images.githubusercontent.com/54404474/150407363-c05c616e-fe2d-4a49-a016-2b711bac971b.gif" height="550" width="280" />

**Additional details**
I am working on this issue please assign it to me.

**Comment by palisadoes** [comment]
We only want the invalid password message to occur after hitting `submit`. 

- At that point we should state the password criteria.
- The criteria will need to be translated to all spoken languages supported by the app.

This is the standard approach for most applications.

**Comment by palisadoes** [comment]
Please confirm this methodology before I assign the issue to you.

**Comment by noman2002** [comment]
Yes we can add the password criteria and it can be translated to all the languages supported by the app by using the same method through which we are translating the other elements of the app. 

I am willing to work on this. Please assign it to me.

**Comment by ayushvrma** [comment]
@palisadoes can i work on this too? i feel like it'll be a good first issue for me

**Comment by noman2002** [comment]
> @palisadoes can i work on this too? i feel like it'll be a good first issue for me

Brother I am already working on it. You can take another issue please.

**Comment by palisadoes** [comment]
@ayushvrma There are many ["good first issues"](https://github.com/PalisadoesFoundation/talawa/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to choose from. More than one person working on an issue has been unmanageable in the past. Please take a look. We need to get the reliability of the code improved, and so testing is very important to us now.

**Comment by palisadoes** [comment]
@noman2002 Remember to write tests for your code.

**Comment by noman2002** [comment]
@palisadoes I think there is no test for signup detail page. Do I have to write the whole test for the same. Also there is one open PR #1115 for the same. Do I have to wait for the PR to get merged and then I do changes accordingly.

**Comment by palisadoes** [comment]
No need to write the whole test, but we need tests done. Please work with @ahluwaliatikant to figure out why the tests are failing. You can then merge your changes to the tests for this issue after his PR is merged.

**Comment by noman2002** [comment]
I am done with fixing the password validator. Can I create a PR for that as it is my first contribution and I am very excited to created a PR. I will create another issue for the test and will write it when #1115 will be merged.

**Comment by palisadoes** [comment]
OK

**Comment by noman2002** [comment]
Thank you so much. I am creating the PR now.
