### ISSUE TITLE
Testcases failing for password validation in signup_details_view_model_test.dart

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#1151]
**Describe the bug**
Test is failing due to test cases are outdated and it is checking of "Invalid Password" which is now updated.

**To Reproduce**

1. run flutter test
2. You will get some test failed.

**Screenshots**
![Screenshot from 2022-01-23 00-46-32](https://user-images.githubusercontent.com/54404474/150652508-b18b090e-eb19-4d8a-ab9b-e5ce6338467e.png)

**Additional details**
I am working on it. Please assign it to me.

**Comment by noman2002** [comment]
@palisadoes Someone else resolved this issue in some other PR. Should I close this issue?

**Comment by palisadoes** [comment]
- Which PR fixed it?
- According to the [code coverage report](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/view_model/pre_auth_view_models/signup_details_view_model.dart) this file has no tests written for it.

**Comment by noman2002** [comment]
#1155  resolved this issue. 
But after pulling the code from develop branch no test is failing on my local machine.
