### ISSUE TITLE
Etiquette - Low Quality Issues and PRs

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1152]
Hey everyone!

The maintainers of Palisadoes Foundation are very happy and appreciative of the recent influx of interest for Talawa.

We know everyone is anxious and are excited to contribute, but we've noticed an increase in duplicate and low quality issues and PR's.

Please have a look at the contributing guidelines for each Talawa repo:
1. [Talawa contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/develop/CONTRIBUTING.md) as reference to how we operate.
1. [Talawa-API contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/CONTRIBUTING.md) as reference to how we operate.
1. [Talawa-Admin contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/CONTRIBUTING.md) as reference to how we operate.

Just some reminders:

1. Please refrain from creating a PR without a linked issue. Every PR must have a linked issue.
2. Check to see if the issue you're creating has already been created to reduce duplicates
3. Please be patient if your issue or pr hasn't been reviewed, we're working on getting them reviewed as fast as we can.

For any other questions, feel free to reach out and communicate with other contributors on [Slack](http://slack.palisadoes.org)

Once again, we're grateful for all the support we have been receiving.

Peter,
Palisadoes Foundation

**N.B:** We'll be flagging accounts that have a consistent pattern of spamming LQ posts

**Comment by AjayMaheshwari23** [comment]
I have recently created [this](https://github.com/PalisadoesFoundation/talawa-admin/issues/457) issue , but i am not getting any response from your side so if you are considering it to be a low quality issue you can close that so that I won't keep waiting for your response.
Thank you
