### ISSUE TITLE
Receiving a bunch of 'Missing a required trailing comma' warnings

### ISSUE THREAD

**Issue by umang-sinha** [PalisadoesFoundation/talawa#1153]
**Describe the bug**
Not exactly a bug but the entire codebase has missing trailing commas in most of the function calls and declarations. This is not a good linting practice as specified by the [Dart Linter Rules](https://dart.dev/tools/linter-rules#require_trailing_commas)

**To Reproduce**

1. If you have the Flutter and Dart plugin for VS Code installed, you should receive a bunch of warnings with the message "Missing a required trailing comma."

**Screenshots**
![image](https://user-images.githubusercontent.com/58984048/150672459-f0d73abd-7b76-4eac-8e11-eaadccebeba8.png)

**Comment by umang-sinha** [comment]
I would love to work on improving the linting in the entire repository. Please assign it to me

**Comment by umang-sinha** [comment]
So I added trailing commas wherever they were missing and then formatted the code using `dartfmt`. These trailing commas have been added to a total of 99 files. Not sure if I should add all of it in a single pull request or break it down into smaller pull requests based on changes in a sub-directory. What do you suggest?

**Comment by palisadoes** [comment]
Our pull request automation [pull-request.yml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml) file runs a `flutter format --set-exit-if-changed .` command on the submitted repo files. We do this for linting consistency. 

Unless the command you propose is available with all operating systems we cannot use it.

**Comment by umang-sinha** [comment]
Dart Formatter comes by default with the Dart plugin on VS Code. 
Also, `flutter format` is essentially doing the same thing and they operate identically. `flutter format` is just a wrapper around `dart format` as pointed out in this [StackOverflow answer.](https://stackoverflow.com/a/66051657/14327844)

**Comment by palisadoes** [comment]
If that is the case, then open a separate PR just for linting.
