### ISSUE TITLE
Unittests for widget custom_list_tile.dart 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1174]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
custom_list_tile.dart 
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by ayushvrma** [comment]
hi, can I work on this issue?

**Comment by ayushvrma** [comment]
@palisadoes i can see that a test file for custom_list_tile.dart already exists via pr #1084 . What all can I do to improve on it?

**Comment by palisadoes** [comment]
[The code coverage for that file is only 90%](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets), try to get to 100%.

**Comment by ayushvrma** [comment]
@Literal-Eval can you help me out a bit on this issue please?
 `
orgInfo!.isPublic!
--
114 | ? AppLocalizations.of(context)!
115 | .strictTranslate('Public')
`
on how to cover this path of the code?

**Comment by ayushvrma** [comment]
@palisadoes can you help me out a bit?
```
testWidgets('Creating Custom List (giving custom options)', (tester) async {
      await tester.pumpWidget(createCustomListTileUser(
          type: TileType.option,
          option: Options(
              icon: const Icon(Icons.add),
              title: 'henlo',
              subtitle: 'yesh',
              trailingIconButton: null)));
      final Text text =
          tester.firstWidget(find.byKey(const Key('trailingIconButton')));
      expect(text.style!.getTextStyle(),
           equals(Theme.of(MockBuildContext()).textTheme.bodyText2));
    });
```
I'm writing this test so as to cover the path of TileType being option to cover 100% of the code but I'm getting back different types of TextSyles as expected. Could you help me out a bit?

**Comment by ayushvrma** [comment]
Okay so I followed your advice and made the changes accordingly, just wanting to know how the 'key' parameter works in building CustomListTile when it's built when type = TileType.org?

**Comment by ayushvrma** [comment]
Tests for the user are done, but when the widget is built using TileType.org, it fails to build giving me improper errors, where can I find more information about orgs in Talawa, I've already looked up org_info.dart , so do I need to create a new org by myself to test this widget or is there another way? @palisadoes

**Comment by palisadoes** [comment]
Please ask @ahluwaliatikant or @guptapriyanshu7 for assistance. They have extensive experience writing tests for the code base.

**Comment by RandyKdev** [comment]
Hi @palisadoes, I would like to work on this.
