### ISSUE TITLE
Unittests for widget raised_round_edge_button.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1178]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
raised_round_edge_button.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by ahluwaliatikant** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by ahluwaliatikant** [comment]
Hey @palisadoes , I think this issue has already been resolved. There is a test file already present and the [code coverage report](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/raised_round_edge_button.dart) also shows 100%.
