### ISSUE TITLE
Unittests for widget rich_text.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1179]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
rich_text.dart
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by MnCSSJ4x** [comment]
I am new to contribution and would love to add to this. Can someone guide me in this and assign this?

**Comment by palisadoes** [comment]
For guidance, please ask the [contributors who have recently closed PRs](https://github.com/PalisadoesFoundation/talawa/pulls?q=is%3Apr+is%3Aclosed). They will be glad to assist. They are also available on our Slack channel.

**Comment by palisadoes** [comment]
Try upgrading to the latest version of flutter and updating the packages in your local repo

**Comment by MnCSSJ4x** [comment]
Tried to fix this, still get the same error. This is an existing error with [dart](https://github.com/dart-lang/sdk/issues/45115) .  Please check this soon.

**Comment by ahluwaliatikant** [comment]
@palisadoes Sir, this file already has 100% coverage according to the [codecov report].(https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib/widgets/rich_text.dart)

**Comment by palisadoes** [comment]
You are correct. I'll close the issue.
