### ISSUE TITLE
Textfield's icon and border not visible when out of focus due to background picture in register and login page.

### ISSUE THREAD

**Issue by AniketSindhu** [PalisadoesFoundation/talawa#118]
<img src="https://user-images.githubusercontent.com/57598532/110855160-01d3b600-82dc-11eb-8f4a-3a447f5b1bc8.png" width="200">    &nbsp;   <img src="https://user-images.githubusercontent.com/57598532/110855200-0f893b80-82dc-11eb-8698-897aca1645de.png" width="200">

**Comment by adithyaakrishna** [comment]
@AniketSindhu I guess this is related to #99 
As the icons and background deal are a part of the whole UI

**Comment by yasharth291** [comment]
yeah i think @AniketSindhu  you can close your issue as it is duplicate of #99

**Comment by AniketSindhu** [comment]
Where is that design channel ??

**Comment by yasharth291** [comment]
slack

**Comment by AniketSindhu** [comment]
> slack

yes i dont see the design channel there
![image](https://user-images.githubusercontent.com/57598532/110859794-fc796a00-82e1-11eb-8a70-3ecb02a01e0f.png)

**Comment by adithyaakrishna** [comment]
Click on add channel, you will get the option

**Comment by AniketSindhu** [comment]
thanks closing the issue

**Comment by AniketSindhu** [comment]
Merged #124
