### ISSUE TITLE
Help Button May Not be in the right place.

### ISSUE THREAD

**Issue by architsangal** [PalisadoesFoundation/talawa#1183]
**Is your feature request related to a problem? Please describe.**

- The help button is under the profile section. If someone wants to look for a button like help, that person will probably not click on the profile button for that.  
- The help button can be reached only after we have successfully Signed Up or have Logged In. According to me, some alternative to the help button is required there too. Some users may get confused there.

**Describe the solution you'd like**

- According to me, it would make much more sense if we place it in the custom drawer.
- We can have `?` on every screen at the top right corner (If required). And that can be used to direct to a kind of user manual for the users. Right now, there is no functionality being attached to 'Help' as raised in issue #1107, for these problems we can have a special web page similar to `talawa documentation but for regular users` of the app.
- `talawa documentation but for regular users` must be different from `talawa documentation`, otherwise it may confuse a regular user of the application.

If this feature gets approved, I would like to work on it.

**Comment by architsangal** [comment]
@palisadoes 

#1107 and #1183 (look identical). Can I work on these issues?

**Comment by palisadoes** [comment]
The help option must be removed for the reasons in:

- https://github.com/PalisadoesFoundation/talawa/issues/1107
