### ISSUE TITLE
Adding better validators for password field

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1188]
**Is your feature request related to a problem? Please describe.**
The password field's validator does it signify what it wants for a successful entry. It only says Invalid password while signing up.

<img src="https://user-images.githubusercontent.com/69353350/152417960-7238c506-9efb-42ae-a8dc-a9266df461c3.png" height="500"/>

**Describe the solution you'd like**
It should show various conditions like characters needed, length, etc.

**Approach to be followed (optional)**
Adding a few conditions and error messages to the validator.

**Comment by ItsAdityaKSingh** [comment]
Hey @Tusharkhati, currently I am working on resolving this issue. If not resolved, you may see this through :)

**Comment by palisadoes** [comment]
This was supposed to have been addressed in this issue:
- https://github.com/PalisadoesFoundation/talawa/issues/1145

What has changed?

**Comment by ItsAdityaKSingh** [comment]
It still just shows an **invalid password**. Moreover, there are no conditions to tell users what extra needs to be done.

**Comment by palisadoes** [comment]
Please only state what needs to be done after submitting the password.
