### ISSUE TITLE
Making last name field optional for users signing up

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1189]
**Is your feature request related to a problem? Please describe.**
While signing up, the last name field has been made mandatory. 

<img src="https://user-images.githubusercontent.com/69353350/152418577-21bdefef-0e90-4ba4-adf4-af1a6add71ec.png" height="500"/>

**Describe the solution you'd like**
Many users may not be having or may not be wanting to use the last name, so making the field optional could be better.

**Additional context**
This topic is open for discussion and ideas.

**Comment by palisadoes** [comment]
A good observation, but gor identification purposes we need to have a last name. Organizations will want to have that control. I'll close the issue.
