### ISSUE TITLE
How about if we can add Social Media Authentication to the app?

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#119]
**Description:** Adding Social Media (Google/FB/Twitter) SignIn or SignUp for the application

**Why:** I would say adding this feature would simplify the whole SignUp & Login Process as we can get different parameters from the auth provider like UserName, Email, ProfilePic etc along with reducing the time for the SignIn/SignUp Process

If this Idea is approved, I would love to Implement the same after thorough discussion with the Maintainers

**Comment by yasharth291** [comment]
As the Project is under migration phase so adding some new feature should be avoided till then.

**Comment by adithyaakrishna** [comment]
Yeah, that's totally understandable but I thought this would be a nice feature/enhancement which can be implemented in the future 👀

**Comment by yasharth291** [comment]
yeah i think mentors will like it. But we don't have hosted backend for this i don't think its good to implement now.

**Comment by cyber-venom003** [comment]
@yasharth291 I guess API is deployed at following links:
```
const String baseRoute = "https://talawa-api.herokuapp.com";

const String httpTalawaDev = "https://talawa-testing.herokuapp.com/graphql/";
```
This snippet was in 2020-Q4 branch in lib/Utils/globals.dart

**Comment by cyber-venom003** [comment]
> 
> 
> Yeah, that's totally understandable but I thought this would be a nice feature/enhancement which can be implemented in the future 👀

This implementation would require much work on backend side i guess.

**Comment by yasharth291** [comment]
not at all google signup facebook signup doesn't require the backend involvement

**Comment by adithyaakrishna** [comment]
I think it would be great if we move the talk to the discussions #122
