### ISSUE TITLE
Implement user image upload

### ISSUE THREAD

**Issue by HowardJTJ** [PalisadoesFoundation/talawa#12]

**Comment by Deandrew007** [comment]
Ideally, would you want the user uploading profile pic done from here? 
![Screenshot_20200406-122833](https://user-images.githubusercontent.com/16479694/78587663-e2e2bf00-7802-11ea-8009-fad63fa5c127.png)

**Comment by HowardJTJ** [comment]
Yes, currently, there is the user's first initial acting as a placeholder for a user's image. This also has to be handled on the back end as well in regards to caching and retrieving said images.
