### ISSUE TITLE
App won't build because of some error in query.dart

### ISSUE THREAD

**Issue by ayushvrma** [PalisadoesFoundation/talawa#1201]
**Describe the bug**
The app won't built but throws the following error
```
Error: Required named parameter 'parserFn' must be provided.
../…/widgets/query.dart:79
      initialData: observableQuery?.latestResult ?? QueryResult.loading(),

```
**To Reproduce**

1. Open in editor
2. Run main.dart (debug)

**Expected behavior**
To build the app and show home screen to select language

**Comment by palisadoes** [comment]
Are you working on the latest version of the `develop` branch? The `master` is out of date.

**Comment by ayushvrma** [comment]
yes, I'm working on the `develop` branch
<img width="302" alt="image" src="https://user-images.githubusercontent.com/65159146/153636182-b0396488-6e21-44ba-8810-90f93f8341b7.png">
output of `git pull `:
`Already up to date.`

**Comment by ayushvrma** [comment]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/65159146/153636547-615663d9-4cfa-48be-818b-05d2ee679dcc.png">

**Comment by palisadoes** [comment]
Are you using the latest version of flutter? Try doing a flutter upgrade.

**Comment by palisadoes** [comment]
Is this still an issue?
