### ISSUE TITLE
Fix Deprecated UniLinksPlugin API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1204]
**Describe the bug**
When building the `talawa` app we get an UniLinksPlugin API warning message. This needs to be fixed

- Our test code coverage percentage will need to be improved or maintained as part of this fix.
- **DO NOT ATTEMPT to solve the issue by ignoring the error message in `build.gradle`** That is not a viable solution to this issue.

**To Reproduce**

1. Build the Talawa app
2. Monitor the console
3. See message below

**Expected behavior**
There should be no deprecation warning

**Actual behavior**
```
Note: /home/xxx/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/uni_links-0.5.1/android/src/main/java/name/avioli/unilinks/UniLinksPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Screenshots**
N/A

**Additional details**
N/A

**Comment by noman2002** [comment]
If no one is working on this. Please assign it to me.

**Comment by CyberWake** [comment]
@palisadoes this is not a talawa specific issue since this is a dependency in our codebase and it's stable enough inspite being deprecated there is nothing much we could handle in talawa codebase about it. Plus they have [this](https://github.com/avioli/uni_links/issues/82) issue being worked upon.

**Comment by palisadoes** [comment]
Should we therefore find another package to use instead?

**Comment by palisadoes** [comment]
In that case let's apply the suggested fix.

The fewer spurious messages the better

**Comment by CyberWake** [comment]
@palisadoes I don't [this](https://stackoverflow.com/questions/61702748/note-recompile-with-xlintdeprecation-for-details-solved) works have tried this but it still gives the warning.
I have also gone through the depth of the issue this is basically due to the native java or kotlin code used in the dependency and the codebase of dependency is not perfectly linted. Due to which we get this warning.

**Comment by palisadoes** [comment]
OK, I'll close the issue. Thanks
