### ISSUE TITLE
Fix Unsafe PathProvider API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1205]
**Describe the bug**
When building the `talawa` app we get an PathProvider API warning message about the package using `unchecked or unsafe operations`. This needs to be fixed.

- Our test code coverage percentage will need to be improved or maintained as part of this fix.
- **DO NOT ATTEMPT to solve the issue by ignoring the error message in `build.gradle`** That is not a viable solution to this issue.

**To Reproduce**

1. Build the Talawa app
2. Monitor the console
3. See message below

**Expected behavior**
There should be no warning

**Actual behavior**
```
Note: /home/xxx/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.9/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Screenshots**
N/A

**Additional details**
N/A

**Comment by Tusharkhati** [comment]
can I work on this?

**Comment by CyberWake** [comment]
@palisadoes this issue is from the dependency being used in the talawa codebase which comes in from the flutter community itself so I guess this should not be a issue at this point considering the point it is a dependency. Also [here](https://github.com/flutter/flutter/issues/93389) is a brief info regarding the issue

**Comment by palisadoes** [comment]
Should we replace this with a supported package then?

**Comment by CyberWake** [comment]
this is a best in class package maintained by the flutter community itself I feel this is safe to use since you can see this is one of the most liked packages in the flutter community for getting paths for local disk storage.

**Comment by CyberWake** [comment]
[Here](https://pub.dev/packages?q=is%3Aflutter-favorite&sort=like&page=2) is the link to it's rating. It's in top 13.

**Comment by palisadoes** [comment]
OK. I'll close the issue
