### ISSUE TITLE
Remove Unused RazorPay Support - This will be handled by the API in future

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1206]
**Describe the bug**
When building the `talawa` app we get an RazorPay API warning message. In early 2021, this support was considered, but we decided to include it as an API plugin. This means that `talawa` will need to interface with the `talawa-api` plugin and not RazorPay directly.

RazorPay support must be removed.

### Our test code coverage percentage will need to be improved or maintained as part of this fix.

**To Reproduce**

1. Build the Talawa app
2. Monitor the console
3. See message below

**Expected behavior**

RazorPay support must be removed so that there is no error.

**Actual behavior**
```
Note: /home/xxx/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_flutter-1.2.7/android/src/main/java/com/razorpay/razorpay_flutter/RazorpayFlutterPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Screenshots**
N/A

**Additional details**
N/A

**Comment by ayushvrma** [comment]
hi can I work on this issue as it is a bit beginner friendly?

**Comment by noman2002** [comment]
Is this issue still open? Can I work on this one?
