### ISSUE TITLE
Making the Docker Container for the project.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#121]
I think it is difficult for everyone to read documents and set system environment instead we can add the docker container in it.

**Comment by yasharth291** [comment]
#117  will do it along with the autofill option

**Comment by yasharth291** [comment]
@heyjordn @jordanliu @DeltaHarbinger could anyone of you label it and see the PR #117 regarding it please

**Comment by yasharth291** [comment]
@heyjordn @jordanliu  @DeltaHarbinger you could close this issue as the PR related to it has been merged in the branch.

**Comment by yasharth291** [comment]
@heyjordn  this is also completed by merging the pr #117  you can close this one as well

**Comment by Sagar2366** [comment]
Closing this issue as it is fixed as part of https://github.com/PalisadoesFoundation/talawa/pull/117
