### ISSUE TITLE
Write a script to check if all pull requests meet the requirements for generating documentation using Dart Doc

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1215]
In order to ensure that documentation is seamlessly being created with each addition/modification of a file, write a script to check that the file follows the specifications described in the Getting Started section [here](https://dart.dev/tools/dart-doc). Note that `dart analyze` has to be used first without errors in order to successfully use the `dart doc` command.

This task essentially involves the creating of a parser (preferred from a maintainability point of view) or use of a regular expression that will check to see if the patterns for generating documentation are adhered to. The script should be written in Python and is written with the goal of it being used with a Github action being triggered upon a pull request.

**Parent Issue**
- https://github.com/PalisadoesFoundation/talawa-docs/issues/189

**Comment by CyberWake** [comment]
@palisadoes @DMills27 can you please assign this to me.
