### ISSUE TITLE
CI/CD pipeline for generating JSDoc artifacts used for automating documentation

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1216]
Following https://github.com/PalisadoesFoundation/talawa/issues/1215, create a pipeline to run the `dart doc` command for any files that get approved in a pull request. After the command has been run, the artifact HTML files generated from this should then be added via a pull request to the path `docs/talawa/` in the Talawa Docs repo (https://github.com/PalisadoesFoundation/talawa-docs).

**Parent Issue**
- https://github.com/PalisadoesFoundation/talawa-docs/issues/189

**Sister Issue**
- https://github.com/PalisadoesFoundation/talawa/issues/1215

**Comment by Raunakk02** [comment]
@DMills27 Can I take up this issue?

**Comment by CyberWake** [comment]
@palisadoes can you assign this to me.
