### ISSUE TITLE
Views: Create tests for edit_profile_page.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1229]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/profile/edit_profile_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/profile_test/edit_profile_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/profile/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by CyberWake** [comment]
@palisadoes can you assign this to me.

**Comment by jadeharr** [comment]
This is going to be the third pending issue in talawa you will be assigned. Make sure to complete some before asking for more.

**Comment by palisadoes** [comment]
Reopening only 85% code coverage

**Comment by AyushRaghuvanshi** [comment]
Would like to work on this. Please Assign me

**Comment by ilakshaygupt** [comment]
Can you please assign me this issue?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by RunTerror** [comment]
@Cioppolo14 Please assign me this issue

**Comment by nenezoe** [comment]
i would like to be assigned this issue

**Comment by nenezoe** [comment]
two tests has been written so far , one passed, still working on the second due to some issues encountered

**Comment by Azad99-9** [comment]
@nenezoe need any help ?

**Comment by nenezoe** [comment]
yes i do

**Comment by nenezoe** [comment]
> @nenezoe need any help ?

yes i do

**Comment by nenezoe** [comment]
> > @nenezoe need any help ?
> 
> yes i do

@palisadoes i need help on some issues i'm encountering

**Comment by nenezoe** [comment]
> > @nenezoe need any help ?
> 
> yes i do

@palisadoes i need help on some issues i'm encountering

**Comment by Azad99-9** [comment]
Please share the details of what you are exactly facing. I will try to help you.

**Comment by nenezoe** [comment]
Dear PalisadoesFoundation/talawa
From this code


test('Get Image from Gallery Test', () async {
  final File imageFile = File('path/to/image.jpg');

  // Ensure that the mock returns a Future<File?> that resolves to a
non-null value
  when(mockMultiMediaPickerService.getPhotoFromGallery(camera: false))
      .thenAnswer((_) async => imageFile);

  await viewModel.getImage();

  expect(viewModel.imageFile, equals(imageFile));
});

i'm getting this error
test\views\after_auth_screens\profile_test\edit_profile_page_test.dart 15:7
  MockMultiMediaPickerService.getPhotoFromGallery
test\views\after_auth_screens\profile_test\edit_profile_page_test.dart
52:40  main.<fn>.<fn>

type 'Null' is not a subtype of type 'Future<File?>'

Warm Regards
Okereke Juliet Nene

**Comment by Azad99-9** [comment]
please use the below code snippet and let me know If it solves your issue.

'''
test('Get Image from Gallery Test', () async {
      final viewModel = EditProfilePageViewModel();
      final mock = getAndRegisterMultiMediaPickerService();
      viewModel.initialize();
      final File imageFile = File('path/to/image.jpg');
      

      // Ensure that the mock returns a Future<File?> that resolves to a
      // non-null value
      when(mock.getPhotoFromGallery(camera: false))
          .thenAnswer((_) async {
            return imageFile;
          });

      await viewModel.getImage();

      expect(viewModel.imageFile, equals(imageFile));
    });
'''

**Comment by Azad99-9** [comment]
Please use the below code snippet and let me know if this fixed your issue.

![carbon(9)](https://github.com/PalisadoesFoundation/talawa/assets/120930148/6ff31d1c-a0e3-4654-acd8-d4866e09524d)

**Comment by nenezoe** [comment]
okay, Thanks, i will try it and get back to you

**Comment by nenezoe** [comment]
> Please use the below code snippet and let me know if this fixed your issue.
> 
> ![carbon(9)](https://private-user-images.githubusercontent.com/120930148/313393430-6ff31d1c-a0e3-4654-acd8-d4866e09524d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTkzNTksIm5iZiI6MTcxMDU5OTA1OSwicGF0aCI6Ii8xMjA5MzAxNDgvMzEzMzkzNDMwLTZmZjMxZDFjLWEwZTMtNDY1NC1hY2Q4LWQ0ODY2ZTA5NTI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNlQxNDI0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGQ5NGYyMzhkMDQ0MWM1YTIzNDQ5MjQzMTlkNDQ5MTQwZjljMjMwMzRmNDc4MDdmYzgyMDkwY2RiODM2NDQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.79dQtjTVslRARB9CW33XRisSlF_Bysye24OWyqt5JUE)

It works perfectly well, thanks alot

**Comment by nenezoe** [comment]
@palisadoes where do i push the code for the edit_profile_page_test to ?

**Comment by palisadoes** [comment]
To the `develop` branch of the repository

**Comment by nenezoe** [comment]
> To the `develop` branch of the repository

i'm getting this when i push.  remote: Permission to PalisadoesFoundation/talawa.git denied to nenezoe.
fatal: unable to access 'https://github.com/PalisadoesFoundation/talawa.git/': The requested URL returned error: 403

**Comment by palisadoes** [comment]
You cannot push directly to our repositories. You have to create a pull request. There is lots of documentation on this on the GitHub site.

**Comment by nenezoe** [comment]
> You cannot push directly to our repositories. You have to create a pull request. There is lots of documentation on this on the GitHub site.

@palisadoes please can you send me the link to the documentation on this

**Comment by palisadoes** [comment]
Please use Google

**Comment by nenezoe** [comment]
@palisadoes  there is no way i can access _multiMediaPickerService in the test file because it is a private class there without setting a setter and getter there to use it to access it in the other file

**Comment by Azad99-9** [comment]
You can use `locator<MultiMediaPickerService>()` for accessing the service.

**Comment by nenezoe** [comment]
> locator<MultiMediaPickerService>()

okay , thanks

**Comment by nenezoe** [comment]
I made a PR waiting for feedback from the people assigned to look at the PR
