### ISSUE TITLE
Views: Create tests for individual_post.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1234]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/feed/individual_post.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/feed_test/individual_post_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/feed/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by ahluwaliatikant** [comment]
I would like to work on this issue @palisadoes Sir, Please assign it to me.

**Comment by priyanshu029** [comment]
Hello @palisadoes  can i work on this test.

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by Ayush0Chaudhary** [comment]
https://github.com/PalisadoesFoundation/talawa/issues/1398
this issue is completed by me @palisadoes @noman2002 in this PR https://github.com/PalisadoesFoundation/talawa/pull/1461
It is duplicate issue I guess.

**Comment by Ayush0Chaudhary** [comment]
you can close it after PR is merged

**Comment by palisadoes** [comment]
Closing as a duplicate
