### ISSUE TITLE
Views: Create tests for app_settings_page.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1244]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/app_settings/app_settings_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/app_settings_test/app_settings_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/app_settings/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by CyberWake** [comment]
@palisadoes can you assign this to me.

**Comment by Sagar2366** [comment]
We can definitely assign more issues to you. 
@CyberWake can you please finish working on other assigned issues ?

**Comment by palisadoes** [comment]
@CyberWake I mistakenly merged your PR which for this issue when you were not assigned the task. Please do not submit PRs for issues to which you are not assigned. You risk the PR being closed.
