### ISSUE TITLE
Views: Create tests for signup_details.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1247]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/pre_auth_screens/signup_details.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/pre_auth_screens_test/signup_details_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/pre_auth_screens/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by rskbansal** [comment]
May I do this ?

**Comment by literalEval** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Ayush0Chaudhary** [comment]
I would like to work on this issue too 
Please assign me if literalEvan is not doing it. @palisadoes

**Comment by literalEval** [comment]
Hey @palisadoes, sorry for unavailability. I will continue on this issue. Please reassign to me.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Are you still working on this?

**Comment by Ayush0Chaudhary** [comment]
Yes I am working on it, got busy in these PR to your org only
https://github.com/PalisadoesFoundation/talawa/pull/1382
https://github.com/PalisadoesFoundation/talawa/pull/1380

**Comment by literalEval** [comment]
Cool.
