### ISSUE TITLE
Views: Create tests for login.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1252]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/pre_auth_screens/login.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/pre_auth_screens_test/login_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/pre_auth_screens/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by sudo-saksham** [comment]
Could you please assign me this issue?

**Comment by sudo-saksham** [comment]
@palisadoes  
It seems when I test this, it's not approving the test for Hide Password button even though in the application the IconButton is working fine. I've attached the related information here: https://thepalisadoes-dyb6419.slack.com/archives/CSW3ETABE/p1646415886967029

**Comment by palisadoes** [comment]
Is there a mock package that could be used to assist? I've had difficulties in the past with testing network Image widgets, and had to use a mock to get it to work.

**Comment by sudo-saksham** [comment]
I don't think that Mock packages will work here. We are not calling anything via HTTP call or fetching anything from database.

**Comment by sudo-saksham** [comment]
Unassigning myself from this issue. Will work on it later. :)

**Comment by noman2002** [comment]
I would like to try this one also. Please assign it.

**Comment by palisadoes** [comment]
@noman2002 You have been assigned three issues. Please wait until your PRs are merged before asking for this or other assignments.

**Comment by noman2002** [comment]
> @noman2002 You have been assigned three issues. Please wait until your PRs are merged before asking for this or other assignments.

ok, Thank you. I will wait for the PR to be merged. I thought I can work on other issues after creating a PR for the previously assigned.
