### ISSUE TITLE
Remove hard coded Heroku instance URL from code base

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1256]
**Describe the bug**

The Talawa App's default URL points to our Heroku test instance at  [talawa-graphql-api.herokuapp.com/graphql](https://talawa-graphql-api.herokuapp.com/graphql). This is not sustainable as real organizations should not be using our test instance for their members.

This needs to be fixed before we can do Alpha testing.

**To Reproduce**

Install Talawa. The default Heroku instance URL will be populated in the opening screen.

**Expected behavior**

1. The hard coded Heroku instance URL needs to be removed from the code base
1. The test cases need to be updated to reflect the change
1. A Talawa INSTALLATION.md document needs to be created to let new developers know:
    1. How to install and run Talawa
    1. The API URLs to use for the most common use cases. (ie developers on a local machine, developers on a local machine using Docker, a remote machine) References to the API documentation may be useful here.
1. Existing instructions in the README.md file should be moved to the new INSTALLATION.md file. 
1. A reference to the new installation document must be maintained.

**The documentation needs to be FLAWLESS.** Time will need to be taken to ensure that all new users understand what to do to make the app work. Step by step instructions will need to be provided.

Anyone must be able to run Talawa without incident when this bug issue is resolved.

**Actual behavior**

The URL defaults to our test Heroku instance.

**Screenshots**

N/A

**Additional details**

N/A

**Comment by noman2002** [comment]
I am willing to work on this. 
Do I have to just remove the hard-coded URL and fix the test and documentation.?
