### ISSUE TITLE
[Enhancement] Add the CODE_OF_CONDUCT in the project to make the project better.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#126]

**Comment by yasharth291** [comment]
@heyjordn @jordanliu @DeltaHarbinger could anyone of you label it

**Comment by yasharth291** [comment]
@DeltaHarbinger  please see this

**Comment by DeltaHarbinger** [comment]
Hey @yasharth291, I can run this by the others managing the repo. In my opinion, this should be a good addition

**Comment by yasharth291** [comment]
Thanks sir

**Comment by i-anuragmishra** [comment]
Hey @Sagar2366 this issue is unassigned. If nobody is working on it can i be assigned this issue. I have no issue assigned to me right now.

**Comment by i-anuragmishra** [comment]
Issue Description: All maintained project are advised to include an Code of conduct .md file. it highly advised to make project better and transparent.

Issue Severity: Moderate

Expected Changes: Addition of file Code_of_Conduct.md

**Comment by i-anuragmishra** [comment]
i have created PR #473 to Resolve this issue assigned. Mentors i request you review please.
