### ISSUE TITLE
Button text not visible on events page in dark/light modes

### ISSUE THREAD

**Issue by bhattabhi013** [PalisadoesFoundation/talawa#1261]
**Describe the bug**
Button text not ### visible

**To Reproduce**

1. Sign-up/ Login in the app
2. Go to event tabs
3. Click on any of the available event
4. Green button at the bottom doesn't have any text.

**Expected behavior**
Text should be available on the button for better user-experience.

**Screenshots**
<img width="243" alt="image" src="https://user-images.githubusercontent.com/47862474/157934860-09a74292-e755-4a74-b41f-55e416ad7ccb.png">

**Additional details**
I've selected ARTEEVS org2 as organization while signing-up.

**Comment by palisadoes** [comment]
Would you like to work on this? Remember that all the text in the app changes depending on the language selected. You will have to consider that too.

**Comment by bhattabhi013** [comment]
Thanks for the opportunity, but can anyone please confirm that this issue also occurs at their end, so that I can confirm that this is not a device- or user-specific issue. Please let me know if any help is required to replicate the issue.

**Comment by palisadoes** [comment]
Please ask for verification on the #talawa slack channel.

**Comment by bhattabhi013** [comment]
Please assign this issue to me.

**Comment by noman2002** [comment]
Can I work on this? Please assign it to me.

**Comment by mananmehta3** [comment]
Is this issue still open? 
If yes I would like to work on this.
Please assign it to me.

**Comment by noman2002** [comment]
> Is this issue still open? If yes I would like to work on this. Please assign it to me.

Sure, you can work on this issue. @palisadoes will assign it to you.

**Comment by tamojitalwaysghosh** [comment]
hey ,this issue looks interesting, I think I might be able to solve it, so may I get a chance to resolve this?

**Comment by harshitraisahab** [comment]
is this still open ? i easily fix that  issue please assign to me

**Comment by harshitraisahab** [comment]
@bhattabhi013 is this still open ? i easily fix that issue please assign to me

**Comment by palisadoes** [comment]
@harshitraisahab you are already working on the other issues. Please focus on those.

**Comment by gayatribkar** [comment]
Is this issue still open? If yes, then I would like to work on it.

**Comment by m-eraf** [comment]
@palisadoes  is this issue still open? 
I wanted to to work on it plz assign it to me.

**Comment by noman2002** [comment]
@m-eraf this is already assigned to @gayatribkar. You can work on some other issues. Have a look at the open issues for unittesting.

**Comment by noman2002** [comment]
@gayatribkar  Any progress ??

**Comment by literalEval** [comment]
I would like to work on this issue. @palisadoes

**Comment by palisadoes** [comment]
@m-eraf   Do you still want to work on this? You are next in line.

**Comment by noman2002** [comment]
Unassigned due to inactivity.
@literalEval You were next but you have various issues assigned.

**Comment by SamarthAsthan** [comment]
@noman2002  can you assign it to me?

**Comment by SamarthAsthan** [comment]
@noman2002 is there any public API key or will the entire server setup have to be done on Local machine only?

**Comment by noman2002** [comment]
You have to locally setup the api.

**Comment by CyberWake** [comment]
@SamarthAsthan please refer talawa-api to setup the server locally all the setup to setup could be found [here](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md).

**Comment by tamojitalwaysghosh** [comment]
is this issue still open? I can work on it

**Comment by tamojitalwaysghosh** [comment]
i am not getting access to the app to see the issue beforehand , please help

**Comment by literalEval** [comment]
@tamojitalwaysghosh what issue are you facing ?

**Comment by tamojitalwaysghosh** [comment]
> @tamojitalwaysghosh what issue are you facing ?

i am not getting the access to the app

**Comment by literalEval** [comment]
@tamojitalwaysghosh you can join the community slack and have a look there. Moreover, there is well written documentation on using the Talawa ecosystem. Please have a look at INSTALLATION.md

**Comment by tamojitalwaysghosh** [comment]
ok thanks @literalEval

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no linked pull request

**Comment by nidhin29** [comment]
@noman2002 Sir, can I work on this issue

**Comment by nidhin29** [comment]
Currently there are no events in any organisation and also I am not able to add an event, So it is not possible to solve this issue without an event

**Comment by nidhin29** [comment]
It wasn't possible to add an event or see an event in any organisation few days back currently it is possible so I'm working on it now

**Comment by nidhin29** [comment]
Again I'm not able to add or see events

**Comment by jaivsh** [comment]
@noman2002 @palisadoes I want to work on this, please assign this to me. Thank you!

**Comment by Cioppolo14** [comment]
Unassigning due to inactivity.

**Comment by Kaps61929** [comment]
@noman2002 @palisadoes Sir, is this issue still open? 
I would love to contribute. Please assign it to me.

**Comment by palisadoes** [comment]
This issue is out of date. Closing
