### ISSUE TITLE
Add organization URL in documentation

### ISSUE THREAD

**Issue by bhattabhi013** [PalisadoesFoundation/talawa#1263]
**Is your feature request related to a problem? Please describe.**
At present, there is a lot of confusion about adding organization URL while setting up the development environment.

**Describe the solution you'd like**
Adding organization URL in the documentation will help the developer's to get rid of  confusion related to organization's URL

**Approach to be followed (optional)**
 Organization URL  example should be documented.

**Comment by palisadoes** [comment]
Do you want to work on this?

**Comment by bhattabhi013** [comment]
Yes, please assign this issue to me.
