### ISSUE TITLE
Views: Create tests for set_url.dart - Part 2

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1270]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

We are at 96% code coverage for this file, but it's an important part of the code base as it determines the success of communicating with the API.

![image](https://user-images.githubusercontent.com/16875803/158201387-b93e87ef-7971-4f3b-957b-782029dc6c45.png)

Previous test work for this was done with this issue:
- https://github.com/PalisadoesFoundation/talawa/issues/1248

Tests need to be written for file `lib/views/pre_auth_screens/set_url.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/pre_auth_screens_test/set_url_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/pre_auth_screens/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal

### Section for attention

![image](https://user-images.githubusercontent.com/16875803/158202001-21995122-7a17-4889-97c4-1a2d6aa99851.png)

and

![image](https://user-images.githubusercontent.com/16875803/158203341-a454423d-5ad2-48b1-b0f6-47c3df7739ba.png)

**Comment by RandyKdev** [comment]
Good day, I would like to have a shot at this.

**Comment by palisadoes** [comment]
Reopening. We need to get this to 100% coverage.

- The current code coverage for this file can be found here:
    - https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by palisadoes** [comment]
Reopening. We need to get the coverage to 100%

- The current code coverage for this file can be found here:
    - https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list
