### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by PrabeshPP** [PalisadoesFoundation/talawa#1271]
**Describe the bug**
When the Project is run ,it throws an error saying it requires JAVA version 11. 

**To Reproduce**

1.Fork the repository.
2.Run git clone (Repo URL).
3.Run the flutter pub get command in terminal.
4.Run the develop branch in VS Code.

**Expected behavior**
Was expecting it to run on my local machine in order to contribute on this Project.

**Actual behavior**
It threw an error saying it requires Java Version 11.However,my other projects that I have been working runs perfectly.

**Screenshots**
![issue1](https://user-images.githubusercontent.com/83439329/158304251-b8d081ab-7d72-4e60-98c9-b5cb6eede578.jpg)

**Additional details**

**Comment by palisadoes** [comment]
Thanks. You will need to upgrade your SDK version to that of the Talawa project. Java 11 should work. We do all our automated testing using Java 12, and therefore should probably upgrade the gradle settings accordingly.

**Comment by PrabeshPP** [comment]
hey @palisadoes ,
should I upgrade my flutter SDK version or ?

**Comment by palisadoes** [comment]
In Android Studio you can assign a SDK version to a particular project. I'm not sure about other IDEs

**Comment by PrabeshPP** [comment]
Okay ,I will try that solution. What about on VS code??

**Comment by PrabeshPP** [comment]
Hi @palisadoes  it shows the same error even after upgrading the Java SDK version to 11.

**Comment by noman2002** [comment]
@PrabeshPP I think there is some issue with your vscode configuration. Try running `flutter doctor` to check if there is an error.

**Comment by PrabeshPP** [comment]
hi @noman2002  I did try running the flutter doctor ,but there is no error. I will re-install the VS code. Hope it would work.

**Comment by noman2002** [comment]
> hi @noman2002 I did try running the flutter doctor ,but there is no error. I will re-install the VS code. Hope it would work.

Is it working after reinstallation?

**Comment by PrabeshPP** [comment]
Even after re-installation , it's showing same error.

**Comment by noman2002** [comment]
> Even after re-installation , it's showing same error.

Text on slack. Someone will help you there for sure.

**Comment by CyberWake** [comment]
@PrabeshPP the problem is not with flutter setup the problem is with the non appropriate jdk version

**Comment by sudo-saksham** [comment]
Follow the below steps :
1) Run `flutter clean`
2) go to `android/` and run `./gradlew clean`

Repeat step 2 until it executes 100% successfully.
