### ISSUE TITLE
Remove print statements from tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1276]
**Describe the bug**
Some of our recent test suites have many print statements in them. It's best that they are removed. It makes isolating failures in our CI/CD pipeline easier.

The files that need the statements removed are:

```
test/widget_tests/pre_auth_screens/select_language_page_test.dart
test/widget_tests/pre_auth_screens/set_url_page_test.dart
```

**Comment by CyberWake** [comment]
can I work on this one @palisadoes
