### ISSUE TITLE
Import errors and missing packages/dart files

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#133]
Greetings to everyone!

I just cloned the repo on my local machine and I am facing the following issue after cloning the repo -
**Steps to reproduce:**

1.  Cloning and changing to the project on the local machine:
     

> 

     git clone https://github.com/PalisadoesFoundation/talawa.git
     cd talawa

2.  Installing the packages

> 

     flutter pub get

**Found Error**

In most of the files under `talawa/lib/views` and `talawa/lib/controllers` I am getting import errors. 

For eg:
In `talawa/lib/views/widgets/forms/edit_responsibility_form.dart`, we have two imports:
>

     import 'package:talawa/controllers/responsibility_controller.dart';
     import 'package:talawa/model/responsibility.dart';

First of all the import paths are incorrect, it should be corrected to:
>

     import 'package:talawa/lib/controllers/responsibility_controller.dart';
     import 'package:talawa/lib/model/responsibility.dart';

Secondly, even if we correct the import path then also there is no such file as `responsibility_controller.dart` in the `talawa/lib/controllers` folder or the `responsibility.dart` file in the `talawa/lib/model` folder.

Any help on this issue will be much appreciated. Thanks!

**Comment by Swayam221** [comment]
Hey @Raunakk02 ! you must be using the master branch. Switch to 2020-Q4. Also, if not already, please join the slack channel to interact and discuss issues with us all https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-nk79xxlg-OxTdlrD7RLaswu8EO_Q5rg

**Comment by utkarshshendge** [comment]
@Raunakk02 maintainers are working on it #111

**Comment by yasharth291** [comment]
#92 duplicate he should close this.

**Comment by Raunakk02** [comment]
> Hey @Raunakk02 ! you must be using the master branch. Switch to 2020-Q4. Also, if not already, please join the slack channel to interact and discuss issues with us all https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-nk79xxlg-OxTdlrD7RLaswu8EO_Q5rg

Thanks for your help! Closing this issue now
