### ISSUE TITLE
The app is using an older version of android embedding which is going to be depreciated

### ISSUE THREAD

**Issue by sidx8** [PalisadoesFoundation/talawa#134]
flutter is going to deprecate the android embedding which we are currently using in favor of the latest version we should probably migrate it to the latest version and if so I would like to work on it
![talwadart](https://user-images.githubusercontent.com/43761908/110969011-34ce8600-837e-11eb-98d9-a014b10eb917.png)

**Comment by yasharth291** [comment]
Please do not duplicate the issues. This issue is same as #111

**Comment by sidx8** [comment]
@yasharth291 sorry I did not notice it was already there
