### ISSUE TITLE
Adding Camera option in the signup page for taking the image.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#135]
As i saw there is only photo gallery option in the section of taking the profile photo a enhancement in the project will be to have camera and drive option as well along with them. @jordanliu @heyjordn

**Comment by yasharth291** [comment]
it is implemented in the pull request #117

**Comment by yasharth291** [comment]
@heyjordn @jordanliu @DeltaHarbinger could anyone of you label it and see the PR #139  regarding it please

**Comment by yasharth291** [comment]
the enhancement is made with the request merged #139

**Comment by heyjordn** [comment]
Thanks! Closing.
