### ISSUE TITLE
In login screen , keyboard covering huge portion of UI

### ISSUE THREAD

**Issue by Tanmoy741127** [PalisadoesFoundation/talawa#1371]
**Describe the bug**
For small mobile screens, the keyboard is covering the UI part for Login Screen. Which is not an user friendly.

**To Reproduce**
1. Go to Sign in Screen
2. Tap on any text edit box

**Expected behavior**
When the textedit box will be focused or keybaord is in open state, the top padding  of content need to be reduced, So that the textedit box and the button is visible to user , keyboard open state. When the focus removed or keyboard dismissed, it should rollback to old config.

**Actual behavior**
This time, if you tap on any textbox, it will open keyboard, and you can not go to next box or tap on the login button.

**Screenshots**
<img src="https://user-images.githubusercontent.com/57363826/206972212-fc7b4828-e99f-4636-8633-31e50c43f2a4.png" width="250px"/>

**Comment by Tanmoy741127** [comment]
@palisadoes I am working on the issue, please assign

**Comment by Tanmoy741127** [comment]
@palisadoes I have opened an PR at #1375 to fixed the issue. Please review that.

**Comment by palisadoes** [comment]
This issue is being reopened as the reporter bug is still present. The Pull Request was closed by the submitter without him providing a rationale.

**Comment by ALIRAZA17** [comment]
@palisadoes I am working on this issue please assign.

**Comment by ALIRAZA17** [comment]
@palisadoes I have opened a PR at #1412. Can you review that please!!
