### ISSUE TITLE
[Bug] Testing Org URL not working

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1374]
**Describe the bug**
The default Organization URL doesn't seem to be working as expected; it is returning HTML I guess. Login and Registration fail with Server Exception.

**To Reproduce**

1. Enter the Organization URL provided in Contributing.Md
2. Try to Login or Register

**Expected behavior**
User should be able to login/register

**Screenshots**

![org_url_bug_palisadoes](https://user-images.githubusercontent.com/62198564/207609416-fa0d5afa-dd57-419e-8195-9116ac4af38d.png)

**Comment by Tanmoy741127** [comment]
You have used which url ?

1. <ip>:<port>
2. <ip>:<port>/graphql

**Comment by literalEval** [comment]
https://talawa-graphql-api.herokuapp.com/graphql

this one.

**Comment by Tanmoy741127** [comment]
I don't think so this url is live now. 
Better, if you can run the [talawa-api](https://github.com/PalisadoesFoundation/talawa-api) in your local system. 
You can get guide to install talawa-api in local enviroment by docker here.
[https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#installation-using-docker](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#installation-using-docker)

**Comment by palisadoes** [comment]
@literalEval I'll try to get the URL working, but in the mean time I suggest doing the following:
1. Create a PR replacing the URL with the alternative in INSTALLATION.md
1. Update Talawa to give a meaningful message if the URL isn't available.

**Comment by literalEval** [comment]
Sure. Will do.

**Comment by literalEval** [comment]
Hello @palisadoes , INSTALLATION.md contains the exact same URL and it is still not working.
About the Error message, there is already a message in the login page if there is URL error. So I am adding an error message on the Sign Up page.

**Comment by literalEval** [comment]
Hello @palisadoes is the URL fixed now ?

**Comment by palisadoes** [comment]
No. I plan to fix it soon. I updated the documentation to only use the local docker instance. This will be sufficient until the test instance is fixed.

**Comment by literalEval** [comment]
Okay. Thanks.

**Comment by literalEval** [comment]
Hello @palisadoes, I set up talawa-api locally (the non-docker one). The server starts fine and I am able to open the GraphQL site on my machine in the browser, but it does not work in the Talawa app. I tried opening in the browser on my phone, but it doesn't open there either. 
Any solutions to this ? I am not able to run the app because of this issue.

**Comment by literalEval** [comment]
I got it working. Now how to create organizations to choose from ?

**Comment by palisadoes** [comment]
Organizations are created in Talawa Admin.

As you have issues with the setup, do you think the API documentation needs to be updated? Is so, how?

**Comment by literalEval** [comment]
Yes I do think so. I will make respective PR on the individual repos.

**Comment by palisadoes** [comment]
- Please create issues prior to generating the PR.
- Also, we have made significant improvements to the installation documentation in the past week. Updates to it may not be necessary.

**Comment by palisadoes** [comment]
I'll close this issue as the URL has been deactivated and removed from our documentation

**Comment by literalEval** [comment]
I am a contributor to this project since last year. I it's okay for you then please provide me with access to the working link. That will be of great help to me as I will the explore the app fully.
