### ISSUE TITLE
Update Talawa to give a meaningful message if the URL isn't available. 

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1378]
**Is your feature request related to a problem? Please describe.**
When I started the app and followed the setup documentation I ran into this problem, Only got to know about it after I checked out community slack

**Describe the solution you'd like**
Give proper error messages when URl isn't available

**Describe alternatives you've considered**
Give error message

**Comment by Ayush0Chaudhary** [comment]
@palisadoes please assign it to me, I'll complete this issue

**Comment by Ayush0Chaudhary** [comment]
https://github.com/PalisadoesFoundation/talawa/blob/46cf4efd53cbdbdba3e42633875c667eff4a94cf/lib/widgets/organization_list.dart#L34-L51

I went through the code and I think issue exists here.


If we set `showSnackBar = true` 
the code will try to show SnackBar while building the screen, thus throwing a error.
Am I going in right direction @palisadoes @SiddheshKukade ??

**Comment by Ayush0Chaudhary** [comment]
Hi, @palisadoes I implemented the solution, can you review it??
Please suggest changes if any required...
https://github.com/Ayush0Chaudhary/talawa/commit/c22d5937166845a2af4005c712ed0e4320ce8104

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please open a pull request against this repo

**Comment by Ayush0Chaudhary** [comment]
I opened the PR against this issue but later was asked to change the PR title
@palisadoes

**Comment by Ayush0Chaudhary** [comment]
https://github.com/PalisadoesFoundation/talawa/pull/1380

Here is the link to PR @palisadoes
