### ISSUE TITLE
Overflow on set_url page in landscape mode

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1381]
**Describe the bug**
when we rotate the screen in landscape-mode on set_url page their is a overflow of 110 pixels in my device. 
also we cannot set url in landscape mode.
**To Reproduce**

1. open the app
2. go to set url page
3. rotate the phone by 90 degrees 

**Expected behavior**
It should have not overflowed and alowwed to set url in landscape mode

**Actual behavior**
It overflowed

**Screenshots**
![issue](https://user-images.githubusercontent.com/95746190/210116911-f32e258e-ae42-4650-9e42-26750fba8141.jpg)
![issue2](https://user-images.githubusercontent.com/95746190/210116916-69394773-13fb-41c5-bb53-19bc32c174a4.jpg)

**Comment by Ayush0Chaudhary** [comment]
I want to solve this issue @palisadoes

As solution I can fix it in portrait mode or just fix the overflow? 

What do you suggest, which approach I should follow??

**Comment by Ayush0Chaudhary** [comment]
@SiddheshKukade I want to work on this.

**Comment by TheHazeEffect** [comment]
> @SiddheshKukade I want to work on this.

Hey, for now we're thinking of locking the app to be portrait mode only

**Comment by palisadoes** [comment]
@Ayush0Chaudhary  Are you still working on this?

**Comment by Ayush0Chaudhary** [comment]
I completed this issue and raised the PR.
The PR was not reviewed.

There was some issue with your code dev report, I commented my research on code dev report issue in the PR.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes
