### ISSUE TITLE
Improve Talawa-Admin Installation Documentation for Talawa

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1389]
In Talawa's  [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/INSTALLATION.md) document under the `Developer Environment Setup` heading, there is extensive setup instructions for `Talawa-Admin` where they should be in the `Talawa-Admin` [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md) file instead. The Talawa instructions must be updated when this is done.

Where necessary we need to update both the documentation and the code base accordingly.

This is a joint issue with: https://github.com/PalisadoesFoundation/talawa-admin/issues/390

**Comment by AmanGit010** [comment]
So we basically want to move the instructions provided under Developer Environment Setup in the Talawa's instruction.md file to Talawa-admin's instruction.md file right? and also update the Talawa instructions for setting up the developer environment locally for Flutter.

I would love to work on this issue, please assign me this issue. @palisadoes

**Comment by SiddheshKukade** [comment]
I think we should just add a link pointing out to this [`INSTALLATION.md` ](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md) file. to fix this.

**Comment by palisadoes** [comment]
> So we basically want to move the instructions provided under Developer Environment Setup in the Talawa's instruction.md file to Talawa-admin's instruction.md file right? and also update the Talawa instructions for setting up the developer environment locally for Flutter.
> 
> I would love to work on this issue, please assign me this issue. @palisadoes

@AmanGit010

1. It requires accepting to fixing this and the joint issue with: https://github.com/PalisadoesFoundation/talawa-admin/issues/390. There will need to be code changes with this issue.
2. Yes, we should move the section in this to the just link to the Talawa-Admin [INSTALLATION.md ](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md) file.

So...

1. Are you willing to do both? Typescript knowledge will be necessary.
1. Can you complete this over the weekend? If not I'll have to reassign it.

**Comment by palisadoes** [comment]
@SiddheshKukade Please also add a table of contents to this INSTALLATION.md file for readability

**Comment by AmanGit010** [comment]
> I think we should just add a link pointing out to this [`INSTALLATION.md` ](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md) file to fix this. I'd like to take this if that's okay.

I was working on this, anyways no problem 
go ahead 👍🏻
