### ISSUE TITLE
Test: lib/widgets/task_schedule.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1396]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
organization_list.dart 
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002  please assign me this PR

**Comment by Adiii1436** [comment]
Hello @palisadoes ! I want to work on this issue . Please assign this issue to me.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 can you assign me this, my PR is waiting for review, and only 1 issue assigned

**Comment by literalEval** [comment]
@Ayush0Chaudhary are you still working on this issue ? If no, then please assign this to me.

**Comment by Ayush0Chaudhary** [comment]
Still working on it, will complete my PR by today.🤞
