### ISSUE TITLE
Test: lib/widgets/task_form.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1397]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
organization_list.dart 
```

This file can be found in the `lib/widgets` directory

Parent Issue: 
- https://github.com/PalisadoesFoundation/talawa/issues/1125

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/widgets)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- No functionality must be removed to achieve this goal

**Comment by Ayush0Chaudhary** [comment]
does this issue needs the unittest for **organization_list.dart ** as it says 

---------------------->
Any widgets referenced in this file must also have unittests done
`organization_list.dart `

If no, can you assign me this @palisadoes @noman2002 my PR is just waiting for review??

**Comment by literalEval** [comment]
@palisadoes I would like to work on this issue.

**Comment by palisadoes** [comment]
@literalEval You already have two issues assigned.

**Comment by aks-2101** [comment]
@palisadoes @noman2002 please assign me this issue.

**Comment by literalEval** [comment]
@palisadoes since there is no response from @aks-2101, please assign this to me.

**Comment by palisadoes** [comment]
@literalEval 'm unassigning. You have other issues to work on.

**Comment by Manik2708** [comment]
@palisadoes @noman2002 Can you assign this issue to me?

**Comment by Cioppolo14** [comment]
@Manik2708 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Once you have less than 2 issues, feel free to tag me and comment on the next open issue you'd like.

**Comment by Dante291** [comment]
@Cioppolo14 @palisadoes This can be closed as we are removing Tasks feature
