### ISSUE TITLE
Views: Create tests for event_tasks_page.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1400]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/tasks/event_tasks_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/tasks/event_tasks_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/tasks/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by dkgoutham** [comment]
I would like to work on this!

**Comment by aks-2101** [comment]
@palisadoes @noman2002 can you assign me this issue??

**Comment by aks-2101** [comment]
if @dkgoutham is unable to do this.

**Comment by noman2002** [comment]
@dkgoutham Any progress ?

**Comment by noman2002** [comment]
Unassigning due to inactivity

**Comment by noman2002** [comment]
> if @dkgoutham is unable to do this.

You already have 2 issues in your name. And that is the maximum limit. Please get the PRs merged first.

**Comment by ikjot-2605** [comment]
@noman2002 @palisadoes can I work on this?

**Comment by palisadoes** [comment]
@ikjot-2605 You already have two signed issues

**Comment by ikjot-2605** [comment]
@palisadoes could I work on this now, since I only have one assigned issue - the PR for which is ready.

**Comment by Dante291** [comment]
@palisadoes This can be closed as we are removing Task feature.
