### ISSUE TITLE
Views: Create tests for edit_task_page.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1401]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/tasks/edit_task_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/tasks/edit_task_page_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/tasks/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by iamansoni** [comment]
Hi @palisadoes!
I have created the above PR to resolve this issue, do review it once.

**Comment by noman2002** [comment]
Please get the issue assigned to you before creating a PR. Please follow the procedure. Hopefully you'll understand.

**Comment by noman2002** [comment]
Assigned this to you. Now you can work on it and create PR.

**Comment by literalEval** [comment]
I would like to work on this issue. Please assign to me if not being actively worked upon.

**Comment by usmanIITR** [comment]
I would like to contribute to this issue.

**Comment by noman2002** [comment]
@iamansoni Are you still working on this?

**Comment by iamansoni** [comment]
Hi @noman2002!
I won't be able to take this up anytime soon, 
plz, feel free to assign this to someone else.

**Comment by palisadoes** [comment]
@usmanIITR I'm assigning this to you as a newcomer.

**Comment by noman2002** [comment]
@usmanIITR Any update on this one?

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by ikjot-2605** [comment]
@noman2002 @palisadoes can I work on this?
