### ISSUE TITLE
Views: Create tests for event_info_body.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1404]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/events/event_info_body.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/events/event_info_body_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/events/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by literalEval** [comment]
I would like to work on this issue and make the tests reach 100%. Please assign it to me.

**Comment by literalEval** [comment]
@noman2002 @CyberWake @TheHazeEffect I need some help regarding testing. 

In this particular block, there is conditional rendering based on whether the view model is busy or not. How to test this functionality ? I mean how to set the view model to be busy and idle on wish ?

![image](https://user-images.githubusercontent.com/62198564/216932166-30f04aaa-2da3-462a-b64e-152fc93b0d8e.png)

**Comment by literalEval** [comment]
I figured it out. The setState method is already exposed to the viewModel. Leaving the comments as it is so that maybe someone can find in the future.
