### ISSUE TITLE
Views: Create tests for chat_input_field.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1406]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/widgets/chat_input_field.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/chat/widgets/chat_input_field_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/chat/widgets/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by literalEval** [comment]
I would like to work on this issue if @Sudhanva-Nadiger is not actively working.

**Comment by Sudhanva-Nadiger** [comment]
I am working on it !

**Comment by usmanIITR** [comment]
@palisadoes , can you please assign this issue to me ?

**Comment by Skdahale** [comment]
@palisadoes Can i work on this issues

**Comment by noman2002** [comment]
@usmanIITR Any update ?

**Comment by noman2002** [comment]
@Skdahale Assigned you one issue. Please work on it and get the PR merged.

**Comment by usmanIITR** [comment]
Also I didn't get the notification that you mentioned me, so missed your message

**Comment by usmanIITR** [comment]
I'll try to complete easy issues

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @xoldyckk @TheHazeEffect can you please assign me this.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary You already have 2 issues assigned.

**Comment by ikjot-2605** [comment]
@palisadoes @noman2002 I have created 2 PRs for my currently assigned issues. Could you assign me this as well, so that I can keep working on the project?

**Comment by palisadoes** [comment]
@ikjot-2605 You already have two issues. I made an exception before, however we also need to consider others getting a chance to contribute. Please wait until at least one of your other PRs are merged.

**Comment by ikjot-2605** [comment]
> @ikjot-2605 You already have two issues. I made an exception before, however we also need to consider others getting a chance to contribute. Please wait until at least one of your other PRs are merged.

Understood, apologies for the inconvenience.

**Comment by Kushalrock** [comment]
@palisadoes May I take up this issue? As I have already completed my app localization test ting with complete code coverage.

**Comment by jadeharr** [comment]
@Kushalrock You have two issues open. Please wait until at least one of your other PRs have been merged.

**Comment by Kushalrock** [comment]
@jadeharr Ya I am waiting for review it's been some time. I thought in the meanwhile I could take up one more issue. This issue interested me so i commented on it.

**Comment by Kushalrock** [comment]
@palisadoes Now can I take up this issue? Thank you...
