### ISSUE TITLE
Views: Create tests for chat_message_screen.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1408]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/chat_message_screen.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/chat/chat_message_screen_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/chat/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by antonio-pedro99** [comment]
@noman2002  can you assign it to me?

**Comment by palisadoes** [comment]
@antonio-pedro99 You already have 4 assigned issues: https://github.com/PalisadoesFoundation/talawa/issues/assigned/antonio-pedro99 Please wait until your outstanding PRs are merged

**Comment by antonio-pedro99** [comment]
@palisadoes i have unsigned one of them to work specifically on this.

**Comment by noman2002** [comment]
@antonio-pedro99 Any update on this one ?

**Comment by antonio-pedro99** [comment]
@noman2002 Hi! I have started solving it but I had to stop due to some college works. I will continue and make PR during the weekend only!

**Comment by noman2002** [comment]
@antonio-pedro99 Its been more than 2 weeks. Please update the progress. If you are having some trouble, please give others a chance.

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes can you please assign me this??

**Comment by Ayush0Chaudhary** [comment]
unassigning myself because of https://github.com/PalisadoesFoundation/talawa/issues/1573

**Comment by ikjot-2605** [comment]
Hi @palisadoes, could I work on this issue?
