### ISSUE TITLE
View Model: Tests for select_contact_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1410]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
after_auth_view_models/chat_view_models/select_contact_view_model.dart
```

This file can be found in the `lib/view_model` directory

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1003

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/view_model/after_auth_view_models/chat_view_models)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by Ayush0Chaudhary** [comment]
@noman2002 assign me this please!
@palisadoes
