### ISSUE TITLE
`flutter analyze --no-pub` command failing in our GitHub action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1413]
**Describe the bug**

We recently had to change our `setup-java` GitHub action to `v3` as the version we were using will be deprecated shortly. We also updated the `checkout` action to `v3` for similar reasons. The changes can be found in [pull-request.yml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml) and [push.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/push.yaml)

- This change has possibly altered the output of the `flutter analyze --no-pub` command used in the GitHub action and/or
- We merged a PR in the past that contained errors

This has lead to errors in the [Checking codebase](https://github.com/PalisadoesFoundation/talawa/actions/runs/4001226394/jobs/6867319973#logs) stage of our GitHub action. See the link for a recent example.

**Note:** This error didn't start occurring until the #1412 PR was submitted, which also has the same error. The new `checkout` action for pushes may be checking out  code at the commit of the most recent PR. This will need to be investigated. [Checkout Action Documentation](https://github.com/actions/checkout)

- PRs should checkout the commit of the PR. 
- Pushes should checkout the commit of the most recently merged PR.

The current errors are:

1. `error • Too many positional arguments: 0 expected, but 1 found • lib/view_model/main_screen_view_model.dart:105:7 • extra_positional_arguments_could_be_named`
1. ` error • The named parameter 'context' is required, but there's no corresponding argument • lib/view_model/main_screen_view_model.dart:125:8 • missing_required_argument`
1. `error • The getter 'channel' isn't defined for the type 'MethodChannelFirebase' • test/helpers/setup_firebase_mocks.dart:22:25 • undefined_getter`

This needs to be resolved that there are no errors with the `flutter analyze --no-pub` command completing successfully.

**To Reproduce**
Run the `flutter analyze --no-pub` command

**Expected behavior**
Command passes

**Actual behavior**
Command fails

**Screenshots**
N/A

**Additional details**
N/A

**Comment by noman2002** [comment]
I am working on this.
