### ISSUE TITLE
Models: Tests for user_info.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1416]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/user/user_info.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/user)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by literalEval** [comment]
I would like to work on this issue. Please assign it to me.
