### ISSUE TITLE
Models: Tests for post_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1417]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/post/post_model.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/post)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by arunavabasu-03** [comment]
@tonythegr8 @nesiann @noman2002 , can I work on this ??

**Comment by noman2002** [comment]
@arunavabasu-03 I am unassigning this. Because You already have 2 issues assigned to you. Please create a PR for them. Thank you.

**Comment by arunavabasu-03** [comment]
Ok

**Comment by noman2002** [comment]
Okay no problem.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes assign me this please, I think I can do this!
