### ISSUE TITLE
Models: Tests for org_info.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1419]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/organization/org_info.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/organization)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by arunavabasu-03** [comment]
@tonythegr8 @nesiann @noman2002 , can I work on this ??

**Comment by literalEval** [comment]
I would like to work on this issue if no progress is being made.

**Comment by palisadoes** [comment]
@literalEval Please consider https://github.com/PalisadoesFoundation/talawa/issues/1418 to another file in the same directory. It is unassigned.

**Comment by literalEval** [comment]
#1418 is a helper file and will be automatically tested if this issue is done correctly. Also, #1418 can't be tested in isolation from #1419 as both files work together.

**Comment by palisadoes** [comment]
Thanks for the clarification.

**Comment by literalEval** [comment]
@palisadoes I think @arunavabasu-03 is busy and I would like to fix this issue.

**Comment by palisadoes** [comment]
I'm going to unassign and see if anyone else is willing to try.

**Comment by droy312** [comment]
Can I work on this issue?
