### ISSUE TITLE
Overflowing widget issue + unexpected character

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#142]
![Screenshot_20210313-152044](https://user-images.githubusercontent.com/51524156/111026499-90495400-8410-11eb-9880-9072775e8b0a.png)

I tried to sign up and used basic characters as my password and username. An exception was thrown and that exception widget was overflowing. I would like to work on this issue.

![Screenshot (188)](https://user-images.githubusercontent.com/51524156/111026508-9a6b5280-8410-11eb-8eb1-ca534c3aafe8.png)

**Comment by pr4nshul** [comment]
I used a dot(.) in my email , and my password didn't have any special characters just capital and small letters and a number.

**Comment by pr4nshul** [comment]
Also when you click sign up , the keyboard doesn't disappear hence the exception is not easily visible to the user at once.

**Comment by yasharth291** [comment]
please read the closed issues these all are over @pr4nshul  please close it as it is duplicate

**Comment by pr4nshul** [comment]
Ok , so how do I register. Because right now I can't I have tried various permutations.

**Comment by yasharth291** [comment]
first you have to go to the another branch of the same which is 2020-Q4

and then set up the backend locally and then signup

**Comment by yasharth291** [comment]
if your doubt is clear you can close this issue

**Comment by pr4nshul** [comment]
Well, this is 2020-Q4 branch. Although I haven't setup backend locally. Do you have any steps for doing the same?

**Comment by yasharth291** [comment]
yeah read the documentation in the talawa-api

**Comment by yasharth291** [comment]
and please close this issue as it is duplicate
