### ISSUE TITLE
Models: Tests for event_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1420]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/events/event_model.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/events)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by arunavabasu-03** [comment]
can i work on this ??

**Comment by palisadoes** [comment]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by arunavabasu-03** [comment]
@tonythegr8
@nesiann
@noman2002 , can I work on this ??

**Comment by noman2002** [comment]
sure, Go ahead.

**Comment by arunavabasu-03** [comment]
@noman2002 , i unassigning this !! 😅

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes can you assign me this issue?? I know my 2 PRs are not merged. but I find this issue interesting and want to work on it
.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes can you assign me this issue??
