### ISSUE TITLE
Models: Tests for comment_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1421]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/comment/comment_model.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/comment)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by arunavabasu-03** [comment]
@tonythegr8 @nesiann @noman2002 , can I work on this ??

**Comment by noman2002** [comment]
@arunavabasu-03 I have already assigned you 2 new issues please work it. More that 2 issues can't be assigned at single time. Please create a PR for the assigned issues first. Thank you.

**Comment by arunavabasu-03** [comment]
Ok , thanks for informing 😀

**Comment by Ayush0Chaudhary** [comment]
@noman2002 can i do this issue??

**Comment by palisadoes** [comment]
@Ayush0Chaudhary You are already assigned 4 issues. Please wait until your outstanding PRs are merged.

Thanks for your and @arunavabasu-03 's enthusiasm.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 assign this issue to me

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @SiddheshKukade @TheHazeEffect

**Comment by noman2002** [comment]
@Ayush0Chaudhary Please try to get the open PRs merged before working on new issues. You already have 4 issues assigned to you and 3 PRs are still open. Try to fix the failing tests and make the suggested changes and get it merged. Thank You.

**Comment by Ayush0Chaudhary** [comment]
@noman2002 can you assigned me this now, only 1 PR left and only 1 issue related to that PR only is assigned to me

**Comment by noman2002** [comment]
Sure , you can work on this now. Good work so far.

**Comment by Ayush0Chaudhary** [comment]
thank you @noman2002
