### ISSUE TITLE
Models: Tests for chat_message.g.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1424]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/chats/chat_message.g.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/chats)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by antonio-pedro99** [comment]
@noman2002 as I worked on #1425, can I work on this?

**Comment by literalEval** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by literalEval** [comment]
But this file is a part of chat_message.dart and thus the test of chat_message.dart which I wrote earlier already covers this file too. Codecov shows 100% for this file. I think this issue should be closed. If you think otherwise, do let me know.
