### ISSUE TITLE
Models: Tests for chat_message.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1425]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/chats/chat_message.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/chats)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by antonio-pedro99** [comment]
@palisadoes can I work on this?

**Comment by palisadoes** [comment]
Please coordinate with the contributors referenced in the issue.

**Comment by antonio-pedro99** [comment]
@noman2002 it seems that ChatUser is not fully serializable. 
check the output in here:
{_id: 1, sender: Instance of 'ChatUser', receiver: Instance of 'ChatUser', messageContent: Hello, how are you?}

when I call `final json = chatMessage.toJson()`

I do have the chat_user.g.dart and chat_message.g.dart files, but still it is not serializing properly. any suggestion?

**Comment by noman2002** [comment]
@palisadoes Your thought?

**Comment by antonio-pedro99** [comment]
@noman2002  I do not have experience  with object serialization yet, but allow me sometime to learn about it.
My thoughts now are that this should be printed
{_id: 1, sender: {...}, receiver: {...}, messageContent: Hello, how are you?}
as the objects are serializable.

**Comment by antonio-pedro99** [comment]
I just took a look at https://docs.flutter.dev/development/data-and-backend/json and found a possible solution.

**Comment by noman2002** [comment]
@antonio-pedro99 I don't think there is any issue with serialisation. It shows like that because we are using models for that and that is being printed over there as Instance of 'chatuser'.

**Comment by noman2002** [comment]
> I just took a look at https://docs.flutter.dev/development/data-and-backend/json and found a possible solution.

Sure go ahead.

**Comment by antonio-pedro99** [comment]
@noman2002 fixed! 

`@JsonSerializable(explicitToJson: true)
class ChatMessage {
  ChatMessage(
    this.id,
    this.sender,
    this.messageContent,
    this.receiver,
  );

  factory ChatMessage.fromJson(Map<String, dynamic> json) =>
      _$ChatMessageFromJson(json);
  Map<String, dynamic> toJson() => _$ChatMessageToJson(this);

  String? id;
  ChatUser? sender;
  ChatUser? receiver;
  String? messageContent;
}`

**Comment by noman2002** [comment]
Great. Have you written the test for it? If yes, check the code coverage, if it is 100%, Please create a PR for it.

**Comment by antonio-pedro99** [comment]
@noman2002 how can I check the coverage?

**Comment by shivanshu814** [comment]
I want to contribute to this repository and want to get involved in GSoC discussions.

**Comment by noman2002** [comment]
You can join the slack channel @shivanshu814

**Comment by palisadoes** [comment]
> @noman2002 how can I check the coverage?

Please check the CONTRIBUTING.md file in the repository's root directory. If the instructions are not sufficient then let me know
