### ISSUE TITLE
Models: Tests for chat_list_tile_data_model.g.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1426]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/models/chats/chat_list_tile_data_model.g.dart
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa/issues/1414

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/models/chats)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by droy312** [comment]
Can I work in this issue? @palisadoes

**Comment by droy312** [comment]
The code coverage of this file is already 100%.
I believe the test for this file was already covered in PR #1433 
![Capture](https://user-images.githubusercontent.com/37190888/215345673-e179eaf1-45a4-4362-947d-e30a2aa363e1.PNG)
