### ISSUE TITLE
Making indicator for strong password

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#143]
writing regex for the strong password will help it to become stronger

**Comment by yasharth291** [comment]
@DeltaHarbinger @heyjordn @jordanliu

**Comment by yasharth291** [comment]
#144  i have made a proposal for the same @DeltaHarbinger you can tell me if i have to do some changes on it.

**Comment by Sagar2366** [comment]
Closing this issue as fixed in https://github.com/PalisadoesFoundation/talawa/pull/158
