### ISSUE TITLE
Update set_url_page_test.dart: Remove herokuapp.com reference

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1435]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359
 
We are no longer using the `talawa-graphql-api.herokuapp.com` domain as an external API testing URL. This is because we had no feasible way of controlling access, cost and long term maintainability. This file has these references to the URL which must be removed.

Testing integrity must be maintained. Removing the specific tests is not an acceptable solution

```
talawa/test/widget_tests/pre_auth_screens/set_url_page_test.dart:248:        'https://talawa-graphql-api.herokuapp.com/graphql',
talawa/test/widget_tests/pre_auth_screens/set_url_page_test.dart:320:        'https://talawa-graphql-api.herokuapp.com/graphql',
talawa/test/widget_tests/pre_auth_screens/set_url_page_test.dart:580:        'https://talawa-graphql-api.herokuapp.com/graphql',
```

**Comment by StarTrooper08** [comment]
Hello @palisadoes can I work on this issue?
I think I can solve this issue

**Comment by literalEval** [comment]
I would like to fix this issue. Please assign it to me if not being actively worked upon.

**Comment by StarTrooper08** [comment]
I'm working on it @literalEval

**Comment by noman2002** [comment]
@StarTrooper08 Any update ?

**Comment by StarTrooper08** [comment]
I'm stucked at dev setup

**Comment by palisadoes** [comment]
@StarTrooper08 Please work with the community on our #talawa slack channel to help you get things set up. The documentation has been greatly improved recently and it should be easier. There is a working Talawa-API instance that is mentioned in a pinned post.

I'll unassign you. Let us know when you are ready. You may have to work on another issue at that time as this one may be reassigned.

**Comment by StarTrooper08** [comment]
Ok np

**Comment by Skdahale** [comment]
Can I work on this issue?
@palisadoes

**Comment by Digu650** [comment]
Can i work on this issue as this would open the gate of open source for me??

**Comment by noman2002** [comment]
@Digu650 Sure, please proceed. All the best. And Welcome to *THE PALISADOES FOUNDATION*.

**Comment by palisadoes** [comment]
Unassigning due to lack of activity

**Comment by Amogh35** [comment]
I would like to work on this issue
