### ISSUE TITLE
Utilize TalawaErrorWidget Throughout App

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1437]
1. We do not have a standardized error reporting scheme
1. We recently created TalawaErrorWidget for handling errors. We need use it for all our error messages.

Ideally there should be ways to adjust the output depending on the error severity for example:

1. Warning
2. Info
3. Error

Additionally:

1. The error messaging must also adjust any text to match the user's selected language of choice
2. The methodology must output messages to the console for ease of troubleshooting

**Comment by prathamesh-mutkure** [comment]
Hello @palisadoes, I'd like to work on this issue

**Comment by palisadoes** [comment]
1. We are focusing on bugs and testing issues. 
1. When we get back to working on features we'll need to discuss a design for the messages. The existing widget may not meet the needs of all use cases and will have to be adjusted accordingly, or new widgets may need to be created.

**Comment by prathamesh-mutkure** [comment]
Okay, so we are not working on this issue for a while, right?

**Comment by palisadoes** [comment]
Correct

**Comment by shivanshu814** [comment]
I want to contribute to this repository and want to get involved in GSoC discussions.

**Comment by Ayush0Chaudhary** [comment]
Yes, we can create something like this for showing errors, info, warning.
 
We can tweak part of the dialog to show _warning, info, and errors._ 

For this we can add argument in TalawaErrorWidget for ex. 
`navigationService.showTalawaErrorDialog("Enter a validpassword", type: ErrorType.warning);`

here ErrorType can be a enum like
`enum ErrorType { error, warning, info }`

We should definitely add **multi language** functionality, 
It will be good idea if we add **debugPrint** statement for these method so in future it will be easier to debug

@palisadoes @noman2002 @SiddheshKukade @TheHazeEffect

**Comment by Ayush0Chaudhary** [comment]
Can I work on this?? @noman2002 @TheHazeEffect

**Comment by Ayush0Chaudhary** [comment]
![Screenshot from 2023-02-16 00-03-46](https://user-images.githubusercontent.com/95746190/219363706-d810c85a-d843-4ecb-89c6-c1a143e6bff0.png)

@palisadoes @noman2002 what about these pop up, should I make something like these??

**Comment by palisadoes** [comment]
Yes and also consider how they would work if there is so much text that it scrolls off the screen

**Comment by Ayush0Chaudhary** [comment]
ok @palisadoes  i'll keep that in mind.

**Comment by palisadoes** [comment]
Also ensure that the errors support multilingual needs.

**Comment by Ayush0Chaudhary** [comment]
Sure

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @xoldyckk @SiddheshKukade @TheHazeEffect 

 the feature of adding multilingual needs is time consuming and boring.
it will get a little late for PR as my Mid-exams are also going on.
sorry for delay!
only multilingual part is left rest is finished
