### ISSUE TITLE
Update method of User class updates wrongly.

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1438]
**Describe the bug**
update method of User class has abnormality (due to copy paste I guess). Currently it updates firstName, lastName, email and image to firstName

**Expected behavior**
Attributes should update correctly.

**Actual behavior**
4 attributes are updating to a single value.

**Screenshots**
![image](https://user-images.githubusercontent.com/62198564/215250087-b092e2ed-cdd4-45b6-921e-c59e7f35cab4.png)

@palisadoes please assign this to me.

**Comment by palisadoes** [comment]
This means the tests for the class are incomplete. Please ensure that the tests for the file in which this class is listed has 100% code coverage as part of the PR to resolve this issue

**Comment by literalEval** [comment]
Actually I was working on its test and found out this issue. Will resolve of of them.

**Comment by palisadoes** [comment]
I'm going to close both the PR and the issue. The aim of doing tests is to fix bugs that are found as part of the process. Creating a bug for every testing error found creates more work for our team of volunteers. Please respect their time.

**Comment by literalEval** [comment]
Understood. From next time I will add the code modifications in the test itself. Sorry for inconvenience.
