### ISSUE TITLE
[Update Installation.md] Outdated typo mistakes

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa#1453]
**Describe the Issues:**
1. in the Installation.md Under the [Apply the Firebase Keys to the Talawa Mobile App](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#apply-the-firebase-keys-to-the-talawa-mobile-appl) section in the 14.  & 15. point, **it says to add the parameters of firebaseOptions to the .env file under the android/IosFirebaseOptions heading, but the  .env file does not contain any android/ios heading.** check out the screenshot below !

![firebaseOptions parameteres](https://user-images.githubusercontent.com/115649011/215825124-cd34b50b-8925-4078-b73d-89cadff4db9d.png)

2. under the [Creating .env file](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#creating-env-file) section **there is a typo error ".env.sample" wherein it is ".env.example" file.**

![Screenshot 2023-01-31 221852](https://user-images.githubusercontent.com/115649011/215828164-8dffd33b-748d-41bf-abd7-21c4f1619f12.png)

**.env.example file Screenshot**
![Screenshot 2023-01-31 221852](https://user-images.githubusercontent.com/115649011/215828691-daadfd65-1ffd-424b-a00d-3e2b3052f479.png)

**Assign me this issue so that I can update this ASAP!!!**

**Comment by palisadoes** [comment]
If you search the `.env.sample` file you will find lines with the following strings commented out:

1. `androidFirebaseOptions`
1. `iosFirebaseOptions`

The documentation is correct.

There is no `.env.example` the documentation references [.env.sample](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.env.sample) which is correct.

The documentation is correct in both cases.

**Comment by palisadoes** [comment]
I'm going to close this issue.

**Comment by saadabban76** [comment]
> If you search the `.env.sample` file you will find lines with the following strings commented out:
> 
> 1. `androidFirebaseOptions`
> 2. `iosFirebaseOptions`
> 
> The documentation is correct.
> 
> There is no `.env.example` the documentation references [.env.sample](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.env.sample) which is correct.
> 
> The documentation is correct in both cases.

on cloning the talawa_admin reprository, you will the file called .env.example in the root directory check out the below screenshot .
![Screenshot 2023-01-31 221852](https://user-images.githubusercontent.com/115649011/215832452-8203fb2a-5136-4618-93db-5507727bbd7b.png)

**Comment by palisadoes** [comment]
- Thanks, but it is not there: https://github.com/PalisadoesFoundation/talawa-api
- Please sync with the latest versions of the code base
