### ISSUE TITLE
Adding Hide/Show Password feature in the Login and Register Forms

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#146]
A button needed which can hide and show password as per requirement in the Login and Register form fields. 

#145 opened for this.

**Comment by heyjordn** [comment]
Ok thanks! Will review shortly

**Comment by DeltaHarbinger** [comment]
Hey @CoderMayhem, I made a comment on the pull request you created. Take a look as it requires attention

**Comment by CoderMayhem** [comment]
@DeltaHarbinger did the needful. PR ready for review.

**Comment by Sagar2366** [comment]
Closing this issue as fixed in https://github.com/PalisadoesFoundation/talawa/pull/207
