### ISSUE TITLE
GitHub Actions not failing on warnings

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1467]
**Describe the bug**
Our `Codebase testing` section of our [pull-request.yml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/pull-request.yml) GitHub action is not failing on warnings. This means:

1. Tests are not sufficiently verifying code operation
1. Our code base is more prone to a poor UX.

Many of the tests that are failing are for widgets and the warnings imply screen overflow concerns. 

**To Reproduce**

## Method 1
Follow these steps:
1. Take a look at this [recent GitHub Action run](https://github.com/PalisadoesFoundation/talawa/actions/runs/4107719370/jobs/7087567772)
2. Click on the `Codebase testing` section and scroll to the various warnings

## Method 2
Follow these steps:
1. Run the `flutter test --coverage` command in the root directory of the repo

Here is some sample output:

```
Warning: A call to tap() with finder "exactly one widget with text "Next" (ignoring offstage widgets): Text("Next", inherit: true, color: Color(0xff008a37), size: 18.0, weight: 400, dependencies: [DefaultTextStyle, MediaQuery, _ScrollableScope])" derived an Offset (Offset(400.0, 676.1)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot receive pointer events.
Indeed, Offset(400.0, 676.1) is outside the bounds of the root of the render tree, Size(800.0, 600.0).
The finder corresponds to this RenderBox: RenderParagraph#298a5 relayoutBoundary=up3
The hit test result at that offset is: HitTestResult(HitTestEntry<HitTestTarget>#d3eb1(RenderView#d9235), HitTestEntry<HitTestTarget>#25b59(<AutomatedTestWidgetsFlutterBinding>))
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:956:25)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:839:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:273:18)
#3      main.<anonymous closure> (file:///home/runner/work/talawa/talawa/test/widget_tests/pre_auth_screens/signup_details_test.dart:205:18)
<asynchronous suspension>
#4      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:125:47)
<asynchronous suspension>
To silence this warning, pass "warnIfMissed: false" to "tap()".
To make this warning fatal, set WidgetController.hitTestWarningShouldBeFatal to true.
```

**Expected behavior**
1. Tests fail on warning both from the CLI and in the GitHub action
1. Existing tests that fail with warnings must be fixed. The affected files must attain 100% test code coverage.
1. The overall test code coverage must not decline

**Actual behavior**
See above

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/217125741-57fd1830-ef4c-42c8-9746-0e3cc0c1daaa.png)

**Additional details**
N/A

**Comment by chiggshiggs** [comment]
I want to work on this  issue, please assign it to me.

**Comment by chiggshiggs** [comment]
On looking into the issue, a possible solution was to declare bool `hitTestWarningShouldBeFatal = false` in  a file that is usually flutter_test_config.dart, (https://api.flutter.dev/flutter/flutter_test/WidgetController/hitTestWarningShouldBeFatal.html).

So in our case, what file would it be?

**Comment by palisadoes** [comment]
@literalEval please fix the warnings as part of the issue.

**Comment by literalEval** [comment]
Will try to do this once I get Custom Lint integration and GraphQL Scalar migration done. Sorry for being late.

**Comment by palisadoes** [comment]
@chiggshiggs Do you still want to work on this

**Comment by chiggshiggs** [comment]
@palisadoes i ll be working on this one

**Comment by palisadoes** [comment]
There has been no follow up discussion on your progress on this issue, nor a PR submitted. Please submit a PR in the next day or I'll need to reassign it.

**Comment by literalEval** [comment]
@palisadoes please assign this to me. I will fix this in conjunction with #1660

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Azad99-9** [comment]
@noman2002 @palisadoes @Cioppolo14 @Kevoniat please assign this issue to me.

**Comment by Azad99-9** [comment]
@Cioppolo14 please assign this issue to me.
