### ISSUE TITLE
Unittest for router.dart

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1473]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

Router is important part of the app, it makes sure that correct screen shows up when asked for.

I'll like to have 100% coverage in this file

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 can we do this issue??

**Comment by Ayush0Chaudhary** [comment]
can you assign it to me if possible.

**Comment by prathamesh-mutkure** [comment]
Hi @noman2002, can I be assigned this issue if no one is working on this?

**Comment by noman2002** [comment]
@prathamesh-mutkure You have 3 issues assigned. As per the rule "maximum of 2 issues can be assigned at once". I request you to please unassign any one of those 3 which you are not working currently or I'll have unassign any one randomly. Thank You.

**Comment by prathamesh-mutkure** [comment]
Sure I'll unassign from Issue 1481

**Comment by palisadoes** [comment]
Unassigning due to lack of activity. We need to give others a chance.

**Comment by Azad99-9** [comment]
@aashimawadhwa could please assign this issue to me.
