### ISSUE TITLE
Write a tutorial on Flutter Testing

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1481]
Recently I have seen a couple of test PRs which are
- Not covering all the cases of the file
- Importing unnecessary files
- Not generating/using mocks properly
- .....

**Describe the solution you'd like**
I would like to write some sort of documentation on testing with Flutter so that
- Beginners will get a decent resource to start with
- New-comers will get to know about the existing mocks, stubbs that we already have and can you them

**Describe alternatives you've considered**
An alternative could be to document/comment the mocks and stubbs themselves, but I think creating a webpage/documentation page would be a better idea.

**Approach to be followed (optional)**
- What are tests and why do we need them ?
- How to cover all the corner cases ?
- How to start with Flutter testing ?
- What are mocks and to generate them ?
- How to stub methods and classes ?
- What to do if you find a bug while writing test for that file ?
- .....

**Comment by palisadoes** [comment]
Thanks. This is really needed.
1. This needs to be added to the CONTRIBUTING.md file.
1. However, please focus on that linting issue. That's a game changer, and it would be really sweet if we could make it into a `GitHub Action` as another Palisadoes repo!

**Comment by literalEval** [comment]
Sure. I will work on the linting issue along with other small issues. Since it is a huge task in itself and will require some time and work, I will maybe use fun issues like this one for taking a break from it for some time :)

**Comment by noman2002** [comment]
@literalEval Sorry I can't assign this. You are way too above the limit.

**Comment by literalEval** [comment]
I have already created PRs for 2 of them :) Have complete half of one of the issues and started the documentation one. Also, this is a fun thing to do (writing an article), so I think I can do it.

**Comment by prathamesh-mutkure** [comment]
Hey @noman2002, can I work on this?

**Comment by literalEval** [comment]
@prathamesh-mutkure I am already working on this. Have already wrote half of the article.

**Comment by palisadoes** [comment]
It's not assigned to anyone. Both of you have two open issues.

Either wait until your PRs are merged otherwise we'll assign it to someone else.

Everyone needs a chance

**Comment by SumantxD** [comment]
@noman2002 can you please assign me this issue

**Comment by literalEval** [comment]
@palisadoes @noman2002 please assign this to me.

**Comment by palisadoes** [comment]
Ravi, you have two issues. Please return when they are completed

**Comment by noman2002** [comment]
@prathamesh-mutkure Please go ahead.
@literalEval You have already worked on various PRs. Let him work on this one.

**Comment by ALIRAZA17** [comment]
@palisadoes Can I work on this one?

**Comment by literalEval** [comment]
@ALIRAZA17 Welcome to Palisadoes !! please make sure you write a thorough testing guide.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by palisadoes** [comment]
@literalEval Is there a reference on the flutter site that we can use instead of having to write this ourselves?
If there is one, let us know.

**Comment by literalEval** [comment]
@palisadoes [this guide at official Flutter site](https://docs.flutter.dev/cookbook/testing/unit/introduction) might do.

**Comment by Cioppolo14** [comment]
@literalEval That link will work. Can you add it to the CONTRIBUTING.md file & Talawa docs and we can close this issue out?

**Comment by literalEval** [comment]
Sure. Will do tomorrow morning. Thanks.

**Comment by Cioppolo14** [comment]
@literalEval Can we close this?

**Comment by palisadoes** [comment]
Closing. We'll add the link to the CONTRIBUTING.md file

**Comment by literalEval** [comment]
Thanks.
