### ISSUE TITLE
showSnackBar error: showing snackbar before screen is built

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1483]
**Describe the bug**

**To Reproduce**

1. Use this org url https://talawaapi.azurewebsites.net/graphql
2. click o sign up button
3. screen will appear

**Expected behavior**
Should provide with poper error

**Actual behavior**
giving this error screen 

**Screenshots**
![Screenshot from 2023-02-14 01-13-23](https://user-images.githubusercontent.com/95746190/218559187-7eaaf9dd-f7b5-41b9-9e73-8c2d2ff2fc82.png)

**Additional details**
I checked the error stack and it showed the this line showed this error
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L126-L128

we have to make the changes in these line too so we don't get same error in the future
https://github.com/PalisadoesFoundation/talawa/blob/ac0571bcf6c7fc0a3bd930989a9848348024d094/lib/services/database_mutation_functions.dart#L89-L124

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect please take a look and assign me this, **I have solved this problem before also**.

**Comment by Ayush0Chaudhary** [comment]
![Screenshot from 2023-02-14 01-32-20](https://user-images.githubusercontent.com/95746190/218562694-521f6c02-8968-4dbd-97fa-287c65fdbd3e.png)
I corrected it on my local Machine and showed this error.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary are you using `TalawaErrorWidget` for this?

**Comment by Ayush0Chaudhary** [comment]
Yes @palisadoes, should I use something else??

**Comment by palisadoes** [comment]
1. No, it was recently created and I want to make sure we consider using it.
2. Depending on your experience with it, we may want to adjust the widget to be more flexible.
3. We have an issue https://github.com/PalisadoesFoundation/talawa/issues/1437 that's on hold pending a few more developer experiences. 

Your feedback on its use could be integrated into the other issue.
