### ISSUE TITLE
Gradle error during project build

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#149]
Hey everyone!

I was facing this issue of Gradle error while building my project:
>

![build_error](https://user-images.githubusercontent.com/56073198/111040295-5b60ef80-8458-11eb-883a-560af40c8615.PNG)

I figured out that the problem was caused by the Gradle and Kotlin versions in the project. 

Here is the screenshot of the original `talawa/android/build.gradle` file:

![android_build gradle - old](https://user-images.githubusercontent.com/56073198/111040409-d5917400-8458-11eb-9254-da76f33769e1.PNG)

and the screenshot of the original `talawa/android/gradle/wrapper/gradle-wrapper.properties`file:

![gradle-wrapper properites - old](https://user-images.githubusercontent.com/56073198/111040449-f9ed5080-8458-11eb-81c9-7cf4b41a2315.PNG)

I modified the versions of Gradle and Kotlin in both of these files like so:
>

Modified `talawa/android/build.gradle` file:

![android_build gradle - new](https://user-images.githubusercontent.com/56073198/111040499-2c974900-8459-11eb-96b8-a197efd6575b.PNG)
>

Modified `talawa/android/gradle/wrapper/gradle-wrapper.properties`file:

![gradle-wrapper properites - new](https://user-images.githubusercontent.com/56073198/111040515-3f118280-8459-11eb-9da0-d64b224559ad.PNG)

And now the project builds fine without any error.
I am submitting a PR for the same.
Please give it a review!

**Comment by yasharth291** [comment]
which branch you were working on?

**Comment by yasharth291** [comment]
if it was on the main branch then you have to remove your pr as it is under maintenance and a big thing is going to be merged. it is better to work on Q4-2020

**Comment by Raunakk02** [comment]
I was working on 2020-Q4 branch.

**Comment by yasharth291** [comment]
there was no such error with me 
i also worked on the same branch. So you should see your system problems first because it is not a problem with the repo
![Capture](https://user-images.githubusercontent.com/55004621/111043469-c286a000-8468-11eb-815a-6610a3180478.JPG)

**Comment by yasharth291** [comment]
@Raunakk02  its better to close the pull as well as the issue as it is not the problem of the repo but the problem of your environment.

**Comment by DeltaHarbinger** [comment]
Hey @Raunakk02, this was fixed in a major update to the master branch. The Gradle version actually needed to be higher than the one shown in your pull request. Please pull master and see if everything is alright with you now
