### ISSUE TITLE
Bump build_runner from 2.1.10 to 2.3.3

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1493]
Bump build_runner from 2.1.10 to 2.3.3

We need to do this upgrade to improve the performance, reliability and security of the code base.

1. This upgrade will require you to fix other dependencies. You can verify this with the command `flutter pub get`
1. All tests will need to pass after this is completed
1. All existing functionality will need be maintained after this is completed

This is tied to PR https://github.com/PalisadoesFoundation/talawa/pull/1492
Your PR will need to be merged beforehand so that we can successfully close the one mentioned previously

**Comment by literalEval** [comment]
Does this issue need work ? If yes, then please assign this to me.

**Comment by literalEval** [comment]
@palisadoes this bump requires higher SDK version.

**Comment by palisadoes** [comment]
What SDK version would you recommend. I think we are using Java v12 which is not a long term support version. In fact it may soon be deprecated from GitHub actions.

**Comment by literalEval** [comment]
Hmm. Flutter latest version from the stable channel is what I am upgrading to for now. If flutter upgrade gets merged without issues, then we will discuss for Java etc. Till then, I will also research on what others are using and what's better.
