### ISSUE TITLE
Bump lint from 1.6.0 to 2.0.1

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1494]
Bump lint from 1.6.0 to 2.0.1

We need to do this upgrade to improve the performance, reliability and security of the code base.

1. This upgrade will require you to fix other dependencies. You can verify this with the command `flutter pub get`
1. All tests will need to pass after this is completed
1. All existing functionality will need be maintained after this is completed

This is tied to PR https://github.com/PalisadoesFoundation/talawa/pull/1489
Your PR will need to be merged beforehand so that we can successfully close the one mentioned previously

**Comment by Ghazali32** [comment]
Hey can you Assign this to me!!

**Comment by Digu650** [comment]
Hey there can you assign this issue to me???
As this would open the gate of open source for me

**Comment by palisadoes** [comment]
@Digu650 This will most likely be fixed with PR #1510
