### ISSUE TITLE
Bump hive from 2.2.1 to 2.2.3

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1495]
Bump hive from 2.2.1 to 2.2.3

We need to do this upgrade to improve the performance, reliability and security of the code base.

1. This upgrade will require you to fix other dependencies. You can verify this with the command `flutter pub get`
1. All tests will need to pass after this is completed
1. All existing functionality will need be maintained after this is completed

This is tied to PR https://github.com/PalisadoesFoundation/talawa/pull/1488
Your PR will need to be merged beforehand so that we can successfully close the one mentioned previously

**Comment by literalEval** [comment]
I would like to work on this issue.

**Comment by literalEval** [comment]
@palisadoes currently the `hive` version is "2.0.4" and not "2.2.1". Should I bump from "2.0.4" to "2.2.3" ?

**Comment by palisadoes** [comment]
Yes

**Comment by literalEval** [comment]
Okay.

**Comment by literalEval** [comment]
After bump, no error is reported and all tests are passing. Maybe there were no breaking changes ? 
Should I check something else ? Or should I open respective PR ?

**Comment by noman2002** [comment]
> @palisadoes After bump, no error is reported and all tests are passing. Maybe there were no breaking changes ? Should I check something else ? Or should I open respective PR ?

#1488
