### ISSUE TITLE
Upgrade flutter version in the workflow

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1500]
**Is your feature request related to a problem? Please describe.**

Flutter version used in our workflow is almost 1 years old now. We are using `flutter: 3.0.0`, whereas the latest is `flutter: 3.7.3` on the `stable channel`. This will soon lead to dependency issues and upgrading packages won't work.

**Describe the solution you'd like**

I would like to bump the flutter version in our workflow and upgrade/fix any dependency issue/deprecation which comes due to this bump.

**Comment by palisadoes** [comment]
You will also need to upgrade flutter in the code base. Is that included in your plan?

**Comment by literalEval** [comment]
Yes. I have done it locally. Gives 2 errors and 800 lint warnings/depracations :)

**Comment by literalEval** [comment]
@palisadoes any updates on this ?

**Comment by palisadoes** [comment]
If you have done the upgrade to the latest flutter to be compatible with the work flow, then submit the PR. Make sure the test coverage level is maintained.

**Comment by literalEval** [comment]
Sure. I will open a PR tomorrow. Can you please stop merging new PRs till then ? Because it will cause massive merge conflicts.

**Comment by palisadoes** [comment]
OK

**Comment by literalEval** [comment]
@palisadoes some <10 tests are failing. How about I comment them out and push. And after the merge, I will make them work in new PRs or maybe some newcomer can tackle them ? 
Because making all the tests to work may take some time which will unnecessarily halt others' work. If you like this idea, then I will open the respective PR tomorrow. Otherwise I will try to fix them.

Thanks and good night.

**Comment by palisadoes** [comment]
OK. Please provide the full paths to the files that the failing tests are testing.
