### ISSUE TITLE
Restore functionality to analysis_options.yaml

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1512]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Describe the bug**
As part of PR https://github.com/PalisadoesFoundation/talawa/pull/1510 for upgrading the flutter code upgrade to `v3.7.0`  we made edits to the [analysis_options.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/analysis_options.yaml) file.

**To Reproduce**

Run the current suite of tests and they all pass. This is because some checks have been disabled

**Expected behavior**

We need to re-enable:

- `depend_on_referenced_packages`
- `avoid_dynamic_calls`
- `deprecated_member_use`
- `lowercase_with_underscores`

Run the checks and fix all the resulting  errors 

**Actual behavior**

The code section in the file to focus on is here:

A clear and concise description of how the code performed w.r.t expectations.
    ####################################################
    #### Added to make things work for now. Must be ####
    ############# removed in future PRs ################
    ####################################################

    # Advises to explicitly install any plugin which you are using
    # in your codebase. At many places in our codebase we have used
    # things of a plugin which is not in our pubspec.yaml. Say we have
    # installed plugin A, which in turn internally installs plugin B, as
    # A depends on B, and then we are using functionalities of B, even
    # though we never installed them explicitly; they just got installed.
    #
    # To fix: Uncomment below lint and check for warnings it creates. Then
    # install the dependencies one by one.

    depend_on_referenced_packages: false
    
    # This new lint rule advises to use methods on dynamic objects
    # only after properly type casting. It's quite good and will avoid
    # null errors. 
    # For now, it affects the whole code base; wherever we have done 
    # something like 
    # 
    # ``` 
    # var obj = json_data['obj'];
    # obj.fun_call(param);
    # ```
    #
    # To fix: Turn on this lint and type cast the object of your file as 
    #
    # ```
    # MyObj obj = json_data['obj'] as MyObj;
    # ```
    
    avoid_dynamic_calls: false

    # deprecated_member_use is turned off for file - test/helpers/test_helpers.dart
    # to suppress returnNullOnMissingStub deprecation. 
    # To fix: Remove the lint suppress directive and update to latest API
**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/219898981-bcb16c2d-3b38-4120-8714-1eaee313af5c.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
@palisadoes the 3rd changed analysis option is `deprecated_member_use` and not `lowercase_with_underscores` :)

**Comment by palisadoes** [comment]
Thanks. We used to have `lowercase_with_underscores` enabled, but it was commented out in the file. I want that restored too.

**Comment by literalEval** [comment]
Sure.

**Comment by Amogh35** [comment]
i would like to work on this issue
