### ISSUE TITLE
Tests for lib/utils/post_queries.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1516]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/utils/post_queries.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by Amogh35** [comment]
@palisadoes, please assign this issue to me.

**Comment by palisadoes** [comment]
Thanks for the wanting to be a part of the community.

- Please request assignment from the persons on this list. https://github.com/PalisadoesFoundation/talawa/issues/359
- We are trying to streamline things for the expected GSoC workload.

**Comment by Amogh35** [comment]
@noman @TheHazeEffect I would like to work on this issue

**Comment by Amogh35** [comment]
@noman2002 @TheHazeEffect i would like to work on this issue
