### ISSUE TITLE
Tests for edit_event_page.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1517]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/events/edit_event_page.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by salehdemir** [comment]
I want to work in this issue please assign me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Azad99-9** [comment]
@palisadoes could you please assign this issue to me. I would like to work on this.

**Comment by palisadoes** [comment]
@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.
