### ISSUE TITLE
Tests for chat_message_bubble.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1518]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/widgets/chat_message_bubble.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by Amogh35** [comment]
Hello @palisadoes,
I am a beginner and want to contribute to Palisadoes. I wanted to work on this issue, but it looks like the test for this file already exists. However, codecov does not show coverage for this file.
Can you please look into this.

**Comment by noman2002** [comment]
@Amogh35 test for this file exists but its not at 100%.

**Comment by noman2002** [comment]
@Amogh35 Assigned this to you. Please work on it and get it to 100%

**Comment by Amogh35** [comment]
Thanks, i will look into it.

**Comment by noman2002** [comment]
@Amogh35 You already have 2 issues assigned apart from this one. Unassigning this one.

**Comment by noman2002** [comment]
@Amogh35 You can work on this now.

**Comment by Amogh35** [comment]
Thanks for assigning this issue to me @noman2002,  but after going through the issue, it seems that the coverage for the existing file is already at 100%. Below is the required proof.

![image](https://user-images.githubusercontent.com/105104954/220268936-3c875f5b-915a-4357-b626-dc9a949dbaa0.png)

**Comment by noman2002** [comment]
Thanks for the confirmation @Amogh35
