### ISSUE TITLE
Tests for profile_page_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1519]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/view_model/after_auth_view_models/profile_view_models/profile_page_view_model.dart
`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal.

**Comment by 007AnupamSharma** [comment]
@palisadoes  I would like to work on this issue ... Please assign me ... and also please guide me because i'm new in the open source

**Comment by 007AnupamSharma** [comment]
@palisadoes would you please guide me? .. like how to start it .. i'm new in this

**Comment by palisadoes** [comment]
1. There are many guides to writing Dart tests. 
2. There are also many tests that have already been written in the repository. Please take a look at those too.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Dante291** [comment]
Duplicate [issue](https://github.com/PalisadoesFoundation/talawa/issues/2142) @noman2002

**Comment by Cioppolo14** [comment]
@palisadoes  @noman2002 I am closing this issue as a duplicate.
