### ISSUE TITLE
Still some depreciated things in the code after migration to v 2.0

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#152]
![Capture](https://user-images.githubusercontent.com/55004621/111044330-e26c9280-846d-11eb-8c39-2241b0b4854d.JPG)
this is one of the example where the code is being depreciated. The code has to be changed a few little times.

**Comment by yasharth291** [comment]
@Sagar2366

**Comment by yasharth291** [comment]
i think there should be some discussion regarding it. please anyone label it as enhancement and discussion

**Comment by DeltaHarbinger** [comment]
Hey @yasharth291, #77 has already been created regarding outdated APIs. Feel free to bring the discussion to that PR. This will be flagged as duplicate and closed.
