### ISSUE TITLE
Tests for select_contact.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1520]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/chat/select_contact.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal.

**Comment by literalEval** [comment]
I would like to work on this issue @palisadoes @noman2002

**Comment by palisadoes** [comment]
Thanks for the wanting to be a part of the community.

- Please request assignment from the persons on this list. https://github.com/PalisadoesFoundation/talawa/issues/359
- We are trying to streamline things for the expected GSoC workload.

**Comment by literalEval** [comment]
@noman2002 @CyberWake :)

**Comment by noman2002** [comment]
@literalEval I am unassigning this because you have 4 issues assigned and as per rules it cannot be more than 2.

**Comment by Kraken005** [comment]
Hey, I want to work on this!

**Comment by palisadoes** [comment]
@Kraken005  Unassigning due to inactivity others need to get a chance. let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Kraken005** [comment]
Yes, I want to be reassigned. Working on it.

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by palisadoes** [comment]
There is a PR related to this. Reassigning.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by imshivam-gupta** [comment]
@noman2002 @Cioppolo14 Please let me work on this issue
