### ISSUE TITLE
Test event_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1531]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file:
```
lib/services/event_service.dart
```
- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal.

**Comment by usmanIITR** [comment]
@noman2002 @palisadoes can you assign me this issue??

**Comment by palisadoes** [comment]
@usmanIITR I'm unassigning due to inactivity

**Comment by ANUKULJHA1506** [comment]
@palisadoes can you assign me this issue ??

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by ANUKULJHA1506** [comment]
due travelling issue I was unable to get proper network , please reassign me this issue @palisadoes

**Comment by ANUKULJHA1506** [comment]
send the PR for merging

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by SHREYANSH-AGRAWAL0** [comment]
@palisadoes  can you assign me this issue??

**Comment by SHREYANSH-AGRAWAL0** [comment]
send the PR for merging

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by AVtheking** [comment]
Can you assign this issue to me ?

**Comment by Dante291** [comment]
Duplicate issue for this [this](https://github.com/PalisadoesFoundation/talawa/issues/2154) issue and someone is already working on this.

**Comment by AVtheking** [comment]
So do I can work on ir or not ?

**Comment by Dante291** [comment]
> So I can work on it or not ?

Nope there are many good first issues @AVtheking that are need to be addressed, you could start with writing test as this would make you understand the codebase.

**Comment by AVtheking** [comment]
Ok

**Comment by AVtheking** [comment]
I have asked for assignment in some good frst issues which are not assigned to anyone please look into it
