### ISSUE TITLE
Test post_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1535]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file:
```
lib/services/post_service.dart
```
- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by SiddheshKukade** [comment]
@palisadoes  @noman2002  Sir I would like to work on this. I can write unit tests for the functions. please assign

**Comment by palisadoes** [comment]
@SiddheshKukade  Are you still working on this? It's been over 10 days since you made an update.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade Are you still working on this? It's been over 10 days since you made an update.

@palisadoes,  Sorry for the delayed response. I was working on the other bugs and writing documentation for them as we've now added a check for it in the past few days.
The added document task took quite a bit time to understand the linter. Which caused the delay for this Pull request.
I'm currently trying to fix new bugs discovered recently by other contributors. I think they hold a higher urgency to fix to keep the app running without any problems.
I would like to work on them for now and  get unassigned from this issue.

I would  be ready to solve this one (If not already solved by other contributors) after the bugs are fixed.

**Comment by Nitya-Pasrija** [comment]
@palisadoes 
Can I give this one a try?

**Comment by AyushRaghuvanshi** [comment]
Hey, I would like to pick this issue up, Can you assign me this one?

**Comment by AyushRaghuvanshi** [comment]
Hey @noman2002 , I was going through the code for inspiration for my next issue, where i noticed when testing a service file people have just mocked the network call and then hit that call, they are not verifying whether the function is properly doing its task. Why is it so? is it not needed.
For Example: in post_services.dart getPosts() function calls network to receive all organization posts and then add it into a stream.
Now people have just called getPosts and left it as it is.
What I propose is we should then test whether those posts are succesfully added into postStream as well.
Is it not necessary? I hope I was clear with my doubt.
