### ISSUE TITLE
Test chat_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1536]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file:
```
lib/services/chat_service.dart
```
- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by ditya17** [comment]
Hello @palisadoes, I want to work on this issue please assign it to me.

**Comment by noman2002** [comment]
@ditya17 Any progress?

**Comment by palisadoes** [comment]
Unassigning due to inactivity. We need to give others a chance.

**Comment by palisadoes** [comment]
Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Muhammed-EmadEldeen** [comment]
Can you assign me to this issue, please?

**Comment by Muhammed-EmadEldeen** [comment]
Sorry but can you help me, I have done the test for the first method in the chat service which is sendMessageToDirect chat but apparently, this method isn't working correctly as it is supposed to take the output of the query and convert it to Map<String,dynamic> and then convert it chat message (which is ChatMessage.fromJson()) but it is telling me that the input is not a map but is null, when I tried to make a dummy map and make it the input of the ChatMessage.fromJson() it worked correctly, so apparently there is problem in line 63 in chat_service.dart file, so can I raise an issue about that and continue working on the tests (but it will raises an error in sendMessageToDirectChat) ? @palisadoes

**Comment by palisadoes** [comment]
Please ask the `#talawa-mobile` channel in slack
