### ISSUE TITLE
No autofill in the login page and the organization page.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#154]
the autofill in the signup page is working fine and same autofill should be added to login page and the organization page as well

**Comment by yasharth291** [comment]
@Sagar2366 @heyjordn @jordanliu @DeltaHarbinger

**Comment by DeltaHarbinger** [comment]
It seems like autofill has been added to the login page already. Can you confirm it isn't on the organization page?

**Comment by yasharth291** [comment]
i confirmed it is not and i am currently working on it sir 
@DeltaHarbinger
