### ISSUE TITLE
Test multi_media_pick_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1541]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage. 

Tests need to be written for file:
```
lib/services/third_party_service/multi_media_pick_service.dart
```
- When complete, all methods, classes and/or functions in the file will need to be tested. 
- Our `test/` folder has the same structure as the `lib` folder. Place your test file in the equivalent folder under `test/`. You may need to create the appropriate directory structure to do this.
- [Current test code coverage for this file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa?search=&displayType=list)

### IMPORTANT:
Please refer to this issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- No functionality must be removed to achieve this goal.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)

**Comment by m-eraf** [comment]
hello i want to work on this issue plz assign it to me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity. We need to give others a chance.

**Comment by ANUKULJHA1506** [comment]
Hi  , I want  to work on this issue , please assign me this issue

**Comment by Manik2708** [comment]
The current code coverage of this file is 87%, can you assign this issue to me? @palisadoes @noman2002
