### ISSUE TITLE
Upgrade Project to support java 17

### ISSUE THREAD

**Issue by TheHazeEffect** [PalisadoesFoundation/talawa#1542]
**Is your feature request related to a problem? Please describe.**
Talawa currently uses Java version 8, which although benefits from extended support, will eventually approach the end of it's long term support cycle.

**Describe the solution you'd like**
We would like to upgrade the Java version used in Talawa to the latest LTS(Long term support) version, which is Java 17. This will bring performance and security improvements to the project and ensures that it remains compatible with the latest Java features.

**Describe alternatives you've considered**
We have considered sticking with Java 8, but this becomes less ideal as we move closer to end of support. As an Open Source project, we would like to ensure due diligence in exercising that we do not leave potential security and performance improvements that would benefit the community behind.

**Approach to be followed (optional)**
The following steps will be followed to upgrade the Java version:

- Update the build.gradle file to use the latest version of Gradle that supports Java 17.
- Update any dependencies that may not be compatible with Java 17.
- Ensure the app properly builds and runs for Android
- Ensure the Pipeline is still able to build the project

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
@TheHazeEffect please assign this to me. I will do it as a part of post-sdk-migration.

**Comment by gvjkumar2004** [comment]
Hi There, I am familiar with this, Can I go work on it ?

**Comment by palisadoes** [comment]
It's already assigned

**Comment by noman2002** [comment]
@literalEval Unassigning you because you have two other big issues in your name.

**Comment by noman2002** [comment]
@gvjkumar2004 You can work on this.

**Comment by noman2002** [comment]
@gvjkumar2004 Any update?

**Comment by gvjkumar2004** [comment]
Yea working on it !

**Comment by palisadoes** [comment]
@gvjkumar2004 What progress have you made? We'd like to get this done, and possibly give someone else a chance if you are unable for any reason.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 can I work on this? if @gvjkumar2004 is not working on it anymore

**Comment by Ayush0Chaudhary** [comment]
@TheHazeEffect @palisadoes @noman2002   @literalEval we use currently gradle 7.0.2 which according to this [answer](https://stackoverflow.com/questions/69801373/starting-from-which-version-gradle-supports-java-17) uses Java 16

**Comment by Ayush0Chaudhary** [comment]
Is this an issue as new flutter project are also made on gradle 7.0.2 ?

**Comment by Ayush0Chaudhary** [comment]
Am I getting it wrong? Do correct me if so.

**Comment by literalEval** [comment]
Yep @Ayush0Chaudhary we will need to upgrade Gradle, Java and other stuff altogether as they won't work if their versions don't match. Like a few years back, Flutter only supported Java 11, in spite of release of other Java updates. I still use OpenJDK 11.x.x in my machine. So please also look into whether Flutter now supports newer versions or not.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Ayush0Chaudhary** [comment]
Hi @palisadoes 
I researched this issue.
The current gradle v supports Java 16. It is compatible with gradle, latest flutter v support. Nothing was failing once I upgraded the version. 

@TheHazeEffect

**Comment by palisadoes** [comment]
@Ayush0Chaudhary Please submit a PR

**Comment by literalEval** [comment]
@Ayush0Chaudhary were you able to do a clean build after the migration ?

**Comment by Ayush0Chaudhary** [comment]
> @Ayush0Chaudhary were you able to do a clean build after the migration ?


Yes changed the java version on my machine and everything was working. There is no need of PR in this issue. 

@TheHazeEffect your views?

@palisadoes

**Comment by palisadoes** [comment]
OK, I'll close this issue
