### ISSUE TITLE
Upgrade the Mockito package to the latest version

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1548]
**Describe the bug**

`returnNullOnMissingStub` is now deprecated in `Mockito` and needs to be migrated to their latest API.

**Mitigation Process**

- Remove `// ignore: ....` from the top of `test/helpers/test_helpers.dart`
- Fix all the lint warnings by migrating `returnNullOnMissingStub` to its latest alternative.

**Comment by gvjkumar2004** [comment]
Hii Palisadoes, I wanna work on this, can u assign this to me !

**Comment by literalEval** [comment]
@gvjkumar2004 can you please tag me when you open the respective PR for this issue ?

**Comment by gvjkumar2004** [comment]
sure Ravu !

**Comment by literalEval** [comment]
Thanks

**Comment by gvjkumar2004** [comment]
can anyone help me on this part of the process:
 "Fix all the lint warnings by migrating returnNullOnMissingStub to its latest alternative."
I am done with the first one....

**Comment by palisadoes** [comment]
The lint warnings tell you what you should do.

**Comment by literalEval** [comment]
@gvjkumar2004 search for that deprecation. It will lead you to their documentation that tells you what are the latest alternatives to the deprecation. And then you will need to migrate accordingly. Hope this helps.

**Comment by palisadoes** [comment]
@gvjkumar2004 Are you still working on this?

**Comment by noman2002** [comment]
Unassigning due to inactivity.

**Comment by gvjkumar2004** [comment]
Sorry for not responding, I was busy with my exams !

**Comment by ALIRAZA17** [comment]
@noman2002 Can you assign me this issue please if noone is doing it?

**Comment by ALIRAZA17** [comment]
@palisadoes I have created another PR #1707 for this issue because the other one became too messy Can you look at it?
