### ISSUE TITLE
Login and create create account buttons do not work (discussion)

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#155]
Login and create create account buttons do not work on master branch.

https://user-images.githubusercontent.com/68892315/111050883-3e86e500-8475-11eb-8092-82c5ed20d5db.mp4
Im actually trying to click the create an account and login buttons (the on tap is not visible) .

**Comment by Sagar2366** [comment]
@Swayam221 do you see any error on login or signup ? Share the screenshot, that would help to understand issue better.

**Comment by yasharth291** [comment]
yeah he is saying true the buttons on the main page are not working

**Comment by adithyaakrishna** [comment]
It's not an error, when the org url is given, and it successfully sets the url to execute graphql queries, the login and create account buttons comes up

**Comment by Swayam221** [comment]
@adithyaakrishna You're right! but it does seem a bit odd that a user will have to set a url first and then click the create an account button if the pages are actually scrollable.

**Comment by Swayam221** [comment]
Can we let the URL be be decided on the login and register pages separately? @jordanliu @DeltaHarbinger

**Comment by DeltaHarbinger** [comment]
We could make it so that the buttons aren't shown until a URL is provided, or that the user may press the button but is then prompted for a URL. Do either of those sound good?

**Comment by AniketSindhu** [comment]
@DeltaHarbinger I think showing buttons after adding url will be better. Should I start working on that or anyone else handling this issue?

**Comment by DeltaHarbinger** [comment]
@Swayam221 was the original person to open this issue.

@Swayam221, are you already attempting something, or should I assign @AniketSindhu

**Comment by Sagar2366** [comment]
@DeltaHarbinger, first option sounds good to me. We should show buttons after url is provided and it's valid.

**Comment by DeltaHarbinger** [comment]
@Sagar2366 sounds good.



@AniketSindhu, if @Swayam221 doesn't respond as to whether or not he wants to tackle the issue, I'll assign it to you instead

**Comment by Swayam221** [comment]
> @Sagar2366 sounds good.
> 
> @AniketSindhu, if @Swayam221 doesn't respond as to whether or not he wants to tackle the issue, I'll assign it to you instead

@DeltaHarbinger i would like to work on the issue

**Comment by Swayam221** [comment]
> We could make it so that the buttons aren't shown until a URL is provided, or that the user may press the button but is then prompted for a URL. Do either of those sound good?
@DeltaHarbinger actually this is exactly what is happening at the moment. But, even if the user doesnt provide a url, he/she can just swipe to the register page and signup without an org. This leaves no point for the buttons not being active until a url is provided. I think we should change create a guest/anonymous type login for a user who doesnt provide a url and keep both the buttons active (create an account & login) .

**Comment by adithyaakrishna** [comment]
What if we can create a dropdown kind of option to select the URL, the different organizations have to register and then their Name will be added as an option to the dropdown, we can create a basic UI in Talawa-Api for this and once an org. registers with their Name and URL, the Org. Name will be shown as n option in the Talawa App

**Comment by Swayam221** [comment]
@DeltaHarbinger , looks like @CoderMayhem solved this discussion in PR #265 . @CoderMayhem Please take care of duplicates issues, it is good that you are helping us all but duplicate issues can be frustrating when someone comes and sees what they've been working on has already been fixed  (it feels like a waste of time) . Still Thankyou! this issue can be closed now. @adithyaakrishna you can make your proposal in another issue.

**Comment by DeltaHarbinger** [comment]
Hey @Swayam221, it seems that @CoderMayhem has stopped the screen from scrolling left & right when no URL has been provided. You can still work on removing the login & sign-up buttons until a URL is provided. Does that sound good?

**Comment by AniketSindhu** [comment]
@DeltaHarbinger the buttons are not clickable until URL is set. Also, they change color when the URL is set showing the user that they are now clickable

**Comment by CoderMayhem** [comment]
Yes the sliding issue has been fixed and regarding the buttons they are not active until a URL value has been set, so rather than removing the buttons we can show a nice toast saying : "Fill up the organisation URL before proceeding!" (Or something similar) whenever the user clicks on these buttons without entering the URL.

**Comment by CoderMayhem** [comment]
> @DeltaHarbinger , looks like @CoderMayhem solved this discussion in PR #265 . @CoderMayhem Please take care of duplicates issues, it is good that you are helping us all but duplicate issues can be frustrating when someone comes and sees what they've been working on has already been fixed (it feels like a waste of time) . Still Thankyou! this issue can be closed now. @adithyaakrishna you can make your proposal in another issue.

Bro the issue title should have been changed accordingly if you were working on fixing the sliding issue. I did not see any pre-existing issue that's why I created one. Still I apologise for any trouble.

**Comment by AniketSindhu** [comment]
@CoderMayhem great idea! So who will be working on that?

**Comment by Swayam221** [comment]
@DeltaHarbinger everything seems fixed now sir. I will move on to other issues now. If further discussion is not required, we can close this issue.

**Comment by Swayam221** [comment]
> @CoderMayhem great idea! So who will be working on that?

I think @yasharth291 is fixing it as per #180

**Comment by CoderMayhem** [comment]
Issue 180 is not about that. I guess nobody is working on this. If anyone wants to implement this they can discuss with the maintainers if it's worth implementing.

**Comment by Swayam221** [comment]
I would like to ask the maintainers if they want this change to made regarding this discussion, the change proposed is: let the 'create an account' button and 'login' button on the mainscreen be active all the time and a toast message is displayed when the user clicks these without setting a url first saying "please set a url first". If we do not want this change, we can close this issue i think.

**Comment by DeltaHarbinger** [comment]
Hey @Swayam221, the change implemented in #265 was the removal of scrolling to the login or sign-up pages without a link being present. I believe it would be great if you want to implement a SnackBar or Toast message to state that users need to enter a link before signing up. If you want to implement this, please respond here

**Comment by Swayam221** [comment]
> Hey @Swayam221, the change implemented in #265 was the removal of scrolling to the login or sign-up pages without a link being present. I believe it would be great if you want to implement a SnackBar or Toast message to state that users need to enter a link before signing up. If you want to implement this, please respond here

Yes, I surely would like to implement this.

**Comment by Sagar2366** [comment]
@Swayam221 this is not required feature. Since only enter organization box is in active state it will make sense to the user that they needs to enter parent organization before creating account. It is one kind of multi-factor authentication. By enabling signup/login buttons all time, we are unnecessarily adding code/feature which is not required. 

Closing this issue as it is not required feature.
