### ISSUE TITLE
Adding some custom lint rules to Talawa

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1550]
This issue tracks the progress for #1479. 

- [x] Integrate `custom_lint` in Talawa
- [x] Add a custom lint rule that checks if documentation is present for every declaration, with some exceptions being `State` of a `StatefulWidget` etc.
- [ ] Add a custom lint rule that checks if the documentation provided is in correct format
  - [x] Check if the first sentence is a single line and ends with an `end puncuation`, i.e. `.`, `!` etc.
  - [x] Check if the second line (if exists) is a blank one. If so, there must be a third line which should not be blank.
  - [ ] For function declarations - 
    - [x] Check if a line contains `params:` keyword. This will mark the beginning of documentation for function parameters.
    - [ ] Check if all the parameters are listed in their own lines/paragraphs, after the line at which `params:` is found and start with ``* `param_name`: ``, followed by description.

**Comment by literalEval** [comment]
@palisadoes feel free to add anything which you think we need in our lint rule.

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar Please verify that these rules translate into comments that DartDoc will easily parse for our automated documentation workflow. Please request any modifications that may be needed to do so.
- https://github.com/PalisadoesFoundation/talawa/issues/1479 Please look at this issue for reference.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @literalEval @xoldyckk @noman2002 we can add rule to avoid print statement, instead have debugPrint or something else 
because **print() will print logs in release builds as well**, which is something that shouldn't happen as our might log a sensitive information.
If we add this now, future catastrophes can be avoided.

**Comment by palisadoes** [comment]
I agree, we need to check for that. It also clutters the test log screens and makes it harder to identify failing tests.

**Comment by literalEval** [comment]
@Ayush0Chaudhary @palisadoes  there already exists a lint rule for that as far as I know.

**Comment by palisadoes** [comment]
You are right. The errors are gone now.

**Comment by noman2002** [comment]
@literalEval You have 3 issues assigned.  As per rules maximum of 2 issues can be assigned at once. Please unassign any one of those or I have to do it randomly.

**Comment by literalEval** [comment]
@palisadoes it would be great if someone comes with me for testing of this implementation. Like I wanted to see whether the plugin integrates correctly on the first go on everyone's IDE and works without issues.

@Ayush0Chaudhary @SiddheshKukade @noman2002 anyone ?

**Comment by palisadoes** [comment]
How would this be integrated into vscode for example?

**Comment by literalEval** [comment]
Yeah @palisadoes  I think we have not talked about this. So

1. The official dart lint analyzer tool (which is used by IDEs like VSCode to get the lint errors, warning etc) provides plugin integration, which means we can write our own plugins. The problem being that it isn't officially available for use to normal users and writing all of the custom stuff is a pain, until unless we clone all of their codebase, which we were talking about in the beginning.
2. This is the problem that `custom_lint` solves. It does all of that in the background and allows us to focus only on writing custom lints. We add a plugin to our `analysis_options.yaml` telling the Dart linter that we are using our custom lint rules.
3. Then, whenever Dart analyzer is run on that project, it finds that there is a custom lint rule and add that rule to its list, checking all the files for lint errors. So whenever you open your IDE, it will start the Dart analysis server, which in turn will run our custom lint and start scanning for warning/errors.

This is really nice as it shows the problems in the IDE itself.

**Comment by noman2002** [comment]
Sounds like a great idea to show it in the ide itself. I think we should do this.
@palisadoes Your thoughts.

**Comment by palisadoes** [comment]
Agreed.

! @literalEval can you point us to the instructions to implement this and test?
1. Will the eventual presence of the ignore statement in the files cause it to be ineffective?

**Comment by literalEval** [comment]
1. Nothing extra is needed and it works fine in my setup. The reason why I want some other people to 'test' this is because I have troubleshooted many things before `custom_lint` eventually got integrated in Talawa, and in the same course of time SDK bump also happened. So I just wanted to see whether it works out of the box in other's environment too or gives some versioning errors. If everything goes well, people should be able to see the custom lint warnings/errors just after they open their IDE.
2. Yes. It will not parse the files with ignore statements. And I think it is awesome because then contributors won't be distracted by warnings/errors of the files they are not working with.

@palisadoes if this sounds logical to you, can you please ask someone to collaborate with me for a simple test run ? Thanks.
