### ISSUE TITLE
Feature Request: Using proper graphql scalars for different data types shared between clients and server

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa#1559]
**Is your feature request related to a problem? Please describe.**

Talawa-api currently uses default scalars provided by graphql to parse/validate queries and exchange data with the clients. We are migrating to making use of graphql-scalars package and custom scalar types in talawa-api. Check out these links for more info:- [link1](https://github.com/PalisadoesFoundation/talawa-api/pull/1081), [link2](https://github.com/PalisadoesFoundation/talawa-api/pull/1085).

You can work with [eshaan](https://github.com/EshaanAgg) who's working on this in talawa-api to figure stuff out.

**Describe the solution you'd like**

We'd like talawa mobile to migrate their graphql SDL documents to make use of the new scalars. This would provide better validation to fields and a certain standard to the data exchanged between talawa mobile and talawa api.

**Describe alternatives you've considered**

 -
 
**Approach to be followed**

1. Replace the old scalar values with the new ones in the main app. This would probably include the functionality of receiving the new scalar type values from the api and parsing/transforming them to whatever the data type requirements are in dart/flutter and the app.
2. Migrate your test code to make use of the new scalar values. In the tests make sure you're not using dummy data which doesn't conform to new scalars as later it could prove fatal if api is used in any way for E2E tests or something of the sort.

**Additional context**

 -

**Potential internship candidates**

 -

**Comment by literalEval** [comment]
Seems like an important migration. @palisadoes @noman2002 can you please assign this to me as I am working on migration issues these days.

**Comment by xoldyckk** [comment]
> Seems like an important migration. @palisadoes @noman2002 can you please assign this to me as I am working on migration issues these days.

done

**Comment by EshaanAgg** [comment]
@literalEval In addition to migrating the SDL definitions to the new scalars, you would also need to check compatibility for date objects as `ISO 8601` standard, instead of the earlier `UNIX Timestamp` standard.
Details about the same can be found in this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/500)

**Comment by literalEval** [comment]
Noted

**Comment by noman2002** [comment]
@literalEval I have to unassign this. It will unfair to others. You are 4 issues in your name.

**Comment by literalEval** [comment]
Understandable. Since my exams are over today, I'll do all of the ones assigned to me and come back real quick :)

**Comment by xoldyckk** [comment]
@noman2002 @literalEval 

Hehe this is a bit problematic. I'd like people to start working on this refactor asap. Btw it shouldn't be limited to only one person, many people can collab to work on this dividing up work.

**Comment by literalEval** [comment]
:) assign this to me. I'm waiting lmao

**Comment by noman2002** [comment]
> @noman2002 the two issues related to Custom Lint are literally the same issue. One of them is just for tracking purposes. I have said this earlier too. That issue will take some time as currently I am looking for someone who can test that feature with me. In the meantime I can work on this. Please assign this to me :(

Things don't work this way. The custom lint issue is huge. You cannot work on both at the same time. Let others try this. Complete the custom lint issue get it merged then I'll be more than happy to assign.

**Comment by noman2002** [comment]
If both the issues are same then why are we having two issues. Close any one of them.

**Comment by literalEval** [comment]
@noman2002 I have closed one of them :)

**Comment by xoldyckk** [comment]
@literalEval are u working on this? This is important as api and admin have already made all the changes and the changes are merged. If mobile is not migrated quickly many contributers will get issues.

**Comment by literalEval** [comment]
@xoldyckk Yes I am working on this on priority basis and am in continuous contact with @EshaanAgg

**Comment by literalEval** [comment]
@xoldyckk I have migrated for the event system. Migration for Posts remains.

**Comment by literalEval** [comment]
Since Event is the most used feature (as it is fetched/displayed by default), should we merge the work done till now and deal with Post in another PR ? This will at least reduce the error frequency and then I will migrate Post system by tomorrow ?

**Comment by xoldyckk** [comment]
@literalEval You can create many small PRs. Just reference this issue in them so they'll be easier to track cuz they are sub PRs for a bigger issue.

Also, I'm clueless about dart/flutter so your PRs won't be reviewed by me. So, I can't say anything about them getting merged.

**Comment by literalEval** [comment]
Yeah got it

**Comment by literalEval** [comment]
The PR related to Posts is pending. Once it gets merged, I will migrate it to scalars.

**Comment by Ayush0Chaudhary** [comment]
@literalEval can i also work on this alongside you? this is a big issue.

@noman2002 @palisadoes @xoldyckk

**Comment by Ayush0Chaudhary** [comment]
corrected!

**Comment by literalEval** [comment]
Telegram pe reply kar fatafat

**Comment by palisadoes** [comment]
@literalEval Are you still working on this?

**Comment by literalEval** [comment]
Yeah @palisadoes I and @Ayush0Chaudhary both are working on this. We decided to pair up as this is a very important and large issue. Thanks.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes other services are still left to be corrected, we should reopen this.

**Comment by palisadoes** [comment]
1. What services are left?
1. Why don't we create individual issues for them?

We can add check boxes to this issue to keep track.

We have reopened this issue multiple times. That's not a suitable way to operate.

**Comment by Ayush0Chaudhary** [comment]
> 1. What services are left?
> 2. Why don't we create individual issues for them?
> 
> We can add check boxes to this issue to keep track.
> 
> We have reopened this issue multiple times. That's not a suitable way to operate.

@palisadoes @noman2002 @xoldyckk 

- [ ] Direct Service
- [ ] Comment Services
- [ ] User Config

These are only few that I know of, other are still unidentified.

**Comment by literalEval** [comment]
> > 1. What services are left?
> > 2. Why don't we create individual issues for them?
> > 
> > We can add check boxes to this issue to keep track.
> > We have reopened this issue multiple times. That's not a suitable way to operate.
> 
> @palisadoes @noman2002 @xoldyckk
> 
> * [ ]  Direct Service
> * [ ]  Comment Services
> * [ ]  User Config
> 
> These are only few that I know of, others are still unidentified.

@Ayush0Chaudhary are you working on these? Or should I start from my end?

**Comment by Ayush0Chaudhary** [comment]
For now you can leave them, I will address them in other issue which Target all similar shortcomings.
