### ISSUE TITLE
Overflow Issue on Events Page

### ISSUE THREAD

**Issue by mmjsmohit** [PalisadoesFoundation/talawa#1561]
**Describe the bug**
Overflow in the top bar of Events Screen

**To Reproduce**

**Screenshots**
![photo_2023-02-24_15-28-27](https://user-images.githubusercontent.com/65406090/221149548-9020c787-282f-4143-97ad-9b29eecc234b.jpg)

**Comment by mmjsmohit** [comment]
Willing to work on this, Can you please assign me this issue?

**Comment by noman2002** [comment]
@mmjsmohit Assigned to you. Good Luck.

**Comment by SamarthAsthan** [comment]
Hi @noman2002 , I would like to take on the task of fixing this bug. Could you please assign it to me?

**Comment by noman2002** [comment]
@SamarthAsthan This issue is already assigned. You can take other issues.

**Comment by salehdemir** [comment]
please assign me

**Comment by aryamanshrivastava** [comment]
Could you kindly grant me permission to work on this issue?

**Comment by palisadoes** [comment]
@mmjsmohit  are you still working on this? We will reassign of we don't have an update on a day

**Comment by SiddheshKukade** [comment]
Hello @palisadoes Sir, I've also tried to see if I could fix this and have managed to fix it with just **one line of code**  instead of changing the widgets.  I would also like to be assigned.

**Comment by palisadoes** [comment]
@mmjsmohit I'm unassigning due to inactivity.
