### ISSUE TITLE
Add Back button to go to select org screen

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1574]
**Describe the bug**
No back button to remove the current screen, user is stuck!

**To Reproduce**

1. Do sign up
2. select org
3. signup screen will be prompted

**Expected behavior**
Should have a back button so the user can choose other organization
**Actual behavior**
NO back button
**Screenshots**
![Screenshot from 2023-02-27 05-22-13](https://user-images.githubusercontent.com/95746190/221445483-a7432be5-fd48-49d2-ac06-8e73c6c24679.png)

**I suggest**  doing the following
![Screenshot from 2023-02-27 05-33-31](https://user-images.githubusercontent.com/95746190/221445636-375965bc-1eac-45b5-bf92-f484a4baacea.png)

**Additional details**
it is a small issue **but very important to increase app's UX**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002 @TheHazeEffect can i work on this??

**Comment by Cioppolo14** [comment]
@palisadoes @Ayush0Chaudhary @noman2002 @TheHazeEffect  I assigned it to @Ayush0Chaudhary since there is only one other item assigned to them. I am learning the ropes for these tasks so feel free to correct & educate me as needed. Trying to help take some of the workload off the rest of the group.

**Comment by Cioppolo14** [comment]
Did not mean to close it...as you can see I am learning.

**Comment by Ayush0Chaudhary** [comment]
ma'am please assign me this issue 
@Cioppolo14

**Comment by noman2002** [comment]
> @palisadoes @Ayush0Chaudhary @noman2002 @TheHazeEffect I assigned it to @Ayush0Chaudhary since there is only one other item assigned to them. I am learning the ropes for these tasks so feel free to correct & educate me as needed. Trying to help take some of the workload off the rest of the group.

Thats very kind of you @Cioppolo14 . You doing a great job.
