### ISSUE TITLE
Inconsistent UI on Profile Screen

### ISSUE THREAD

**Issue by mmjsmohit** [PalisadoesFoundation/talawa#1578]
**Describe the bug**
Inconsistent spacing and paddings on Profile Screen.
**Screenshots**
1. Inconsistent Spacing between User Badge and List Tiles
2. Fix some List Tile Descriptions.
3. Currency selector in Donate Us Bottom Sheet opens up full screen, it should only take up bottomSheet Height.

Inconsistent UI             |  Currency Selector Bottom Sheet
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/65406090/221479472-7c997da3-4a85-414a-8676-751f4101fb56.png" width=40% height=40%>  | <img src="https://user-images.githubusercontent.com/65406090/221480201-0464515e-46b9-43ec-bdd5-920438c96e7e.png" width=40% height=40%>

**Comment by mmjsmohit** [comment]
I would like to work on this issue.

**Comment by palisadoes** [comment]
We are focusing on breaking bugs right now as outlined in the video https://youtu.be/ix3eSReJj2k

Closing
