### ISSUE TITLE
Unable to logout after initial login 

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1581]
**Describe the bug**
After an initial log in, you are unable to log out from the Talawa application.

**To Reproduce**

[![Follow the steps outlined here till the 50 second mark](https://img.youtube.com/vi/ix3eSReJj2k?/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=23)

**Expected behavior**
Clicking the logout option should take you to the login screen.

**Actual behavior**
Choosing the logout option takes you to the screen you're currently on.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by shubham21155102** [comment]
@DMills27 please assign this issue to me

**Comment by salehdemir** [comment]
If this issue not solved please assign me.

**Comment by meenaljain0303** [comment]
I can help with this issue too, @noman2002

**Comment by SiddheshKukade** [comment]
@palisadoes @DMills27 @noman2002 Sir,  It's been a week since the previous assignee has been working on it . So, I've tried to fix it in code and have successfully fixed it. ✅  
Please assign to me so that I can make a Pull request.

https://user-images.githubusercontent.com/65951872/222961678-ac227786-f398-4091-97e3-91e82122f5cf.mp4

**Comment by palisadoes** [comment]
@shubham21155102 What's the status of this? If there is no update on this we'll need to remove your assignment.

**Comment by shubham21155102** [comment]
@palisadoes i am working but as he is saying he has solved the issue then assign him i will work on another issue.
