### ISSUE TITLE
Implement the "Add Hashtag" Functionailty

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1583]
**Is your feature request related to a problem? Please describe.**
Currently the "Add Hashtag" option does nothing; we would like for its required functionality to be implemented. See the video for a description of the issue 

[![Steps outlined here till 2:41](https://img.youtube.com/vi/ix3eSReJj2k?/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=124)

**Describe the solution you'd like**
When clicking the "Add Hashtag" option (pictured below), allow the user to add a hashtag . Currently, it does nothing.  

<img width="325" alt="Screenshot at Feb 27 06-21-01" src="https://user-images.githubusercontent.com/5251658/221551012-bd5bd42d-7352-4e8f-8340-e9eef8d4bf9f.png">

**Describe alternatives you've considered**
If possible, write some functionality to detect if a hashtag is present on a post rather than having the user select an "Add Hashtag" option. If this route is chosen then remove the "Add Hashtag" option altogether. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Omegaviv** [comment]
Hey, I would like to work on this, is there any design or any reference that how exactly users can enter hashtags?

**Comment by palisadoes** [comment]
Are you still working on this? We'd like to give someone else a chance.

**Comment by Omegaviv** [comment]
Currently, I am stuck with the PR failing test, and have not started working on this yet.

**Comment by palisadoes** [comment]
Thanks. I'm going to unassign you. Let's see if anyone else can figure it out.

**Comment by indresh149** [comment]
@palisadoes sir may I work on this issue? I have two issues assigned, one is resolved and I am working on the second. I would like to work on this also.

**Comment by palisadoes** [comment]
> @palisadoes sir may I work on this issue? I have two issues assigned, one is resolved and I am working on the second. I would like to work on this also.

You have 3 assigned issues:
- https://github.com/PalisadoesFoundation/talawa/issues/assigned/indresh149

**Comment by sumittiware** [comment]
@palisadoes sir, I would like to work on this issue.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by ALIRAZA17** [comment]
@palisadoes Can I work on this one?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by andoriyaprashant** [comment]
Hey @palisadoes @DMills27 I would like to work on this issue. Please assign it to me as I have previous experience working on similar features
Thank you

**Comment by andoriyaprashant** [comment]
Hello @DMills27 @palisadoes  Could you kindly review the pull request I've submitted for the hashtag feature addition #2003 
Your feedback on these changes would be much appreciated
Thank you

**Comment by palisadoes** [comment]
This is being worked on as a part of our GSoC timeline. We'll have to close it
