### ISSUE TITLE
Post `Implement Custom Lint` work

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1584]
### Bugs 
- [x] Get `flutter pub get` to run inside `talawa_lint`
- [x] Upgrade or remove explicitly mentioned `Dart version` in `push.yaml` (Remove only if it can be proved that explicit definition is not doing anything special)

### Core Implementation
- [x] Add ignore directive corresponding to our new custom lint rules at the beginning of each file.
- [x] Add a script that will check for the presence of our ignore directive in entirety of a file and
  - [x] Pass if ignore directive is not found anywhere
  - [x] Fail otherwise
- [x] Add `flutter pub run custom_lint` in the workflow so that our custom lint rules are actually checked for during pull request and push.

**Comment by literalEval** [comment]
@palisadoes 

![Screenshot_20230227_213101](https://user-images.githubusercontent.com/62198564/221614897-2133d1f5-d112-4e3d-9e76-132092af1685.png)

I am able to check our custom lint rules in the workflow :confetti_ball:

**Comment by palisadoes** [comment]
- This is good news, steady progress.
- Where are you planning on documenting this? We may need a separate style guide external to contributing.md and link between the two.

**Comment by literalEval** [comment]
Yeah. I believe we should add it's documentation in our docs site and refer to it in Contributing.md

**Comment by palisadoes** [comment]
@literalEval What's the progress on this an the related open issues?

**Comment by literalEval** [comment]
Will try to create a new PR till night. Sorry, was busy travelling.

**Comment by palisadoes** [comment]
Happy Holi!

**Comment by literalEval** [comment]
Same to you @palisadoes :confetti_ball: :confetti_ball:

**Comment by literalEval** [comment]
@palisadoes can you please stop merging new PRs from now on till I get the `Add ignore statement to files` task of this issue merged ? I will open the respective PR after your confirmation. Thanks.

**Comment by palisadoes** [comment]
OK

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar This issue is nearing completion for forcing contributors to have valid DartDoc comments when submitting PRs. Please take a final look on #1479 to make sure that the formatting proposed in compatible with DartDoc. 

- https://github.com/PalisadoesFoundation/talawa/issues/1479
- https://github.com/PalisadoesFoundation/talawa/issues/1550

This will hopefully improve the quality of our code over time.
