### ISSUE TITLE
Ensure posts show up on the newsfeed after they are created.

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1585]
**Is your feature request related to a problem? Please describe.**
After a new post is created, a notification at the bottom of the screen says "post is uploaded" however when navigating to the posts section of the app, no posts are shown.

See the steps outlined here till  5:15 to better understand the issue
 [![See the steps outlined here till  5:15 to better understand the issue](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=286)

**Describe the solution you'd like**

We want new posts to be shown the moment they are created. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Kushalrock** [comment]
![image](https://user-images.githubusercontent.com/64556649/222940740-adf93ce2-e5a7-413e-babe-3ab3831392b7.png)

I guess this issue has something to do with this function. It's just a mock function and isn't actually doing any network calls to upload the post but just showing fake post si uploaded message

**Comment by palisadoes** [comment]
Please refer to https://github.com/PalisadoesFoundation/talawa-api/pull/1115 and related issues that will be created as a result. Comment there as necessary.
