### ISSUE TITLE
No notification is given if an image is added. 

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1586]
**Describe the bug**
Under Add Event page, there is an Add Image option. When an image is added there is no notification or preview, so the user is unaware if an image was actually added. 

**To Reproduce**

Follow the steps outlined in the video below till 6:00
[![Follow the steps outlined here till 6:00](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=325)

**Expected behavior**
Show a toast/popup of that the image was added and add a preview of said image in the post.

**Actual behavior**
There is no indication that an image is added. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by salehdemir** [comment]
If this issue not solved please assign me.

**Comment by palisadoes** [comment]
@salehdemir I'm unassigning you due to inactivity. Please leave a comment here if you want to be reassigned.

**Comment by Muhammed-EmadEldeen** [comment]
If this issue is not solved please assign me.

**Comment by ALIRAZA17** [comment]
If this issue is still open Can you please assign me?
