### ISSUE TITLE
Create a more intuitive design for editing a given event 

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1588]
**Is your feature request related to a problem? Please describe.**
In the events details page there are some edit options in the hamburger menu at the bottom right-hand side of the page. This is unintuitive can could be better design with better iconography.

<img width="318" alt="Screenshot at Feb 27 07-23-59" src="https://user-images.githubusercontent.com/5251658/221563777-3db87a41-4f61-4684-b716-707bcd6cdbb3.png">

<img width="318" alt="Screenshot at Feb 27 07-24-33" src="https://user-images.githubusercontent.com/5251658/221563815-9ae31681-2b73-4161-95ce-d3440500287b.png">

See the video below till 6:42

[![Follow the steps outlined here till the 50 second mark](https://img.youtube.com/vi/ix3eSReJj2k?/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=372)

**Describe the solution you'd like**
We need a more useful way of describing the edit functionality such as using a pencil icon rather than a hamburger menu, and perhaps placing it in a better area on the screen. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@DMills27 can I do this issue?

**Comment by Ayush0Chaudhary** [comment]
My pr is waiting for review

**Comment by Ayush0Chaudhary** [comment]
@Cioppolo14 can you assign me this too?

**Comment by noman2002** [comment]
Assigned you another issue. Please work on it.

**Comment by ikjot-2605** [comment]
For this issue, I had a simple idea to make the entire process seem a little more intuitive for the user.
We could:

1. Show the edit icon next to the message icon(just below the image, on the same row as the event name).
2. Have the delete button as a FAB(Floating Action Button). Here, to prevent accidental deletion of event, we can show a dialog box as well to confirm event deletion.

![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/55295613/222258325-c36cce64-d708-4460-9ca6-cfaf14409c5f.png)

If this approach seems okay, I can go ahead with implementing it. Suggestions please :smiley: 

@noman2002 @DMills27

**Comment by ikjot-2605** [comment]
> For this issue, I had a simple idea to make the entire process seem a little more intuitive for the user. We could:
> 
>     1. Show the edit icon next to the message icon(just below the image, on the same row as the event name).
> 
>     2. Have the delete button as a FAB(Floating Action Button). Here, to prevent accidental deletion of event, we can show a dialog box as well to confirm event deletion.
> 
> 
> ![Untitled Diagram drawio(1)](https://user-images.githubusercontent.com/55295613/222258325-c36cce64-d708-4460-9ca6-cfaf14409c5f.png)
> 
> If this approach seems okay, I can go ahead with implementing it. Suggestions please smiley
> 
> @noman2002 @DMills27

Hey @noman2002, does this approach look okay to you?
