### ISSUE TITLE
The done button doesn't do anything when you modify an event 

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1589]
**Describe the bug**
After entering the details and 

**To Reproduce**

Watch this video and follow the steps outlined here till 7:02

[![Follow the steps outlined here till the 50 second mark](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=405)

**Expected behavior**
The event should be modified with the details when 'done' is clicked.

**Actual behavior**
Nothing happens

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@DMills27 can you assign me this issue

**Comment by palisadoes** [comment]
@Ayush0Chaudhary are you still working on this?

**Comment by Ayush0Chaudhary** [comment]
Yes I am working on it, been a little busy with the proposal.

**Comment by palisadoes** [comment]
You were assigned another issue today. Are you ready to start working on this one again? If not we'll need to unassign you. Everyone needs a chance.

**Comment by Ayush0Chaudhary** [comment]
Sorry @palisadoes I completely forgot about this, as this is not a issue.

we can close this, this is working properly.

Before
![Screenshot from 2023-03-14 18-07-48](https://user-images.githubusercontent.com/95746190/225096191-b27713c4-b754-4eff-825e-b32471fc9ac2.png)

After
![Screenshot from 2023-03-14 18-07-24](https://user-images.githubusercontent.com/95746190/225096408-02a0a537-2c4a-4a55-a7c3-e1663d3d1aaa.png)

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @CyberWake
