### ISSUE TITLE
Disable a user being added to an event if they have already been added

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1600]
**Is your feature request related to a problem? Please describe.**
In the 'Add Event' page fix the bug that allows the user to add a user that is already added.Also, remove the distinction of them being an admin or not as it is irrelevant.

**Describe the solution you'd like**

Follow the steps outlined here till 9:42
[![Follow the steps outlined here](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=538)

As shown in the screenshot below form a single list instead of separating it into "members" and "admin" and prevent a user that has already been added from being added again.

<img width="328" alt="Screenshot at Mar 01 22-02-06" src="https://user-images.githubusercontent.com/5251658/222320208-18aa5d61-d042-4dba-9cca-9ccf155451ac.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Kushalrock** [comment]
Hello there can I take up this task?

**Comment by Kushalrock** [comment]
Hello there can I take up this task?

**Comment by Kushalrock** [comment]
Just a question you want the admin thing totally removed and just the members thing remaining right??

**Comment by palisadoes** [comment]
All invited members should be visible. There should be no distinct section for members who happen to be admins

**Comment by Kushalrock** [comment]
![image](https://user-images.githubusercontent.com/64556649/222654596-cda62329-c272-452a-ba02-2a1a24a088de.png)


![image](https://user-images.githubusercontent.com/64556649/222654812-4a01e7d5-a97c-4eb0-a773-21086b61771f.png)

![image](https://user-images.githubusercontent.com/64556649/222654889-da7aaf83-6a79-4aea-9fb2-d411965cf5c1.png)

Is this okay?? I have removed the add admins section and instead made a make admin button in the bottom modal sheet. This way if someone is not a member he can't be an admin also.

**Comment by palisadoes** [comment]
This is a good thought, however you will see on our GSoC ideas page that [we will not support administrative functions in the mobile app.](https://docs.talawa.io/docs/internships/internship-ideas/#research) That way we don't have to enable or disable features according the the user's role. It makes the mobile app code much simpler.

**Comment by Kushalrock** [comment]
Okay so it means I just have to remove the admins section and admin related code. I just made it more complex for myself I suppose. I thought the problem was that a person who is not a member is also an admin. Therefore went this route. 

In reality in the app side there will no distinction in roles of admin  and members or more specifically we can't set admins through app therefore just removing the admin section related ui and code will do? Am I getting you correctly?

**Comment by palisadoes** [comment]
Yes, it is a simple issue. All invited members must be shown, but there must be no distinction as to whether they are an admin or not
