### ISSUE TITLE
Implement scrolling functionality for the Event Details page

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1601]
**Is your feature request related to a problem? Please describe.**

Under the "Attendees" section in the "Events Details" page implement the ability to scroll down the page to see all the attendees and remove the "See all" option.

**Describe the solution you'd like**

Follow the steps outlined here till 10:16
[![Follow the steps outlined here](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=582)

<img width="322" alt="Screenshot at Mar 01 22-09-13" src="https://user-images.githubusercontent.com/5251658/222321151-2cdce6ef-ea06-4dd7-9dcb-b7486da6df3b.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aboutaditya** [comment]
i would like to work on the issue, kindly assign me this task

**Comment by jadeharr** [comment]
@aboutaditya Are you still working on this issue?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Ladyperpetua** [comment]
@palisadoes please can i be assigned this issue?

**Comment by ALIRAZA17** [comment]
@palisadoes Can I work on this issue?

**Comment by Rizwan201** [comment]
@ALIRAZA17 cool lemme know if any update on still working
