### ISSUE TITLE
Create a more intuitive way of filtering for different events in the Explore Events page

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1602]
**Is your feature request related to a problem? Please describe.**
The way events are filtered are cumbersome and could work better if the could be filtered by toggling different option in the form of checkboxes or some other way than they are now.

**Describe the solution you'd like**

Follow the steps outlined here till 11:42
[![Follow the steps outlined here](https://img.youtube.com/vi/ix3eSReJj2k/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=617)

<img width="324" alt="Screenshot at Mar 01 22-16-36" src="https://user-images.githubusercontent.com/5251658/222322041-9ecd8702-4f68-4d3b-9b09-52368333223f.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aboutaditya** [comment]
i would like to work on this issue and i have design idea for filtering
![Image 02-03-23 at 3 23 PM](https://user-images.githubusercontent.com/100947528/222394835-8e54a3df-25a2-432f-a325-f9e05799afde.jpg)
I can create ui like this according to the decided filter fields.
kindly assign me the issue if you like this or let me know if i should give more options

**Comment by Cioppolo14** [comment]
@aboutaditya  I am assigning it to you. Please review the video linked above at the time mentioned to ensure your solutions aligns with the discussion. Thank you!

**Comment by palisadoes** [comment]
I'm unassigning you due to inactivity. Please leave a comment here if you want to be reassigned.

**Comment by Ladyperpetua** [comment]
@palisadoes Please can I be assigned this issue ?

**Comment by ALIRAZA17** [comment]
@palisadoes Can I work on this one?

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by ALIRAZA17** [comment]
@palisadoes please reassign this to me because I'm working on it. Was busy with some other work. Will complete this as soon as possible!

**Comment by ALIRAZA17** [comment]
@palisadoes Should I replace these dropbox options with Radio Buttons because I can't think of a solution other than this in such a small space. Moreover dropbox is better in this kind of space coz its a relevant one. If you allow getting this thing out of there and propose some kind of solution at the bottom of the screen, then I may have a solution!

**Comment by ALIRAZA17** [comment]
@palisadoes What kind of solution do you want?

**Comment by palisadoes** [comment]
Which solution are you proposing as the best solution? It is not clear

**Comment by palisadoes** [comment]
Unassigned due to inactivity

**Comment by akshayw1** [comment]
@palisadoes Can I work on this issue

**Comment by Azad99-9** [comment]
@palisadoes could you please assign this issue to me.

For the design, i would like to replicate the ui mentioned in the comment: https://github.com/PalisadoesFoundation/talawa/issues/1602#issuecomment-1451600254

**Comment by palisadoes** [comment]
@rishav-jha-mech @EshaanAgg Do you have any comments on this before assigning?

**Comment by aashimawadhwa** [comment]
I think we can discuss a little more about what should be defined in the options for filteration of events we can start from generic and simple options for eg: lowest fare was quite irrelevant as of now
@palisadoes

**Comment by palisadoes** [comment]
@Azad99-9 What filtering options are you proposing? How will you test this functionality?

**Comment by Azad99-9** [comment]
@palisadoes I've watched the video and was hoping to get some more details about what's needed from the filtering menu. This would help me to come up with a more precise solution.

**Comment by palisadoes** [comment]
@Azad99-9 Please work with @DMills27 on this

**Comment by Azad99-9** [comment]
> @palisadoes I've watched the video and was hoping to get some more details about what's needed from the filtering menu. This would help me to come up with a more precise solution.

@DMills27 could you please give me some more clarity on this.

**Comment by AyushRaghuvanshi** [comment]
Hey, @Azad99-9  is this issue assigned to you? This looks interesting. If not @aashimawadhwa  can you assign it to me? 
I do have some idea on how to give more clarity with what filters intend to do.

**Comment by Azad99-9** [comment]
@AyushRaghuvanshi currently I am working on some other issue, so yeah if you want you can take this issue👍.

**Comment by aashimawadhwa** [comment]
@AyushRaghuvanshi  assigned to you.

**Comment by AyushRaghuvanshi** [comment]
@DMills27 @aashimawadhwa  Hey so I have a proposal for UX I was thinking about making a UI like [this](https://github.com/PalisadoesFoundation/talawa/issues/1602#issuecomment-1451600254) for more intuitiveness.

And I was also thinking of adding a subtitle text under each filter which explains that filter in two three words. That would add to some clarity as well.

**Comment by aashimawadhwa** [comment]
@AyushRaghuvanshi  what filtering options you will be implementing !? You can read the conversation in this pr and then come up woth a solution.

**Comment by AyushRaghuvanshi** [comment]
- All Events : Show All Events of this organization
- My Events: Events Created by me
- Registered Events: Events I have regsitered to
- Public Event : Anyone can join
- Private Events: Need a approval from the Event organizer to attend.

So Plan is to make a card with title and a greyish subtitle which will contain this small information of that filter... This I think will increase the clarity

**Comment by DMills27** [comment]
@AyushRaghuvanshi The idea you have in theory sounds good but you'll need to design it properly to avoid any unnecessary clutter with the filters. I would like to see a mockup of how this would look before you start to work on it.

**Comment by AyushRaghuvanshi** [comment]
https://www.figma.com/file/hu3U2tqiD4KetkndJKsiPi/Talawa-Mockup?type=design&node-id=0%3A1&mode=design&t=I4FRWntfdMPFmxa3-1

![image](https://github.com/PalisadoesFoundation/talawa/assets/62144720/ef9c786c-9fba-4f95-ba2f-7b6d7d655bea)

Hey @DMills27  Can you review and see if it works? Colors are inaccurate I will make it accurate in app if you approve.

**Comment by AyushRaghuvanshi** [comment]
@aashimawadhwa can you look into this?

**Comment by palisadoes** [comment]
@rishav-jha-mech Please take a look too.

**Comment by rishav-jha-mech** [comment]
The design mockup LGTM

**Comment by AyushRaghuvanshi** [comment]
ohkay Ill start working on it
