### ISSUE TITLE
The profile page screen looks weird, irregular and overflowed

### ISSUE THREAD

**Issue by Kushalrock** [PalisadoesFoundation/talawa#1608]
**Describe the bug**
The profile page looks weird and irregular and also overflows on certain older screens like Google Pixel 2.

**To Reproduce**

1. Open the app
2. Go to the profile page

**Expected behavior**
It should have been regular and no overflow should have happened

**Actual behavior**
Irregular and overflow. By irregular I mean the spacing between different menu bar tiles (specifically my bar and donate us) and overflowing of pixels. Please see the attached image. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64556649/222874089-0d8643f7-6bb4-4ae5-af45-d7285cea68e9.png)

**Additional details**
Model Of Phone - Google pixel 2

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Kushalrock** [comment]
Is it okay if I take up this issue?

**Comment by palisadoes** [comment]
Please explain what weird and irregular means

**Comment by Kushalrock** [comment]
@palisadoes I have attached an image you can see my task and donate us don't have much space in between them also overflowing by pixels.

**Comment by palisadoes** [comment]
Please state that in the issue description so that other people will know exactly what you are mentioning. We use the issue template to make it easier for us to do searches for past problems. When they are not sufficiently descriptive this is harder.

**Comment by Kushalrock** [comment]
> Please state that in the issue description so that other people will know exactly what you are mentioning. We use the issue template to make it easier for us to do searches for past problems. When they are not sufficiently descriptive this is harder.

I have updated the issue description. Sorry about that. Please let me know if you assign me this task. I would be more than happy to contribute to this.

**Comment by palisadoes** [comment]
https://youtu.be/ix3eSReJj2k?t=1256 There is more to this. The icon colors are not consistent and may be hard coded versus using a variable that passenger can recognize. 

This is shown in the video link. Please update that too in your fix.

**Comment by palisadoes** [comment]
Yes.
