### ISSUE TITLE
Post Not Being Created in Database after Posting Something

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa#1610]
**Describe the bug**
When we create a post using the ```Add``` button in the app, it does nothing, and shows ```Post is uploaded```, but, inside the database, we don't have any post created.

**To Reproduce**

1. Go to Talawa-App
2. Create a new post
3. Check database for all post documents
4. No document will be there for recently created post

**Expected behavior**
There should be a post created.

**Actual behavior**
No post is being created.

**Screenshots**
![image](https://user-images.githubusercontent.com/94157520/222938208-e7f648ef-4206-40d4-84dd-459a5b986809.png)
![image](https://user-images.githubusercontent.com/94157520/222938228-a84cf8cc-04be-4134-89e0-a52554588a94.png)

**Additional details**
No

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Kushalrock** [comment]
I guess this is related to graphql changes in the backend with DateTime. Events Services has been migrated but Post Services and Comments have not been, I had the same query. Therefore you will see something went wrong error. Also this is an issue already highlighted. See issue #1585.

**Comment by anshgoyalevil** [comment]
@Kushalrock 

There is no API call made to the server, so we can't say that the problem is with API.

I guess, the Create Post login in the app is not able to make any API call. What do you think?

**Comment by Kushalrock** [comment]
Let me check my mongo db posts collection name and see if it is being called from flutter app.

**Comment by Kushalrock** [comment]
@anshgoyalevil Can you close this issue and let's talk in the main issue thread? Because there is redundancy in issues. Meet e at issue #1585

**Comment by anshgoyalevil** [comment]
@Kushalrock 

Let's wait for other view on this issue.

Separating the issues, so working upon this feature becomes more easy.

**Comment by Kushalrock** [comment]
Sure @anshgoyalevil. Btw this has something to do with uploadPost function which is just a mock functiona nd doing no network callls

**Comment by palisadoes** [comment]
Please refer to https://github.com/PalisadoesFoundation/talawa-api/pull/1115 and related issues that will be created as a result. Comment there as necessary.

**Comment by literalEval** [comment]
Is anyone implementing this feature ?

**Comment by literalEval** [comment]
@palisadoes this is indeed an issue and a blocker in some GSoC projects because they rely on this system to work fine. If posts don't work at all, how would someone build a project on top of that.

**Comment by anshgoyalevil** [comment]
@Kushalrock Have you tried resolving it.?

**Comment by palisadoes** [comment]
@anshgoyalevil can you work on this? It's been 5 days.

**Comment by anshgoyalevil** [comment]
@palisadoes 

Sir, I don't have much expertise in Flutter and Mobile Development. 

I would request mobile app contributors to have a look into this issue.

**Comment by Kushalrock** [comment]
@anshgoyalevil I was busy with other issues. As soon as I am over with them I wilk take this up.

**Comment by palisadoes** [comment]
@Kushalrock I'm assigning this to you as a priority though you are over the issue limit.

**Comment by Kushalrock** [comment]
@palisadoes Sure I will revert back asap.
