### ISSUE TITLE
No Messaging When No Organizations are Created

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1612]
**Describe the bug**
1. When no organizations are created, Talawa presents an empty screen in the select organization screen.
1. No information is provided as to how the user must proceed.

**To Reproduce**

1. Install Talawa, Talawa-API and Talawa-Admin as per their installation guides
2. When you try to select an organization in Talawa, you get no error message about why none are being displayed.

**Expected behavior**
We need a popup message that states "No organizations found Please create one using Talawa Admin"."

**Actual behavior**
See above

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/222945994-2cc40611-d51c-4e81-8f7f-12a5921eee97.png)

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by indresh149** [comment]
may I work on this issue?

**Comment by palisadoes** [comment]
@indresh149
1. It also doesn't make sense to have a `Continue` button. It should say  `Back` or something similar
1. Make sure your message automatically changes depending on the language. This may require you to add some entries in the Talawa-API translations. Try searching closed PRs to see how this is done.

**Comment by indresh149** [comment]
@palisadoes ok sure I will try to fix this I think there should be a Back button instead of continue.

**Comment by aryamanshrivastava** [comment]
may I work on this issue?

**Comment by palisadoes** [comment]
@aryamanshrivastava is already been assigned. Please look at other issues in the queue.

1. There are many test case issues
1. Look for bugs that have a serious impact on the operation of the app and create issues for it. This issue was created after a bug was found

**Comment by indresh149** [comment]
which snackbar i will use for showing this message (No organization exist please create one) ? 

![image](https://user-images.githubusercontent.com/76736055/223475857-c90720bd-aaf0-4e80-b01d-e5e41400b5d5.png)

or 

![image](https://user-images.githubusercontent.com/76736055/223476141-46ea4a72-2e2d-4b3d-8ae8-2b56ac6e44b2.png)

@palisadoes

**Comment by Ayush0Chaudhary** [comment]
![Screenshot from 2023-04-14 12-38-06](https://user-images.githubusercontent.com/95746190/231969753-b1d0a557-660e-4fc6-9c66-1e1da58ad34e.png)
@palisadoes 
The current implementation to solve this issue is not working. 
It is not considering the multiple refetch of the orglist.

I think we should reopen this issue.

**Comment by Ayush0Chaudhary** [comment]
Instead of calling it after adding frame, we should add a timer of like 5 seconds.
If the orgs are not fetched by then. then we should show this error widget

**Comment by SiddheshKukade** [comment]
@Ayush0Chaudhary the solution was working fine for me. Make sure you're using all of the updated versions of API.

**Comment by Ayush0Chaudhary** [comment]
@SiddheshKukade please have a look at the code.

https://github.com/PalisadoesFoundation/talawa/blob/f9a1ca78a8b309b005034a5507fb9d52520553cb/lib/widgets/organization_list.dart#L61-L74



> @Ayush0Chaudhary the solution was working fine for me. Make sure you're using all of the updated versions of API.

I checked it, I have the latest version.

PS: My intentions were not to offend you. :v:

**Comment by Ayush0Chaudhary** [comment]
![Screenshot from 2023-04-14 12-38-06](https://user-images.githubusercontent.com/95746190/231969753-b1d0a557-660e-4fc6-9c66-1e1da58ad34e.png)
@palisadoes @SiddheshKukade 
The current implementation  **is not considering the multiple refetch** of the orglist.

Should we reopen this issue?

**Comment by SiddheshKukade** [comment]
> PS: My intentions were not to offend you. ✌️

@Ayush0Chaudhary 

I'm not offended at all. I was just confused about why was that code working for me. (you can also refer to the screenshots of the past PRs )

**Comment by Ayush0Chaudhary** [comment]
> > PS: My intentions were not to offend you. v
> 
> @Ayush0Chaudhary
> 
> I'm not offended at all. I was just confused about why was that code working for me. (you can also refer to the screenshots of the past PRs )

The code was failing because it checks whether the data has arrived as soon as the widget are rendered. And in real world there is a lot of latency.
@SiddheshKukade

**Comment by SiddheshKukade** [comment]
@Ayush0Chaudhary I actually tested on the real device, and I think you're testing it on emulator r. That's why there might be some latency.
