### ISSUE TITLE
No message on Clicking verify organisation url

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1615]
**Describe the bug**
1. In talawa app on startup page , No message is showing on clicking verify.
2. It should show a verify message or an error in case of invalid url.

**To Reproduce**

1. Install Talawa, Talawa-API and Talawa-Admin as per their installation guides
2. When you try to login and enter the url of organization it will show nothing.

**Expected behavior**
It should show a verify message or an error in case of invalid url.

**Actual behavior**
It is showing nothing

**Screenshots**

https://user-images.githubusercontent.com/76736055/222953485-1d9a002e-87fb-4d65-af42-2cb0cd0d001e.mp4

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by indresh149** [comment]
![image](https://user-images.githubusercontent.com/76736055/223211077-5992b46c-1029-48e4-8533-ce445cf4c6a2.png)

@palisadoes @Cioppolo14 This type of pop-up dialog is good to show message or I will do something else?

**Comment by palisadoes** [comment]
There is a standard warning popup you can use. Please modify it for events that are successful or create a new one.

**Comment by palisadoes** [comment]
1. Use the first one when it's valid. 
1. Use the second one when it's not

**Comment by indresh149** [comment]
@palisadoes ok, I opened one PR please review. Thank You
