### ISSUE TITLE
Post is not showing in the talawa-App after adding in talawa-admin

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1617]
**Describe the bug**
 1. Post is not showing in the Talawa after being created in the Talawa- admin.
 2. And the post created using the Talawa- App is also not showing neither in Database of (Talawa-admin) nor on the Talawa Home page.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides
2. log in to the Talawa-Admin and Talawa app.
3. Make a post manually on Talawa-Admin.
4. Try to refresh the Talawa app. It is not showing the post.

**Expected behavior**
Created post of that organization should be shown on the Home page of the Talawa app

**Actual behavior**
It is not showing any posts from that organization

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/222955961-3843eaf5-f19e-4dd2-8575-b9be0572be0d.png)

**Additional details**
See Above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
Unassigned because you had 4 issues assigned to you @indresh149

**Comment by Ladyperpetua** [comment]
can this issue be assigned to me please?
