### ISSUE TITLE
No proper installation instruction in Talawa Installation Docs

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa#1623]
**Is your feature request related to a problem? Please describe.**
There are no proper instructions for using the Local Talawa API Instance inside the Talawa App.

For example, we have Talawa Api running inside local machine and we can access it using ```localhost:{PORT_NUMBER}/graphql```

Now, how can we access this URL inside the Mobile App running on a real device or, inside the Android Virtual Device. Like we can use ```10.0.2.2``` for AVD, and IPV4 address for a real device.

**Describe the solution you'd like**
Changes to installation docs need to be done for users to figure out this thing.

**Describe alternatives you've considered**
Alternatively, developers can search the web for this thing, but, it is not what should be done.

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
No

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes Could you please assign this issue to me.

**Comment by palisadoes** [comment]
The current INSTALLATION.md file refers to the INSTALLATION.md file in Talawa-API to get the URL which should be the only source of truth while development is so fluid. 

When things settle down, then we can think about updating the Talawa INSTALLATION.md file.

Closing. 

It's a valid request. Please open a similar issue in Talawa-API
