### ISSUE TITLE
Bug: Keyboard opens on its own after closing the Drawer

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1626]
**Describe the bug**
1. After opening the keyboard first time for adding text to the post keyboard automatically 
    opens after closing the Drawer without selecting any Input fields.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides
2. Login in the Talawa and go to the  Add Page write something in the post text.
3. Close the post section and go to Home Page(or any page) open the Drawer and close the App bar 
4. After closing the Drawer, the keyboard opens by own although we are not writing on any input text field.

**Expected behavior**
The keyboard should open automatically only when we try to input on any TextInput field.

**Actual behavior**
The keyboard is opening on its own after closing Drawer.

**Screenshots**

https://user-images.githubusercontent.com/76736055/223049542-edbfd747-6850-4973-8652-9d4b41d8041f.mp4

**Additional details**
I have tested it on Redmi Note 7(Android 10), Redmi Y2(Android 9) , Emulator(Android 10)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@indresh149 Is this an issue you'd like to be assigned?

**Comment by indresh149** [comment]
yes I would like to be assigned

**Comment by noman2002** [comment]
@indresh149 You have 4 issues assigned right now. I am unassigning 2 because as per rule maximum of 2 can be assigned at once.

**Comment by SiddheshKukade** [comment]
@noman2002, @palisadoes I would like to work on this issue. I've took a look at `add_post_page.dart`. I can solve it. 
please assign. I don't have any other pending PR or Issues.

**Comment by palisadoes** [comment]
Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by palisadoes** [comment]
> @noman2002, @palisadoes Sir, I would like to work on this issue. I've took a look at `add_post_page.dart`. I can solve it. please assign. I don't have any other pending PR or Issues.

Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by SiddheshKukade** [comment]
@palisadoes Sir, I agree with you.

I'm sorry that I didn't noticed about my  previously assigned issues and I've explained the reason for that there 

I think the keyboard unexpectedly pooping on the screen is a bad user experience and should be fixed first.
Please let me know if I can take this up now.

(I've unassigned myself from the previously incompleted issue)

**Comment by vishal28d** [comment]
Sir, I would like to work on this issue.

**Comment by m-eraf** [comment]
I WANT TO WORK ON THIS PLZ ASSIGN IT TO ME.

**Comment by m-eraf** [comment]
@palisadoes can u guide me to write gsoc proposal??

**Comment by Rizwan201** [comment]
@Cioppolo14 @noman2002 as i see this issue is still open if no one is working on this can it be assigned to me ?

**Comment by m-eraf** [comment]
@Rizwan201 i am still working on this issue!.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Ronakkkkk** [comment]
Can you assign me this if its still open!

**Comment by Ronakkkkk** [comment]
@palisadoes I am not being able to locally host the talawa mobile app. Firsty the 'intl' dependency is deprecated and that is incompatible with the version required by flutter_localizations from the Flutter SDK. I tried updating the intl version to 0.18.0, which resolves the conflict but the earlier problem still remains; "Field 'httpLink' has not been initialized exception". which doesn't let the app to be built.

**Comment by Ronakkkkk** [comment]
@palisadoes what should I use in the organization URL while setting up the talwa pp locally on a physical device. I tried the local host one, and also the process from Wireless Lan Adapter WiFi still it shows invalid URL. My talawa-api is running and creates a playground when I run the code with npm run dev

**Comment by SiddheshKukade** [comment]
@Ronakkkkk are you running on a local wifi or a phone's hotspot for the internet??

**Comment by Ronakkkkk** [comment]
I tried both; connecting through the same wifi in both devices and also connecting to the personal hotspot by the PC.

**Comment by Ronakkkkk** [comment]
Can anyone help me with this.

**Comment by palisadoes** [comment]
Please ask the slack forums for assistance. The community there will assist.
