### ISSUE TITLE
Edit event erroneously changes the time of the event.

### ISSUE THREAD

**Issue by ikjot-2605** [PalisadoesFoundation/talawa#1630]
**Describe the bug**
In it's current implementation, the Edit Event action erroneously changes the time of the event. This is possibly a time-zone issue, but needs to be investigated. I have attached the same below: 

**To Reproduce**

1. Install Talawa, Talawa-API and Talawa-Admin as per their installation guides
2.  Login as a talawa user into the application and create an event.
3. Go to the Event Info Page and subsequently open the Edit Event Page.
4. Update some values of the event and press "Done".
5. Check the time on the updated event on the explore events page.

**Expected behavior**
If the user edits the time of the event, the edited event should reflect the same. If the user edits other parameters of the event apart from the timing, the timing should remain the same, and not change.

**Actual behavior**
Currently, the time selected/left as default by the user gets changed automatically to an incorrect time.

**Screenshots**

https://user-images.githubusercontent.com/55295613/223223804-01b23206-b855-466d-891f-ec4cd89f43fc.mp4

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@ikjot-2605 Is this an issue you'd like to be assigned once you've completed one of your two open issues?

**Comment by literalEval** [comment]
@ikjot-2605 it is indeed a timezone issue and will be fixed after GraphQL Scalars migration.

**Comment by literalEval** [comment]
@ikjot-2605 it is indeed a timezone issue and will be fixed after GraphQL Scalars migration.

**Comment by ikjot-2605** [comment]
Oh I see @literalEval.
In that case, we can just wait for that MR to be closed and then we can close this issue.

@Cioppolo14

**Comment by SiddheshKukade** [comment]
@ikjot-2605 you start date is 8th march and end date is 7th. I think that can also cause the issue due to which time it is not getting saved properly. I'm working on fixing that in #1616.
