### ISSUE TITLE
Feature Request: Google Places Autocomplete for Adding location on Add Events Page

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1636]
**Is your feature request related to a problem? Please describe.**
In add Event page on creating new events there should have an Autocomplete feature in Add Location section which is found in most apps like Ola and Uber.

**Describe the solution you'd like**
On manually entering the Address, Autocomplete should suggest some common places which match the entered location

**Describe alternatives you've considered**
See above

**Approach to be followed (optional)**
We can implement this using the Google Places API.

Screenshot of the page where we can implement it.

![image](https://user-images.githubusercontent.com/76736055/223495910-aa31896e-6ebc-446f-ae72-ad1241d7a564.png)

**Additional context**

https://user-images.githubusercontent.com/76736055/223495642-86de4128-3080-4d70-a070-1175c48e985e.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
This is a good idea for an addition for a GSOC or Outreachy project.  I'm going to close this for now, as for this time period we are focusing on bugs.
