### ISSUE TITLE
Add a reference for our custom lint rules

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1641]
**Is your feature request related to a problem? Please describe.**
We recently implemented custom lint rules but some contributors are facing difficulty in getting hold of what the rules expect.

**Describe the solution you'd like**
Add an example file in `talawa_lint` directory that will contain an exhaustive list of examples of our custom lint rules.

**Describe alternatives you've considered**
1. Add examples in CONTRIBUTING.md. But that will unnecessarily clutter this file.
2. Add examples in the official Talawa doc. I believe this can be done in conjunction with the original solution presented in this issue, so that the official doc serves as the official source of truth while the file in `talawa_lint` will come handy in referencing stuff quickly and locally.

**Comment by literalEval** [comment]
@palisadoes please confirm so that I can open respective PR. Also, this issue is based on my conversation with some contributors who reached out to me.

**Comment by palisadoes** [comment]
Talawa Docs would be the place. Then we can add a link to the page in the PR template.

**Comment by literalEval** [comment]
@palisadoes I am getting `Page not found` for [talawa-docs](https://docs.talawa.io/talawa-docs/). Where am I supposed to updated these things ?

**Comment by palisadoes** [comment]
The DOCUMENTATION.md file has information. You will need to create an issue/PR here https://github.com/PalisadoesFoundation/talawa-docs

**Comment by literalEval** [comment]
Should I add a Documentation section under `Developer Resources --> Talawa` ?

**Comment by palisadoes** [comment]
Add a new page they

**Comment by literalEval** [comment]
Okay.
