### ISSUE TITLE
Bug Report: Add event button is overlapping with the event cards.

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1653]
**Describe the bug**
Add event button is overlapping with the cards due to same color of both.

**To Reproduce**

1.Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2.log in to the Talawa app.
3.Add two events in the events section 
4.You can see that the add event button is not visible properly due to same color overlap.

**Expected behavior**
Add button should be clearly visible in both light and dark mode.

**Actual behavior**
Add button is overlapping with the event card

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/224532321-9d4de034-199f-4861-b77e-f39090b0034d.png)

**Additional details**
see above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by indresh149** [comment]
![image](https://user-images.githubusercontent.com/76736055/224540417-61c3bdef-4958-4415-9e28-1f09cb868329.png)

@palisadoes sir is it ok now ? . I have applied another color on  that floating button.

**Comment by palisadoes** [comment]
Submit a PR. The reviewers will let you know. It doesn't stand out enough. 
Please follow up with the assigned PR reviewers.

**Comment by indresh149** [comment]
@palisadoes okk sir I will submit a pr . Thank you
