### ISSUE TITLE
Bug Report : Type error thrown during lint execution

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa#1654]
**Describe the bug**
I've discovered an error with the latest implementation of the `talawa_lint` . which was unpredictively throwing errors during it's execution.
**To Reproduce**

1. run `flutter pub run custom_lint`
2.  An error is thrown sometimes.
 
![image](https://user-images.githubusercontent.com/65951872/224541857-e49b3522-4685-4f62-acef-cb0b94358116.png)

3. Actual errors are here : https://github.com/PalisadoesFoundation/talawa/actions/runs/4396186607/jobs/7698467575

**Expected behavior**
Flutter pub lint should run without errors
**Actual behavior**
error stops the execution

**Screenshots**
 
 
![image](https://user-images.githubusercontent.com/65951872/224541857-e49b3522-4685-4f62-acef-cb0b94358116.png)

**Additional details**
Some type checking must be added to fix this 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
@palisadoes Sir , Please assign me this issue as I've fixed this in #1632 
The error can be viewed here: https://github.com/PalisadoesFoundation/talawa/actions/runs/4396186607/jobs/7698467575

**Comment by SiddheshKukade** [comment]
Solution added in this file : https://github.com/PalisadoesFoundation/talawa/pull/1632/files#diff-45d7d209f4b4520529ab9a6ce5dd7b09f1eb7d3d6b486c31d0c762ca9a36e2f3

**Comment by literalEval** [comment]
@SiddheshKukade please do the `talawa_lint` changes in a separate PR, referring to this issue. That will help. Thanks.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade please do the `talawa_lint` changes in a separate PR, referring to this issue. That will help. Thanks.

@literalEval It is not possible the current PR's build will fail again, If I removed that file from it.

**Comment by literalEval** [comment]
No it won't. Give it a try :)
And if it does, then let it be. No worries.

**Comment by literalEval** [comment]
Also, @SiddheshKukade we have a pending PR in the custom_lint repo. Not getting merged due to lack of tests. Can you work on that ?

**Comment by SiddheshKukade** [comment]
> No it won't. Give it a try :) And if it does, then let it be. No worries.

I know it will.
Which are are you referring to ?

**Comment by literalEval** [comment]
We can discuss this on Slack ?

**Comment by SiddheshKukade** [comment]
Hello @palisadoes Sir, this one can also be **closed** as  #1632 is merged. I'm not sure why this issue did not appeared in that PR's page, even though it was linked in the description.
![image](https://user-images.githubusercontent.com/65951872/224794698-cd113de9-09e0-40c2-bdd8-883c3fbe59ac.png)
