### ISSUE TITLE
Bug Report: Overflow error in explore_events.dart

### ISSUE THREAD

**Issue by droy312** [PalisadoesFoundation/talawa#1655]
**To Reproduce**

1. Open Explore Events page in portrait mode

**Expected behavior**
There should be no overflow error. The widgets should be able to scroll in the horizontal direction.

**Actual behavior**
There is an overflow error. The widgets are not scrolling.

**Screenshots**
![Screenshot_20230312_214352](https://user-images.githubusercontent.com/37190888/224557719-538c7875-9402-4318-9038-c34f5aeb92de.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by droy312** [comment]
Can I work in this issue?

**Comment by noman2002** [comment]
This is already fixed in #1640 .
