### ISSUE TITLE
Bug Report: Upload image is not working in profile page 

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1658]
**Describe the bug**
1. Upload profile image in the profile section is not working .
2. It is giving: MultiMediaPickerService : Exception occurred while cropping Image
log in to the terminal.
3. It should show an error message if the Image upload fails or a successful upload message if the Image gets uploaded.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
3. log in to the Talawa app.
4. Go to the profile update  section and try to add a profile image
5. Image is not uploading and also not showing any error message or successful message.

**Expected behavior**
It should show a preview of the uploaded image and also show an error message if the Image upload fails or a successful upload message if the Image gets uploaded.

**Actual behavior**
The profile image upload section of the profile section is not working.

**Screenshots**

https://user-images.githubusercontent.com/76736055/224601474-2491f849-8588-48ee-8e10-2f17b75abf25.mp4

**Additional details**
see above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
This may be dependent on this PR. Please take a look at the files to be modified. You may not be able to fix this until the PR is merged. Comment on the PR if necessary.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1168

**Comment by noman2002** [comment]
> This may be dependent on this PR. Please take a look at the files to be modified. You may not be able to fix this until the PR is merged. Comment on the PR if necessary.
> 
>     * [image upload resolver init talawa-api#1168](https://github.com/PalisadoesFoundation/talawa-api/pull/1168)

Its almost completed.
