### ISSUE TITLE
Adding a release build to the repository from a workflow build artefacts.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#1660]
**Is your feature request related to a problem? Please describe.**
Yes, this will help new and existing contributors to get the application overview without getting the the repository setup locally. Will really help contributors from talawa-api and talawa-admin.

**Describe the solution you'd like**
Add a workflow to push releases to GitHub after the build artefacts are yielded.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
NR

**Comment by literalEval** [comment]
Do we need this for iOS too ? Cause iOS requires some plist and stuff to get a final ipa and installing packages via ipa isn't common too.

**Comment by CyberWake** [comment]
Also please do not try taking up multiple issues together we already have a lot of contributor so please get the one assigned to you first and then pick the next. Taking up multiple issues at a go really doesn't give others a chance to contribute.

**Comment by literalEval** [comment]
@CyberWake that's cool then. Also, do we need the releases at the release section of the repo of will it be fine to have them in build artifacts ?

**Comment by literalEval** [comment]
> Also please do not try taking up multiple issues together we already have a lot of contributor so please get the one assigned to you first and then pick the next. Taking up multiple issues at a go really doesn't give others a chance to contribute.

Oh sorry for that. Didn't see this comment. Actually one of those issues was pending for a lot of time and no one was showing genuine interest in fixing that. So I thought of fixing that myself.

**Comment by literalEval** [comment]
> @CyberWake that's cool then. Also, do we need the releases at the release section of the repo of will it be fine to have them in build artifacts ?

Also, can you please clarify this @CyberWake ? So that I can open the respective PR as I have already done this :)

**Comment by literalEval** [comment]
@palisadoes please assign this to me. I have the code changes ready. Thanks.

**Comment by palisadoes** [comment]
Ask @CyberWake  to review your PR.

**Comment by literalEval** [comment]
@CyberWake I will open the respective PR once you resolve my query I have asked above. Thanks.

**Comment by literalEval** [comment]
@palisadoes I need approval to move forward.

**Comment by palisadoes** [comment]
Go ahead

**Comment by literalEval** [comment]
@palisadoes sure.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by literalEval** [comment]
@palisadoes please reassign. I had the changes ready, but got busy in the docs issues. Will open a PR for this by today EOD.
