### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kyendereta** [PalisadoesFoundation/talawa#1661]
**Is your feature request related to a problem? Please describe.**
The current user interface (UI) and user experience (UX) of the Talawa open source mobile app have some usability issues that need to be addressed. There are certain areas of the app where the UI and UX are not optimal, and improvements could be made to make the app more user-friendly.

**Describe the solution you'd like**
I would like to see some improvements made to the UI and UX of the Talawa mobile app to address the current usability issues. This would involve identifying areas of the app where the UI and UX are not optimal, and making changes to improve the app's usability.

**Describe alternatives you've considered**
One alternative solution would be to redesign the entire app, but given the scope of the project and available resources, we believe that making targeted improvements to the UI and UX of the app is a more feasible solution.

**Approach to be followed (optional)**
My proposed approach would involve:
1. Conducting a review of the current UI and UX of the Talawa mobile app to identify areas where improvements can be made.
2. Drafting a report based on the findings, outlining the areas of the app that need improvement and suggesting potential solutions.
3. Making targeted improvements to the UI and UX of the app based on the report's recommendations.
4. Conducting user testing and iterating the app's design as necessary to further improve usability.

**Additional context**
The Talawa mobile app currently has some usability issues, particularly with regards to the UI and UX. Making targeted improvements to these areas of the app can help to make it more user-friendly and accessible.

**Comment by kyendereta** [comment]
Can I do this?

**Comment by jadeharr** [comment]
@kyendereta Is there an example of a usability issue you have seen? At the moment this issue is very broad and vague.

**Comment by kyendereta** [comment]
@jadeharr I am currently researching and compiling examples of usability issues to provide a more specific understanding of the problem at hand.

**Comment by noman2002** [comment]
@kyendereta The description not clear about the issue, I am closing this for now. Feel free to open an issue when find a potential bug or usability issue as you mentioned and please attach a screenshot or video for better understanding. Good Luck !!
