### ISSUE TITLE
[Bug Report] Multiple heroes with same tag on MainScreen

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1663]
**Describe the bug**
Main screen gives a `Multiple Heroes with same tag` error.

**To Reproduce**

1. Install and run Talawa app normally

**Expected behavior**
It should not show any errors and every hero should work fine.

**Screenshots**

![Screenshot_20230314_204617](https://user-images.githubusercontent.com/62198564/225052690-64ba7383-b595-4e10-bdf9-58b08b02daa7.png)

**Comment by Cioppolo14** [comment]
@noman2002 Thank you for your submission.  Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by khaledmurtaja** [comment]
why its unapproved ? @noman2002

**Comment by palisadoes** [comment]
Because it isn't assigned to anyone.

**Comment by literalEval** [comment]
@khaledmurtaja you can try taking this issue and fixing it. All of the recently opened issues are beginner friendly too.

**Comment by khaledmurtaja** [comment]
@literalEval  yes, i can give it a try

**Comment by Amogh35** [comment]
If no one is currently working on this issue, i would love to take this up.

**Comment by khaledmurtaja** [comment]
> If no one is currently working on this issue, i would love to take this up.

I'm working on it right now.
But it's not assigned for anyone.

**Comment by palisadoes** [comment]
@khaledmurtaja It won't be assigned if no one specifically asks for it. I have mentioned this to you before. I'll assign it to you now, but the next time the assignment will go to the person who first formally requests it.

**Comment by khaledmurtaja** [comment]
**UPDATE**
I have finally found a fix for this bug 💯  
@palisadoes

**Comment by khaledmurtaja** [comment]
@literalEval may you close this issue as **completed**.
