### ISSUE TITLE
[Bug Report] LateInitializationError when opening app for the first time

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1664]
**Describe the bug**
LateInitializationError when opening the app for the first time. Possibly because the app is trying to fetch data but the org URL is not set till then.

**To Reproduce**

1. Uninstall Talawa
2. Install cleanly
3. Check terminal

**Expected behavior**
The app should not fetch data when never logged in.

**Actual behavior**
App fetches data even though never logged in.

**Screenshots**
![Screenshot_20230314_204147](https://user-images.githubusercontent.com/62198564/225054914-19de227c-f1ca-43cd-9d89-b0326944a712.png)

**Comment by noman2002** [comment]
Thanks for pointing out, I have also faced this.

**Comment by literalEval** [comment]
Comes from line 186 in `main.dart` I believe. the `FetchPluginList()` should be conditional.
![image](https://user-images.githubusercontent.com/62198564/225253462-8d99ea27-369a-46e0-a661-f737613254c9.png)

**Comment by Amogh35** [comment]
I would like to work on this issue.
