### ISSUE TITLE
[BUG REPORT] Mutation `joinPublicOrganization` not complatible with talawa-api

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1665]
**Describe the bug**
This is the Error we face when we try to Signup user for the first time

**To Reproduce**

1.Try to Signup
2.
3.
4.

**Expected behavior**
Should be able to join org

**Actual behavior**
not allowing

**Additional details**
    **Failing mutation**
     ```
      mutation {
         joinPublicOrganization(organizationId: "$orgId") {
             joinedOrganizations{
               _id
               name
               image
               description
               isPublic
               creator{
                 _id
                 firstName
                 lastName
                 image
               }
               
             }
         }
    }
    ```

 **Api-error-log**
Cannot return null for non-nullable field Organization.name. {"locations":[{"line":8,"column":7}],"path":["joinPublicOrganization","joinedOrganizations",0,"name"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["/home/panda/talawa-api/node_modules/graphql/execution/execute.js:559","      throw new Error(\"Cannot return null for non-nullable field \".concat(info.parentType.name, \".\").concat(info.fieldName, \".\"));","            ^","","Error: Cannot return null for non-nullable field Organization.name.","    at completeValue (/home/panda/talawa-api/node_modules/graphql/execution/execute.js:559:13)","    at resolveField

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
This is an urgent issue as it will not let new contributors to enter the app

**Comment by Ayush0Chaudhary** [comment]
This prevent a newcomer to enter the app until and unless he use some tricks like 
first signing up and catching the error, then use same creds to loggin, and enter the org

**Comment by Ayush0Chaudhary** [comment]
@noman2002 @palisadoes @xoldyckk  
The error is resolved, but the PR on talawa-api needs to merged first before the PR on this repo

I am raising the PRs now.

**Comment by Ayush0Chaudhary** [comment]
Now new contributor will be able to at least start the app. :partying_face:

**Comment by palisadoes** [comment]
Which PR is that?

**Comment by Ayush0Chaudhary** [comment]
PR on talawa-api require test, Can I publish the PR without test, new to writing test in mongoose, Can I write test  later.?

**Comment by Ayush0Chaudhary** [comment]
> Which PR is that?
https://github.com/PalisadoesFoundation/talawa-api/pull/1205

**Comment by palisadoes** [comment]
> PR on talawa-api require test, Can I publish the PR without test, new to writing test in mongoose, Can I write test later.?

You'll need to write the tests now, or else there is no guarantee they will be completed.

**Comment by Ayush0Chaudhary** [comment]
Okay I'll write them by tonight 🫡

**Comment by xoldyckk** [comment]
@Ayush0Chaudhary Can you explain what the difference between public and private organization is? Also, how it's implemented in talawa flutter app?
