### ISSUE TITLE
[Feature Request] A thorough flow-chart of the app

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1667]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but more of an enhancement. We can make a thorough document that mentions the flow of our app in detail, start from the `main.dart` itself.

**Describe the solution you'd like**
We can make a detailed flowchart of the app to ensure that new contributors understand the app correctly. Also, existing contributors will be helped a lot if they want to implement a new feature on top of another feature and want to understand how it works under the hood.

**Approach to be followed (optional)**
There are a few options
1. [draw.io](draw.io)
2. Maybe a Google Doc
3. Figma Design (overkill ?)
4. [Excalidraw](https://excalidraw.com/)

**Comment by palisadoes** [comment]
Please close this issue here and open it in Talawa-Docs. Clearly explain that you are referring to the operation of the Talawa Mobile App.

**Comment by literalEval** [comment]
Sure @palisadoes. Will do.
