### ISSUE TITLE
[Worflow Enhancement] Using caching in the workflow to boost workflow time

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1668]
**Is your feature request related to a problem? Please describe.**
In the current workflow, the build jobs (and many others) take too much time as they are run from scratch every time.

**Describe the solution you'd like**
Workflow jobs should run as fast as possible. We can use caching offered by GitHub actions to cache a lot of intermediate stuff so that subsequent runs will be a lot faster.

**Approach to be followed (optional)**
We can use [cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) offered by GitHub.

**Additional context**
This causes more problems, for example, when changing some things in the workflow. We literally have to wait 10-20 minutes for the results to come.

**Comment by literalEval** [comment]
@palisadoes, please review this issue.

**Comment by palisadoes** [comment]
What's the progress on this?

**Comment by literalEval** [comment]
Had some progress last month. Will get this done by this week.

**Comment by palisadoes** [comment]
What's the status on this?

**Comment by literalEval** [comment]
Same as before. Got busy with the GSoC project. Will try to rework on this from next week, if a new comer doesn't claim this issue in between.

**Comment by palisadoes** [comment]
@literalEval Anything new?

**Comment by literalEval** [comment]
@palisadoes didn't look into this after GSoC period started. Moreover, since we are doing a lot of update work (especially SDK), the cache etc will be violated soon. I'd say we should look into this once we go to a stable SDK that we plan to use for a longer time.

**Comment by palisadoes** [comment]
Thanks. I'll close the issue.
