### ISSUE TITLE
Bug Report :Unresponsive UI of App drawer (UI Improvement) 

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1669]
**Describe the bug**
The UI of the App Drawer is unresponsive and shows irregular padding behavior on the bottom side in different screen sizes.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2. log in to Talawa and open the App Drawer.
3. See the bottom of the App drawer, it has different padding on different devices, in some devices, it is showing zero padding.

**Expected behavior**
The Bottom name should have some padding according to the screen size.

**Actual behavior**
It is showing zero padding on some devices.

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/225397842-14b51d0b-b57e-4606-bb4a-fc4a4b6a9681.png)

![image](https://user-images.githubusercontent.com/76736055/225397917-4d12de53-f41d-445f-8529-7e6afaf77019.png)

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@indresh149 Do you want to work on this? If so, please say you want to be assigned immediately upon creating the issue.

**Comment by indresh149** [comment]
@palisadoes yes sir I want to work on this . Sorry for the inconvenience.

**Comment by aryamanshrivastava** [comment]
@palisadoes can you please assign this issue to me.

**Comment by palisadoes** [comment]
> @palisadoes can you please assign this issue to me.

If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Ronakkkkk** [comment]
Can you assign me this if its not assigned to anyone yet!
