### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field 'httpLink' has not been initialized

### ISSUE THREAD

**Issue by khaledmurtaja** [PalisadoesFoundation/talawa#1670]
**The earliest error shows up to the debug console after running the app for the first time!(before adding org url)**
This error caused by the call for the `getOrgUrl` which failed to set an url value to the httplink variable **because the hive box does not conation any data, its the first time the app is running(user did not enter the org url)**
**To Reproduce**
1. in my opinion i don't think we need to call the `getOrgUrl` in the  pre-auth screens.
any opinions ??
![Screen Shot 2023-03-16 at 1 35 55](https://user-images.githubusercontent.com/79102102/225467096-3b8423be-c5e2-486c-9a3d-351edbfc2408.png)

**Comment by Ayush0Chaudhary** [comment]
#1664

**Comment by palisadoes** [comment]
@khaledmurtaja Closing as a duplicate.  A good observation. Please continue using the apps and suggest more bug fixes.
