### ISSUE TITLE
Adding Pagination in Join Organization Page

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#168]
By adding the pagination we can reduce the screen loading time.

**Comment by DeltaHarbinger** [comment]
This seems interesting. I'm looking forward to seeing your implementation.

**Comment by sumitra19jha** [comment]
I am excited to for this @DeltaHarbinger.
Today I just completed its backend part. Waiting for @Laurell876 to review and merge my PR so that i can begin the frontend implementation also.

**Comment by DeltaHarbinger** [comment]
Hey @sumitra19jha, a quick heads up before you work on this. Documents related to our goals for the app will be released soon. I'm not sure if these goals will include this feature, so I would recommend you wait to see if the document contradicts this idea before we progress

**Comment by sumitra19jha** [comment]
Sure. Will wait for it

**Comment by sumitra19jha** [comment]
@palisadoes @DeltaHarbinger @Sagar2366 Am I allowed to work on this issue?
In the [docs](https://palisadoesfoundation.github.io/talawa-docs/docs/features/organisations/organisations-onboarding), major changes that are suggested are concerning to organisation creation and privacy but not regarding the display of organisation list.

As the number of the organisation is increasing so is the loading time. With pagination, the user experience can be enhanced. So irrespective of the number of organisation in the database only the first few will load instantly and user can paginate afterwards. 

https://user-images.githubusercontent.com/35868598/112831948-45873780-90b2-11eb-8bba-7f3312720c8e.mov

**Comment by sumitra19jha** [comment]
@Sagar2366 This issue has been marked as unapproved. Can you tell me its current status?
Am I allowed to work on this

**Comment by palisadoes** [comment]
@sumitra19jha The code freeze has been lifted. Please merge this to the develop branch as it is a feature enhancement.

**Comment by sumitra19jha** [comment]
Sure.

**Comment by sumitra19jha** [comment]
One of the major issues that we are having currently is handling the scaling aspect of the database. As the number of organisation will increase, the current existing logic let the frontend client to first fetch the entire organisation data and then display it in the form of a list, and also the search capability is embedded with that fetched list. Therefore, the entire organisation's data needs to be fetched whatever may be the case.

Well this works great if the number of the created organisation is small, but as the number of organisation will increase this will create the following issue:
1. `Increase in Waiting Time`: The time taken to fetch the data will increase 
2. `Bad experience in finding the desired organisation`: As the number of organisation will increase, if the user wants to join a particular organisation, the search doesn't provide the capability to search in the database directly through backend API rather all organisation needs to be fetched first and then the only search can be performed.

To handle this `scaling` aspect, the PR is created whose results are shown in the video below.
The benefits of the PR are:
1. `Reduce Screen Loading Time`: Load 10 data points at a time and let the user paginate accordingly
2. `Handle Scaling Capability`: Search is connected using backend API, and displays 10 results at a time to load response as fast as possible. No need to fetch the entire list and then perform a search on that list.
3. `Filter Options`: To help the user navigate easily between `Public` & `Private` Organisation

@palisadoes @Sagar2366 @DeltaHarbinger I request you to provide your feedback on the PR


https://user-images.githubusercontent.com/35868598/116360231-58119f80-a81d-11eb-8930-bb0aeaaa6b08.mp4

**Comment by sumitra19jha** [comment]
@Sagar2366 @DeltaHarbinger @palisadoes If you find this work useful then should we do the same for the news feed page and members page?

**Comment by palisadoes** [comment]
@sumitra19jha what do apps like Instagram and LinkedIn do to prevent the user from having to click to see more data? There must be a way to use a swipe to trigger the load instead of forcing the user to click an icon.

**Comment by sumitra19jha** [comment]
@palisadoes Apps like instagram or LinkedIn use cursor methodology for pagination. Currently, in the back-end I have created queries with two parameters called `first` and `skip`, which we use to paginate the screen. By providing these values datas are fetched accordingly. Example:
```
first: 10, skip: 5
Means from first entry in database skip first 5 elements then fetch next 10 elements
```

I will try to paginate like instagram with existing queries and create a PR for that as soon as possible.

**Comment by sumitra19jha** [comment]
@palisadoes @DeltaHarbinger @Sagar2366 I created a new PR with improved pagination.
I need your feedback on whether the pagination looks good as per our requirement and can I do the same for the `newsfeed page` and `members page`?

**Comment by palisadoes** [comment]
> @palisadoes @DeltaHarbinger @Sagar2366 I created a new PR with improved pagination.
> I need your feedback on whether the pagination looks good as per our requirement and can I do the same for the `newsfeed page` and `members page`?

@sumitra19jha I merged your PR. Please proceed.

**Comment by sumitra19jha** [comment]
Sure @palisadoes
