### ISSUE TITLE
Add post view model and add post page test

### ISSUE THREAD

**Issue by Kushalrock** [PalisadoesFoundation/talawa#1680]
The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

The tests need to be written for add post view model and add post page screen. 

When complete, all methods, classes and/or functions in the file will need to be tested.
Our test/ folder has the same structure as the lib folder. Place your test file in the equivalent folder under test/. You may need to create the appropriate directory structure to do this.

Please refer to this issue on how to implement these tests correctly:(#1217)

**Comment by Kushalrock** [comment]
@palisadoes

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Kushalrock** [comment]
@palisadoes Was out for a couple of days sorry about that. I have worked a little I will wrap this up and give it by 3rd or 4th April.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.
