### ISSUE TITLE
MultiMediaPickerService : Exception occurred while cropping Image

### ISSUE THREAD

**Issue by khaledmurtaja** [PalisadoesFoundation/talawa#1681]
**Describe the bug**
on the `add new post screen`,  clicking to the `image Icon` after selecting an image from gallery then clicking the **done button**, unfortunately the `getImageFromGallery/cropImage` function, does not return any XFile or any path, that's mean that the function is not working properly, where is should return some path which i can use for adding or previewing the image inside the app so the user could be sure that the image is selected.
somehow this issue is related to **#1569** as we should fix this issue before trying to work on **#1569** because it depends on this issue

**To Reproduce**

1.making the `getImageFromGallery `return a xfile path (after applying the crop function)

**Expected behavior**
returning the image path

**Actual behavior**
no path is returned after the async function **completes**
**Screenshots**
![Screen Shot 2023-03-19 at 21 07 55](https://user-images.githubusercontent.com/79102102/226203818-0b9c6a92-658e-4fce-ae0d-9b7e37f969f6.png)
![WhatsApp Image 2023-03-19 at 9 08 31 PM](https://user-images.githubusercontent.com/79102102/226203820-be1fe440-48d7-4ff8-89d2-23ec01a2a573.jpeg)

**Comment by khaledmurtaja** [comment]
@palisadoes could you assign me for this issue?

**Comment by Pardeeplamba** [comment]
assign me for this issue . i will resolve this bug

**Comment by palisadoes** [comment]
@Pardeeplamba We have to close this as a duplicate
