### ISSUE TITLE
[ BUG REPORT ]directChatservice is not compatible with api [DirectChats not found]

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1684]
**Describe the bug**
The direct chat shows error when we open the app for the first time
**To Reproduce**

1.Complete the signup
or 
1. Complete the login

**Expected behavior**
Direct chat services should work
**Actual behavior**
Direct chat doesn't work
**Screenshots**

**Additional details**
error log s
```
[ +354 ms] I/flutter ( 4758): [GraphQLError(message: DirectChats not found, locations: null, path: null, extensions: null)]
[   +7 ms] E/flutter ( 4758): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The getter 'data' was called on null.
[        ] E/flutter ( 4758): Receiver: null
[        ] E/flutter ( 4758): Tried calling: data
[        ] E/flutter ( 4758): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
[        ] E/flutter ( 4758): #1      ChatService.getDirectChatsByUserId (package:talawa/services/chat_service.dart:89:38)
[        ] E/flutter ( 4758): <asynchronous suspension>
[        ] E/flutter ( 4758): #2      DirectChatViewModel.initialise (package:talawa/view_model/after_auth_view_models/chat_view_models/direct_chat_view_model.dart:59:5)
[        ] E/flutter ( 4758): <asynchronous suspension>
[        ] E/flutter ( 4758): 
```

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
yes

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002

**Comment by Ayush0Chaudhary** [comment]
This will not let users use the pre-implemented features that our app provide. We should repair it.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Muhammed-EmadEldeen** [comment]
Are you still working on this issue @Ayush0Chaudhary , if not I want to get assigned @palisadoes .

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Muhammed-EmadEldeen** [comment]
I have found that there is no bug in the code in the Talawa app. What happens is that the mobile app tries to get the chats with the current user and sends a query to the backend, the backend returns null as there is no table for the chats yet created in the database because the user has no chats created and thus this error appears, I have found there are two solutions for that:

1. The first is to prevent the function from raising an error when the backend returns null.
2. The second is creating a chat with a default user (this user can be the admin) and then erasing this chat to make sure that the table for chats is created and the backend doesn't return null (the default user can also be the current user of the app which will enable users to save messages in the app similar to what's in Whatsapp and telegram).

there may be other better solutions but these two were what came to my mind, I want to do the second but unfortunately, there are bugs in other functions related to the chat service, so if you want I can create multiple issues about these bugs and work on them with other contributors.

**Comment by palisadoes** [comment]
Yes, go ahead with creating the related issues.

**Comment by palisadoes** [comment]
There must be a way to do this without involving the admin user or any other user for that matter. This could open up a security hole, even for a brief period. This is not desirable. Please figure out a solution that takes this into consideration and propose it here.

**Comment by Muhammed-EmadEldeen** [comment]
I think creating a default chat with the user himself is the safest and best option, as I mentioned above it can be used as a feature to enable the user to save messages by sending them to himself or by forwarding them.

This can be done after solving all the issues related to the chat feature

I think this issue can be closed for now by creating a boolean variable telling if the user created any chats and if not then don't raise an error on null output coming from the backend

**Comment by Ayush0Chaudhary** [comment]
Hi, ayush this side, I am also a contributor at this foundation. If you would allow me , I'd like to share my views.

1. This is a shortcomings on the backend side, it should return a proper message stating that there are no chats yet. But it return null.

2. There exist functions to create chat but recently the database changed from nested to relational. So chats only contain chat uid. You can contact kanishka regarding this.

**Comment by Muhammed-EmadEldeen** [comment]
Hi, Ayush thanks for your continuous help. Okay, I will contact him as I have some questions about the chat.

**Comment by Muhammed-EmadEldeen** [comment]
Do I create a pull request for this issue as I promised or wait until they fix the backend and close this issue @palisadoes?

**Comment by palisadoes** [comment]
You'll need to create an issue in the other repo to fix the API. Then you'll need to start with on this when that is completed.

**Comment by palisadoes** [comment]
Unassigned due to inactivity

**Comment by palisadoes** [comment]
@indresh149 this is something that may interest you. We need to get chat working properly

**Comment by Manik2708** [comment]
Hey @palisadoes What are the updates? Is this issue fixed in Talawa API? I know Typescript also, so let me know if I can fix issues is Talawa API also, if it is already fixed then I can work on this issue!

**Comment by Dante291** [comment]
@noman2002 this can be closed as this potential GSoC project.

**Comment by Cioppolo14** [comment]
@Manik2708 Is this something you can work on?

**Comment by Dante291** [comment]
@Cioppolo14  Can i get a chance to work on this? As it was me who made chat inaccessible from the app and have made some contribution so i have proper understanding of codebase. I have worked on chat functionality in somewhat similar app with custom backend too.

**Comment by Dante291** [comment]
Also i just checked ain't this planned as potential GSoC project by @palisadoes

**Comment by Manik2708** [comment]
> Also i just checked ain't this planned as potential GSoC project by @palisadoes

Ya, I also asked from @palisadoes, so @Cioppolo14 I think this issue can be closed for now! As chats are potential GSoC project!

**Comment by palisadoes** [comment]
This should have been closed long ago
