### ISSUE TITLE
Mobile-app polling the server multiple time per sec to check plugin change

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1688]
**Describe the bug**
Although not a bug, the current approach for obtaining real-time upgrades through the mobile app is sub-optimal as it involves sending approximately 50-60 requests per second to check for any changes in the plugins.

**To Reproduce**

1.Complete the setuo of talawa-api, mobile and admin
2.run the app
3.See the logs of talawa-api

**Expected behavior**
To achieve real-time features without causing server overload, there are several techniques that can be employed. One such technique is the use of sockets, which allow the server to communicate with the client and inform it of any changes as they happen. This approach can reduce the number of unnecessary requests and improve the overall efficiency of the system.

Another approach is to reduce the frequency of updates, particularly for short-term needs. This can involve adjusting the polling frequency or employing caching mechanisms to avoid excessive requests to the server. Additionally, implementing server-side push notifications or utilizing WebSockets can enable real-time communication without overloading the server.

These techniques can be further optimized by implementing strategies such as load balancing, caching, and distributed computing, which can help distribute the workload and prevent any single component from becoming a bottleneck. Overall, the key is to strike a balance between real-time responsiveness and server performance, ensuring a seamless user experience while maintaining system stability.

**Actual behavior**
Making multiple request to server for now to get updates

**Screenshots**
**Additional details**
I opened the issue so that we can track this problem
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
I will like to implement short term solution quickly
@palisadoes @noman2002 @CyberWake @TheHazeEffect

**Comment by SiddheshKukade** [comment]
@Ayush0Chaudhary I think this is already a part of the GSoC idea for this year.

**Comment by palisadoes** [comment]
It's not a specific GSoC idea, however it was [identified here as a known issue](https://youtu.be/ix3eSReJj2k?t=1271) that should have been fixed and it was suggested that we include it as part of the plugin idea.
