### ISSUE TITLE
Search box not working in Create or Join Organisation Page

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#169]
The search box is not working. Also in the search box, as users enter string the result should be displayed based on:
1. name
2. description
3. category

**Comment by DeltaHarbinger** [comment]
@sumitra19jha Thanks for pointing this out.

**Comment by sumitra19jha** [comment]
You're welcome.
Also @DeltaHarbinger, Can we have a filter button on the page?
The filter button will order list by:
1. name
2. category
3. date

**Comment by yasharth291** [comment]
@sumitra19jha it is now working can you check please

**Comment by sumitra19jha** [comment]
> @sumitra19jha it is now working can you check please

Yes @yasharth291 . The result does not match with the given string.
It is an query issue, have already submitted the pull request on the talawa-api

**Comment by sumitra19jha** [comment]
Yes the click is working now

**Comment by CyberWake** [comment]
Please mart this issue as closed as it's working now.
