### ISSUE TITLE
Bug Report: Update Visibility_detector

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1694]
**Describe the bug**:
Update visibility_detector 0.3.3 to 0.4.0+2 per PR #1648 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by WojuadeAA** [comment]
Hello i will like to take on this issue
