### ISSUE TITLE
Bug Report: Update Flutter_svg 

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1695]
**Describe the bug**
Update flutter_svg from 2.0.2 to 2.0.4 per PR #1666 

-
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by WojuadeAA** [comment]
Hello, can this issue be assigned to me?
