### ISSUE TITLE
Bug Report:Update Firebase Messaging

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1697]
**Describe the bug**
Update firebase_messaging from 14.2.5 to 14.3.0 per PR #1674.
(https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Amogh35** [comment]
I would like to work on this issue
