### ISSUE TITLE
Issue when creating account

### ISSUE THREAD

**Issue by DeltaHarbinger** [PalisadoesFoundation/talawa#171]
Issue when creating an account. Possibly happens when a weak password is used (6 characters, all common letters)

**Comment by DeltaHarbinger** [comment]
![Screenshot_20210313-210032.jpg](https://user-images.githubusercontent.com/23224397/111055009-6b200a00-843f-11eb-9753-b6f5f0e60e5a.jpg)

**Comment by sumitra19jha** [comment]
Can I look into this @DeltaHarbinger ?

**Comment by DeltaHarbinger** [comment]
Yes @sumitra19jha, you're free to look into this. I just saw this issue, so I'm not sure if the actual issue is caused by the front or back end, but we can at least see that the message overflows in the box in flutter, and it need stock be fixed

**Comment by DeltaHarbinger** [comment]
I'll assign it to you @sumitra19jha

**Comment by sumitra19jha** [comment]
ok @DeltaHarbinger

**Comment by sumitra19jha** [comment]
![Screenshot 2021-03-14 at 8 49 37 AM](https://user-images.githubusercontent.com/35868598/111056167-072f2d00-84a3-11eb-8477-4b0f940cad02.png)

**Comment by sumitra19jha** [comment]
PR #177 created to resolve the issue

**Comment by DeltaHarbinger** [comment]
Thanks for fixing the issue @sumitra19jha

**Comment by sumitra19jha** [comment]
My pleasure
