### ISSUE TITLE
Make organization_list.dart multilingual

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1710]
**Describe the bug**

1. We need to make the error message displayed in `lib/widgets/organization_list.dart` multilingual to support our internationalization efforts.
2. We should remove unnecessary print statements in the file 
3. We should also make sure that the test coverage for the file gets as close to 100% as possible

**To Reproduce**

The most obvious section of the code can be found here:

```
            print("is empyt or nt");
              print(model.organizations.isEmpty);
              if (model.organizations.isEmpty) {
                navigationServiceLocal.showTalawaErrorDialog(
                  "No organizations found ! Please contact your admin ",
                  MessageType.error,
                );
              }
            });
```

**Expected behavior**

See above

**Actual behavior**

See above

**Screenshots**

N/A

**Additional details**

N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
I'd to get assigned to add multiple languages responses in all these files :
![image](https://user-images.githubusercontent.com/65951872/227702659-460411de-137a-4628-9431-ed5bba6873e5.png)
