### ISSUE TITLE
Bug Report: Update Geocoding from 2.0.5 to 2.1.0

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1711]
**Describe the bug**
Update geocoding from 2.0.5 to 2.1.0 per PR #1698.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
@Cioppolo14  I'd like to get assigned to fix this issue.
