### ISSUE TITLE
Bug Report: Update video_player from 2.5.3 to 2.6.0

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1712]
**Describe the bug**
Update video_player from 2.5.3 to 2.6.0 per PR #1699.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by WojuadeAA** [comment]
Hello, i would like to  be assigned to this issue
