### ISSUE TITLE
Bug Report: Update tutorial_coach_mark from 1.2.6 to 1.2.8

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1713]
**Describe the bug**
Update tutorial_coach_mark from 1.2.6 to 1.2.8 per PR #1700.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ALIRAZA17** [comment]
Can I work on this one?

**Comment by ALIRAZA17** [comment]
Can I work on this @Cioppolo14?
