### ISSUE TITLE
Bug Report: Update shared_preferences from 2.0.18 to 2.0.20

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1714]
**Describe the bug**
Update shared_preferences from 2.0.18 to 2.0.20 per PR 1703. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by WojuadeAA** [comment]
Hello, i would like to  be assigned to this issue.
