### ISSUE TITLE
Adding loading Spinner to join button

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#172]
As the user press the `join` button, to make the app user interface responsive, the presence of a loading spinner at the `join` button after the dialogue box will make the page transition experience better for the user.

**Comment by adithyaakrishna** [comment]
@sumitra19jha Are you working on this issue?

**Comment by sumitra19jha** [comment]
No @adithyaakrishna I am not currently working on this issue. You can go ahead :)

**Comment by adithyaakrishna** [comment]
Thanks Man💯
Do Lmk if I can work on some others too :)

**Comment by sumitra19jha** [comment]
Ok

**Comment by DeltaHarbinger** [comment]
Hey @sumitra19jha, thanks for bringing up the issue, I'll assign it to @adithyaakrishna. Please remember to link this issue to the PR which fixes it @adithyaakrishna

**Comment by sumitra19jha** [comment]
My pleasure @DeltaHarbinger 
Good luck fixing the issue @adithyaakrishna  :)
Do let me know iff you need any help

**Comment by adithyaakrishna** [comment]
Thanks @sumitra19jha 🙌

**Comment by sumitra19jha** [comment]
@adithyaakrishna is the issue being resolved ?

**Comment by DeltaHarbinger** [comment]
Hey @adithyaakrishna, please remember to add this issue to the PR if you are working on it.

If you decided not to work on it, please comment here

**Comment by adithyaakrishna** [comment]
> Hey @adithyaakrishna, please remember to add this issue to the PR if you are working on it.
> 
> If you decided not to work on it, please comment here

@DeltaHarbinger @sumitra19jha I've worked on it but was facing some issue so had to rework the thing again, I'll create a PR for the same by the EOD 💯

**Comment by sumitra19jha** [comment]
Hey, @adithyaakrishna if you are currently busy with another issue do let me know. Most of my issue are either waiting to be assigned or waiting for the goals of the app to be released. So if you are busy with some other issue do let me know.

**Comment by adithyaakrishna** [comment]
> Hey, @adithyaakrishna if you are currently busy with another issue do let me know. Most of my issue are either waiting to be assigned or waiting for the goals of the app to be released. So if you are busy with some other issue do let me know, I will work on this one.

Working on yours rn, these issues have to be discussed with the maintainers before working on them. I had some merge conflicts while trying to create a PR for your issue, so have to fix them before pushing a final commit and as @jordanliu had said that the repo is under code freeze, I wont be creating the PR but will commit to a new branch in my fork and wait for updates from maintainers :)

**Comment by sumitra19jha** [comment]
Ok!!!

**Comment by adithyaakrishna** [comment]
@sumitra19jha Its done :)
