### ISSUE TITLE
Enabling `avoid_dynamic_calls` in analysis_options.yaml

### ISSUE THREAD

**Issue by Amogh35** [PalisadoesFoundation/talawa#1721]
**Describe the bug**
As part of PR https://github.com/PalisadoesFoundation/talawa/pull/1510 for upgrading the flutter code upgrade to v3.7.0, we made edits to the [analysis_options.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/analysis_options.yaml) file. Although most of these changes have been reverted, we still need to re-enable `avoid_dynamic_calls` and fix the resulting bugs throughout the codebase.

**To Reproduce**
Run the current suite of tests, and they all pass. This is because the `avoid_dynamic_calls` check has been disabled

**Expected behavior**
`avoid_dynamic_calls` must be re-enabled, and all the resulting errors must be fixed.

**Actual behavior**
`avoid_dynamic_calls` is currently disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/105104954/227762191-ad1d209c-7acc-4014-8218-bca1b3eec2a2.png)

## Progress
- [ ] Posts
- [ ] Chats
- [ ] Events
- [ ] Profile
- [ ] Widgets
- [ ] Plugin
- [ ] Comments
- [ ] database mutations
- [ ] Main screen
- [ ] Pre-auth screens
- [ ] Miscellaneous

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Amogh35** [comment]
I would like to fix this issue myself.

**Comment by SiddheshKukade** [comment]
Hello @Amogh35, can you please give me an idea to me about which bugs can be fixed by enabling the `avoid_dynamic_calls` option in the YAML file?

**Comment by Amogh35** [comment]
Hello @SiddheshKukade, a basic description of the resulting bugs has been described by @literalEval in the snapshot attached to the issue.

**Comment by palisadoes** [comment]
Unassigned due to inactivity

**Comment by Amogh35** [comment]
I'm sorry I couldn't give enough time to this issue because of my GSOC proposal, but I'm almost done fixing the resulting bugs now. Could you please reassign this issue to me

**Comment by Amogh35** [comment]
@palisadoes After repeated testing, I believe it would be best to solve this issue under different PRs based on their functionality, as even a single bug could cause the whole app to crash or lose functionality. By solving it under different PRs, we can easily spot the problem in case something goes wrong.
Moreover, creating a single PR for this might cause merge conflicts with other pending PRs, as changes would need to be made throughout the codebase.
Please let me know if there are any problems with this approach.

**Comment by palisadoes** [comment]
OK, create multiple issues to fix each use case.

**Comment by ShubhamTiwari55** [comment]
@palisadoes I think the issue has been already resolved as the avoid_dynamic_calls is enabled. So, can you please tell me actually what is this issue is about?
<img width="500" alt="image" src="https://github.com/PalisadoesFoundation/talawa/assets/125534462/dbb1fd5f-1847-45bc-bfad-87da0721a2b9">

**Comment by literalEval** [comment]
@ShubhamTiwari55 have a look at [this PR](https://github.com/PalisadoesFoundation/talawa/pull/1771). This lint rule was enabled but was ignored in many files. The task now is to remove the ignore directive from those files and fix the issues respectively.

**Comment by Azad99-9** [comment]
@noman2002 @Cioppolo14 @Kevoniat can any one of you please assign this issue to me. I would like to work on this.
