### ISSUE TITLE
check_ignore.py script fails on images

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1729]
**Describe the bug**
The [check_ignore.py](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/check_ignore.py) script fails when checking PRs. It does not discern between code and image files.

- https://github.com/PalisadoesFoundation/talawa/actions/runs/4546366024/jobs/8014902440#step:13:54

**Comment by palisadoes** [comment]
@literalEval this one is for you

**Comment by literalEval** [comment]
Yeah found it. The original idea was to only allow files in the `lib` directory, which somehow I forgot. Sorry for the inconvenience and thanks for the catch :)
