### ISSUE TITLE
Bug Report: Overflow error in event_info_body.dart

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa#1734]
**Describe the bug**
if the title of the event is large then instead of showing it in the next line, it is giving an overflow error.

**To Reproduce**

1. Install Talawa, Talawa-API, and Talawa-Admin as per their installation guides.
2. log in to Talawa and open the events section.
3. Click on the event card to see info about the event.
4. If the title of the event is large, then an overflow error is showing.

**Expected behavior**
If the title of the event is large then that part should be visible in the next line instead of an overflow error.

**Actual behavior**
It is giving an overflow error.

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/228929287-fab0bd1d-2a63-4377-93a8-6911fad6d403.png)

**Additional details**
see above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Reopening. We need to remove the hard coded padding that was related to this PR. We need a solution that will work for any screen size.

**Comment by indresh149** [comment]
Sorry for the inconvenience sir, I will improve the solution to make it responsive for any screen size.
