### ISSUE TITLE
[Bug] Update Profile Page Creation

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#174]
### Description
The implementation for the [update profile page](https://github.com/PalisadoesFoundation/talawa/blob/master/lib/views/pages/organization/profile_page.dart) needs to be created as it is missing in the list tile.

```
ListTile(
      title: Text(
        'Update Profile',
         style: TextStyle(fontSize: 18.0),
       ),
       leading: Icon(
          Icons.person,
          color: UIData.secondaryColor,
       ),
       onTap: () {},
)
```

### Steps to produce the issue:
1. Login/Signup
2. Press Profile Bottom Navigation Button
3. Press Update Profile 

Issue here is: Nothing will happen.

### Changes to be required
Profile Page Building

**Comment by Sagar2366** [comment]
@shikharsaurav you can start working on this issue (Closed duplicate issue you created - https://github.com/PalisadoesFoundation/talawa/issues/398)

**Comment by Sagar2366** [comment]
> @shikharsaurav you can start working on this issue (Closed duplicate issue you created - #398)
Use issue template from here https://github.com/PalisadoesFoundation/talawa/tree/master/templates and update the issue.

**Comment by shikharsaurav** [comment]
Issue Description:
No Update profile page exists
Environment Details:
in Profile Page
Observed Behaviour:
No response
Expected Behaviour:
Open update Profile Page
Does this issue need immediate attention?
Yes
Are you willing to work on this issue:
Yes

**Comment by shikharsaurav** [comment]
plz assign me
@Sagar2366

**Comment by Sagar2366** [comment]
@shikharsaurav sorry for this.  Let @sumitra19jha work on this. I will assign another issue to you.

**Comment by shikharsaurav** [comment]
but sir i have started working on it 2 hr ago @Sagar2366

**Comment by sumitra19jha** [comment]
Hey, @shikharsaurav hi
I am Sumitra, I am currently working on this profile page creation. If you have already worked on a part of the screen, you can share with me your idea about the page on slack. Would love to hear your thoughts and work.

**Comment by shikharsaurav** [comment]
sry @sumitra19jha  i am replying late bcuz i was working on other issue
can u share how much have u done so that i can help u

**Comment by sumitra19jha** [comment]
I made the PR request and attached the video of the UI outlook. You can review it and suggest the required changes. Feel free to put the message on slack. #talawa-design channel to the best of my knowledge is made for the discussion on UI part. We can discuss there along with the opinion of other fellow collaborators and can come up with even a better solution than this.

**Comment by shikharsaurav** [comment]
ok thanks
