### ISSUE TITLE
Fix test for `signup_details_view_model.dart`

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1740]
Recently we enforced `explicit return type declaration` for functions, which led to the discovery of many poorly written tests. Many of those were fixed at the same time, but some will take some extra consideration. One of them being the [test/view_model_tests/signup_details_view_model_test.dart](https://github.com/PalisadoesFoundation/talawa/pull/1739/files#diff-e7e823d12511d8f2945de143a2d91d0fd96b93bc8dcb50e2058c99b53481adb0) file.

When you `signUp`, the test is supposed to test all of the `TextControllers`, `InputFields` and `GraphQL queries` to dictate whether they are working fine or not. But the earlier test simply leveraged the dynamic return type to return `String` and assert 100% coverage.

![image](https://user-images.githubusercontent.com/62198564/229336415-aeafdc47-6a55-4adb-bf1d-24ac7c315bd2.png)

**Solution**
Test the failing test shown in the above image properly.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by literalEval** [comment]
@palisadoes oh sorry. I didn't notice that you assigned this to me :)
Let someone else do this one. I already have quite some issues to work on :)

**Comment by Dante291** [comment]
@Ayush0Chaudhary Sir there is already a valid modified test written for this file so close this issue. [test/view_model_tests/pre_auth_view_models/signup_details_view_model_test.dart](https://github.com/PalisadoesFoundation/talawa/blob/develop/test/view_model_tests/pre_auth_view_models/signup_details_view_model_test.dart)
