### ISSUE TITLE
Overflow issue on events page

### ISSUE THREAD

**Issue by Amogh35** [PalisadoesFoundation/talawa#1746]
**Describe the bug**
Overflow in the top bar of the events screen

**To Reproduce**

1. Open the events page in the app

**Screenshots**
![image](https://user-images.githubusercontent.com/105104954/229724098-72cf2340-8386-4168-9d3d-1ee5099da82a.png)

**Additional details**
This issue has been opened before too In #1561, but it looks like the solution was hardcoded through the PR #1640.
This needs to be fixed using dynamic layouts like expanded widget so that this problem doesn't come up again in any unforeseen circumstances

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Amogh35** [comment]
I would like to work on this issue myself.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Amogh35** [comment]
@palisadoes I submitted a PR for this issue over 2 weeks ago and am currently working on the changes which were requested after my PR was reviewed just a few days ago.
Please reassign this issue to me, as I am already done with the requested changes.
