### ISSUE TITLE
Bug Report: Update video_player from 2.6.0 to 2.6.1

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1747]
**Describe the bug**
Update video_player from 2.6.0 to 2.6.1 per PR #1745 
(https://github.com/PalisadoesFoundation/talawa/pull/1745/commits/b507d337a24e795d1a69269e8df6a30d5b380bf0)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ALIRAZA17** [comment]
@Cioppolo14 Can I work on this issue?

**Comment by Ronakkkkk** [comment]
Hey @palisadoes to solve this, I believe I just need to change the version of video_player from 2.6.0 to 2.6.1. What sort tests I need to write, if I am supposed to.

**Comment by palisadoes** [comment]
All existing tests must pass after the upgrade
