### ISSUE TITLE
[Bug Report] Performing comprehensive testing of all mutations and debugging any non-functional mutations.

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1748]
**Describe the bug**
Currently some services are failing. For example chatservice, direct message and some unidentified. They are failing because of talawa-api shift to non-nested schema. Many are unidentified too.

We should make our app at-least functional

We should solve these bugs before the GSoC period starts so that the selected people can focus on there ideas.

I'll **make a task list of all the errors** and correct them accordingly.

Current Failing services list
- [ ] DirectChat Service
- [ ] Fetch Comment Services
- [ ] Create Comment Services
- [ ] User Config
- [ ] Membership Request
- [ ] Event Fetch 
- [ ] Logout service

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002

**Comment by Ayush0Chaudhary** [comment]
I'll do the thorough testing and update the list

**Comment by literalEval** [comment]
This is a great issue @Ayush0Chaudhary. Though we increased our testing in the past, many of the tests are poorly written just for the sake of increasing the coverage. Please be thorough in your testing and use the mocks properly.

**Comment by Ayush0Chaudhary** [comment]
@literalEval 
I was thinking of testing if the mutation used by our mobile app are working properly. Was not thinking about writing tests for them.
Maybe we can do that in other issues.

**Comment by literalEval** [comment]
That's great.

**Comment by Ayush0Chaudhary** [comment]
@palisadoes I guess the list is complete.

**Comment by palisadoes** [comment]
So that means we should close this?

**Comment by Ayush0Chaudhary** [comment]
Why don't we create individual issues for them?
We can add check boxes in this issue to keep track. 
or 
I can solve all of the above issue in ! PR
@palisadoes

**Comment by palisadoes** [comment]
Fix them in one PR.
