### ISSUE TITLE
Remove `docs` directory from codebase

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1750]
Currently, we have a `docs` folder in the root of the codebase, which contains the documentation generated by `dart doc`. This issue proposes to remove this directory entirely.

The reasons can be explained as:

1. The directory is currently of about ~20mbs. That's a waste of bandwidth and space.
2. Everything that the doc mentions is already in the codebase and can be generated by `dart doc` on the go. Anyone can do this on their local machine.
3. We are already hosting our documentation on `Talawa-docs`

**Comment by anwersayeed** [comment]
@literalEval Please create a PR for the substitute option you are recommending before deleting the `docs` folder.

**Comment by literalEval** [comment]
@anwersayeed sure

**Comment by literalEval** [comment]
@anwersayeed can you please confirm whether the update docs workflow works for now or not? I can't see it updating the documentation in `Talawa Docs`. The workflow does run but changes nothing.

**Comment by anwersayeed** [comment]
@literalEval It commits only when it detects any change in the documentation!

**Comment by literalEval** [comment]
@anwersayeed that I understand :)
But how does it define "change in documentation?" Because the PR I have mentioned above did change the documentation of some fields. Not only that specific PR, but all of the PRs I saw had the same message of "no documentation change" even though documentation was changed for fields. That is why Talawa Docs has quite old documentation of the codebase.

**Comment by anwersayeed** [comment]
@literalEval We have a folder `talawa/docs`. A documentation change will be detected when files inside this folder are changed.

**Comment by literalEval** [comment]
@anwersayeed Oh okay. So we generate the docs, match them with the ones in the `talawa/docs` folder, and if changes are detected, we push to `Talawa Docs`. Is that correct ?

**Comment by anwersayeed** [comment]
> @anwersayeed that I understand :) But how does it define "change in documentation?" Because the PR I have mentioned above did change the documentation of some fields. Not only that specific PR, but all of the PRs I saw had the same message of "no documentation change" even though documentation was changed for fields. That is why Talawa Docs has quite old documentation of the codebase.

Checkout this workflow, `Update-Documentation`. It seems `docs/talawa` are not receiving changes.

**Comment by anwersayeed** [comment]
> @anwersayeed Oh okay. So we generate the docs, match them with the ones in the `talawa/docs` folder, and if changes are detected, we push to `Talawa Docs`. Is that correct ?

Yeah, we cannot commit without any changes.

**Comment by literalEval** [comment]
How about we match the doc generated during workflow build, and the one in the `Talawa Docs` folder? Because we are generating the docs and cloning `Talawa Docs` anyway, so they will be no new overhead. That way we can get rid of having the `docs` directory in the codebase completely. What do you think @anwersayeed ?

**Comment by anwersayeed** [comment]
> How about we match the doc generated during workflow build, and the one in the `Talawa Docs` folder? Because we are generating the docs and cloning `Talawa Docs` anyway, so they will be no new overhead. That way we can get rid of having the `docs` directory in the codebase completely, and ensure that we always have the latest documentation build without depending on the contributor to do so. What do you think @anwersayeed ?

Perfect, that is what I initially thought. Please go ahead.

**Comment by literalEval** [comment]
@anwersayeed but the current implementation too seems to be trying to do this.

![Screenshot_20230409_170933](https://user-images.githubusercontent.com/62198564/230770423-e856345a-0e81-489b-9e98-86a68e52f656.png)

According to the above snippet, the documentation is generated and then we check whether it changed any files or not. That should do be doing its job at least, because the logic to check changes is also correct. I doesn't depend on the contributor to do so. Why does it show "no doc change" then ?

**Comment by literalEval** [comment]
@anwersayeed So I migrated the `steps-state` in the workflow to its latest alternative, and it seems to be working now.

**Comment by literalEval** [comment]
@anwersayeed @palisadoes The `steps output` in the [GitHub workflow is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), and was not working in our workflow for some months. Migrating to the newer alternative causes everything to work fine now :)

**Comment by literalEval** [comment]
@palisadoes I fixed this locally. We don't need the `docs` directory anymore :)
Opening the PR. It is related to the PUSH workflow, so you might need to merge many times :)
