### ISSUE TITLE
Pinned Post Feature is not intuitive. Better solutions exist.

### ISSUE THREAD

**Issue by usmanIITR** [PalisadoesFoundation/talawa#1753]
**Describe the bug**
Pinned Post Feature is not intuitive. Better solutions exist.
**To Reproduce**

1.open the app.

**Expected behavior**
Pinned post section should be shown as it is shown in telegram/slack.

**Actual behavior**
Current UI is not using pinned post feature to its fullest.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by usmanIITR** [comment]
@palisadoes @CyberWake @noman2002 .

**Comment by palisadoes** [comment]
This is how we want it implemented. Can are you willing and able to do this?

- https://github.com/PalisadoesFoundation/talawa-api/issues/1096

**Comment by palisadoes** [comment]
Closing. This is on the GSoC ideas list and we are evaluating proposals now.

- https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas#mobile-app-improved-member-management-and-news-feed
