### ISSUE TITLE
Leave Organization button edge case error

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#176]
If user is not a part of any organization then a `snackbar` should be created informing, `user is not a part of any organisation`. Currently, Alert Dialogue is displayed asking for the permission to leave even if user is added to no organisation at all.

![WhatsApp Image 2021-03-14 at 8 41 21 AM](https://user-images.githubusercontent.com/35868598/111055966-2dec6400-84a1-11eb-971d-06a069217701.jpeg)

**Comment by cyber-venom003** [comment]
@sumitra19jha Are you working on this?? Or can I try to solve this??

**Comment by sumitra19jha** [comment]
Hi, @cyber-venom003 ,
I am currently working on some other issue. I will be very happy, if you can devotee your time in this issue.

**Comment by cyber-venom003** [comment]
Sure @sumitra19jha . I'm working on this :)

**Comment by sumitra19jha** [comment]
Great

**Comment by sumitra19jha** [comment]
Hey @cyber-venom003 , I was not talking about that snackbar. What i mean was if user is not a part of any organisation and presses leave button then a snackbar saying, "User is not part of any organisation" will appear.

**Comment by cyber-venom003** [comment]
> Hey @cyber-venom003 , I was not talking about that snackbar. What i mean was if user is not a part of any organisation and presses leave button then a snackbar saying, "User is not part of any organisation" will appear.

Ohh, so you talked about replacing a toast with snack bar, right??

**Comment by sumitra19jha** [comment]
No @cyber-venom003 
User signup ==> Join Organization ==> Left the organzation.
So user is not a part of `any organization at all ` currently.

**Current Scenario** 
Users click `leave button` again ===> Pop up Message appear ==>Select yes, nothing happens
Nothing happens because user is not part of any organization

**Proposal**
If User is not a part of any organization at all, then if user clicks 
`leave Button` ==> `SnackBar Appear instead of Dialogue`

Message of snackbar should be something like: 'This action cannot be performed as, you are not a part of any organization'

**Comment by cyber-venom003** [comment]
> No @cyber-venom003 
> User signup ==> Join Organization ==> Left the organzation.
> So user is not a part of `any organization at all ` currently.
> 
> **Current Scenario** 
> If users click `leave button` again ===> Pop up Message appear ==>Select yes, nothing happens
> Nothing happens because user is not part of any organization currently
> 
> **Proposal**
> If User is not a part of any organization at all, then if user clicks 
> `leave Button` ==> `SnackBar Appear instead of Dialogue`
> 
> Message of snackbar should be something like: 'This action cannot be performed as, you are not a part of any organization'

Okay, I got it, Lemme push one more commit in same PR. Thanks for guiding btw

**Comment by SriramPatibanda** [comment]
Hey @Sagar2366 Can you please assign this to me?

**Comment by ayushs136** [comment]
I can fix this one, can you assign it to me? @Sagar2366
