### ISSUE TITLE
Enabling `avoid_dynamic_calls` for post related functionalities

### ISSUE THREAD

**Issue by Amogh35** [PalisadoesFoundation/talawa#1761]
**Describe the bug**
We need to re-enable the `avoid_dynamic_calls` check and fix the resulting bugs. However since the bugs are highly sensitive, we are creating multiple issues for different functionalities so that it becomes easier to spot any unforeseen problems.

**To Reproduce**
Run the current suite of tests, and they all pass. This is because the avoid_dynamic_calls check has been disabled

**Expected behavior**
`avoid_dynamic_calls` must be re-enabled, and all the resulting errors must be fixed.

**Actual behavior**
`avoid_dynamic_calls` is currently disabled.

**Additional details**
This is a sub-part of issue #1721 for all the post-related bugs.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Amogh35** [comment]
@palisadoes, please assign as I am already done fixing this.

**Comment by palisadoes** [comment]
Unassigned due to inactivity

**Comment by palisadoes** [comment]
Reopening as this is a best practice.

**Comment by ilakshaygupt** [comment]
Can you please assign me this issue?

**Comment by Azad99-9** [comment]
@palisadoes this issue is fixed in [this](https://github.com/PalisadoesFoundation/talawa/pull/2312#issue-2069308542) PR.

As the `ignore_directive : avoid_dynamic_calls` has been removed from entire codebase, this issue just becomes the subset of issue #1721

**Comment by Azad99-9** [comment]
@palisadoes please close this issue as it is already fixed in [this](https://github.com/PalisadoesFoundation/talawa/pull/2312#issue-2069308542) PR
