### ISSUE TITLE
Bug Report: Update flutter_svg from 2.0.4 to 2.0.5.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1765]
**Describe the bug**
Update [flutter_svg](https://github.com/dnfield/flutter_svg) from 2.0.4 to 2.0.5. See the PR #1764.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SHREYANSH-AGRAWAL0** [comment]
can you please assign this to me

**Comment by palisadoes** [comment]
Using due to inactivity
