### ISSUE TITLE
[Feature Request] Add git hooks to run workflow checks locally before push

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1766]
**Is your feature request related to a problem? Please describe.**

There are a lot of tests that run on the codebase once a PR is opened. Many times contributors, in a hurry or ignorance of the workflow, submit the PR and fix the prerequisites only when the PR run fails. This has become more common since our introduction of custom lint rules. Doc checks are failing quite often.

**Describe the solution you'd like**

I would like to add  `pre-push git hooks` to our repos' git workflow (not GitHub workflow) so that some tests will run locally in contributors' machines when they commit anything and will fail on the spot if anything is wrong.

**Approach to be followed (optional)**

Modify `.git/hooks/pre-commit.sh` file and add commands to run the workflow scripts locally.

**Additional context**

There are a lot of tests that run on the files like `countlines`, `doc check`, `formatting check` etc. Contributors (which includes me too) often forget to follow one or two of these, which wastes our repos' resources when unnecessarily running the GitHub workflow actions.

The only addition for the contributors will be that they will need to have Python installed. I don't see this as a problem, as developers do have python, gcc etc installed. But if this seems like a problem, then we can also covert our simple python script to bash scripts.

**Comment by literalEval** [comment]
@palisadoes which tests should I include in the `pre push` hook ?

- [ ] Count line
- [ ] Correct formatting
- [ ] Default linting
- [ ] Custom linting
- [ ] Clean build

**Comment by literalEval** [comment]
@palisadoes I don't really have anything extra to say other than what I have mentioned in the issue's description :)
Can you please tell what you need me to explain ?

**Comment by palisadoes** [comment]
So you are suggesting the five in the hook? Please be clearer in future.

These should be OK. The reviewers will have the final say.

**Comment by literalEval** [comment]
> Please be clearer in future.
Oh sorry. Yes I meant that I am suggesting these 5 initially.

**Comment by literalEval** [comment]
@palisadoes I was thinking that the build, custom lint, etc take quite some time to finish up. Should we make the hook jobs voluntary? Like we prompt them for each test and they can choose whether or not they want to run it? The reason is that sometimes you push something with some silly mistake and then try to fix it immediately. In that case, the hooks shouldn't be stopping the contributor. What do you think?
