### ISSUE TITLE
Updating Talawa-Docs with DartDoc markdown files fails

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1768]
**Describe the bug**
We recognized that Talawa-Docs was not getting updated as expected in this issue:

- https://github.com/PalisadoesFoundation/talawa/issues/1750

However, documentation is not getting updated as expected. The push workflow created is not working and needs to be rectified:

- [push.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/push.yaml)

**To Reproduce**

All our pushes are failing. This needs to be fixed.

- https://github.com/PalisadoesFoundation/talawa/actions

**Expected behavior**

See Above

**Actual behavior**

See Above

**Screenshots**

N/A

**Additional details**

N/A

**Comment by literalEval** [comment]
@palisadoes on it :)

**Comment by literalEval** [comment]
@palisadoes so I read [this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule) in detail. Have you allowed "force push" to the admin account ?

**Comment by palisadoes** [comment]
We got it working with this GitHub action.
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push-documentation.yml


The settings for all reps are the same and should be OK.

**Comment by literalEval** [comment]
@palisadoes that's what the current `push.yml` is doing in this repo. Does that mean it will be working fine now ?

**Comment by palisadoes** [comment]
The current `push.yml` file doesn't use the `TALAWA_DOCS_SYNC` environment variable nor the `TALAWA_ENVIRONMENT` environment variable. Therefore it may not be working correctly. Please work with @EshaanAgg to verify whether what you currently have is correct.

**Comment by literalEval** [comment]
Oh I forgot to push. I meant that my current local implementation whose screenshot I showed as a working example. is working fine and is using these environment secrets. The updated file can be seen [here](https://github.com/literalEval/talawa/blob/boi/.github/workflows/push.yaml) (I had changes the repo's name to check its working on my fork).

With these changes, it should work right ?

**Comment by literalEval** [comment]
@palisadoes I am opening a PR.
