### ISSUE TITLE
file_picker Plugin deprecation warning

### ISSUE THREAD

**Issue by cyber-venom003** [PalisadoesFoundation/talawa#178]
The current hosted version of file_picker on [pub.dev](https://pub.dev/packages/file_picker/install) is 3.0.0, but Talawa app uses 2.0.7. 
Update it and do the needful changes in complete codebase. 
![issue_1](https://user-images.githubusercontent.com/58390399/111056476-10b99480-84a5-11eb-9e11-d95103d67328.PNG)

@DeltaHarbinger @Deandrew007 @heyjordn Please assign it to me so that I can work on this.
It is a small, but 1st contribution of mine in organisation 😅

**Comment by yasharth291** [comment]
i already opened the same issue and wanted to work for it #152

**Comment by yasharth291** [comment]
@Sagar2366  please can you help us

**Comment by DeltaHarbinger** [comment]
Hey @yasharth291, you can go ahead and start fixing deprecation issues. Since @cyber-venom003 pointed out a specific one, do you mind letting him tackle that one in particular, and you can start fixing the rest?

**Comment by CyberWake** [comment]
@cyber-venom003 thanks for showing the concern we are migrating to flutter 2 #834  and upgrading dependencies #835 hence we can close this issue now.
@palisadoes sir we can close this issue. As already handled in #835 GSoC labelled.
