### ISSUE TITLE
Feature Request: Maintain a list of all the queries and mutations being used in the client

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa#1783]
**Is your feature request related to a problem? Please describe.**
Since the Talawa client and the API is very tightly linked, it would make sense to maintain a list of all the graphql queries and mutations being used in the client currently in a single markdown file, so that the developers can easily refer to the same whenever some typeDefs are changed in the API, so as to be certain if the changes made there will make an breaking effect on the clients or not. 

**Describe the solution you'd like**
A markdown file listing all the queries and mutations being used. 

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

**Comment by literalEval** [comment]
@EshaanAgg seems to be a nice idea. I too thought something kind of this a while ago #1667

**Comment by EshaanAgg** [comment]
@palisadoes I would like to work on this issue.

**Comment by palisadoes** [comment]
1. Is there a way to automate this? It sounds like you are going to do a manual approach which will always be out of date.
2. Would a better approach be to refactor the code and its comments so that the queries and mutations are more easily found in the automated documentation?

**Comment by literalEval** [comment]
Since the queries and mutations follow a specific naming convention (query functions always end with `query`, etc), we can try making something with the use of `Talawa Lint` and `DartDoc`. 
Or maybe we can play with the autogenerated `.md` and `.html` files, parse them and extract informtation.

**Comment by palisadoes** [comment]
Wouldn't it be better to document which apps use the mutations and queries in the API code itself? That way the documentation would be automatically generated by TSDoc. This seems like unnecessary work for this repo. We need to minimize the manual update of documentation across repos.

**Comment by EshaanAgg** [comment]
The problem with that is practically no contributor would like to hop over to another repo and update the documentation whenever they want to introduce a new query/mutation to a client. The documentation should reside where the code is. 

I also completely agree with the problem that you have described of manual updation of stuff, and the simplest solution to automate the same would be to use a custom linter or a script. But the same would be highly exploratory in nature, and would require comparitvely a lot of time to be devoted to the same.
