### ISSUE TITLE
Bug Report: Update firebase_messaging from 14.3.0 to 14.4.1.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1789]
**Describe the bug**
Update [firebase_messaging](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) from 14.3.0 to 14.4.1 per PR #1787. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
@Cioppolo14 I will do this quickly :)
please assign.
