### ISSUE TITLE
Incorrect Type casting issue on 

### ISSUE THREAD

**Issue by Add00w** [PalisadoesFoundation/talawa#1798]
**Describe the bug**
```type 'List<Object?>' is not a subtype of type 'List<String>' in type cast```

**To Reproduce**

1. Run the app and see the console

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Where is this error found? Please provide more data.

**Comment by Add00w** [comment]
> Where is this error found? Please provide more data.

in main_screen_view_model.dart there is this line of code ``pluginList = (Hive.box('pluginBox').get('plugins') ?? []) as List<String>`` which is casting plugins to a list of strings but when using it expecting map in it.

**Comment by palisadoes** [comment]
@SiddheshKukade weren't you working on restoring this functionality before?

**Comment by Add00w** [comment]
> @SiddheshKukade weren't you working on restoring this functionality before?

Sorry I don't understand?

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade weren't you working on restoring this functionality before?
@palisadoes
Yes, I am sorry, I had to take a few days of break due to a small operation of my left eye. I will raise a PR in a few hours

**Comment by palisadoes** [comment]
Closing. The plugin code was deleted and needs to be restored which will solve this issue. Restoration will be resolved in the PR from @SiddheshKukade.
