### ISSUE TITLE
[Bug] Alert for not putting URL in the first page 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#180]
i have signed up without putting the URL of the organization the home screen is stuck on loading.

**Comment by Sagar2366** [comment]
I think this issue will fix it - https://github.com/PalisadoesFoundation/talawa/issues/155

**Comment by yasharth291** [comment]
its not about it. it is when we are not putting any URL in the first page it should show no URL instead it just load and load while trying to login

**Comment by Sagar2366** [comment]
Closing this issue as already fixed in recent changes.
