### ISSUE TITLE
Bug Report: Bumps json_serializable from 6.6.1 to 6.6.2.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1805]
**Describe the bug**
Bumps [json_serializable](https://github.com/google/json_serializable.dart) from 6.6.1 to 6.6.2.  See PR #1804. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
@Cioppolo14, please assign
