### ISSUE TITLE
Bug Report: Update firebase_messaging from 14.4.1 to 14.5.0

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1810]
**Describe the bug**
Update firebase_messaging from 14.4.1 to 14.5.0. See PR #1808 for more information. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
@Cioppolo14, please assign

**Comment by Cioppolo14** [comment]
@SiddheshKukade  I'm assigning all 3 as I assume they'll be quick, easy fixes? Please let me know if that's incorrect.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade I'm assigning all 3 as I assume they'll be quick, easy fixes? Please let me know if that's incorrect.

Yes, they are thanks. @Cioppolo14

**Comment by SiddheshKukade** [comment]
@Cioppolo14 Mam, you could also add the `good-first-issue` label in the other "Update versions" issues. It would also help to catch attention of new contributors 👍🏻

**Comment by SiddheshKukade** [comment]
This is completed in #1901
