### ISSUE TITLE
Bug Report: Bumps quick_actions from 1.0.2 to 1.0.3.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1818]
**Describe the bug**
Bumps [quick_actions](https://github.com/flutter/packages/tree/main/packages/quick_actions) from 1.0.2 to 1.0.3 per PR #1816.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by andoriyaprashant** [comment]
Hey @Cioppolo14 @palisadoes I want to work on this issue please assign me 
Thank you
