### ISSUE TITLE
Issue on signup

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#183]
Signup without setting an org causes error on join org page

https://user-images.githubusercontent.com/68892315/111057288-4b72fb00-84ac-11eb-9e7c-7c8e0bf22a68.mp4

I signed-up without setting any URL.

**Comment by Sagar2366** [comment]
Duplicate issue - https://github.com/PalisadoesFoundation/talawa/issues/155. 
This should get fixed as part of https://github.com/PalisadoesFoundation/talawa/issues/155

**Comment by Swayam221** [comment]
@Sagar2366 the two are different sir. let me edit the description to describe it better.

**Comment by Sagar2366** [comment]
Ok. Please add more details to understand exact issue.

**Comment by Swayam221** [comment]
@Sagar2366 this used to be an issue when a user could have logged in what no url was provided. Now the app is working fine I guess. This issue can be closed.
