### ISSUE TITLE
Bug Report: Bumps firebase_messaging from 14.4.1 to 14.6.0.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1830]
**Describe the bug**
Bumps [firebase_messaging](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) from 14.4.1 to 14.6.0 per PR #1829.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by andoriyaprashant** [comment]
Hey @Cioppolo14 can you also assign me this issue if it's open?
Thank you

**Comment by palisadoes** [comment]
Closing. We are at v14.6.3
