### ISSUE TITLE
Bug Report: Update lint from 2.0.1 to 2.0.20.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1831]
**Describe the bug**
Bumps [lint](https://github.com/passsy/dart-lint) from 2.0.1 to 2.0.20, per PR #1828. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ronakkkkk** [comment]
please assign if available.

**Comment by Ronakkkkk** [comment]
assign if available
