### ISSUE TITLE
Bug Report: Update lint from 2.0.1 to 2.0.20.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1832]
**Describe the bug**
Bumps [lint](https://github.com/passsy/dart-lint) from 2.0.1 to 2.0.20 per PR #1828. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@andoriyaprashant  Would you like this issue?

**Comment by andoriyaprashant** [comment]
Yes @Cioppolo14 please Assign me this issue. I will start working on it
Thank you

**Comment by palisadoes** [comment]
This needs to be closed. We have a custom linter.
