### ISSUE TITLE
Bug Report: Update connectivity_plus from 3.0.3 to 3.0.6.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1833]
**Describe the bug**
Update [connectivity_plus](https://github.com/fluttercommunity/plus_plugins/tree/main/packages) from 3.0.3 to 3.0.6 per PR #1827.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
Please close as already updated.
