### ISSUE TITLE
[BUG] Cant see news feed option when joined an organization 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#184]
when i joined the organization there is no option to see the news feed
![Capture](https://user-images.githubusercontent.com/55004621/111056937-64c67800-84a9-11eb-8b1f-a12df4222a34.JPG)

**Comment by pr4nshul** [comment]
Do you want an option to see the newsfeed on profile page? because I can see the option to view newsfeed on my device.

**Comment by guptapriyanshu7** [comment]
@yasharth291 are you working on this?

**Comment by guptapriyanshu7** [comment]
> 
> 
> Do you want an option to see the newsfeed on profile page? because I can see the option to view newsfeed on my device.

This happens just after you enter on joining/creating a organisation.
Basically a person is stuck on this profile tab and cannot go anywhere else.
To do so, you got to exit the app and re-enter.

**Comment by yasharth291** [comment]
no i am not working it currently you can work

**Comment by guptapriyanshu7** [comment]
Okay I am working on this.

**Comment by yasharth291** [comment]
@Sagar2366  please can you assign this to @guptapriyanshu7
