### ISSUE TITLE
Bug Report: Update image_cropper from 3.0.3 to 4.0.1

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1845]
**Describe the bug**
Update [image_cropper](https://github.com/hnvn/flutter_image_cropper) from 3.0.3 to 4.0.1. See PR #1839. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ronakkkkk** [comment]
Please assign if available.
