### ISSUE TITLE
Bug Report: Update firebase_messaging from 14.4.1 to 14.6.1.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1851]
**Describe the bug**
Update [firebase_messaging](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) from 14.4.1 to 14.6.1.  See PR #1848.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ronakkkkk** [comment]
Please assign if available.
