### ISSUE TITLE
Bug Report: Update flutter_speed_dial from 6.2.0 to 6.3.0.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1859]
**Describe the bug**
Update [flutter_speed_dial](https://github.com/darioielardi/flutter_speed_dial) from 6.2.0 to 6.3.0. See PR #1857.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
@Cioppolo14 should I open a quick PR updating all of the packages at once? That will close all of the packages issues for now.

**Comment by Cioppolo14** [comment]
@literalEval That would be very helpful. I can assign all of the open ones that aren't assigned already to you?

**Comment by literalEval** [comment]
That'll work. I'll open a PR in 1-2 hrs.
