### ISSUE TITLE
[Enhancement] Cant send message in the event .

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#187]
when i tried sending message in the event the button didn't work

**Comment by GMGOG** [comment]
also UI is breaking. 
https://user-images.githubusercontent.com/43651504/111065492-1aacb900-84e0-11eb-9e19-a9743103123a.mp4

Can I work on this issue? @yasharth291

**Comment by yasharth291** [comment]
i am currently working on it sorry

**Comment by GMGOG** [comment]
Can I work on this [https://github.com/PalisadoesFoundation/talawa/issues/235 ](issue). I you working on this issue. @Sagar2366

**Comment by GMGOG** [comment]
okay, Can I work on issue **[BUG] Issue with the post #235** if you are working in this? @Sagar2366 can you assign issue #235 to me?

**Comment by yasharth291** [comment]
i am working on issues created by me

**Comment by yasharth291** [comment]
i am already working on my issues from 5 days on different branches

**Comment by GMGOG** [comment]
sharing the load will increase the productivity & you raised this issue 40 mins ago so I thought you haven't started working on this. just a small suggestion: Don't work parallelly on the issues this can make delays in resolving the issues.

**Comment by yasharth291** [comment]
Could you please choose some easy issues and let the major issues resolved by me?

**Comment by yasharth291** [comment]
you can try #240

**Comment by yasharth291** [comment]
it is a major issue by the way you can go for #240

**Comment by guptapriyanshu7** [comment]
@Sagar2366 @DeltaHarbinger can you assign this to me?

**Comment by SriramPatibanda** [comment]
@Sagar2366 Can I take up this issue?

**Comment by yasharth291** [comment]
no enhancement till code freeze. No one is working the repo is under code freeze

**Comment by Sagar2366** [comment]
duplicate issue - https://github.com/PalisadoesFoundation/talawa/issues/187

**Comment by yasharth291** [comment]
sir but duplicate of which issue?
@Sagar2366
