### ISSUE TITLE
Bug Report: Update flutter_local_notifications from 14.1.0 to 14.1.1.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1881]
**Describe the bug**
Update [flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications) from 14.1.0 to 14.1.1.  See PR #1878.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Manas-33** [comment]
Hey! Can I work on this issue?

**Comment by palisadoes** [comment]
Unassigning due to inactivity
