### ISSUE TITLE
Bug Report: Update connectivity_plus from 3.0.6 to 4.0.1.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1884]
**Describe the bug**
Bumps [connectivity_plus](https://github.com/fluttercommunity/plus_plugins/tree/main/packages) from 3.0.6 to 4.0.1.  See PR #1883.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lalitkumawat1m** [comment]
can i fix this issue ?

**Comment by palisadoes** [comment]
You need to create a pull request against the develop branch of https://github.com/PalisadoesFoundation/talawa not your personal branch.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by pranavkonidena** [comment]
Hey, could u pls assign this issue to me? I need to change the dependency in the pubspec.yaml file right and then flutter pub get automatically fetches the newer version of the dependency?

**Comment by shashican17** [comment]
Hi @palisadoes

I have read the CONTRIBUTING.md file and INSTALLATION.md file. I can fix the bug. Can you please assign it to me?

**Comment by pranavkonidena** [comment]
Hey @palisadoes , The issue seems to be fixed already.. In PR (#1975 ).

**Comment by palisadoes** [comment]
Correct. Thanks. Closing
