### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by andoriyaprashant** [PalisadoesFoundation/talawa#1886]
## Describe the bug
This Project is outdated, it is crucial to keep the project dependencies and version up to date to leverage the latest features, bug fixes, and improvements offered by the Flutter ecosystem and its associated packages.

To resolve this issue, the dependencies listed in the project's "pubspec.yaml" file need to be updated to their latest versions.
And we also have to update build.gradle file for this

## To Reproduce

1. Go to pubspec.yaml file and build.gradle android\app file for check the version
2. Click on terminal and type "flutter pub get" to know the updates before this we have to change the version of environment: sdk in
pubspec.yaml file
3. Scroll down to see the updates

## Expected behavior
 Version up to date 

## Screenshots
![Screenshot 2023-06-06 200401](https://github.com/PalisadoesFoundation/talawa/assets/121665385/9c9c766f-ec5c-47c3-a076-a297dae6041c)

**build.gradle android\app file**
![Screenshot 2023-06-06 200501](https://github.com/PalisadoesFoundation/talawa/assets/121665385/9a39cdea-8775-4e69-8a33-1508abb6abc2)

**Comment by andoriyaprashant** [comment]
Hey @literalEval 
Please review my pull request #1887 
Thank you

**Comment by Cioppolo14** [comment]
@andoriyaprashant  Instead of making this issue, can you mention all the issues that are tracking version updates that you have addressed in your PR?

**Comment by andoriyaprashant** [comment]
Hello @Cioppolo14 
In this Pr #1887 
i changed intl version first bcz in terminal i got an error like this - 
![Screenshot 2023-06-07 173835](https://github.com/PalisadoesFoundation/talawa/assets/121665385/fdd6ad48-a917-4481-badf-9c964c8f76a2)
and after that i also upgrade the packages

**Comment by palisadoes** [comment]
Closing. We will address this at a later date.
