### ISSUE TITLE
Bug Report: Update permission_handler from 10.2.0 to 10.3.0.

### ISSUE THREAD

**Issue by Cioppolo14** [PalisadoesFoundation/talawa#1892]
**Describe the bug**
Update [permission_handler](https://github.com/baseflow/flutter-permission-handler) from 10.2.0 to 10.3.0. See PR #1890. 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by literalEval** [comment]
Please close this issue, as the said package has been updated.
