### ISSUE TITLE
[GSoC] Add request-screen-1 with optional message.

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1895]
According to my proposal, new UI

![image](https://github.com/PalisadoesFoundation/talawa/assets/95746190/7b6a529c-2c87-4995-8af6-5050d6541f0d)

**Comment by BrawlerXull** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
@BrawlerXull This is already assigned

**Comment by Ayush0Chaudhary** [comment]
@palisadoes this issue is completed, we can close this.
