### ISSUE TITLE
[Enhancement] giving minimum word limit to ever thing 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#190]
Description
There is no limit on the text currently and to make it more optimized we need to limit the text.

I am adding letter limit to post title, post description, comment, organization description, organization attendees description, event title, event description.

Issue Severity
Moderate

Observed Behavior:
No limit on the text 

Expected Behavior:
There should be limit on the text size

**Comment by utkarshshendge** [comment]
Hi @yasharth291, sorry but I didn't understand the issue title.
Adding a description is always a good practice.

**Comment by yasharth291** [comment]
@Sagar2366  can you assign me this please

**Comment by sumitra19jha** [comment]
Yeah this issue is actually repeated to a lot of place. There is no use of `TextOverflow` parameter in most of the text widget(which are generally wrapped in a `Row`, due to which they don't have multiple lines either).

**Comment by yasharth291** [comment]
yeah i am working on it and now work on this as well thanks @sumitra19jha  for pointing out

**Comment by sumitra19jha** [comment]
Great

**Comment by yasharth291** [comment]
@Sagar2366  Can you please assign me this issue it needs to be worked on

**Comment by yasharth291** [comment]
@Sagar2366  sir can you please assign me this so i can work on this

**Comment by yasharth291** [comment]
thanks sir working on it

**Comment by Sagar2366** [comment]
@yasharth291 update issue description by following issue template.

**Comment by yasharth291** [comment]
ok sir

**Comment by Sagar2366** [comment]
> Done sir

Add proper issue description @yasharth291 for which fields you are adding word limits. Spend 5-10 minutes and add more details to issue.

**Comment by yasharth291** [comment]
ok sir
