### ISSUE TITLE
Bug :  Update lint from 2.0.20 to 2.1.2

### ISSUE THREAD

**Issue by andoriyaprashant** [PalisadoesFoundation/talawa#1906]
**Describe the bug**
Bumps[ lint ](https://github.com/passsy/dart-lint) from 2.0.20 to 2.1.2, Upgradation of Pr #1900 

**To Reproduce**

1. Open talawa repo
2. Go to talawa\pubspec.yaml

**Expected behavior**
Version Up to date 

**Actual behavior**
![image](https://github.com/PalisadoesFoundation/talawa/assets/121665385/4b707c0b-5a99-4ef9-ac27-9be56c1d3a1c)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by andoriyaprashant** [comment]
Please assign me this issue @palisadoes 
Thank you

**Comment by Cioppolo14** [comment]
@andoriyaprashant This is a duplication of another issue. I can assign you that one.

**Comment by andoriyaprashant** [comment]
Ok @Cioppolo14 Thank you
