### ISSUE TITLE
[Enhancement] Adding favorite button in the organization and post section 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#192]
it will be a nice idea if we will have a favorite button like a heart in the post and organization section

**Comment by yasharth291** [comment]
@Sagar2366

**Comment by Bhavay192** [comment]
hey @yasharth291 are u working on this issue? If no , then @Sagar2366  please assign me this issue . thanks

**Comment by yasharth291** [comment]
yeah i am working on the post section all together. if you want you can go for #231

**Comment by palisadoes** [comment]
@Bhavay192 Are you willing to work on #231 as @yasharth291 suggested?
