### ISSUE TITLE
[proposal] No option to like or reply the comment 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#194]
no option to like the comment on the comment

**Comment by yasharth291** [comment]
sagar

**Comment by palisadoes** [comment]
@yasharth291  Is this still an issue?

**Comment by yasharth291** [comment]
yes sir we have to change the backend for it as there is no index as likedby in the comment entity

**Comment by palisadoes** [comment]
Can you ask someone in the API slack channel to provide that?

**Comment by yasharth291** [comment]
ok sir

**Comment by yasharth291** [comment]
Sir i will work on the same on day after Tomorrow on this @palisadoes

**Comment by yasharth291** [comment]
@Sagar2366  @DeltaHarbinger  could you please assign me this @palisadoes  sir

**Comment by DeltaHarbinger** [comment]
Hey @yasharth291, does the back end have support for this yet? Or does it still need to be implemented there?

**Comment by yasharth291** [comment]
yeah sir backend has support for this

**Comment by yasharth291** [comment]
i have just checked it for now i am adding like and unlike feature for the comments
