### ISSUE TITLE
[Proposal] Multiple Organization Selection during join

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#195]
### Description
When a user visit the page to select the organization, once the user clciks the Join Button, he/she is directly taken to home screen.

If a users wishes to be a part of ``more than one organization`` then that action can only be completed if users visits the `add/create organization page` and `repeat the join button click` for each organization seperately.

### Improvement Suggestion:
To let user perform the action of joining multiple organization in add/create organization itself by creating a button at the bottom to state that `Procced`.

### Work Flow:
1. User Visit Add/Create organization page
2. User Click join button
3. Bottom Raised Button will appear asking Proceed
4. User can join more organization by clicking the Join Button of each organization he/she likes.
5. User click the proceed button to be a part of all the organization, which has been selected as Join
Open for feedback and suggestions.

**Comment by sumitra19jha** [comment]
@Sagar2366 Your views on this?

**Comment by Sagar2366** [comment]
@sumitra19jha closing this feature as it is not required for now.
