### ISSUE TITLE
[GSoC]Feature Request: New Post UI 

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#1972]
**Is your feature request related to a problem? Please describe.**
Current Post UI is optimal to our use, we need to incorporate the new UI

**Describe the solution you'd like**
https://www.figma.com/file/oWg3Y5InWmjVQV4KSvj8t7/GSoC-Designs?type=design&node-id=0-1&mode=design&t=zYS6ExtQ1hjUPOZo-0

**Describe alternatives you've considered**
https://www.figma.com/file/oWg3Y5InWmjVQV4KSvj8t7/GSoC-Designs?type=design&node-id=0-1&mode=design&t=zYS6ExtQ1hjUPOZo-0

**Approach to be followed (optional)**[
A clear and concise description of approach to be followed.
](https://www.figma.com/file/oWg3Y5InWmjVQV4KSvj8t7/GSoC-Designs?type=design&node-id=0-1&mode=design&t=zYS6ExtQ1hjUPOZo-0)
**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa/assets/95746190/ce884021-204b-4e0f-a09d-703515d20667)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by sahilambure94** [comment]
@palisadoes If this issue is not resolved yet, I would like to work on it.

**Comment by akshayw1** [comment]
Can I work on this issue

**Comment by Ayush0Chaudhary** [comment]
It is a completed issue @palisadoes we can close this

**Comment by akshayw1** [comment]
@Ayush0Chaudhary Are there any issues, I could work on Presently, and Please Check your Slack too.
