### ISSUE TITLE
Unittests for  `graphql_config.dart`

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#1986]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/services/graphql_config.dart
```

This file can be found in the `lib/services` directory

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib%2Fservices%2Fgraphql_config.dart)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by Dante291** [comment]
@noman2002 I would like to work on this sir.

**Comment by palisadoes** [comment]
@noman2002 does this issue make sense? The only lines without coverage are a mock.

**Comment by noman2002** [comment]
@palisadoes I think we should close this.
