### ISSUE TITLE
Unittests for `select_contact.dart`

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#1987]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/views/after_auth_screens/chat/select_contact.dart
```

This file can be found in the `lib/views` directory

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/blob/develop/lib%2Fviews%2Fafter_auth_screens%2Fchat%2Fselect_contact.dart)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by asv018** [comment]
@noman2002 Sir can you assign this issue to me , I will be working on it.

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by andoriyaprashant** [comment]
Hello @noman2002 @palisadoes could you assign this issue to me 
Thank you

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Dante291** [comment]
@palisadoes @noman2002 as chat functionality is removed for now to make app MVP, would it still be ok work on this issue? If yes i would like to work on this.

**Comment by palisadoes** [comment]
Closing. We may need to revisit this later.
