### ISSUE TITLE
[Bug] FormatException in members.dart

### ISSUE THREAD

**Issue by cyber-venom003** [PalisadoesFoundation/talawa#199]
![issue_2](https://user-images.githubusercontent.com/58390399/111057550-72cac780-84ae-11eb-9b0c-ef60780ac4a1.PNG)

![Screenshot_1615697336](https://user-images.githubusercontent.com/58390399/111057582-bc1b1700-84ae-11eb-8232-559a9ec7a0a5.png)

When we login, this is exception comes up.

**Comment by pr4nshul** [comment]
Yes, i faced a similar issue. Is anyone working on this?

**Comment by Sagar2366** [comment]
@pr4nshul please always mention on issue if you are working [Especially, if someone else has reported issue, to avoid duplication of work].

**Comment by pr4nshul** [comment]
Ok, I will remember this next time. Although as @cyber-venom003 didn't mention he was working on it. I was just trying if I can resolve it and it worked the first time. But I will make sure this doesn't happen next time. Sorry for the inconvenience caused. @Sagar2366

**Comment by cyber-venom003** [comment]
> Ok, I will remember this next time. Although as @cyber-venom003 didn't mention he was working on it. I was just trying if I can resolve it and it worked the first time. But I will make sure this doesn't happen next time. Sorry for the inconvenience caused. @Sagar2366 

Yup, you were right, btw, you can work on it as I didn't mentioned it😅😅as I was busy in solving another issue.
