### ISSUE TITLE
Upgrade intl from 0.17.0 to 0.18.1

### ISSUE THREAD

**Issue by jay11125** [PalisadoesFoundation/talawa#1996]
**Describe the bug**
Upgrade [intl](https://pub.dev/packages/intl) package to 0.18.1 because version solving failed with flutter_localizations when running `flutter pub get`

**To Reproduce**

1. By running `flutter pub get` with latest flutter version 3.13.0 (I just cloned the repo and faced this issue while setting up the project)

**Expected behavior**
Version solving fail must not occur while setting up the project and should get all the packages without any issues.

**Actual behavior**
Version solving failed during `flutter pub get`

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa/assets/70865848/646b5cf5-99da-48ce-ad3b-c2b1dd3aec22)

**Comment by jay11125** [comment]
Hey @palisadoes,
Can you please assign this issue to me?
Thank you.

**Comment by imshivam-gupta** [comment]
@noman2002 Can you please assign this issue to me. I have figured it out.
Thank You.

**Comment by imshivam-gupta** [comment]
@noman2002 Can you please assign this issue to me. I have figured it out.
Thank You.

**Comment by jay11125** [comment]
Hi @noman2002 @palisadoes @imshivam-gupta ,
I am new to open source contributing and this would be my first PR. I already figured how to solve this issue at the time of creating it but didn't created PR as I thought I would have to be assigned first. 
Anyways here is my PR #1998 
Thank You.

**Comment by palisadoes** [comment]
Assigning to @jay11125 
I'll close the PR for @imshivam-gupta
