### ISSUE TITLE
[Enhancement] No option to delete comment and post

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#201]
there is no option to delete comment or delete post. If the Post is created there is no option to delete the post nor there is a option to delete the comments.

**Comment by pr4nshul** [comment]
I would like to work on this , are you currently working on it @yasharth291 ? Also, do we need the delete post and comment button to be user specific. That is the person that wrote that post have the access to delete it. Then maybe I would require some help from you.

**Comment by yasharth291** [comment]
yes i am totally working on the news feed comment and other sections too

**Comment by yasharth291** [comment]
Sorry but you can work on any other issue

**Comment by pr4nshul** [comment]
Ok

**Comment by yasharth291** [comment]
could anyone assign me this as i am done with my other assignments

**Comment by palisadoes** [comment]
@yasharth291 As this is a feature. Apply the PR to the develop branch

**Comment by yasharth291** [comment]
ok sure sir  but i think it will require the backend work as well
