### ISSUE TITLE
Upgrade the app to the latest stable version of Flutter - v3.13

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2013]
**Describe the bug**

We need to make sure that the app works with the latest 3.13 release.

https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d

**To Reproduce**

1. Upgrade the app
2. Make sure all existing tests pass and maintain their functionality (no short cuts)

**Expected behavior**

Code is upgraded and tests pass

**Actual behavior**

Code remains at current version

**Screenshots**

N/A

**Additional details**

N/A
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RathoreAbhiii** [comment]
Hey! Can I work on this issue? If yes, please assign it to me. Thanks!

**Comment by RathoreAbhiii** [comment]
@sahilambure94 Hi there! I am still working on it! Currently fixing errors detected in different tests.

**Comment by sahilambure94** [comment]
@RathoreAbhiii Okay, No worries. All the best.

**Comment by literalEval** [comment]
@Ayush0Chaudhary isn't this issue fixed by you ?

**Comment by Ashurajput02** [comment]
@RathoreAbhiii are you still working on this issue buddy ?

**Comment by palisadoes** [comment]
@Ayush0Chaudhary is working on this

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Ayush0Chaudhary** [comment]
It is completed @palisadoes

**Comment by palisadoes** [comment]
Thanks
