### ISSUE TITLE
[Enhancement] Create Organization Page UX improvement.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#203]
Hello, have a  to improve UX on create organization screen. In the attached video we see:
1. The fields are not auto submitted through keyboard and we need user interaction to bring in focus the next TextFormField.
2. Added the last field in the form is multiline hence the keyboard remains up and goes down on user interaction with native back button.
3. As the form is in SingleChildScrollView it gets shifted upward on last field coming in focus which yes/no questions come in visual range and hence user interacting directing with them doesn't cause keyboard to dismiss.

Uploading t_video6226769570569388561.mp4…

**Comment by adithyaakrishna** [comment]
@CyberWake Ig the video didn't upload

**Comment by CyberWake** [comment]
https://user-images.githubusercontent.com/44184786/111057925-fd142b00-84b0-11eb-8030-87c1fc9e1632.mp4
