### ISSUE TITLE
[GSoC] Write documentation for files

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#2033]
Below mentioned files are modified but no documentation is provided as of now. This issue serves as a checklist for them to be tracked.

- [ ] lib/views/after_auth_screens/feed/organization_feed.dart
- [ ] lib/views/after_auth_screens/join_org_after_auth/access_request_screen.dart
- [ ] lib/views/after_auth_screens/join_org_after_auth/join_organisation_after_auth.dart
- [ ] lib/views/after_auth_screens/profile/profile_page.dart
- [ ] lib/widgets/custom_avatar.dart
- [ ] lib/widgets/post_container.dart
- [ ] lib/widgets/post_detailed_page.dart
- [ ] lib/widgets/post_list_widget.dart
- [ ] lib/widgets/post_widget.dart

**Comment by Ayush0Chaudhary** [comment]
Wrote the documentation for the following files. Issue was created by me in this [PR](https://github.com/PalisadoesFoundation/talawa/pull/1971)


It was a big PR so missed some files.

**Comment by palisadoes** [comment]
@literalEval

1. Please create individual issues for this so that others can work on them quickly.
2. Provide instructions as to how the documentation should be written too.

**Comment by Ayush0Chaudhary** [comment]
> @literalEval
> 
> 1. Please create individual issues for this so that others can work on them quickly.
> 2. Provide instructions as to how the documentation should be written too.

I wrote the documentation already
