### ISSUE TITLE
[GSoC] Add multi-reaction feature on mobile app

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#2039]
**Is your feature request related to a problem? Please describe.**
Adding multireaction feature for post

**Describe the solution you'd like**
add multireaction on the app side, whenever the user click on the like button.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akshayw1** [comment]
Can I work on this Issue?

**Comment by palisadoes** [comment]
@akshayw1 It's already assigned
