### ISSUE TITLE
[bug]Profile Pic doesn't load

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#204]
![Android Emulator - Pixel_2_XL_API_30_5554 14-03-2021 10_26_45](https://user-images.githubusercontent.com/68892315/111057746-d6a1c000-84af-11eb-8b2d-f6c0e1e09a63.png)

i had created an account with a profile pic. As it can be seen in the screenshot, the pic doesnt load.

**Comment by Swayam221** [comment]
This issue might be resolved by PalisadoesFoundation/talawa-api#127.

**Comment by Sagar2366** [comment]
As discussed this issue will get solved on same PR for https://github.com/PalisadoesFoundation/talawa/issues/208.
