### ISSUE TITLE
Deprecated error for splash screen.

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#2061]
**Describe the bug**
A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
**To Reproduce**

1. run the app
2.
3.
4.

**Expected behavior**
no warning

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa/assets/95746190/61d3c7bb-e0dc-4046-8a1d-e3a6807e53d3)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
nice good first issue

**Comment by Aryashakya** [comment]
Hi, I would like to work on this.

**Comment by Aryashakya** [comment]
Please review it. #2070
