### ISSUE TITLE
Bump flutter_reaction_button from 2.0.2 to 3.0.0+2

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2075]
We need to bump [flutter_reaction_button](https://github.com/GeekAbdelouahed/flutter-reaction-button) in the code base from 2.0.2 to 3.0.0+2. 

1. We need to maintain all references to `flutter_reaction_button` in the code base, and you must use the new non-deprecated approaches in this library to maintain the  `flutter_reaction_button` functionality. Deleting flutter_reaction_button functionality is not an option.
2. You must also ensure that all code base tests pass and are valid. Tests without actual executable code does not benefit the community of users, we have experienced this unfortunate fact in the past.
3. The overall code coverage level must be maintained.

<details>
<summary>Release notes for v3.0.0+2</summary>
<p><em>Sourced from <a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/releases">flutter_reaction_button's releases</a>.</em></p>
<blockquote>
<h2>v3.0.0</h2>
<h1>BREAKING CHANGES:</h1>
<ul>
<li><code>FlutterReactionButton</code> and <code>FlutterReactionButtonToggle</code> replaced by <code>ReactionButton</code></li>
<li><code>itemSize</code> is required in <code>ReactionButton</code></li>
<li><code>onReactionChanged</code> callback updated</li>
<li><code>VerticalPosition</code> and <code>HorizontalPosition</code> removed</li>
</ul>
<h1>What's New:</h1>
<ul>
<li>Use overlay instead of navigator</li>
<li>Adds <code>child</code> to <code>ReactionButton</code></li>
<li>Animated <code>ReactionsBox</code></li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/blob/master/CHANGELOG.md">flutter_reaction_button's changelog</a>.</em></p>
<blockquote>
<h2>3.0.0+2</h2>
<ul>
<li>Minor updates</li>
</ul>
<h2>3.0.0+1</h2>
<ul>
<li>Update README</li>
</ul>
<h2>3.0.0</h2>
<ul>
<li><strong>BREAKING CHANGE</strong>:
<ul>
<li><code>FlutterReactionButton</code> and <code>FlutterReactionButtonToggle</code> removed</li>
<li><code>itemSize</code> is required in <code>ReactionButton</code></li>
<li><code>onReactionChanged</code> callback updated</li>
<li><code>VerticalPosition</code> and <code>HorizontalPosition</code> removed</li>
</ul>
</li>
<li>Adds <code>child</code> to <code>ReactionButton</code></li>
<li>Animated <code>ReactionsBox</code></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/8132578dd73d4edc37f350014b53e46e9108983b"><code>8132578</code></a> feat: update CHNAGELOG.md</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/72f2c0bd694793baf8c6eed6f676980d70bd72ac"><code>72f2c0b</code></a> feat: update pubspec.yaml</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/a8ebd81b313a92775acc246fb7048421ea4e2a6e"><code>a8ebd81</code></a> feat: remove unused resources</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/a40b15f4529764e298e7a5e13b2aa0fca0df7540"><code>a40b15f</code></a> Merge branch 'feature/overlay' of <a href="https://github.com/GeekAbdelouahed/flutter-">https://github.com/GeekAbdelouahed/flutter-</a>...</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/439ae8dcbc7a9c19c6e80ea730ab6840ec237423"><code>439ae8d</code></a> feat: update workflows</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/9e9b501bf0ecfd513e92ce338c6e70426253a685"><code>9e9b501</code></a> Update CHANGELOG.md</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/37b73f6184222268062a6d107caf56a0fc7924c3"><code>37b73f6</code></a> feat: update pubspec.yaml</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/1e50dc689e9630afaa429c522f52a4c7c8ad8815"><code>1e50dc6</code></a> feat: update CHANGELOG.md</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/cb5027636e51e3060f302eaf30f42be169c6eb83"><code>cb50276</code></a> feat: remove mouse region</li>
<li><a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/commit/cfd0234519a34b865c7cafd7c98c3b05b7ab97ed"><code>cfd0234</code></a> feat: remove unused resources</li>
<li>Additional commits viewable in <a href="https://github.com/GeekAbdelouahed/flutter-reaction-button/compare/v2.0.2...v3.0.0">compare view</a></li>
</ul>
</details>
<br />

**Comment by Azad99-9** [comment]
@palisadoes could you please assign this issue to me.
