### ISSUE TITLE
[bug]Organisation pic doesnt load

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#208]
upon creating a new org, the org_pic uploaded, is not able to load on  the newsfeed page on the top left corner

**Comment by Swayam221** [comment]
This issue might be resolved by PalisadoesFoundation/talawa-api#127.

**Comment by piyushpradhan** [comment]
**@Swayam221 Are you getting something like this ?** 

HTTP request failed, statusCode: 400, http://calico.palisadoes.org/talawa/graphql/images/dPY5r5Y9J-download.jpeg

When the exception was thrown, this was the stack
#0      NetworkImage._loadAsync
package:flutter/…/painting/_network_image_io.dart:99
<asynchronous suspension>
Image provider: NetworkImage("http://calico.palisadoes.org/talawa/graphql/images/dPY5r5Y9J-download.jpeg", scale: 1.0)
Image key: NetworkImage("http://calico.palisadoes.org/talawa/graphql/images/dPY5r5Y9J-download.jpeg", scale: 1.0)


I tried going to the NetworkImage link -> http://calico.palisadoes.org/talawa/graphql/images/dPY5r5Y9J-download.jpeg, the graphQL playground opened up and it said 

`{
  "error": "Unexpected token < in JSON at position 0"
}`

**Comment by Sagar2366** [comment]
@Swayam221 please update issue description by following our issue template.
Do not forget to add unit test for your PR.

**Comment by pr4nshul** [comment]
Is this issue still open , do you need help if it is? Otherwise, please close this issue.

**Comment by Swayam221** [comment]
@pr4nshul @Sagar2366 this issue has been resolved for the original URI which is calico.palisadoes.org, but there are a lot of issues with images on the new URI talawa-grapghql-api.herokuapp.com

**Comment by CyberWake** [comment]
thank you @Swayam221 we will surely look into upon the rewrite. If you wish we may close this issue or you can wait and check after the freeze lift on master if it still persist please let us know
