### ISSUE TITLE
[Feature Request] Make chat inaccessible to the user for master branch

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#2085]
**Is your feature request related to a problem? Please describe.**
We need to remove chat from the app, as it is not compatible right now.

**Describe the solution you'd like**
simple icon removal from the bottom bar will work

**Additional context**
this is to segregate finished and  unfinished features.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
Hello @Ayush0Chaudhary i would like to work on this issue.

**Comment by Ayush0Chaudhary** [comment]
No
