### ISSUE TITLE
[Feature Request] Remove notification related implementation

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#2086]
**Is your feature request related to a problem? Please describe.**
Currently it doesn't hinder the app but comment out all the notification related logic and add `TODO:`

**Describe the solution you'd like**
comment it out

**Additional context**
this is to make app compatible for MVP

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by andoriyaprashant** [comment]
Hello @Ayush0Chaudhary Please assign me this issue

**Comment by Ayush0Chaudhary** [comment]
This is an urgent issue. Try to do it ASAP.

**Comment by andoriyaprashant** [comment]
Hello @Ayush0Chaudhary  , as you mentioned, I have commented out the notification-related implementation part  (#2089 ) . If you would like to make any changes, please let me know, and I'll try to make them as soon as possible.
Thank you
