### ISSUE TITLE
Upgrade package video_player from 2.7.2 to 2.8.1

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2091]
We need to bump [video_player](https://github.com/flutter/packages/tree/main/packages/video_player) from 2.7.2 to 2.8.1.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2084

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6766167079/job/18386889120?pr=2084

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by vaidic-dodwani** [comment]
"Hello, I'm eager to take on this task. Could you please assign it to me?"
