### ISSUE TITLE
Upgrade package tutorial_coach_mark from 1.2.9 to 1.2.11

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2092]
We need to bump [tutorial_coach_mark](https://github.com/RafaelBarbosatec/tutorial_coach_mark) from 1.2.9 to 1.2.11.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2055

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6773178199/job/18407422166?pr=2055

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by nidhin29** [comment]
Can you assign me this
