### ISSUE TITLE
Upgrade package flutter_svg from 2.0.8 to 2.0.9

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2093]
We need to bump [tutorial_coach_mark](https://github.com/RafaelBarbosatec/tutorial_coach_mark) from 1.2.9 to 1.2.11.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2088

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6779681085/job/18427152252?pr=2088

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by nidhin29** [comment]
can you assign me this

**Comment by palisadoes** [comment]
@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.
