### ISSUE TITLE
Upgrade package firebase_messaging from 14.7.3 to 14.7.4

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2097]
We need to bump [firebase_messaging](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging) from 14.7.3 to 14.7.4.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2094

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6850365206/job/18624516553?pr=2094

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by SamarS1ngh** [comment]
hello there , can u assign me this issue?

**Comment by palisadoes** [comment]
@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.

**Comment by SamarS1ngh** [comment]
Hello there, I can't find the palisadoes foundation slack channel
Can u plz provide me the link or if there's some other name of channel or
medium

Thank you
