### ISSUE TITLE
Bug Report: Overflow Error on Post Widget.

### ISSUE THREAD

**Issue by AyushRaghuvanshi** [PalisadoesFoundation/talawa#2098]
**Describe the bug**

Upon Creating a post from Post Page 
Post widget is throwing overflow error. 

This is due to the sizedBox declared of size not dependent to the screen in the Post widget

**To Reproduce**

1. Run this App on the Pixel 3A_API 34 Extension_level 7 Emulator
2. Create a New Post
3. Check on Feeds Page

**Expected behavior**
The Sized Box which is used to create white space is expected to be dependent on Screen width

**Actual behavior**
Constant Size SizedBox is used, which is causing this overflow error

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa/assets/62144720/29427482-439e-431f-bceb-826d5bb4028b)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AyushRaghuvanshi** [comment]
I would like to work on this issue. Please assign me.

**Comment by noman2002** [comment]
@AyushRaghuvanshi Please write the proper issue in the title. Instead of "Bug Report".
