### ISSUE TITLE
Enhancement for the password strength bar

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#210]
Currently, the **password strength bar** is visible to the user even when the **password text field** is empty.
Also, the **password strength bar** updates only after the `TextFormField` is saved.

**Enhancement:**
1. The **password strength bar** should only be visible if the **password text field** is not empty.

2. The **password strength bar** should update when the content in the `TextFormField` changes.

**Comment by yasharth291** [comment]
nice we can work on it if you want.

**Comment by Raunakk02** [comment]
I enhanced it and am submitting the pull request. Please check if it's working fine or not.

**Comment by yasharth291** [comment]
yeah no problem if it is working. it will be nice well done brother

**Comment by yasharth291** [comment]
one thing that you can do is attaching this issue with the pr @Raunakk02

**Comment by Raunakk02** [comment]
> one thing that you can do is attaching this issue with the pr @Raunakk02

Thanks for the suggestion @yasharth291, but I already linked this issue to the PR.
