### ISSUE TITLE
Upgrade package syncfusion_flutter_calendar from 23.1.43 to 23.1.44

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2105]
We need to bump [syncfusion_flutter_calendar](https://github.com/syncfusion/flutter-widgets/tree/master/packages) from 23.1.43 to 23.1.44.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2101

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6858813373/job/18650190705?pr=2101

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by Dante291** [comment]
@palisadoes I can work on his.

I am unable to tag @aashimawadhwa

**Comment by Dante291** [comment]
@aashimawadha I can work on this.

**Comment by Dante291** [comment]
@aashimawadhwa I can work on this.

**Comment by noman2002** [comment]
@Dante291 Assigned, please consider putting a profile picture. Sometimes it create confusion.
