### ISSUE TITLE
Upgrade package provider from 6.0.5 to 6.1.1

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2106]
We need to bump package [provider](https://github.com/rrousselGit/provider) from 6.0.5 to 6.1.1.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2100

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6858812619/job/18650171426?pr=2100

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by AyushRaghuvanshi** [comment]
This looks like a quick fix. can you assign me this one?

**Comment by rishiofficial** [comment]
hey can you assign me this issue.

**Comment by palisadoes** [comment]
@AyushRaghuvanshi 

@aashimawadhwa will be handling all issue queries and seeking reviewers for PRs. When necessary, this contributor will contact other contributors who will be able to assist. Please ask them for guidance on your future questions.

**Comment by AyushRaghuvanshi** [comment]
Ohkay. that sounds great.
