### ISSUE TITLE
MVP - Talawa

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2108]
We need to have an Talawa MVP by the end of the year. The MVP will be the master branch. To do this we will need to remove features that either don’t work or have insufficient functionality. 

The features to remove include:

1. Links to chat
1. Notifications
    1. https://github.com/PalisadoesFoundation/talawa/issues/2086 Already removed in this issue
1. Dynamic linking

Other

1. You need to work on removing these functionalities from this repo and work with the contributors below to make sure the correct functionality occurs in the other repos.
1. Documentation related to configuring these features needs to be removed as they will be no longer valid.
1. Test code coverage needs to be maintained. Coverage for the PR patches needs to be 100%

The plan is to:

- remove these features from the develop branch by commenting out the code.
- merge the develop branch not containing these features into our master branch.
- make the master branch the default

Please work with @Ayush0Chaudhary (Talawa impacts), @EshaanAgg & @xoldyckk (Talawa-API impacts) @beingnoble03 (Talawa-Admin impacts). Ask to be assigned this task by them.

Issues related to this one include:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1069
- https://github.com/PalisadoesFoundation/talawa-api/issues/1427
- https://github.com/PalisadoesFoundation/talawa/issues/2108

**Comment by AyushRaghuvanshi** [comment]
Hey, I would like to work on this. Can you please Assign me this one?

**Comment by palisadoes** [comment]
Please work with @Ayush0Chaudhary on this. He's worked extensively with this repo

**Comment by AyushRaghuvanshi** [comment]
ohkay

**Comment by AyushRaghuvanshi** [comment]
Hey, @Ayush0Chaudhary , so I just wanted to give a small plan of action. so that maybe you can double check and may be give some suggestions.
-> I would start with basically removing Chat_services file (commenting out) and then just comment out every unused or error occurring line.
But i suppose that would remove the whole chat feature. PR mentions we are supposed to remove Links to Chats does this mean this only? or m I on the wrong track?

**Comment by Ayush0Chaudhary** [comment]
> Hey, @Ayush0Chaudhary , so I just wanted to give a small plan of action. so that maybe you can double check and may be give some suggestions.
> -> I would start with basically removing Chat_services file (commenting out) and then just comment out every unused or error occurring line.
> But i suppose that would remove the whole chat feature. PR mentions we are supposed to remove Links to Chats does this mean this only? or m I on the wrong track?

Chat removal is completed. Icon removal will work for now.

**Comment by AyushRaghuvanshi** [comment]
ok so i need to work on Dynamic Linking i suppose.  Can you guide me to where it is located?

**Comment by AyushRaghuvanshi** [comment]
@Ayush0Chaudhary Does Dynamic linking removal involves , commenting out the code written to share our App url through socials?

**Comment by Ayush0Chaudhary** [comment]
> ok so i need to work on Dynamic Linking i suppose. Ill work on it, Thank you.

Yes that is pending.
Is your setup complete?

**Comment by AyushRaghuvanshi** [comment]
Yes, My set up is complete,

My Plan of action is to 
-> remove all the share buttons.
-> remove Handle deep linking function from splash screen.
