### ISSUE TITLE
 Upgrade package mockito from 5.4.2 to 5.4.3

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2110]
For security purposes, we need to bump package [mockito](https://github.com/dart-lang/mockito) from 5.4.2 to 5.4.3.

This was attempted as a  PR by dependabot
- https://github.com/PalisadoesFoundation/talawa/pull/2109

However, the checks failed:
- https://github.com/PalisadoesFoundation/talawa/actions/runs/6899520933/job/18771270794?pr=2109

Goals:
- You will need to update the package and make sure the tests pass, with the file in question getting to 100% test coverage.
- Functionality must remain unchanged as a result of completing this issue

**Comment by Dante291** [comment]
I would like to work on this @palisadoes @noman2002
