### ISSUE TITLE
Bug: Talwa Admin link is broken

### ISSUE THREAD

**Issue by grwt** [PalisadoesFoundation/talawa#2132]
**Describe the bug**
"Page not found" is when clicking on talwa admin option

**To Reproduce**

1. go on site  https://docs.talawa.io/
2. then look for the "Developer Docs" option on the top left side
3. then click on the admin option

**Expected behavior**
link should directed to admins page

**Actual behavior**
Page not found

**Screenshots**
![Screenshot 2023-11-22 235915](https://github.com/PalisadoesFoundation/talawa/assets/150654743/f5ef74c1-9c9a-4cfe-8c38-4e5488df8924)

**Comment by palisadoes** [comment]
Thanks this is a known bug. We are working on it. Closing.
