### ISSUE TITLE
Generate an .IPA file and link it to README.md 

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#2136]
**Is your feature request related to a problem? Please describe.**

There currently exists a CI/CD  pipeline for generating Talawa .apk [artifacts](https://github.com/PalisadoesFoundation/talawa/commit/9dac05567a1afdb8c1191ecd1d6f5b6bdc4af6f0#diff-1790f2f8b7123d50d46235053b54f1cc5996bc7388b803aad4233fd5582e0bad), where the output artifact can be found [here](https://github.com/PalisadoesFoundation/talawa/releases). We would like to complete the `iOS-Build` section of this pipeline to generate `.ipa` files for iOS devices. This is a non-trivial task compared to its .apk counterpart as Apple's infrastructure is far more tightly bound and requires a number of workarounds to do this.  Try to automate this process as much as possible following the instructions given [here](https://www.cobeisfresh.com/blog/how-to-implement-a-ci-cd-workflow-for-ios-using-github-actions). Ensure to document any roadblocks/obstacles at you encounter. 

**Describe the solution you'd like**
We would like to complete the `iOS-Build` section of this pipeline to generate `.ipa` files for iOS devices. This is a non-trivial task compared to its .apk counterpart as Apple's infrastructure is far more tightly bound and requires a number of workarounds to do this.  Try to automate this process as much as possible following the instructions given [here](https://www.cobeisfresh.com/blog/how-to-implement-a-ci-cd-workflow-for-ios-using-github-actions). Ensure to document any roadblocks/obstacles at you encounter.  At the end link this new output to the README.md of the repository.

**Comment by Dante291** [comment]
@palisadoes @noman2002 I can work on this.

**Comment by Dante291** [comment]
@DMills27 @palisadoes Sir the document provided above to automate the process of building of .ipa file also includes publishing of the iOS app on Apple app store, but since our app is in MVP stage, do we really need it to publish it on Apple app store? So please do clear out whether I am supposed to just automate the building of iOS app for just our repo or the whole process of building and publishing the app?

**Comment by Dante291** [comment]
@palisadoes @noman2002 I could work on this now.
