### ISSUE TITLE
Refactor the Talawa connection URL string to the hamburger menu. Make the Talawa demo work without URL string.

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#2137]
**Is your feature request related to a problem? Please describe.**
Having to enter a connection URL string in order to use Talawa is counterproductive; it requires one to setup the API or have it available somewhere to see the frontend's features and functionalities. We would much rather have the user be able to enter the app to get a look and free for it without having the API available.

<p align="center">
<img width="257" alt="Screenshot at Nov 24 06-44-01" src="https://github.com/PalisadoesFoundation/talawa/assets/5251658/964f920a-8849-43a6-b0e9-97ab2469ca37">
</p>

**Describe the solution you'd like**
Have the user access the Talawa frontend and then give them an option to connect to an organisation via the hamburger menu, more specifically through the `Join new organization` option. The logic should allow the user to enter a connection string if they are not already connected to any org, as well as, allow them to sift through the different orgs they connected to on a separate page.

<p align="center">
<img width="324" alt="Screenshot at Nov 24 06-46-02" src="https://github.com/PalisadoesFoundation/talawa/assets/5251658/d32c14f4-ba81-4ed2-ad8e-693d2358dd14">
</p>

**Comment by Azad99-9** [comment]
@aashimawadhwa could you please assign this issue to me.

**Comment by Azad99-9** [comment]
@DMills27 , @palisadoes 

Please check if i am in right track, correct me if i am wrong.

1. Changes in Login/Signup section:
    a. Remove the organization url section from login flow.
    b. Directly ask users to either register/login.
    
2. Changes in "Join organization" section from Hamburger menu:
    a. As soon as user clicks on - Join organization, from hamburger menu they will be navigated to a new page. 
    b. This new page is current Join organization page and it will be modified to containing sections. 
    *First Section*: Enter URL of desired organization to join.
    *Second Seciton*: List of all organizations that the user has joined previously and he can
    switch between them from here easily.
        
Clarifications:
1. Will the organization feed left empty if the user is not associated with any organization initially.
2. Does each organisation has its own unique url (or) Single connection URL has one/multiple organizations linked with it.

**Comment by DMills27** [comment]
@Azad99-9 You've got it mostly correct. The step 1b is not needed at the moment. The app should just take the user to an unpopulated home page once loaded. In other words, there should be no authorisation when starting up the app, it should just take the user to a version of Talawa that has not pulled in any data from the API. 

Clarifications:

1. Yes, the feed will be empty if the user is not affiliated with any org.
2. Each organisation has its own unique url.

**Comment by Azad99-9** [comment]
> @Azad99-9 You've got it mostly correct. The step 1b is not needed at the moment. The app should just take the user to an unpopulated home page once loaded. In other words, there should be no authorisation when starting up the app, it should just take the user to a version of Talawa that has not pulled in any data from the API.
> 
> Clarifications:
> 
> 1. Yes, the feed will be empty if the user is not affiliated with any org.
> 2. Each organisation has its own unique url.

follow up:
`{
    _id: ObjectId("6437904485008f171cf29924"),
    status: 'ACTIVE',
    members: [
      ObjectId("64378abd85008f171cf2990d"),
      ObjectId("65378abd85008f171cf2990d")
    ],
    admins: [ ObjectId("64378abd85008f171cf2990d") ],
    groupChats: [],
    posts: [],
    pinnedPosts: [],
    membershipRequests: [],
    blockedUsers: [],
    name: 'The Unity Foundation',
    description: 'A foundation aimed at uniting the world and making it a better place for all.',
    location: 'Delhi, India',
    isPublic: true,
    visibleInSearch: true,
    image: null,
    creator: ObjectId("64378abd85008f171cf2990d"),
    createdAt: ISODate("2023-04-13T05:16:52.827Z"),
    __v: 0
  },
`
@DMills27 please have a look at above mongodb document of The Unity Foundation organization. if each organization has its own unique url then i would like to know why is the url not mentioned in the organisation's respective database document. And also i would like to know where can i access the organization's url.

Rightnow the organization url we are specifying at login time does not belong to any specific org but its the url of the api itself.

**Comment by Azad99-9** [comment]
> > @Azad99-9 You've got it mostly correct. The step 1b is not needed at the moment. The app should just take the user to an unpopulated home page once loaded. In other words, there should be no authorisation when starting up the app, it should just take the user to a version of Talawa that has not pulled in any data from the API.
> > Clarifications:
> > 
> > 1. Yes, the feed will be empty if the user is not affiliated with any org.
> > 2. Each organisation has its own unique url.
> 
> follow up: ![Screenshot from 2023-11-27 22-24-20](https://private-user-images.githubusercontent.com/120930148/285948340-48eb3ff1-6f79-4cbb-a697-164e318c222b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODIzMjYsIm5iZiI6MTcwMTE4MjAyNiwicGF0aCI6Ii8xMjA5MzAxNDgvMjg1OTQ4MzQwLTQ4ZWIzZmYxLTZmNzktNGNiYi1hNjk3LTE2NGUzMThjMjIyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQxNDMzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDFkNWUzNmEyY2FhM2Q0YjZkYTc2Njc0YWZhZjRhYzBlNzUxNzRjMTQ0NGNmZWMxMTFiNjk0OGI5YTBiMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dPYb-wf_obG5jgX0G9ljmx9Od3lCBV3lgMpFs2YhLIg) @DMills27 please have a look at above mongodb document of The Unity Foundation organization. if each organization has its own unique url then i would like to know why is the url not mentioned in the organisation's respective database document. And also i would like to know where can i access the organization's url.
> 
> Rightnow the organization url we are specifying at login time does not belong to any specific org but its the url of the api itself.

@palisadoes please have a look at above comment.

**Comment by palisadoes** [comment]
@Azad99-9 Please refer to this document: https://docs.talawa.io/docs/introduction/core-concepts#community

Each API instance handles a community or `parent` organization. All organizations would be affiliated with this parent. So for example. The `parent` could be the Indian Premier League Fan Club, and each organization would be the fan clubs of each team. Fans of multiple teams could become members of multiple team fan clubs.

So the URL is really a `community` URL, not an `organization` URL. 

Start with the assumption that the Mobile App can store only one URL at a time. When we know that works as part of completing this issue we can focus on the Mobile App storing multiple `community` URLs as a separate issue.

We'll need to change the terminology in the App to `community` URL and eventually alter it in the other repositories.

**Comment by Azad99-9** [comment]
@palisadoes the above information was really helpful and understood.👍

**Comment by Azad99-9** [comment]
@palisadoes , @DMills27 i have implemented the feature and made multiple UI changes in the app that were demanded by the feature. Now how can I share you the apk so that you can review the changes and give me feedback for any modifications.

**Comment by palisadoes** [comment]
1. Please add a video to show what you've done proving that the app will work without the URL.
2. Make sure that it is obvious that it's in demo mode with a clear option to add a real URL. This does not have to be visible in every screen.

@Ayush0Chaudhary This should interest you.

**Comment by Azad99-9** [comment]
@Ayush0Chaudhary , @palisadoes , @DMills27 

please have a look at the demo video and let me know if any modifications.

https://github.com/PalisadoesFoundation/talawa/assets/120930148/3c9da6b2-1d71-4718-8836-4a0cbbffae72

**Comment by palisadoes** [comment]
Thanks. I have a list of comments, please take them as constructive criticisms.

The UI/UX here doesn't clearly show that this in demo mode. Nor does it give an indication of where to go to set it up the properly. We need an intuitive interface for that

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/095967b2-b0e6-4703-aa26-5020872dd386)

**Comment by palisadoes** [comment]
Similarly here. There isn't a way to show that this is a demo mode. A transient informational popup with translated text maybe ?

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/9a4be3e1-90da-48e6-8896-fdfd8c98b7f1)

**Comment by palisadoes** [comment]
Screens like this occur when an action is attempted. Can you make the left drawer appear temporarily to make it clearer? 

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/aea0eaca-c7bc-4f9e-96e2-935d8eac1ca5)

**Comment by Azad99-9** [comment]
@palisadoes i am glad that you have suggested some changes.

One straight forward way would be showing a thin banner on top of navigation bar mentioning the prompt messages like
for example:
1. "For complete access, please log in."
2. "Login to unlock all app functions."
3. "For the full experience, please log in."
 
 by clicking on this banner user can directly go to community url page.
 
I would like to know your thoughts on this approach.

**Comment by DMills27** [comment]
I agree with Peter's suggestions. Additionally, I think you need to make it clear that there's a distinction between logging in and joining an organisation. The video you posted suggests that they are somewhat synonymous in the initial steps when this is not the case. It would be better to prompt the user for an organisation url string then segue to the login screen to make this clear.  This would make the transition more logical.

**Comment by Azad99-9** [comment]
> Remember that we will need to have 100% test code coverage for all the files you edit in the PR for this issue.
yeah noted.

**Comment by Azad99-9** [comment]
> The video you posted suggests that they are somewhat synonymous in the initial steps when this is not the case.

Previously I chose to place the "Login" option in the hamburger menu instead of the "Community URL" is because of the reason users might not immediately grasp the organization's structure within our app. Initially, they are more likely to search for a login or signup option. However, I've reconsidered, and I will now replace the "Login/Signup" section with the "Community URL" option.

> After the user has joined an organisation by inputting an organisation url string they should be prompted to login.

yeah this is already implemented and will be left as it is.

> subsequently after that they should only have the option to sign up for other organisations they wish to join if they have the requisite connection string.

@DMills27 for this part, Currently, we lack unique connection strings for each organization. Therefore, following the suggestion from @palisadoes, our focus will be on entering a sole parent community URL that links to a singular API instance to address this matter for now. At this stage, we'll enable users to switch between the organizations existing within the parent community.

**Comment by Azad99-9** [comment]
> Screens like this occur when an action is attempted. Can you make the left drawer appear temporarily to make it clearer?

@palisadoes i will trigger the left drawer(hamburger menu) whenever a user specific action is performed.

**Comment by Azad99-9** [comment]
![Screenshot from 2023-12-03 18-54-26](https://github.com/PalisadoesFoundation/talawa/assets/120930148/51f76936-08b4-44b5-a4d1-caf6f8f9cf94)

better approach would be prompting the user to enter a community url by focusing on the join organization button from hamburger menu. Letting the user decide to continue the demo mode or join a community.

The UI would look similar to the above image.

@palisadoes , @DMills27 what are your thoughts?

**Comment by Azad99-9** [comment]
@palisadoes , @DMills27 In the demo video I shared, I utilized the approach conditional UI rendering based on the **user.loggedIn** attribute for displaying demo-specific widgets. While this approach worked, as the code expanded, it started to become cumbersome.

So I am considering to define new **Demo routes** to render these **Demo widgets** which would be a more elegant solution. This way we can conditionally navigate to the desired-mode and keep them seperate.

I welcome any better solutions to handle this scenario, from you side.

**Comment by DMills27** [comment]
@Azad99-9 The demo routes idea seems fine. Can you come up with a basic implementation and the post the video recording here? Nothing too fancy we just need to see if you got the gist of what needs to be implemented.

**Comment by DMills27** [comment]
@Azad99-9 For the most part it looks good! I only have some very minor nitpicks such as the speed as to which the various components are being zoomed into. Good job!

**Comment by Azad99-9** [comment]
thanks @DMills27 .

**Comment by Azad99-9** [comment]
is it ok additionally should i enhance any part of it apart from the speed as you have mentioned.
