### ISSUE TITLE
Write tests for lib/utils/encryptor.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2149]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage. No functionality must be removed to achieve this goal.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/utils/encryptor.dart

```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by imshivam-gupta** [comment]
@palisadoes I would like to work on this issue.. can you please assign it to me?

**Comment by Ayush0Chaudhary** [comment]
Solve other issues first

**Comment by Manik2708** [comment]
@Ayush0Chaudhary @noman2002 Can you assign this issue to me?

**Comment by noman2002** [comment]
@literalEval Please answer this query.

**Comment by Manik2708** [comment]
```
AsymmetricKeyPair<PublicKey, PrivateKey> generateRSAKeyPair() {
    final secureRandom = FortunaRandom();
    final random = Random.secure();
    final List<int> seeds = [];
    for (int i = 0; i < 32; i++) {
      seeds.add(random.nextInt(255));
    }
    secureRandom.seed(KeyParameter(Uint8List.fromList(seeds)));
    final rsapars = RSAKeyGeneratorParameters(BigInt.from(65537), 2048, 64);
  final params = ParametersWithRandom(rsapars, secureRandom);
  final keyGenerator = RSAKeyGenerator();
  keyGenerator.init(params);
  return keyGenerator.generateKeyPair();
  }
```
I have modified this function in this way with the help of the blog [Asymmetric Key Generation in Flutter](https://medium.com/flutter-community/asymmetric-key-generation-in-flutter-ad2b912f3309l). Kindly check if it is right!

**Comment by Manik2708** [comment]
I think the PR is not linked with this issue. PR is merged, please close this issue. Will keep in mind next time to link PR properly with issue.

**Comment by literalEval** [comment]
Hello @Manik2708. Sorry for being late to the discussion. There were some packages changes for the encryption system in the end, which might have caused the issue. I idea was to write a skeleton which can be easily implemented. Thanks for pointing out the issue.

If you are interested, we can work on enhancing the encryption system. Thanks and regards.

**Comment by Manik2708** [comment]
> Hello @Manik2708. Sorry for being late to the discussion. There were some packages changes for the encryption system in the end, which might have caused the issue. I idea was to write a skeleton which can be easily implemented. Thanks for pointing out the issue.
> 
> If you are interested, we can work on enhancing the encryption system. Thanks and regards.

No problem, I understand your time constraints. I request you to kindly view the function which I have modified. Is it consistent with the security options? Currently Encryption is working well. I am also working on Chats System in my personal project. So it's a kind of suggestion to move to Cassandra Database for Chats (Other Databases will fail to provide DELETE option to users) in backend. Then I think Chats would work more efficiently. Currently @palisadoes said that Chats are not working, I think we can create a seperate branch to give it a try for chats. Or it might be a probable project for GSoC.

**Comment by palisadoes** [comment]
Fixing Chat and notifications will be a GSoC project
