### ISSUE TITLE
[proposal] Writing proper guidelines about the structure of code.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#215]
There should be a file. which should tell the correct way to write code for example

what should be the way of writing a class or a function. 

what should be the way a variable name should be 

there is one tool which give scores for this named pipette a score above 8 is considered ok. 

@Sagar2366 @heyjordn @jordanliu

**Comment by Sagar2366** [comment]
This should be handled with IDE linters and next check from SonarQube plugin as part of CI/CD plugin.
There are multiple guidelines available on Internet for the same. I don't think this is required.
