### ISSUE TITLE
Write tests for lib/widgets/post_modal.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2150]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage. No functionality must be removed to achieve this goal.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/widgets/post_modal.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by VertikaBajpai** [comment]
Hey, @palisadoes  can you assign me this issue?

**Comment by imshivam-gupta** [comment]
@VertikaBajpai are you still working on this issue?

**Comment by VertikaBajpai** [comment]
Yes, I am working

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by AVtheking** [comment]
can I work on this issue ?
