### ISSUE TITLE
Write tests for join_organisation_after_auth.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2152]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage. No functionality must be removed to achieve this goal.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/views/after_auth_screens/join_org_after_auth/join_organisation_after_auth.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no open submitted PRs

**Comment by Dante291** [comment]
@noman2002 could you assign this to me.

**Comment by Cioppolo14** [comment]
@Dante291 Once one of your issues is completed, you can pick up another one. 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Dante291** [comment]
@noman2002 @Cioppolo14 can I be assigned to it now.
