### ISSUE TITLE
Write tests for lib/services/event_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2154]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.  No functionality must be removed to achieve this goal.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/services/event_service.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by Wreck-X** [comment]
please assign me this issue

**Comment by Wreck-X** [comment]
i will be busy for the upcoming weeks due to personal reasons, ill be unassigning this for myself.

**Comment by PriyadharshiniNagarathinam** [comment]
Shall I work on this issue??

**Comment by PriyadharshiniNagarathinam** [comment]
@noman2002 Could you assign this issue to me?
