### ISSUE TITLE
Write Tests for View Model add_post_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2155]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/view_model/after_auth_view_models/add_post_view_models/add_post_view_model.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by AyushRaghuvanshi** [comment]
Hey, I would like to take this issue up.

**Comment by Dante291** [comment]
@noman2002 I can work on this.
