### ISSUE TITLE
Write tests for view model access_request_view_model.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2157]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/view_model/access_request_view_model.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by Kan7sh** [comment]
Hey can you assign this issue to me

**Comment by palisadoes** [comment]
Unassigning due to no issue activity and no submitted pull request

**Comment by imshivam-gupta** [comment]
@palisadoes I have already created PR for other 2 issues assigned to me. Can you assign me this issue if possible?

**Comment by imshivam-gupta** [comment]
@Cioppolo14 @Kevoniat @noman2002 can you please assign me this issue?
