### ISSUE TITLE
Write tests for service post_service.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2160]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/services/post_service.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by imshivam-gupta** [comment]
@noman2002 Can you please assign this issue to me
