### ISSUE TITLE
Write tests for lib/widgets/pinned_post.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2161]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/widgets/pinned_post.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by nidhin29** [comment]
I want to take this issue

**Comment by nidhin29** [comment]
I have written the test if you are assigning it to me I can give pull request

**Comment by nidhin29** [comment]
@noman2002 can I take this

**Comment by palisadoes** [comment]
1. @nidhin29 Are you still working on this?
2. You have submitted 7 PRs and not merged any code.

**Comment by nidhin29** [comment]
Yes I'm working on it I will provide it as soon as possible
