### ISSUE TITLE
Write tests for lib/utils/queries.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2166]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/utils/queries.dart
```

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- The current code coverage for this file can be found here:
    - https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by cmaustQA** [comment]
Please assign this to me.
