### ISSUE TITLE
The text color on the Type The Org URL screen is not visible

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#217]
**Description:** The text Create an Account and Login aren't visible with the background and they have to be changed to make them a bit visible at least.

**Problem:** As we can see the text doesn't go well with the background along with the border color

<img src="https://user-images.githubusercontent.com/23498248/111059876-b7f6f580-84be-11eb-82f2-07a08ae92234.png" width="100" height="200" />

**Solution:** 

<table>
<thead>
<tr>
<th>When the Org URL isn't set, the button is disabled and the button has no background color</th>
<th>When the Org URL is set, the button is enabled and thus the button has orange background color.</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/23498248/111060544-a106d200-84c3-11eb-93f2-77d1e4fae813.png" width="100" height="200" /></td>
<td><img src="https://user-images.githubusercontent.com/23498248/111060566-cdbae980-84c3-11eb-94a6-dadb66203dec.png" width="100" height="200" /></td>
</tr>
</tbody>
</table>

**Comment by pr4nshul** [comment]
I could work on this, can please someone assign me this issue.

**Comment by Sagar2366** [comment]
@pr4nshul, FYI @adithyaakrishna is already working on this issue and have raised pr for the same. Please check other open issues (confirm no one is working on the issue before start working on issue) or open new issues and raise PR for the same.

**Comment by pr4nshul** [comment]
Yes , I saw the PR and deleted the comment immediately. I am looking into other issues now.

**Comment by pr4nshul** [comment]
This issue should be closed now @Sagar2366 @adithyaakrishna  as #218 is merged into master.

**Comment by adithyaakrishna** [comment]
Yesss @pr4nshul , Thank You For That 🚀
