### ISSUE TITLE
Migrate the depreciated flat button and raised button.

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#219]
Flat button and Raised button are depreciated. To be migrated.

**Comment by adithyaakrishna** [comment]
@i-anuragmishra Hey, Anurag I have worked on this issue and was about to Create a PR for the same

**Comment by i-anuragmishra** [comment]
i think #214 resolves this.

**Comment by theRoushan** [comment]
```diff
- Is this Issue still open?
```
If then
@Sagar2366 Sir, Please assign this issue to me.

**Comment by sakshiisaxena** [comment]
If this is still an active issue, can I work on this? @Sagar2366
