### ISSUE TITLE
Create a consistent UX for adding content

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2191]
**Is your feature request related to a problem? Please describe.**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

There isn't a consistent way of adding content. Each of these features uses a different methodology and in some cases multiple add buttons are visible.
1. Add post
1. Add event
1. Add chat (The icon is not available in current `develop` or `main` branches as chat does not work. We do not want this icon restored in this issue as it is a potential GSoC 2024 project idea. This information is just to provide some context)

This is visible here
- https://youtu.be/86AzK_Y_GCQ?t=206

**Describe the solution you'd like**
- A consistent way of adding content so that only one add icon is visible when an activity is selected. 

**Describe alternatives you've considered**
- The LinkedIn mobile app has one possible approach (there may be others) where a right hand drawer is created that covers the previous screen when a message needs to be sent. The `add post` icon gets replaced with an `add message` icon
- There may be other apps that have other ways of achieving this goal.

**Approach to be followed (optional)**
- N/A

**Additional context**
- You must get the test **_code coverage up to 100%_** for any edited files.

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@Ayush0Chaudhary I apologize for not checking that I have been unassigned from the issue and created a pull request for the issue. I would appreciate it if you could review [this PR](https://github.com/PalisadoesFoundation/talawa/pull/2168). It has been a week, and it's currently pending review.
