### ISSUE TITLE
The Event filtering button is not intuitive to use

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2192]
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

Event filtering button is not intuitive. It says `Add Date` versus  something easier to understand. Changing the wording may not be enough. An easier to use and understand methodology should be considered.

**To Reproduce**

1. Open the mobile app
2. Click on `Events`
3. You'll see the `Add Date` filter in the top right hand corner

**Expected behavior**

1. A more intuitive interface is required
2. Filtering by date must be maintained

**Actual behavior**
See video:

- https://youtu.be/86AzK_Y_GCQ?t=276

**Screenshots**
- N/A

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files. No functionality must be removed to achieve this goal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bhav-khurana** [comment]
@palisadoes Can we add something like "filter by date" instead of "add date"? And may be improving the UI a bit, which allows the user to choose two dates ("From" and "To")

**Comment by Ayush0Chaudhary** [comment]
Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.
