### ISSUE TITLE
Remove Google Maps functionality from event

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2193]
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

The app fails when adding an event and providing a Google Maps reference

**To Reproduce**

1. Start app
2. Click on Events
3. Add an event
4. Add a venue using Google Maps location

**Expected behavior**
- No Google Maps option
- Remove any references to Google Maps or underlying packages from the repo

**Actual behavior**
- https://www.youtube.com/watch?v=86AzK_Y_GCQ&t=303s

**Screenshots**
- N/A

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files. No functionality must be removed to achieve this goal.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bhav-khurana** [comment]
Can I work on this issue? @palisadoes

**Comment by ShubhamTiwari55** [comment]
@Ayush0Chaudhary Please assign this issue to me. I want to resolve this.

**Comment by tarun824** [comment]
Is this issue still open? @palisadoes  @noman2002 can you assign this to me.

**Comment by ShubhamTiwari55** [comment]
@tarun824 Actually I am working on this.

**Comment by Manik2708** [comment]
> @tarun824 Actually I am working on this.

Hi @ShubhamTiwari55 , I explored Map Screen a lot while writing tests for it, so let me know if you are facing any problem which can help you solving this issue.

**Comment by Azad99-9** [comment]
@Cioppolo14 @noman2002 @Kevoniat could any one of you please assign this issue to me.

**Comment by Azad99-9** [comment]
@palisadoes this issue is a subset of #2256, please close this issue.

**Comment by Cioppolo14** [comment]
Closing as a duplicate, see issue #2256.
