### ISSUE TITLE
Profile Settings: `My Tasks` option is duplicated should be removed

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2198]
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

App Setting option doesn't work and should be removed

**To Reproduce**

1. Start app
2. Click on Profile
3. Click on the cog wheel icon
4. A drawer appears with a `My Tasks` option. 

**Expected behavior**
- No `My Tasks` option
- All tasks should be visible on the tasks tab of the profile without doing this extra step
- All modified files must be 100% covered by tests

**Actual behavior**
- `My Tasks` option appears.

**Screenshots**
- https://youtu.be/86AzK_Y_GCQ?t=585

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ShubhamTiwari55** [comment]
@Ayush0Chaudhary Please assign this issue to me. I want to resolve this
