### ISSUE TITLE
Switching organizations fails when organization exists

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2199]
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.
- Switching organizations fails even when the organization exists
- A `No organization found! Please contact your admin` message is seen

**To Reproduce**

1.  Log into the app
2. Access the left drawer to switch organizations
3. Click Join new organization
4. Select organization
5. Error occurs

**Expected behavior**
- No error should occur
- If the user is already a member of the organization, then the transition must be seamless
- If the user is not a member, then a registration screen or something similar must be viewed

**Actual behavior**
- Error occurs

**Screenshots**
- https://www.youtube.com/watch?v=86AzK_Y_GCQ&t=711s
- https://youtu.be/86AzK_Y_GCQ?t=764 This could be related to the Firebase implementation. Ideally we don't want Firebase integration. You may have to work with an API and Admin person on this.

**Additional details**
- You must get the test **_code coverage up to 100%_** for any edited files.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bhav-khurana** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by Dante291** [comment]
I would like to work on this @noman2002 @palisadoes

**Comment by akshayw1** [comment]
I would like to work on this @noman2002 @palisadoes

**Comment by noman2002** [comment]
@akshayw1 One person per issue and we assign on first come first serve basis. Please look at other open issues to get it assigned.
