### ISSUE TITLE
The border Color and Icon Colors of the Input Fields on the Create an Account Screen isn't properly visible

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#220]
**Description:** The text Create an Account and Login aren't visible with the background and they have to be changed to make them a bit visible at least.

**Problem:** As we can see the border color of various input fields aren't visible on the page in the below image

<img src="https://user-images.githubusercontent.com/23498248/111061020-2344c580-84c7-11eb-97ee-dac9b2c4d697.png" width="150" height="300" />

**Comment by CyberWake** [comment]
They are but only when the field is in focus. And I guess giving a different color would ruin the background effect given by the image behind.

**Comment by adithyaakrishna** [comment]
@CyberWake or else we can also remove the border, bc if the black border is there, its just not visible and IMO doesn't go well with the background

**Comment by adithyaakrishna** [comment]
@CyberWake Do lmk your opinion too 👀

**Comment by CyberWake** [comment]
@adithyaakrishna we can go with the light color shade border. Also I feel like automatically focusing the next field on user input would also enhance the UX. I am working on the second part right now if you could change the issue title accordingly would be nice of you :smiley: else will need to have a separate issue raised for the same file feature update
