### ISSUE TITLE
The image touches or the Header Bar overlaps the image in Switch Organization Screen

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#222]
**Problem:**
![image](https://user-images.githubusercontent.com/23498248/111061493-aebf5600-84c9-11eb-93c0-5be4bcc2a2aa.png)

**Comment by SriramPatibanda** [comment]
I would like to work on this issue @adithyaakrishna .

**Comment by adithyaakrishna** [comment]
I'm working on it already @SriramPatibanda

**Comment by Sagar2366** [comment]
@adithyaakrishna, please update the issue and pr description - add before and after visuals.
