### ISSUE TITLE
Error widget overflowing when not able to connect to org

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#223]
There is a similar issue #175 . But It is when switching the organization. So will that PR handle this issue as well. If not I will like to work on it. Also, I would like to know which organization should I type in so that I can sign up.

**Comment by pr4nshul** [comment]
![Uploading Screenshot_20210314-134838.png…]()

**Comment by pr4nshul** [comment]
![Screenshot_20210314-134838](https://user-images.githubusercontent.com/51524156/111062211-8c2f3c00-84cd-11eb-9825-1a1e2859826d.png)

**Comment by yasharth291** [comment]
duplicate 
#142

**Comment by pr4nshul** [comment]
Can you tell me how is it a duplicate, as when a issue occur it is printed through _exceptionToast function and there I am not seeing anything that is handling the overflowing of the string. #142 was a similar issue I agree. But it is still not resolved?

**Comment by pr4nshul** [comment]
It is resolved, I do not know in which PR but today I was working on it . And it is no longer an issue.
