### ISSUE TITLE
Unecessary scroll at login page

### ISSUE THREAD

**Issue by Wreck-X** [PalisadoesFoundation/talawa#2232]
**Describe the bug**
App allows us to scroll at login page when there is no real reason to scroll

**To Reproduce**

1. Attempt to scroll from the login page

**Expected behavior**
No scrolling

**Actual behavior**
scrolling is allowed

**Screenshots/Video**

https://github.com/PalisadoesFoundation/talawa/assets/72601105/4ac385de-13e5-4582-9fc2-d3dbab972b21

**Comment by Wreck-X** [comment]
i have linked a pr for this please review thanks.

**Comment by Wreck-X** [comment]
please assign me this issue

**Comment by noman2002** [comment]
@Wreck-X Currently we are focused on getting a MVP, this a very minor issue and this can be fixed later on. We are prioritizing feature breakdowns and code coverage. Please work on it. Closing this for now.
