### ISSUE TITLE
Remove references to Google Firebase

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2255]
**Is your feature request related to a problem? Please describe.**

We need to make Talawa independent of cloud service providers because:
1. many of their services are becoming paid
1. they require us to hard code access information in the app that would require the Palisadoes Foundation to pay for the usage of those services by all Talawa users
1. the packages get frequently updated taxing our ability to integrate these modifications smoothly in the codebase 
1. It makes setting up Talawa more difficult

Therefore we created an issue in Talawa API to remove Firebase references from that code base. This is being handled by @Veer0x1 through this PR
- https://github.com/PalisadoesFoundation/talawa-api/pull/1503

**Describe the solution you'd like**
We need to remove all references to Firebase in the codebase while:
1. maintaining all non Firebase functionality
1. making all features usable
1. removing all references to Firebase in package management and configuration files

You will need to coordinate with @Veer0x1 to determine the best approach to do this

**Describe alternatives you've considered**

We have a draft GSoC idea to replace Firebase notifications with a solution that is soley managed by Talawa API

**Approach to be followed (optional)**
- Also coordinate with @noman2002 and @DMills27 

**Additional context**
- N/A

**Potential internship candidates**

1. Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
2. **NOTE:** I’ve stopped assigning people to issues due to the workload, no exceptions. Please watch this video on how to proceed.

[![Click me to start video](https://img.youtube.com/vi/GlqUm1UO-xM/0.jpg)](https://www.youtube.com/watch?v=GlqUm1UO-xM)

**Comment by Abhisheksainii** [comment]
@palisadoes this issue has already been resolved in the issue #2195

**Comment by palisadoes** [comment]
There are still numerous references to Firebase in the code base

![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/f74f2694-d874-4ce2-8cd6-b7287ce9dd0d)
![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/ba16eaba-aa9e-4c2b-a5a2-63b0c5f0f686)
![image](https://github.com/PalisadoesFoundation/talawa/assets/16875803/183b3042-f332-4a5d-9f4a-5e86653c981b)

**Comment by palisadoes** [comment]
> @palisadoes this issue has already been resolved in the issue #2195 @noman2002

True, but we need to remove all the other references not related to events. We could assign this to you as a follow up to https://github.com/PalisadoesFoundation/talawa/issues/2195

**Comment by palisadoes** [comment]
@Abhisheksainii I thought https://github.com/PalisadoesFoundation/talawa/issues/2195 had already been merged. Sorry. Should this be closed?

**Comment by Abhisheksainii** [comment]
Yes, you can close this for now as I have removed references of google firebase in #2195 already

**Comment by palisadoes** [comment]
1. Thanks. Please make sure all the conditions above are maintained.
2. I should have been more vigilant
