### ISSUE TITLE
Create ImageService

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#2259]
Since image uploads and edits are supposed to be functional soon, it would be better if we create a dedicated ImageService for the same. Doing so right now will help us in following SOLID principles and ease PR management in the future.

For now, `convertToBase64` can be moved from `EditProfilePageViewModel`

**Comment by Azad99-9** [comment]
@noman2002 @Cioppolo14 @Kevoniat please assign this issue to me.
