### ISSUE TITLE
Ensure that node files don't get added to the repository

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2263]
**Describe the bug**

1. We recently had a Talawa Mobile pull request where many node files were submitted. This appears to have been caused by the person running node related commands for the API or Admin in their local Mobile repository
1. Precautions must be taken to eliminate this from happening

**To Reproduce**

1. Run Node installation related commands in the local repo to generate node related supporting files.
1. Commit the changes
1. View the node files added to the commit

**Expected behavior**

1. Node related files are not committed
1. No functionality of the Mobile app is affected
1. Any changes to configuration files must clearly state why node files have been included for exclusion so that we do not revert to this undesirable state.

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by imshivam-gupta** [comment]
@palisadoes Can you please assign me this issue?
