### ISSUE TITLE
Exception toast in register form screen has overflow errors.

### ISSUE THREAD

**Issue by SriramPatibanda** [PalisadoesFoundation/talawa#227]
### Problem
The exception toast in the register form has overflow errors. 

![WhatsApp Image 2021-03-14 at 2 36 48 PM](https://user-images.githubusercontent.com/56649197/111063080-cfd87480-84d2-11eb-89c8-6481d98a5c11.jpeg)

### Possible solution
Wrapping the Text widget with an Expanded widget would solve the problem.

**Comment by SriramPatibanda** [comment]
@jordanliu  Please assign this issue to me, I would like to work on it.

**Comment by Sagar2366** [comment]
@SriramPatibanda, you are more than welcome to contribute to this project. If this is not duplicate issue, you can start working on this issue and share or for review.

**Comment by adithyaakrishna** [comment]
I guess this is not an Issue, @SriramPatibanda be sure to pull all the changes from the upstream/master to your repo and also set the Org. URL to http://calico.palisadoes.org/talawa/graphql

**Comment by Sagar2366** [comment]
@SriramPatibanda, please share the steps to reproduce this issue. Are you on master branch ? Recently major fix has been added and these issues are already fixed. Please let us know if you still seeing this issue.

**Comment by SriramPatibanda** [comment]
Closing this issue as it has already been fixed.

**Comment by SriramPatibanda** [comment]
The Issue has been reopened as it persists in the app.

The steps to reproduce this issue have been mentioned in the pull request:  #232
