### ISSUE TITLE
Firebase Options Unsupported in Talawa-API and Talawa-Mobile, Causing Login Issues

### ISSUE THREAD

**Issue by gpkonarde** [PalisadoesFoundation/talawa#2274]
Describe the bug:
-I encountered an issue while launching the Talawa mobile application and API. The error seems to be related to Firebase options, which are no longer supported in Talawa-API.

To Reproduce:
-Launch Talawa-mobile.
-Attempt to log in.

Expected behavior:
-The application should launch without any errors related to Firebase options.

Actual behavior:
-An error related to Firebase options is preventing the successful launch of the Talawa mobile application.

Additional details:
It appears that Firebase options are no longer supported in Talawa-API, leading to issues during login. To resolve this, consider removing the occurrences of Firebase options from GraphQL queries.

Potential internship candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

YES

**Comment by gpkonarde** [comment]
@palisadoes @noman2002 @Ayush0Chaudhary @Dante291

**Comment by Cioppolo14** [comment]
@gpkonarde Did you want to work on this issue?

**Comment by PriyadharshiniNagarathinam** [comment]
Shall I work on this issue??

**Comment by gpkonarde** [comment]
@Cioppolo14  yes, kindly assign it to me

**Comment by palisadoes** [comment]
> @Cioppolo14 yes, kindly assign it to me

With this issue, you also need to verify whether the login/authentication still works. We need the authentication to be against the API, not third party services.

**Comment by imshivam-gupta** [comment]
@gpkonarde Are you still working in this issue?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by imshivam-gupta** [comment]
@noman2002 @Cioppolo14 @Kevoniat I would like to work on this, please assign this to me.

**Comment by imshivam-gupta** [comment]
@noman2002 @Cioppolo14 @Kevoniat I would like to work on this, please assign this to me

**Comment by Abhisheksainii** [comment]
@palisadoes With this PR getting merged: https://github.com/PalisadoesFoundation/talawa/pull/2257, all references to the firebase will be removed, so there is no need to resolve the issue again
@imshivam-gupta
@gpkonarde

**Comment by Cioppolo14** [comment]
Since this is a duplicate and is being addressed by the resolution for issue #2195, I am going to close.
