### ISSUE TITLE
Consolidate Talawa Mobile Figma Designs

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2276]
**Is your feature request related to a problem? Please describe.**

We currently have two Figma design documents for Talawa mobile that need to be consolidated into one
- https://docs.talawa.io/docs/design/ux/ux-design-system

There are some disadvantages to them:

1. They are cluttered
2. The ordered flow of screens is not obvious
3. They are not optimally useful for current and future developers

**Describe the solution you'd like**

This is what we'd like to see:

1. Create a new Figma file
4. Merge the two existing files into it
5. Create a logical, uncluttered, connected set of UI workflows for the app showing how the screens are interrelated, similar to the Talawa Admin Figma file on the same page
6. The document must be globally viewable and shared with me with edit rights
7. Any orphan screens should be placed in a separate "Unused Screens" row for clarity
8. The Figma document will be added to:
    - https://docs.talawa.io/docs/design/ux/ux-design-system

**What We Don't Want**

The following are out of scope:

1. Creating any new screens using any design scheme. If screens are missing from what you find in the mobile app then just place a blank white box with the screen dimensions with brief text describing what the screen does instead, and add it to the flow.
1. Modifying the design of any of the screens in any way. If the screen more or less copies what the app displays, then that is good enough. We are focused on the workflow for this exercise.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- We want to use the resulting document as a starting point for GSoC 2024 ideas submissions.

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@Cioppolo14 @palisadoes I could work on this sir.

**Comment by Dante291** [comment]
@palisadoes @noman2002 Also currently the interface of the post widget doesn't match with the app theme, I have some different design in my mind that matches the theme and concept of our app. Since @Ayush0Chaudhary has worked on this before I would like to work under his guidance for this and get his approval for it whether we should make changes for it or not.

**Comment by palisadoes** [comment]
That is out of scope of this issue. It is specifically stated that we don't want any changes in the layouts. We want to document the screen sequencing

**Comment by Dante291** [comment]
> That is out of scope of this issue. It is specifically stated that we don't want any changes in the layouts. We want to document the screen sequencing

Alright then I will just consolidate the two designs into one for this issue and for the changes in UI I will make another issue with my concept design for post widget and ask for approval from @Ayush0Chaudhary.

**Comment by Dante291** [comment]
@palisadoes Done with my work, how do I raise PR for this? like should I just provide the link in here?

**Comment by palisadoes** [comment]
Completed. We'll add it to docs.talawa.io
