### ISSUE TITLE
No validation and confirmation on comments.

### ISSUE THREAD

**Issue by bhoomikshetty** [PalisadoesFoundation/talawa#2277]
**Describe the bug**
Users are able to comment blank texts.

**To Reproduce**

1. Enter the comments view.
2. Without typing anything, hit 'send'.

**Expected behavior**
1. Should not allow sending the comment if the comment is empty.
2. Should provide confirmation once comment is successfully uploaded.

**Actual behavior**
Clicking 'send' is calling the API with empty comment message and adding the blank comment locally.
After an error is received from the backend, the comment disappears.
This leads to a poor user experience.

Can I work on this issue?

**Comment by AVtheking** [comment]
Can I work on it ?

**Comment by Cioppolo14** [comment]
@bhoomikshetty  Please use the issue template.

**Comment by bhoomikshetty** [comment]
> @bhoomikshetty Please use the issue template.

Sorry, updated now.

**Comment by palisadoes** [comment]
Why is this required? No other platform I can think of has confirmation of comments not validation.

**Comment by Azad99-9** [comment]
@palisadoes currently the send button is working even if the comment is blank.

@bhoomikshetty instead of confirming the comment you could just make the send button not work as suggested, in case of blank comment.

**Comment by Cioppolo14** [comment]
@bhoomikshetty I recommended making changes based on @palisadoes' comment and question.

**Comment by bhoomikshetty** [comment]
> Why is this required? No other platform I can think of has confirmation of comments validation.
> 
> Confirmation is the comment itself
> 
> If there is no content, then the send button shouldn't activate.
> 
> Is this the current methodology?
> 

That's my bad, I meant to say confirmation after the comment is sent.

Something like this.
![Screenshot_20231229_125200.jpg](https://github.com/PalisadoesFoundation/talawa/assets/76581406/ac7cd80d-f520-442e-9b4d-fbbc790cd498)

**Comment by Dante291** [comment]
@noman2002 @Cioppolo14 i would like to work on this
