### ISSUE TITLE
Comprehensive Language Translation Enhancement for App Globalization

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa#2283]
**Is your feature request related to a problem? Please describe. **

The current state of language translation in the app is problematic. Many screens exhibit improper translations or, in some cases, fail to translate to the selected language. This results in a suboptimal user experience and impacts the app's usability for non-English-speaking users.

**Describe the solution you'd like**

Implement a comprehensive and accurate language translation system throughout the app. This involves thorough testing of different languages to ensure proper translation on all screens. The goal is to provide a seamless and user-friendly experience for individuals using the app in languages other than the default.

**Describe alternatives you've considered**
Automated Translation Services: Explore the possibility of using reliable automated translation services for accurate and consistent translations.

**Approach to be followed (optional)**
1.Conduct an audit of the current translation across all screens.
2.Identify screens with improper or missing translations.
3.Implement a systematic approach to review and correct translations.
4.Establish a process for ongoing translation maintenance as the app evolves.

**Additional context**
Addressing language translation concerns is crucial for creating an inclusive and accessible user experience across diverse linguistic backgrounds.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
![Screenshot_1703845246](https://github.com/PalisadoesFoundation/talawa/assets/103507835/530992bb-6e5c-44ca-98fd-6c5bad21ed37)
![Screenshot_1703845292](https://github.com/PalisadoesFoundation/talawa/assets/103507835/49a37ae9-6501-4256-91e4-cd56dcdeaad2)
![Screenshot_1703845549](https://github.com/PalisadoesFoundation/talawa/assets/103507835/a8de23b5-d4ab-483c-9ac7-6a81a9f3f3a6)
There are many more screens and widgets where translation need to be fixed.

**Comment by Dante291** [comment]
![Screenshot_1703845246](https://github.com/PalisadoesFoundation/talawa/assets/103507835/4218fc90-3793-487d-9331-9aa5dbfd964d)

![Screenshot_1703845292](https://github.com/PalisadoesFoundation/talawa/assets/103507835/d151e1b1-260b-413f-98d3-cbe57c5ae2e4)

![Screenshot_1703845549](https://github.com/PalisadoesFoundation/talawa/assets/103507835/dad907c8-256b-43be-a0d6-f2fc8746e6cd)

There are many more screens and widgets where translation needs to be fixed.

**Comment by Dante291** [comment]
@noman2002 @Cioppolo14 @Kevoniat I would like to work on this.

**Comment by palisadoes** [comment]
Duplicate. Closing
- https://github.com/PalisadoesFoundation/talawa/pull/2281

**Comment by palisadoes** [comment]
1. You can verify whether this PR is actually working and adjust if necessary.
2. You can also consider refactoring the check so that we can test whether it actually does what it is supposed to do.

**Comment by Dante291** [comment]
> Duplicate. Closing
> 
> * [Fix/actions for translation files #2281](https://github.com/PalisadoesFoundation/talawa/pull/2281)

@palisadoes This PR is the workflow to check whether all translation files consists equal and same number of keys where as this issue addresses the improper translation through out the Talawa App, there are many screens where translation to the selected language fails.

**Comment by Dante291** [comment]
> 1. You can verify whether this PR is actually working and adjust if necessary.
> 2. You can also consider refactoring the check so that we can test whether it actually does what it is supposed to do.

@palisadoes Alright will verify and if required then make necessary changes to this check too

**Comment by Dante291** [comment]
> ![Screenshot_1703845246](https://private-user-images.githubusercontent.com/103507835/293348004-4218fc90-3793-487d-9331-9aa5dbfd964d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjQxNzYsIm5iZiI6MTcwMzg2Mzg3NiwicGF0aCI6Ii8xMDM1MDc4MzUvMjkzMzQ4MDA0LTQyMThmYzkwLTM3OTMtNDg3ZC05MzMxLTlhYTVkYmZkOTY0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNTMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjE1N2QyNTM4ZDRkOWQ3NjMwMTMwYWQ5OWQ5NDNhNDdjMGJkYjM1ZGRkNDljM2IwYmRkY2M0MjZkMTUzNjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NpvmGnt5PhZgZRPmMwt1Kceays5wP56YhBS5PXQDxvk)
> 
> ![Screenshot_1703845292](https://private-user-images.githubusercontent.com/103507835/293348008-d151e1b1-260b-413f-98d3-cbe57c5ae2e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjQxNzYsIm5iZiI6MTcwMzg2Mzg3NiwicGF0aCI6Ii8xMDM1MDc4MzUvMjkzMzQ4MDA4LWQxNTFlMWIxLTI2MGItNDEzZi05OGQzLWNiZTU3YzVhZTJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNTMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWZlNDdmY2QwZDAzYTU2NWMxOWM4ODJjODk2YWQzOGRmODM5MTE1MTdmZjdhOGUxNDQ1MzY5NTI0N2YyYWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0DPs7R0LOULZggvDy5UScV7EGL05LtUaaPwbeKSlG48)
> 
> ![Screenshot_1703845549](https://private-user-images.githubusercontent.com/103507835/293348010-dad907c8-256b-43be-a0d6-f2fc8746e6cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjQxNzYsIm5iZiI6MTcwMzg2Mzg3NiwicGF0aCI6Ii8xMDM1MDc4MzUvMjkzMzQ4MDEwLWRhZDkwN2M4LTI1NmItNDNiZS1hMGQ2LWYyZmM4NzQ2ZTZjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNTMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzIyNWE3ZDdlZmM3ODM4YjBkYjFhMGMwN2Q2Yzk1MmFlZmY1NTU5ZDUyNTIwNTVjMWI5MGEwODU0Nzc4ODdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3O4QnOalo3drBNECzT1GnIVGJTiUk3gn1qt8kHjRdAQ)
> 
> There are many more screens and widgets where translation needs to be fixed.

@palisadoes you could look at this sir.

**Comment by palisadoes** [comment]
1. I can't see the shots.
2. We could split this up into two separate PRs. 
3. One to verify the check
4. The other to fix the translations that are not implemented

Are you interested in both?

**Comment by Dante291** [comment]
> 1. I can't see the shots.
> 2. We could split this up into two separate PRs.
> 3. One to verify the check
> 4. The other to fix the translations that are not implemented
> 
> Are you interested in both?

Yes I could work on this.

**Comment by palisadoes** [comment]
1. Work on the translator checker script first
2. Then fix the screens

That way you'll be able to test your screen work better

**Comment by Dante291** [comment]
> 1. Work on the translator checker script first
> 2. Then fix the screens
> 
> That way you'll be able to test your screen work better

Ok sir
