### ISSUE TITLE
Mobile - Remove Support for Private Organizations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2287]
**Is your feature request related to a problem? Please describe.**
We need to reduce and simplify some of the Talawa features. 

The concept of private organizations is unlikely given that most organizations using Talawa will be non-profits where transparency will be important.

**Describe the solution you'd like**

Remove all support for private organizations in:
1. Screens, sections of screens and supporting code that reference the feature

Other:

1. All tests must be valid and pass
1. No other functionality must be affected.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1604
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327
3. https://github.com/PalisadoesFoundation/talawa/issues/2287

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@noman2002 @Cioppolo14 @Kevoniat can any one of you please assign this issue to me. I would like to work on this.

**Comment by AVtheking** [comment]
Can I work on this issue?

**Comment by Cioppolo14** [comment]
@AVtheking If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Azad99-9** [comment]
@palisadoes a small clarification, the `membership request` feature is only availble for private orgs right ?

**Comment by palisadoes** [comment]
It should be valid for all types of organizations

**Comment by Azad99-9** [comment]
@palisadoes if we remove the support for private orgs then i think the `membership request feature` is of no use because the public orgs allow the users to directly participate.

![Screenshot from 2024-01-04 17-01-58](https://github.com/PalisadoesFoundation/talawa/assets/120930148/eadf5fd7-1201-4a05-be62-f3c5c66af68d)

and in above context the concept of waiting screen also makes no sense.

**Comment by Azad99-9** [comment]
so i am planning to remove both `waiting screen` and `membership request feature` from the application.

**Comment by palisadoes** [comment]
1. When users first create their accounts, they register to an organization and the Admin approves it. 
2. The Admin portal has a request approvals screen for this. 
3. We should consider whether organizations want to have the option of automatic registration or not.

@rishav-jha-mech @aashimawadhwa @beingnoble03 What is the current workflow in the web Admin and User portals?

**Comment by rishav-jha-mech** [comment]
**Admin Panel**

1. The first registered user becomes Superadmin, others will be just the users
2. The superadmin creates Organizations, and can manually add any user to it
3. The superadmin can change the role of any user, from user to admin and vice-versa
4. An admin cannot change the role of other admin 
5. We have a membership requests page, on Admin Panel, only admins who are not approved by an admin will be listed there, it is redundant now, so that will be removed
6. We dont have Membership Requests screen at the moment for the organization, we have to create one

**Comment by Azad99-9** [comment]
@rishav-jha-mech please clarify

1. if an organisation is public, then the users can directly join that org right? No need of membership.

**Comment by Azad99-9** [comment]
> so i am planning to remove both waiting screen and membership request feature from the application.

@palisadoes please suggest, what would be the appropriate solution shall I remove the above screens or leave them as it is.

**Comment by palisadoes** [comment]
> @rishav-jha-mech please clarify
> 
> 1. if an organisation is public, then the users can directly join that org right? No need of sending a  membership request and waiting for the approval.

There may be a requirement by the admin to require  registration approvals for public orgs.

Please reference the issues mentioned in the other tepos

**Comment by palisadoes** [comment]
Please work with @rishav-jha-mech on this

**Comment by palisadoes** [comment]
Please refer to this discussion before proceeding
- https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274

**Comment by Azad99-9** [comment]
@palisadoes this is for your kind information,
as soon as [this](https://github.com/PalisadoesFoundation/talawa-api/pull/1643) PR gets merged i will work on this issue.

**Comment by palisadoes** [comment]
FYI - The issue blocking this has been completed
- https://github.com/PalisadoesFoundation/talawa-api/issues/1604

**Comment by Azad99-9** [comment]
Thanks @palisadoes , I will start working on it.
