### ISSUE TITLE
Mobile - Deprecate the Group Chats for Events Feature

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2297]
**Is your feature request related to a problem? Please describe.**

To simplify the UI/UX we have decided to deprecate group chats tied to Events so that the draft GSoC 2024 chat idea just focuses on creating basic expected functionality.

The link to chats was previously removed from the bottom of the app’s screen because of this lack of functionality. All other chat code remains.

**Describe the solution you'd like**

This means that all support for this feature must be removed. This includes removing all of the following related items:

1. Sections of screens that contain references this feature
1. Any screens completely dedicated to this feature
1. Underlying code related to the specific support of this feature
1. Any testing code specific to this feature

All other code related to group chats must remain. We only want the group chat feature related to Events to be removed.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
The Figma designs showing the relevant Event Group Chat screens can be found here:
- https://docs.talawa.io/docs/design/ux/ux-design-system

**Other**
Issues related to this issue include:
- https://github.com/PalisadoesFoundation/talawa/issues/2297
- https://github.com/PalisadoesFoundation/talawa-api/issues/1618

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@palisadoes Since I was the one who removed chat functionality, I would like to work on this but one of my PR is in pending to be reviewed.

**Comment by Hasnain01-hub** [comment]
I would like to work on this issue

**Comment by Kevoniat** [comment]
@Hasnain01-hub  assigned
