### ISSUE TITLE
[Enhancement] Administer cannot remove other administer but the error page for this is not coming  

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#230]
the error is only showing in the console and not showing in the mobile app
![Capture](https://user-images.githubusercontent.com/55004621/111064273-0ca76a00-84d9-11eb-9d29-0041fec12ec1.JPG)
![WhatsApp Image 2021-03-14 at 3 22 32 PM](https://user-images.githubusercontent.com/55004621/111064283-1df07680-84d9-11eb-9a85-5183acf3fc78.jpeg)

**Comment by yasharth291** [comment]
@Sagar2366 can you please assign me this

**Comment by CyberWake** [comment]
> @Sagar2366 can you please assign me this

these issues are already resolved and I have tested them all in the PR #355 which was the issue assigned to me and successfully dissolved. Till then we can work on trying to find new once. Which really need attention. Let's not waste time in replicating the work.😊

**Comment by yasharth291** [comment]
but the problem is you created duplicate issue started working on it. this is against the guideline. You can work on it but the way you are doing is not according to the guidelines. If this issue is resolved just mention this also in your pr.

**Comment by yasharth291** [comment]
hello @CyberWake  is this issue resolved?

**Comment by CyberWake** [comment]
@yasharth291 yes the issue is fixed now

**Comment by yasharth291** [comment]
Thanks @CyberWake  for solving this issue please try to mention Fixes #issuenumber to automatically close the issue with pr merge
