### ISSUE TITLE
Bug Report:  ViewModel should not have code for View.

### ISSUE THREAD

**Issue by Abhisheksainii** [PalisadoesFoundation/talawa#2303]
**Describe the bug**
The logout dialog has not called as before. The profile page view model contains the code for profile view (the logout one). It needs to be moved to the respective widget's page. View model should not have code for view.

**To Reproduce**

1. Go to profile_page_view_model.dart file 
2. You would see logout function on line no. 90

**Expected behavior**
Move the logout code to somewhere in the profile page

**Actual behavior**
The profile page view model contains the code for logout.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AVtheking** [comment]
I would Like to work on this issue please assign me

**Comment by Dante291** [comment]
@Abhisheksainii Are you gonna work on this? If not I would like work on this

**Comment by Dante291** [comment]
@noman2002 @Cioppolo14 @Kevoniat please assign me this, its a quick fix

**Comment by Abhisheksainii** [comment]
Anyone of you can work on this
