### ISSUE TITLE
[Proposal] Changing the date on the calendar doesn't show the event of particular day

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#231]
When i was clicking on different dates on the calendar the event bar was same but technically a better option would be it should show the events for that current day that is selected in the calendar. here is a short video regarding it.

https://user-images.githubusercontent.com/55004621/111064509-665c6400-84da-11eb-825b-a7e66d45ced3.mp4

**Comment by Bhavay192** [comment]
hey @yasharth291  can u give an idea on how to link the different events with their corresponding dates ?

**Comment by yasharth291** [comment]
by using map indexing

**Comment by Bhavay192** [comment]
hey @yasharth291  can we implement a different flutter package for the app?? it will just make it easy to display the list of events on a particular day ??

**Comment by yasharth291** [comment]
you have to ask @Sagar2366  sir

**Comment by Bhavay192** [comment]
hey @Sagar2366  can we just use an alternative for the calender?? A custom flutter package ??

**Comment by Bhavay192** [comment]
hey @yasharth291  can u pls be more specific about in which file u saw the calender code as I'm trying to figure out the particular page but couldn't

**Comment by Sagar2366** [comment]
@Bhavay192 , try to use existing code until and unless it is valid/not deprecated/best approach. If not propose new changes mentors will review and give you feedback.
