### ISSUE TITLE
Users unable to login

### ISSUE THREAD

**Issue by imshivam-gupta** [PalisadoesFoundation/talawa#2310]
**Describe the bug**

When setting up the mobile repo on android user is unable to login because of `andoridoptions` in graphql query.

**To Reproduce**

1. Clone the repository.
2. Run Talawa-API Locally
3. Try to login with email: `testuser1@example.com` and password: `Pass@123`

**Expected behavior**

User should be able to login.

**Actual behavior**

Error occurs and user is unable to login

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa/assets/93479496/0a98e7b7-effd-4da9-a42b-526001241c7e)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by imshivam-gupta** [comment]
@noman2002 @Kevoniat @Cioppolo14  I would like to work on this, please assign.

**Comment by Dante291** [comment]
Duplicate issue of this https://github.com/PalisadoesFoundation/talawa/issues/2274

**Comment by imshivam-gupta** [comment]
Oh Sorry I didn't check that I will delete this issue
