### ISSUE TITLE
Comments for pinned posts

### ISSUE THREAD

**Issue by imshivam-gupta** [PalisadoesFoundation/talawa#2311]
**Is your feature request related to a problem? Please describe.**
Pinned Posts images are not scaled properly and we should  be able to read comments for pinned posts as well. Also if images fails to load we should not show the loading placeholder only we should replace it by some placeholder image for better UI.

**Describe the solution you'd like**
 For this we can add a floating button to view the comments section like other posts.

**Describe alternatives you've considered**
Alternative is to fix only the image scaling and replacing that by a proper placeholder image in case image is not there. Currently we see only a loading icon there.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa/assets/93479496/a9b0f1c7-8b6e-46f9-a035-b28692e9c131)

![image](https://github.com/PalisadoesFoundation/talawa/assets/93479496/63227f54-a20c-47f2-8c32-99bf74e30d90)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by imshivam-gupta** [comment]
@noman2002 @Cioppolo14 @Kevoniat I would like to work on this, please assign it to me.

**Comment by Dante291** [comment]
@imshivam-gupta Before starting working on this do confirm it with @palisadoes whether comments are actually required for pinned posts?

**Comment by palisadoes** [comment]
@imshivam-gupta 

1. Pinned posts are aimed at being announcements.
2. Though the idea is a good one, we need to focus on other areas of the code base. You'll be able to see where our priorities will be based on the recent PRs in the API
3. Closing
