### ISSUE TITLE
EventCalendar screen failing to open.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2328]
**Describe the bug**
The `EventCalendar` screen is failing to open when the `ExploreEvents` screen is not empty.

**To Reproduce**

1. Navigate to Explore Events Page.
2. Create a new event.
3. Navigate back to Explore Events Page.
4. Open Event Calendar page by clicking on calendar icon.

**Expected behavior**
![Screenshot_20240116-001427](https://github.com/PalisadoesFoundation/talawa/assets/120930148/cf2467fe-7383-4570-bbb2-2a8a40604c66)

**Actual behavior**
![Screenshot_20240116-001659](https://github.com/PalisadoesFoundation/talawa/assets/120930148/12011097-4be2-407a-bd0f-af5e54cd4869)

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Manik2708** [comment]
Can I work on this issue? @palisadoes @noman2002

**Comment by Cioppolo14** [comment]
@Azad99-9 I cannot tell if you wanted to work on this issue or not.  Did you want to work on this issue?

**Comment by Azad99-9** [comment]
@Cioppolo14 no problem, you can assign it to @Manik2708 .

**Comment by abhisheksharma010** [comment]
Hello @Cioppolo14 , can you assign this issue to me? I can easily resolve this.

**Comment by Manik2708** [comment]
Unassigned myself, as I am working on a Talawa API issue. Sorry for this. Please assign it somebobody else.

**Comment by AVtheking** [comment]
I would like to work on this issue

**Comment by Azad99-9** [comment]
@palisadoes @Cioppolo14 this issue isn't completely fixed. It still persists in the app. Can you please reopen this issue.

**Comment by AVtheking** [comment]
it is not showing me error

**Comment by AVtheking** [comment]
Working fine for me

**Comment by Azad99-9** [comment]
@AVtheking please confirm it from other fellow devs some of them including me are facing this issue.

**Comment by Azad99-9** [comment]
@AVtheking did you find the cause of this issue.

**Comment by AVtheking** [comment]
@Azad99-9 sorry  I was busy and haven't look into it.

**Comment by Azad99-9** [comment]
@AVtheking no worries I have found the cause of the issue. Would send you the fix you raise a PR for the same👍

**Comment by AVtheking** [comment]
Instead of me raising the PR I unassign myself and let you get assigned and raise a PR to fix this

**Comment by Azad99-9** [comment]
@AVtheking actually i got already 2 issues assigned.

**Comment by AVtheking** [comment]
Me also ok no worries I will raise the PR
