### ISSUE TITLE
User Interface of Light Mode is Inconsistent.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2329]
**Describe the bug**
Currently the screens related to `Light Theme` of Talawa are not as consistent as the screens of `Dark Theme`.

**To Reproduce**

1. Navigate to Settings Screen.
2. Disable Dark Theme.
3. Explore the User Interface.

**Expected behavior**
Consistent UI:
1. Text should be visible on screen.
2. Containers should have distinction with their background.

**Actual behavior**
1. Text is `invisible` in couple of places.

![Screenshot from 2024-01-16 01-19-55](https://github.com/PalisadoesFoundation/talawa/assets/120930148/62e389d4-9789-463e-bac9-7027fcbecf26)

2. Containsers are not `distinguishable` with respect to their backgrounds.

![Screenshot from 2024-01-16 01-21-45](https://github.com/PalisadoesFoundation/talawa/assets/120930148/0132e3a8-f651-4074-9996-8dd2afa6e2a3)

**Screenshots**

**Additional details**
The provided images highlight only a few examples of a more extensive problem. Numerous other miscellaneous elements within the UI exhibit inconsistencies.
Proposed Solution:
1. Scrutinize the entire 'Light Theme' UI.
2. Identify inconsistencies.
3. Rectify them by implementing the `Talawa design system`.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@noman2002 @palisadoes @Cioppolo14 @Kevoniat please assign this issue to me.

**Comment by Cioppolo14** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code are not acceptable under this policy.

Closing
