### ISSUE TITLE
[BUG] Deleting the Last Event Make screen stuck on loading

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#233]
when we delete the last event from the event list the screen stuck on loading

https://user-images.githubusercontent.com/55004621/111064717-9bb58180-84db-11eb-991e-d6642f855112.mp4

**Comment by adithyaakrishna** [comment]
Okay Will Work on this @yasharth291

**Comment by yasharth291** [comment]
@adithyaakrishna  is this bug solved by you?
