### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by RunTerror** [PalisadoesFoundation/talawa#2336]
BUG

renderflex in showdialogbox

**Expected behavior**
 The end date should be fitted properly inside the box of end date 

**Actual behavior**
 the size of end date box is less to get fit in the box.

**Screenshots**

![Screenshot_1705662467](https://github.com/PalisadoesFoundation/talawa/assets/113206442/44d2c203-750e-4204-92ee-b8cca31f00af)

I'll reduce the text size of date so that it could fix or increase the size of end date box 

please assign me this issue

**Comment by Azad99-9** [comment]
@RunTerror this issue no longer exists and is solved as part of my recent [PR](https://github.com/PalisadoesFoundation/talawa/pull/2332#issue-2088796716).

**Comment by RunTerror** [comment]
Hello @Azad99-9,
Having cloned the develop branch and confirmed its full synchronization, I'm prepared to take charge if the current resolution is deemed insufficient. @palisadoes, may I proceed to rectify the issue and ensure responsiveness?

**Comment by Cioppolo14** [comment]
@RunTerror I'm going to close this for now, since it will be resolved with this above PR.  If it is still happening once that PR is merged, please comment on this issue and we can reopen it.
