### ISSUE TITLE
Feature Request: Replace CircularProgressIndicator with Spinkit

### ISSUE THREAD

**Issue by RunTerror** [PalisadoesFoundation/talawa#2338]
![Screenshot_1705725178](https://github.com/PalisadoesFoundation/talawa/assets/113206442/ca4434b1-5d99-4838-bdad-564bb49c7d72)

In the provided image, we currently use a circular progress indicator for loading images. 
Consider implementing the Spinkit package to showcase a loading animation that aligns seamlessly with the overall theme of our application.

**Comment by Dante291** [comment]
Hello @RunTerror ,we incorporate new packages into our project only if it's challenging to implement a particular feature using existing packages. This approach ensures security, so loading indicator do the work for now.

**Comment by RunTerror** [comment]
can we implement a shimmer effect or another animation. The current progress indicator undergoes shape changes, which can appear somewhat unconventional.

**Comment by Dante291** [comment]
yeah thats a bug need to be fixed you could work on that but i wouldnt suggest adding a whole new package just for this, do ask from @Cioppolo14

**Comment by RunTerror** [comment]
i have tried to create this animation with code only we are not using any package here.

https://github.com/PalisadoesFoundation/talawa/assets/113206442/ee8574b1-7e60-408e-b223-6d448976ecbb

can we implement this in our application directly

**Comment by Azad99-9** [comment]
@RunTerror I appreciate your effort to contribute to Talawa, please go through [this](https://github.com/PalisadoesFoundation/talawa/issues/2329#issuecomment-1893680403) comment before raising any issues.

**Comment by Cioppolo14** [comment]
@RunTerror Thank you for your submission. I am going to close this issue for now. 

We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code are not acceptable under this policy.

Closing
