### ISSUE TITLE
Bug: multiple bugs reported on post screen 

### ISSUE THREAD

**Issue by RunTerror** [PalisadoesFoundation/talawa#2339]
***Bug Description***
1. Duplicate post comes in list of posts 
2. After the deletion of post it does not automatically deletes.

***Expected behavior***
No duplicate post gets come while loading new posts.
Post should be removed when it gets delete.

***Actual behavior***
duplicate post are showing on refreshing
post deletes from database but doesn't reflect on frontend

https://github.com/PalisadoesFoundation/talawa/assets/113206442/11a84763-26f5-46f5-bfd2-22eae010472a

**Comment by RunTerror** [comment]
@noman2002 @palisadoes  Please assign me this issue

**Comment by Cioppolo14** [comment]
@RunTerror Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Dante291** [comment]
All this is fixed in this [PR](https://github.com/PalisadoesFoundation/talawa/pull/2321), you can close this issue also I would suggest you go through all the current issues and raised PRs before making new ones to avoid duplicate issues. 

@Cioppolo14 this can be closed

**Comment by RunTerror** [comment]
@Dante291 sure i'll check other issues before creating new ones.
