### ISSUE TITLE
Adding a Splash Screen | Enhancement 

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#234]
#### Almost every app , now days is having a splash screen with some cool animation . I noticed that Splash screen is not present in the app . If added it will make the app more attractive . Please allow me to do so . @Sagar2366 

- [x] creating a screen 
- [x] adding logo 
- [x] adding some animation .

**Comment by adithyaakrishna** [comment]
Hey @ishan0805 I had worked on this already and designed a basic splash screen for this

**Comment by CoderMayhem** [comment]
It would be great if you can post the designs in the `#talawa-design` slack channel for review. @adithyaakrishna

**Comment by ishan0805** [comment]
Sorry but I didn't   saw any issue related to it and I
 have already finished coding it .

**Comment by ishan0805** [comment]
@adithyaakrishna are you talking about native splash screen

**Comment by adithyaakrishna** [comment]
No worries @ishan0805 Do finish it and create a PR :)

**Comment by Sagar2366** [comment]
Logo is already added in one of recent PR. Rest features are not required.
