### ISSUE TITLE
Mobile - Add support to recurring events.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2341]
**Is your feature request related to a problem? Please describe.**
Implement `recurring events` functionality into Talawa mobile. 

**Describe the solution you'd like**
- The event creation screen(s) should have functionality to create recurring events.
          1. weeks
          2. months 
          3. days 
          4. weekdays 
- The Calendar screen(s) should display all the created recurring events.
- The edit event screen(s) should have funcitonality to edit these recurring events.
          1. All instances in the series
          2. Just the instance in question
          3. The instance in question and all those in future
- Make use of updated `event mutations` to implement the described functionality.
- The screen(s) design must follow the guidelines of Talawa Design System found here:
          - https://docs.talawa.io/docs/design/ux/ux-design-system
- Other functionality must not be affected.
- Write tests and achieve 100% code coverage to all the new functionality added.

**Describe alternatives you've considered**
   N/A

**Approach to be followed (optional)**
   - see above.

**Additional context**
   1. related issues:
       - https://github.com/PalisadoesFoundation/talawa-api/issues/1583#issue-2057545112
   2. related PRs:
       - https://github.com/PalisadoesFoundation/talawa-api/pull/1658#issue-2069943639
       - https://github.com/PalisadoesFoundation/talawa-api/pull/1712#issue-2086753320

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@Cioppolo14 I would like to work on this, please assign me.

**Comment by Azad99-9** [comment]
@palisadoes please have a look at this issue and do let me know if any follow ups and if I missout on any thing.

**Comment by Community-Programmer** [comment]
@Azad99-9 
You are requested to hold off for some time as there is currently a discussion underway regarding whether we should follow a denormalized approach or another one. 
Once it is confirmed, there may be some tweaks that need to be made in the weekly recurring events PR. Until then, please wait. 
Thank you for your understanding

**Comment by Azad99-9** [comment]
Sure @Community-Programmer

**Comment by Azad99-9** [comment]
@Cioppolo14 @noman2002 I would like to work on this, please assign me.

As the implementation of this feature in backend is in progress meanwhile i will start working on the UI part of this issue.

**Comment by Azad99-9** [comment]
Working on this, as the recent PR related to this issue in Talawa API has been closed.

**Comment by Olatade** [comment]
HI @Azad99-9 are you still working on this?

**Comment by Azad99-9** [comment]
@Olatade yes I am working on this. There is a backend dependency.

**Comment by Azad99-9** [comment]
@palisadoes @noman2002 The implementation of this feature requires multiple files to be changed.
- Creation of new Model & View models.
- Modificaton & addition of new Queries.
- New UI changes.

I have also had a word with @meetulr, 2 more PRs related to event updation & deletion are also about to come.

So meanwhile i am thinking to split this issue into multiple PRs and raise them one by one.

**Comment by palisadoes** [comment]
This was expected. Large PRs are too difficult to review effectively.

**Comment by Azad99-9** [comment]
@palisadoes @noman2002 please review the UI and suggest changes if any.
**Note** Api integration not yet done. For now UI is built. 
If finalized i will raise a PR for the same. I will make a seperate PR for Api integration.

https://github.com/PalisadoesFoundation/talawa/assets/120930148/42adca5d-8f0f-4d1d-8e75-3e8a5a8fb61c

**Comment by palisadoes** [comment]
1. Yes this is good
2. Use this to test your work against the API PR in review:
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by Azad99-9** [comment]
@palisadoes @Cioppolo14 still API integration work is pending with this issue. Please reopen this so that I can raise a PR for the same.

**Comment by Azad99-9** [comment]
Api integration completed, writing tests. Will raise the PR by tomorrow.
