### ISSUE TITLE
Bug: App crashes unpredictably.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2342]
**Describe the bug**
1. The signup process occasionally results in the app crashing. Specifically, the signup flow functions correctly at times but experiences issues and crashes unpredictably at other times.
2. After login switching organisations repeatedly is resulting in app crash.

**To Reproduce**

There isn't any defined way to reproduce this behaviour.
1. Launch Talawa app
2. Play around `Login`,`signup` & `organisation switching` functionalities.
3. Try different combinations of above functioinalities
         example combination:
             a. login to the app.
             b. switch organisation.
             c. logout.
             d. Again signup and so on...
4. At some point the app crashes.

**Expected behavior**
App shouldnot crash and work predictably.

**Actual behavior**
some instances of the issue:

    **When switching organisations after Login.**
https://github.com/PalisadoesFoundation/talawa/assets/120930148/1df35659-1978-43e5-bfd7-ff230cecc52d

    **When signup**
https://github.com/PalisadoesFoundation/talawa/assets/120930148/c9bc770f-aa23-4b8b-ae32-bddb09665f2c

**Screenshots**
    **Logs when issue is encountered.**
![Screenshot from 2024-01-22 02-50-08](https://github.com/PalisadoesFoundation/talawa/assets/120930148/d1481f23-d4a5-48ed-9430-209956c4dffb)

**Additional details**
- See above.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@Azad99-9 does it always crashes when switching to another org?

**Comment by Azad99-9** [comment]
@Dante291 the trigger why the app crashes is uncertain, sometimes it crashes if we signup other times it crashes if we switch orgs.
I was facing this prior to latest fetch too but the frequency was less. Post the latest fetch the frequency increased so I thought it should be addressed.

**Comment by Azad99-9** [comment]
@Cioppolo14 I would like to work on this, please assign me.

**Comment by Azad99-9** [comment]
@palisadoes @literalEval @noman2002 @Ayush0Chaudhary  I have found the root cause of this issue.

`cause`: `Race condition` of `refreshToken` method as it is being invoked concurrently from multiple methods.

1. Upon `app startup` or user actions like `logging in` or `signing up`, the initialization methods of multiple screens, including `OrganisationFeed`, `ExploreEvents`, and `ProfileScreen`, are invoked concurrently.
2. Within the initialization method of each mentioned screen, corresponding functions like `getPosts` and `getEvents` are called.
3. The issue arises because these functions include a call to the `refreshToken` method in their implementation.
`Future<void> getEvents() async {
    // refresh user's access token
    await _dbFunctions.refreshAccessToken(userConfig.currentUser.refreshToken!);
    _dbFunctions.init();

  `
  `Future<void> getPosts() async {
    await _dbFunctions.refreshAccessToken(userConfig.currentUser.refreshToken!);
    _dbFunctions.init();`
    
This poses a concern as the token is being refreshed before each API call for fetching posts and events, which may not be an optimal approach for session handling. Additionally, when these functions are called concurrently, it introduces a race condition in the refreshToken method, as observed in this scenario.
 
 fixes:
 
 1. To fix this issue specifically for this bug we could simply handle the above race condition by some flag and fix it.
 
2. But I feel it would be more beneficial if we have a long term fix for this,
 like if we can introduce a `centralized session management` mechanism into the application which strategically refreshes the token at regular intervals of time. This way not only at this instance but also in future we dont need to worry about this type of race conditions.
 
The second second fix proposed above is out of scope of this issue, so i am planning to create a new issue for the same and implement the desired mechanism 
 
 I would like to know your thoughts on this and please tell me how should i proceed ?

**Comment by Azad99-9** [comment]
@palisadoes @noman2002 @literalEval @Ayush0Chaudhary 
Respected mentors I understand that you are busy, I request you to please take a moment and kindly look at above comment and guide me which approach to follow. Thanks.

**Comment by palisadoes** [comment]
We always prefer implementing solutions that will make the code more stable, manageable and readable in the long term

**Comment by Azad99-9** [comment]
@palisadoes Thanks then I will proceed with the long term solution that I have proposed.👍

**Comment by Cioppolo14** [comment]
@Azad99-9 I think the best thing would be to close this issue, and make a new one that describes the broader problem, mentioning that it will also resolve the app crashing unpredictably in the process.  This way it continues to be mentioned in an active issue, but the new issue will have better details to  your new approach. Please tag me when you make it.

**Comment by Azad99-9** [comment]
@Cioppolo14 Thanks doing it.

**Comment by Azad99-9** [comment]
Closing to open a new issue (#2356) which solves this along the way.
