### ISSUE TITLE
[BUG] Issue with the post

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#235]
1.  Tapping like button twice do not remove the like.
2.  Comment icon doesn't work 
3.  Color doesn't changes on clicking the like button
4.  there is no dislike button 
5.  there is not a share button as well
6.  post structure is not good
7.  can't put video or image in the post 

would you please assign me this to do 
@Sagar2366  @DeltaHarbinger @heyjordn @jordanliu 

https://user-images.githubusercontent.com/55004621/111064890-b63c2a80-84dc-11eb-9ecd-b7e605f29c9a.mp4

**Comment by Sagar2366** [comment]
Good observation. Please create separate issues if required wherever necessary. For example - separate iasue for like and comment issues, ans for share, dislike features.

**Comment by yasharth291** [comment]
i thought they will all come under post can you please assign this to me i want to work on it @Sagar2366

**Comment by yasharth291** [comment]
@DeltaHarbinger can you review it sir

**Comment by yasharth291** [comment]
@Sagar2366 please can you label it and assign me this

**Comment by yasharth291** [comment]
thanks sir

**Comment by Sagar2366** [comment]
@yasharth291 for now ignore dislike and share button feature. Focus on remaining features.

**Comment by yasharth291** [comment]
ok sir i am working on both
