### ISSUE TITLE
Mobile: Fix the usage of userType

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2373]
### NOTE

1. This issue will require close coordination with persons assigned issues in the reference section.
2. You may find it easier to split responsibilities in a different way than proposed here to be more efficient is creating the goal

**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.

This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
2. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
3. All other `userType`s would be on a per organization basis

This means that all code logic referencing the `userType` will need to be updated accordingly.

_TALAWA API_

Additional considerations include:

1. New user registrations will need to default to the `userType` `USER` if not done so already
1. The Schema will need to be updated to reflect this requirement
1. Mutations and queries will need to be updated and in some cases new ones added.
1. Changes must be made against the `develop-userTypeFix` branch

_TALAWA ADMIN_

Additional considerations include:

1. The current screen that edits a person's userType will need to be updated. A design is being created for this and will be reflected in the Figma file on our Design Guide page:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
1. Changes must be made against the `develop-userTypeFix` branch

_TALAWA MOBILE_

1. Update the app to work correctly with the modified queries and mutations of the API's `develop-userTypeFix` branch.
1. Changes must be made against the `develop-userTypeFix` branch

**Actual behavior**

- The schema doesn't apply a person's `userType` by organization. 

**Screenshots**

The previouse API schema:

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/cbd791b2-3ff7-44b9-b936-023c9d979b01)

**Additional details**

Related issues and PRs:

1. _Primary_
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1830
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904
1. _Secondary_
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@palisadoes @Cioppolo14  I would like to work on this, please assign me

**Comment by AVtheking** [comment]
As there would be large amount of files that are going to change and we are working on the admin side by spliting this issue in multiple follow up pr this would be better approach here also

**Comment by palisadoes** [comment]
A single PR for all the changes will be impossible to properly review.

Find ways to submit multiple smaller PRs. 

Large PRs lie dormant for weeks, even months. It's not a good approach.

**Comment by Olatade** [comment]
@Dante291 are you still working on this ?

**Comment by palisadoes** [comment]
@Dante291 The PR was merged. What else needs to be done?

**Comment by Dante291** [comment]
@palisadoes sorry for the late reply was busy with my sem exams, this [PR](https://github.com/PalisadoesFoundation/talawa/pull/2389) fixed all the changes that was required to fix userType from the mobile side, this issue can be closed.
