### ISSUE TITLE
Remove the `geolocator` package

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2384]
**Is your feature request related to a problem? Please describe.**
We are not using the geolocator package in the code base, yet we have it in our package definitions

**Describe the solution you'd like**

1. Remove geolocator if unused
2. No other functionality must be affected
3. All tests must pass and be valid

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yousef-Rabia** [comment]
@palisadoes I would like to work on this task
