### ISSUE TITLE
Fix the loading indicator in the story

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#2391]
**Describe the bug**
The loading is stretched.

**To Reproduce**

1. Go to Home Screen

**Expected behavior**
 It should be a normal circular loading. 

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Screenshot_1708871304](https://github.com/PalisadoesFoundation/talawa/assets/54404474/2a64ea15-5eb7-48e3-81b1-c3660b066856)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by M-SAI-SOORYA** [comment]
Can you assign me this issue?

**Comment by ArinNigam** [comment]
@noman2002 I would like to work on this issue.

**Comment by SumitPareek2401** [comment]
@noman2002 @dhanagopu this will look perfect

https://github.com/PalisadoesFoundation/talawa/assets/122019171/6fa85543-1a14-4fc7-8606-476f2ec3b7b5

**Comment by SumitPareek2401** [comment]
@noman2002 @dhanagopu can you assign this issue to me?

**Comment by Cioppolo14** [comment]
@SumitPareek2401 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by SumitPareek2401** [comment]
@M-SAI-SOORYA are you still working on this issue?

**Comment by M-SAI-SOORYA** [comment]
> @M-SAI-SOORYA are you still working on this issue?

Yes @SumitPareek2401

**Comment by SumitPareek2401** [comment]
@Cioppolo14 can you assign this issue to me? I think @M-SAI-SOORYA will not be able to do it at the proper time.

**Comment by Cioppolo14** [comment]
@SumitPareek2401 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by M-SAI-SOORYA** [comment]
@Cioppolo14 @noman2002  i am sorry , i delayed due to my semester exams , please contribute to talawa rapidly from now onwards!

**Comment by palisadoes** [comment]
Unassigning as the PR seemed abandoned.

**Comment by GlenDsza** [comment]
@palisadoes I would like to work on this issue. 
The already assigned 2 issues are related and being solved in single PR (already opened).

**Comment by SumitPareek2401** [comment]
@Cioppolo14 Please assign this issue to me as I asked you last month.

**Comment by Cioppolo14** [comment]
@GlenDsza Since you have two issues, I am going to assign @SumitPareek2401.  @SumitPareek2401, asking when someone else was assigned is not an appropriate way to become assigned.  The person who requested before you has 2 issues, and you have 0, so I will assign you this issue.

**Comment by palisadoes** [comment]
Unassigning. Inactive

**Comment by SumitPareek2401** [comment]
Impressive👍 @GlenDsza
