### ISSUE TITLE
Bug Report: The "Join Organisation button" should stick to the bottom.  

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#2392]
**Describe the bug**
The Join organization button should stick to bottom. 

**To Reproduce**

1. Open drawer

**Expected behavior**
The Join organization button should stick to bottom. 

**Actual behavior**
Currently, Its not stick to the bottom. 

**Screenshots**
![Screenshot_1708871819](https://github.com/PalisadoesFoundation/talawa/assets/54404474/d8e88479-bc66-447c-b38b-16c27259e5a2)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by M-SAI-SOORYA** [comment]
Can you assign me this issue?

**Comment by ArinNigam** [comment]
@noman2002 I would like to work on this issue

**Comment by SumitPareek2401** [comment]
@noman2002 can you assign this issue to me?
