### ISSUE TITLE
Remove shadow from buttons

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#2393]
**Describe the bug**
Remove shadow from buttons.

**Expected behavior**
No shadow on buttons

**Screenshots**
![Screenshot_1708872180](https://github.com/PalisadoesFoundation/talawa/assets/54404474/7558ac72-cb8b-487b-8ff6-02f9b48b30ec)
![Screenshot_1708872226](https://github.com/PalisadoesFoundation/talawa/assets/54404474/0081c9a7-38ee-4b36-9ddf-1286827cb54b)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yousef-Rabia** [comment]
@noman2002 @Cioppolo14 I would like to work on this.
