### ISSUE TITLE
Fix Navigation: On clicking change language it navigates to home screen. 

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa#2394]
**Describe the bug**
On clicking change language it navigates to home screen, it should navigates to changes language screen.

**To Reproduce**

1. Open drawer
2. Click on join org
3. Click on change language

**Expected behavior**
It should navigates to changes language screen.

**Actual behavior**
On clicking change language it navigates to home screen.

**Screenshots**

![untitled](https://github.com/PalisadoesFoundation/talawa/assets/54404474/9c6f069b-b445-4332-927d-bd6f39b0e79b)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by soaham-pimparkar** [comment]
@noman2002 Could you please assign this task to me?

**Comment by soaham-pimparkar** [comment]
Pull request: [soaham-pimparkar:select-language-fix](https://github.com/PalisadoesFoundation/talawa/pull/2402)

Let me know in case of any changes.
