### ISSUE TITLE
[enhancement] adding stories option in the news feed

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#240]
Able to Post short videos in the name of stories will be nice

**Comment by yasharth291** [comment]
@Sagar2366 sir should i start work on this too

**Comment by palisadoes** [comment]
@yasharth291 Can you give priority to #438? The improved over all performance of the app should take precedence

**Comment by yasharth291** [comment]
Sure sir I am first working on that issue
