### ISSUE TITLE
Evaluate whether package `geocoding` is being used and remove if so

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2400]
**Describe the bug**
We have been getting dependabot updates for the `geocoding` package. But it may not be used.

**Resolution Plan**

- Evaluate whether package `geocoding` is being used and remove if so

**Actual behavior**

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ArinNigam** [comment]
@palisadoes can you assign me this issue?

**Comment by Cioppolo14** [comment]
@ArinNigam I have assigned you. Please tag me or another queue monitor as indicated in the slack channel.  Palisadoes does not assign issues except in extremely rare cases.

**Comment by ArinNigam** [comment]
> @ArinNigam I have assigned you. Please tag me or another queue monitor as indicated in the slack channel. Palisadoes does not assign issues except in extremely rare cases.
@Cioppolo14 Ok noted. 

@Cioppolo14 Kindly review the PR
