### ISSUE TITLE
logout button lands to Select Language page even when logout is not successful.

### ISSUE THREAD

**Issue by am-casper** [PalisadoesFoundation/talawa#2416]
**Describe the bug**
When one clicks on Logout button, it will redirect user to the Select Language screen, even when the logout was not successful due to any error occurring back of the scene.

**To Reproduce**

1. Login into an account and go to the settings option on the profile page
2. Turn off the internet connection.
3. Logout the account. This will navigate to the Select Language Screen.
4. Select a language and you will get navigated to the settings screen again, despite being logged out.

**Expected behavior**
The logout should throw an error as the logout is not successful.

**Actual behavior**
The logout is shown as successful and we are navigated to the Select Language screen

**Comment by Huy1996** [comment]
@am-casper If you believe it needs to be fixed, please complete the issue template in detail; otherwise, this issue will be closed.

**Comment by am-casper** [comment]
@Huy1996 i've updated the issue and also, would like to work on it and resolve. Kindly assign me this issue.
