### ISSUE TITLE
Improved GitHub Issue Template

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa#2434]
**Is your feature request related to a problem? Please describe.**

- When creating new issues on GitHub, users often face the challenge of structuring the issue effectively to provide necessary information. It can lead to inconsistencies and difficulties in tracking issues.

**Describe the solution you'd like**

- I would like to propose implementing GitHub templates for issues. These templates will provide a standardized structure for issue creation, ensuring that essential information is included consistently.

**Describe alternatives you've considered**

- One alternative could be manually creating a document outlining the structure for issue creation and asking users to follow it. However, this approach relies heavily on user compliance and can be prone to human error.

Approach to be followed (optional)

- We could create templates for different types of issues, such as bug reports, feature requests, or support inquiries. Each template would include specific sections tailored to the type of issue, guiding users to provide relevant details.

Additional context

- By implementing GitHub templates for issues, we can streamline the issue creation process, improve clarity, and enhance collaboration among contributors.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes Please assign me this issue

**Comment by palisadoes** [comment]
Closing. Not a priority
