### ISSUE TITLE
Merge the `develop-userTypeFix` branch into `develop`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2437]
**Is your feature request related to a problem? Please describe.**

1. We added new features to the API to correct the authorization of Admins and SuperAdmins across organizations
1. These changes need to be reflected in mobile

**Describe the solution you'd like**

1. Merge the `develop-userTypeFix` branch into `develop`
2. Fix merge conflicts 
3. Update and refactor tests for the new functionality
4. All other functionality must be maintained

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

- https://github.com/PalisadoesFoundation/talawa/pull/2389
- https://github.com/PalisadoesFoundation/talawa/pull/243

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@varshith257 Ask to be assigned

**Comment by varshith257** [comment]
Please assign this issue to me

**Comment by GlenDsza** [comment]
@palisadoes probably issue should be closed as PR is merged
