### ISSUE TITLE
Remove the `geolocator` and `geocoding` packages again

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2438]
**Is your feature request related to a problem? Please describe.**

We are not using the `geolocator` or the `geocoding` packages in the code base, yet we have it in our package definitions

**Describe the solution you'd like**

1. Remove `geolocator` if unused
1. Remove `geocoding` if unused
2. No other functionality must be affected
3. All tests must pass and be valid

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- https://github.com/PalisadoesFoundation/talawa/issues/2384
- https://github.com/PalisadoesFoundation/talawa/pull/2403

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@palisadoes  I have fixed them. Please assign this issue to me
