### ISSUE TITLE
[Bug]Url doesnt change once set

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#244]
once any wrong url (say by a typo) is saved (set url is pressed) , It just appears that you can edit and set another, while the app still uses the former
Steps to reproduce:
1. Run the app and set any url which does'nt exist.
![Screenshot_20210315-154110](https://user-images.githubusercontent.com/68892315/111137875-4fcf0f00-85a5-11eb-9e96-3ce78f3b4f1c.jpg)
2. Sign in/Signup
![Screenshot_20210315-154142](https://user-images.githubusercontent.com/68892315/111137896-552c5980-85a5-11eb-9bff-8b7723d5cb71.jpg)
As expected, we get an error message, that we cannot connect to the url.
3. Change the url to an exisitng url(or any other)
![Screenshot_20210315-154439](https://user-images.githubusercontent.com/68892315/111137919-5f4e5800-85a5-11eb-85a0-af9759b9efc0.jpg)
4. Try signing-in/signing-up again.
![Screenshot_20210315-154229](https://user-images.githubusercontent.com/68892315/111137941-64aba280-85a5-11eb-9d49-58e2113e20e1.jpg)
We can see that despite changing the url, the app still tries to connect to the URL which was set first.
This is a bug because we can obviously expect a user to make a typing error while setting the url and if they do that, they wont be able to re-change the url.

**Comment by Sagar2366** [comment]
Please follow guidelines while creating issue or pr's.
Provide proper description, observed and expected behaviour, fix added, snap/video of before and after change.

**Comment by Swayam221** [comment]
> Please follow guidelines while creating issue or pr's.
> Provide proper description, observed and expected behaviour, fix added, steps to reproduce the issue, snap/video of before and after change.

@Sagar2366 i have updated the description. Sorry for any inconveniences caused before.
Please review PR #275 for this.

**Comment by Swayam221** [comment]
@jordanliu please review.

**Comment by Sagar2366** [comment]
As part of this PR https://github.com/PalisadoesFoundation/talawa/pull/335, this issue will never come.
