### ISSUE TITLE
landscape orientation UI 

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#246]
App bar is taking more than half of the screen of the device in profile screen.

There can be two fixes:
1) We should not change the orientation of the app.
2) If we want to keep the landscape orientation we can use Sliver list view with Sliver App Bar.

For which solution I should aim for?

![WhatsApp Image 2021-03-14 at 5 47 36 PM](https://user-images.githubusercontent.com/43651504/111068198-ca3c5800-84ed-11eb-889d-a580fe2d2667.jpeg)

**Comment by adithyaakrishna** [comment]
@GMGOG Ig this is similar to issue no. #173 which was opened by @sumitra19jha

**Comment by GMGOG** [comment]
That was for the organisation page. I am referring profile page here.

**Comment by adithyaakrishna** [comment]
Ohhhh got it 😶
Happy coding 💯🎉

**Comment by sumitra19jha** [comment]
Actually, It was for the entire device. The app is built in such a way that portrait mode will be good for it.
@GMGOG
