### ISSUE TITLE
Error in Event Creation & Fetch due to Faulty mutation

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa#2468]
**Describe the bug**
User is unable to create event due to faulty and old implementation of `createEvent` mutation. The support for recurrance field was removed from API in https://github.com/PalisadoesFoundation/talawa-api/issues/2107 and there are issuein recurrenceRule used on Talawa Mobile.

Update mutation as per latest https://github.com/PalisadoesFoundation/talawa-api/pull/2234

**Errors in console:**

 - **`GraphQLError(message: Variable "$recurrenceRuleData" got invalid value "TU" at "recurrenceRuleData.weekDays[0]"; Value "TU" does not exist in "WeekDays" enum., locations: null, path: null, extensions: null)`**
 -  **`Field "recurrance" is not defined by type "EventInput"`.**

**To Reproduce**

1. Login to a organization.
2. Open Events tab
3. Click on Create Event Button
4. Fill the details and try to create new event
5. Error Dialog is shown on the screen.

**Expected behavior**
On click of create event button, the Event should be created successfully if all details are filled and valid.

**Actual behavior**
On click of create event button, A Error Dialog is shown.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa/assets/109027247/139fa0d8-f512-4d3f-8f2a-89c519dc1673

**Additional details**
Part (pre-requisite) for Event Parity Project.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
Would like to work on this issue

**Comment by meetulr** [comment]
@GlenDsza There's been some modifications in the implementation of recurring events: PalisaDoesFoundation/talawa-api#2234 (The existing code needed some improvements). Please adjust the code according to that😄

**Comment by GlenDsza** [comment]
WIP will submit PR within some time
