### ISSUE TITLE
[CODE] Filtering code and removing deprecated properties or keywords 

### ISSUE THREAD

**Issue by Pr47h4m** [PalisadoesFoundation/talawa#248]
eg. removing "<Widget>", "new" keywords, formatting code

**Comment by yasharth291** [comment]
hey i am already working on it.

**Comment by Pr47h4m** [comment]
same me too

**Comment by Pr47h4m** [comment]
changed some of the files 
#250

**Comment by Sagar2366** [comment]
@yasharth291 @Pr47h4m, avoid duplicating work.

**Comment by yasharth291** [comment]
i was already working from before @Sagar2366

**Comment by adithyaakrishna** [comment]
Yes @yasharth291 had already opened an issue regarding the deprecated properties

**Comment by Pr47h4m** [comment]
ok closing the issue

**Comment by yasharth291** [comment]
> Yes @yasharth291 had already opened an issue regarding the deprecated properties

Hey @adithyaakrishna could you please help me in solving some issues. I have a lots of them on my head.

**Comment by Sagar2366** [comment]
Suggestion - If you find any issues in project and you already occupied with other issues to work on. Don't raise PR or drop message for others to take it up.

**Comment by adithyaakrishna** [comment]
> > Yes @yasharth291 had already opened an issue regarding the deprecated properties
> 
> Hey @adithyaakrishna could you please help me in solving some issues. I have a lots of them on my head.

Yes sure, working on one of yours, do lmk of others too :)
