### ISSUE TITLE
Improve UI & Color Theme (Dark/Light Mode) across screens 

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa#2487]
**Describe the bug**

Talawa Mobile screens have good color theme for Dark Mode but as soon as we switch to light mode in App following issues are noticed 
- various text disappear due to having white color on white background (Name of User in Profile Screen)
- Some components have fixed dark color irrespective of App theme (Donate button in Profile Screen), Login Buttons background disappears in Light Mode.
- The AppBar background color as well as action btn icon colors are inconsistent across screens (Compare profile and Event Screen)
- The Filter Event Bottom Sheet, Logout Dialog, Event Card, etc. have Yellowish white background which makes the UI look dull (can use white & greyish white shade to differentiate)
- The posts displayed on post screen doesn't have any border (could have defined border to look like separate card for each post) currently looks like a joint text chunk.

**To Reproduce**

1. Login 
2. Visit above mentioned screens

**Expected behavior**
Color Theme for various components across screen should be consistent in Dark as well as Light Mode.

**Actual behavior**
Color Theme for various components across screen is inconsistent and has some color (visibility) issues in Dark/Light Mode.

**Screenshots**

| Event Screen | Profile Screen | Post Screen |
|--------------|----------------|-------------|
| ![Event Screen](https://github.com/PalisadoesFoundation/talawa/assets/109027247/c293452d-600a-4db0-a656-2cc2028a9ff8) | ![Profile Screen](https://github.com/PalisadoesFoundation/talawa/assets/109027247/de77da2f-e0b4-4d2f-95eb-5a9578b5aab6) | ![post screen](https://github.com/PalisadoesFoundation/talawa/assets/109027247/4f56b153-380a-4680-9b36-428b9c12192b) |
| Event Screen Bottom Sheet | Login Screen | Logout dialog |
| ![Event Screen Bottom Sheet](https://github.com/PalisadoesFoundation/talawa/assets/109027247/d83f5229-6bdf-485f-a200-fb456bd94efb) | ![login screen](https://github.com/PalisadoesFoundation/talawa/assets/109027247/46e14b56-8d6d-48d0-bb54-8b900abfdfdb) | ![logout dialog](https://github.com/PalisadoesFoundation/talawa/assets/109027247/d42e4c56-1b24-43c4-ad15-bc974cb3cda3) |

**Comment by GlenDsza** [comment]
Would like to work on this

**Comment by palisadoes** [comment]
That was true in January when we were focusing on tests and broken features. We can revisit this now.

**Comment by Azad99-9** [comment]
That's great @palisadoes I guess this opens up a scope for lot of new issues and improvement.
