### ISSUE TITLE
[Bug]: If User is in no Organization

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#249]
If member is in no organization then following error is thrown.

```
I/flutter (14223): GraphQL Errors:
I/flutter (14223): Cast to ObjectId failed for value "null" at path "_id" for model "Organization": Undefined location
E/flutter (14223): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (14223): #0      List.[] (dart:core-patch/growable_array.dart:254:60)
E/flutter (14223): #1      _OrganizationsState.getMembers
package:talawa/…/members/members.dart:83
E/flutter (14223): <asynchronous suspension>

```

**Comment by Sagar2366** [comment]
Please follow the guidelines while creating issues and PR's. Add snapshots/videos, observed and expected behaviour, steps tp reproduce the issue.

**Comment by Sagar2366** [comment]
How https://github.com/PalisadoesFoundation/talawa/issues/256 issue is different from this one ? Can you fix https://github.com/PalisadoesFoundation/talawa/issues/256 in same PR ? 
Avoid creating new issues/pr's for small fixes if not really required.

**Comment by sumitra19jha** [comment]
Ok @Sagar2366 Noted that.

**Comment by Sagar2366** [comment]
> Ok @Sagar2366 Noted that.

Should I close related PR for this https://github.com/PalisadoesFoundation/talawa/pull/252 ? Are you fixing both the issues - https://github.com/PalisadoesFoundation/talawa/issues/249 and https://github.com/PalisadoesFoundation/talawa/issues/256 in https://github.com/PalisadoesFoundation/talawa/pull/257 ?

**Comment by sumitra19jha** [comment]
PR #252 fixes the console error. I suppose it should be there as it is occurring on member page of organization which still will be in visible mode even if user is not part of anh organization at all.

**Comment by sumitra19jha** [comment]
Yes @Sagar2366 the PR #256 is fixing both the issue.
