### ISSUE TITLE
Create an offline detection mechanism(GSoC)

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2520]
**Is your feature request related to a problem? Please describe.**
Currently, Talawa lacks an offline detection mechanism. 

Like other social media apps, the application should support the following features:
1. Detect the mobile device network status.
2. Gracefully prompt the user about his network status.

**Describe the solution you'd like**
1. Develop a `ConnectivityService` to keep track of device network status.
2. Create UI components similar to `YouTube` to prompt the user about network status.

![offline](https://github.com/PalisadoesFoundation/talawa/assets/120930148/6c581d7a-610b-4ab2-b6c0-91e8457bff2a)
![online](https://github.com/PalisadoesFoundation/talawa/assets/120930148/8cfd41fd-a350-4a48-891f-50b5298f2064)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@palisadoes @Cioppolo14 kindly assign me this issue.

**Comment by Azad99-9** [comment]
https://github.com/PalisadoesFoundation/talawa/assets/120930148/0e5e7064-bb18-41a2-9bac-1b37232283ca

@palisadoes @noman2002 please have a look at this new offline detection snackbar UI and tell me if any changes are needed.

**Comment by palisadoes** [comment]
Sorry for the delay. This looks OK, but I'll defer to @noman2002 for the final go-ahead
