### ISSUE TITLE
Implement Venue Management and Booking System for Event PlugIn (GSoC)

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa#2522]
**Is your feature request related to a problem? Please describe.**

Yes, the current event management application lacks a comprehensive venue management feature. Without the ability to effectively manage venue information and bookings, organizations face challenges in planning and executing events.

**Describe the solution you'd like**

Basic CRUD capabilities to add, update, view, and delete venue information, including details such as name, capacity, description, and image URL.

**Additional context**
This feature will significantly enhance the functionality of our event plugin making it more attractive to organizations. It will streamline event planning, reduce administrative overhead, and improve the overall experience for event attendees. The implementation of this feature is crucial for maintaining efficient and effective event management operations.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@palisadoes please assign

**Comment by Cioppolo14** [comment]
@Dante291 Are you still workingon this?

**Comment by Dante291** [comment]
my exams are going on will start working on it right after it

**Comment by Cioppolo14** [comment]
@Dante291 Are you available to work on this now?

**Comment by Dante291** [comment]
Yup just got done with my end sem i have continued working on this
