### ISSUE TITLE
feat: Event Volunteer management (GSoC)

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa#2539]
**Is your feature request related to a problem? Please describe.**
add support for event volunteers

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RSN601KRI** [comment]
Hey @palisadoes @Dante291! 🙌

I saw the feature request about adding support for event volunteers and wanted to jump in! I believe it's a great idea to integrate volunteers, and I'd love to help out with this feature. 

Describe the solution you'd like:  
We could implement a user-friendly system where event volunteers can sign up, manage tasks, and track their contributions. It could also include a dashboard for organizers to assign roles and communicate easily with volunteers.

Describe alternatives you've considered: 
We could also explore creating a centralized database for volunteer applications and roles, but integrating it directly into our existing platform would streamline the process.

Approach to be followed (optional):
- Create a volunteer signup page  
- Add a role management system  
- Develop a communication channel for easy updates.

Kindly assign to me.

Thanks! 😊

**Comment by Dante291** [comment]
> Hey @palisadoes @Dante291! 🙌
> 
> I saw the feature request about adding support for event volunteers and wanted to jump in! I believe it's a great idea to integrate volunteers, and I'd love to help out with this feature.
> 
> Describe the solution you'd like: We could implement a user-friendly system where event volunteers can sign up, manage tasks, and track their contributions. It could also include a dashboard for organizers to assign roles and communicate easily with volunteers.
> 
> Describe alternatives you've considered: We could also explore creating a centralized database for volunteer applications and roles, but integrating it directly into our existing platform would streamline the process.
> 
> Approach to be followed (optional):
> 
> * Create a volunteer signup page
> * Add a role management system
> * Develop a communication channel for easy updates.
> 
> Kindly assign to me.
> 
> Thanks! 😊

kindly look for other issues which are not part of GSoC 2024
