### ISSUE TITLE
UI of the Newsfeed page 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#254]
the News Feed page requires a new UI .

I will be changing the Layout of the newsfeed page which will include rearranging the things.

**Comment by adithyaakrishna** [comment]
Hey @yasharth291 I'm working on this already

**Comment by yasharth291** [comment]
> Hey @yasharth291 I'm working on this already

News feed  #235

**Comment by yasharth291** [comment]
No worries you can see and bring some changes according to you and merge afterwards. My main change was in the layout.

**Comment by yasharth291** [comment]
Was there any issue related to your work?

**Comment by Sagar2366** [comment]
@adithyaakrishna please make sure you create issue to avoid work duplication.

**Comment by yasharth291** [comment]
@Sagar2366  can you please review my pr as i have to continue in the same branch to resolve #235

**Comment by yasharth291** [comment]
@adithyaakrishna  hey can you help me resolve some of my issues please.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna hey can you help me resolve some of my issues please. I have lots of them with me.

Yes Sure, I'll DM you over slack

**Comment by yasharth291** [comment]
na we can talk here

**Comment by yasharth291** [comment]
you can help me resolve #233

**Comment by Sagar2366** [comment]
@yasharth291 , please follow guidelines while creating issues/pr. Above issue description is not helping to understand what changes you will be adding as part of this issue.
