### ISSUE TITLE
Document all the Offline First Features developed so far as part of GSoC.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2548]
**Is your feature request related to a problem? Please describe.**
Currently the offline first features developed as part of GSoC project for the mobile application lack an extensive documentation support on talawa docs.

**Describe the solution you'd like**
Create markdown files explaining all the models, services, flows, features in the mobile app and add them to [talawa-docs](https://docs.talawa.io/)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Azad99-9** [comment]
@palisadoes please assign me this issue.

**Comment by Cioppolo14** [comment]
@Azad99-9 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Azad99-9** [comment]
@Cioppolo14 As this GSoC issue is high priority I have unassigned myself from the other issue. Now kindly assign me this issue.
