### ISSUE TITLE
MOBILE: Automatic Labeling for Dependencies, Security and Design Related Issues

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2555]
**Is your feature request related to a problem? Please describe.**

1. We spend a lot of time manually labeling issues that are created.
2. Automation will significantly reduce this overhead

**Describe the solution you'd like**

Using the `auto-label` GitHub action that we currently use: https://github.com/marketplace/actions/auto-label

1. Make configuration changes to the existing `issue.yml` file. 
1. Do not rename the existing `issue.yml` file.
1. **Dependencies**
    1. When the words `dependabot`, `dependency` or `dependencies` are in the body of the issue 
    2. Add the labels `dependencies`, `security` and `good first issue`
1. **Security**
    1. When the word `security` are in the body of the issue 
    2. Add the label `security` and `good first issue`
1. **Design**
    1. When the words `layout`, `screen`, `design` or `figma` are in the body of the issue 
    2. Add the label `ui/ux` and `good first issue`

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above
- No other functionality must be affected

**Additional context**

Related Issues. The same person must be assigned to both:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/2256
- https://github.com/PalisadoesFoundation/talawa/issues/2555

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VanshikaSabharwal** [comment]
@palisadoes Please assign me this issue. I am willing to modify the issue.yml file to automatically label issues based on the specified keywords

**Comment by VanshikaSabharwal** [comment]
i have raised PR

**Comment by VanshikaSabharwal** [comment]
I have raised PR and i am working on it. #2557

**Comment by palisadoes** [comment]
unassigning. inactivity

**Comment by heropj** [comment]
Hi @palisadoes, I would like to work on this issue. I can make the necessary changes to the issues.yml file as described and resolve it efficiently. Could you please assign this issue to me?
Thank you!

**Comment by SXUBXAM** [comment]
Hi @palisadoes,

I hope this message finds you well. I have forked the repository on my GitHub, resolved the issue, and successfully tested it in my environment. Everything is functioning perfectly. Would you kindly assign this task to me?

Thank you!

![Screenshot from 2024-10-17 12-20-47](https://github.com/user-attachments/assets/52475629-2958-43a4-95ab-ec14b84e8677)

**Comment by ARYPROGRAMMER** [comment]
@palisadoes can i work on this. Seems like I have an optimised approach for this
