### ISSUE TITLE
Timezone Middleware with Apollo

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa#2558]
**Is your feature request related to a problem? Please describe.**
Implement a middleware which converts the time depending on user's app.

**Describe the solution you'd like**
1) For all the requests, we convert all UTC time from DB to client.
2) For all the mutations, we convert all local to UTC time via middleware.

**Describe alternatives you've considered**
Saving and changing all the components depending on timezone.

**Additional context**
Reference: https://github.com/PalisadoesFoundation/talawa-admin/pull/2234

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@pranshugupta54 Are you still working on this?

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by pranshugupta54** [comment]
It's almost done, making a PR.
