### ISSUE TITLE
[Bug] Profile Page error if user is not part of any organization.

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#256]
### Description
The issue is observed in log while opening the Profile Page. The fact this issue occurs is because the user is not part of any organization at all. When user navigate to the profile screen, a query is being made using the organization_id whose value is null at the time of call leading to this issue.

**Observed Behaviour**
```
GraphQL Errors:
I/flutter (21307): Cast to ObjectId failed for value "null" at path "_id" for model "Organization": Undefined location
```

**Expected Behaviour**
No console error is observed as request is made only when Organization Id exists.

**Comment by Sagar2366** [comment]
@sumitra19jha, follow proper guidelines while creating issues and pr's. Add proper description, observed and expected behaviour, snapshots/videos before and after, fix added, environment details.

**Comment by sumitra19jha** [comment]
Ok @Sagar2366 
It's just that this error has no effect on user interface part. The ui will not at all be effected. It was displayed on console, so ended up pasting the console log rather than snapshot. 

But sorry for causing you trouble. Will surely take care from next time and will immediately change all my PR based on the given guidelines.

**Comment by sumitra19jha** [comment]
@Sagar2366 I have modified this issue details and also the PR details #257
