### ISSUE TITLE
Event Agenda management (GSoC)

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa#2577]
**Is your feature request related to a problem? Please describe.**
feature for agenda management

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@palisadoes please assign

**Comment by noman2002** [comment]
@Dante291 Updates in this one ??

**Comment by Dante291** [comment]
> @Dante291 Updates on this one ??

its merged, this can be closed
