### ISSUE TITLE
Error with registered events if events.length is not 0

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#258]
Although , this issue doesn't occur for every registered member. But I saw this in 3 or 4 members , I am working on it. I just need to know if this isn't a duplicate issue.
![Screenshot_20210314-190930](https://user-images.githubusercontent.com/51524156/111070780-3bcdd380-84f9-11eb-9324-74089f62a546.png)

**Comment by pr4nshul** [comment]
@Sagar2366 @yasharth291 If you can assign me this , so that no duplicate work takes place.

**Comment by pr4nshul** [comment]
Ok, i was just looking into the issue and I found out this has some more underlying issues. When userEvents length =0 , no error occurs but if it is not 0. Then the issue comes up.

**Comment by yasharth291** [comment]
I am not a maintainer :)

**Comment by pr4nshul** [comment]
Ok , but I hope you would definitely know if this is a duplicate issue or not xD

**Comment by Sagar2366** [comment]
@pr4nshul , please add description to the issue and PR. Add steps to reproduce the issue, before and after adding changes video.

**Comment by pr4nshul** [comment]
Ok, I am on it. Although I have a description of the PR, I am going to upload the video before and after the changes.

**Comment by pr4nshul** [comment]
This is the error that occurs -

https://user-images.githubusercontent.com/51524156/111196516-6005df00-85e3-11eb-8777-161b9d85e69d.mp4

This is after the resolution-

https://user-images.githubusercontent.com/51524156/111196593-7875f980-85e3-11eb-80be-221a541ad7b5.mp4

Steps to reproduce -

Go to members tab, select an user if that user have 0 events then no error will occur . But if the user has more than 0 but the value of the event is null this error will take place. The reason that I have interpreted is that the event was there, but later it was completed hence was deleted but the user eventList still had the id which was referencing to null. So, If the eventList item is null I am setting the eventList = [] .

**Comment by pr4nshul** [comment]
I printed the length of eventList for various members in addition I also tried to print the event List , I also though if I use string interpolation $ , null would be printed as it is , but the issue with that was the length of eventList which wasn't chainging. So for one user , 54 times null list view was built. As, i have mentioned in the PR. This is a much more than a bug as a similar issue is coming with tasks where description is being printed null. As there string interpolation is used hence error isn't shown. This PR could be used as a placeholder and will work fine for most of the cases but would leave some edge cases. But I would suggest that we should work on resolving it properly, that when the event is deleted or completed the id is also deleted from the eventList. But I couldn't do it right now , because I would need some help in understanding the codebase better. Additionally, this is my first type working on someone else's flutter project so I am learning on the go about the app.

**Comment by Sagar2366** [comment]
@pr4nshul can you test this on latest master ? don't see this error any more

**Comment by pr4nshul** [comment]
Ok let me get back to you.

**Comment by pr4nshul** [comment]
![Screenshot_20210317-235322](https://user-images.githubusercontent.com/51524156/111518792-6da29c80-877c-11eb-90ff-677d4f264d55.png)

@Sagar2366 
It's still a issue, you won't get this issue on every user, but if he ever registered for an event , you would. You can try on the same user that I have in this image. Another user Geetansh monga you can see the error there as well.
Sorry for these big screenshots I can't resize them otherwise the image is going corrupt for some reason.

**Comment by ayushs136** [comment]
I have fixed this issue?
should I make a PR?

**Comment by pr4nshul** [comment]
@ayushs136 It was assigned to me . Please don't make duplicate work if there is a issue with my PR then you may.

**Comment by ayushs136** [comment]
Okay, got it.

**Comment by pr4nshul** [comment]
As you can see I have already made an pull request #283

**Comment by ayushs136** [comment]
Hey @pr4nshul, I see you have an unapproved PR? and commits you made wouldn't really fix it.

**Comment by pr4nshul** [comment]
Well it's unapproved as maintainers haven't reviewed it yet. And if they decide , that doesn't fix it and your fix is better. I wouldn't mind if the issue is being resolved.

**Comment by ayushs136** [comment]
Okay! Got it. Peace! btw who is the maintainer? @pr4nshul

**Comment by pr4nshul** [comment]
Sagar is one of them whom I have interacted with. There are more , you can join the slack channel for such queries.
