### ISSUE TITLE
Feature Request: Remove the code which updates the docs because workflow is shifted to talawa_docs repo

### ISSUE THREAD

**Issue by gautam-divyanshu** [PalisadoesFoundation/talawa#2589]
**Is your feature request related to a problem? Please describe.**
code cleanup because it shifted to talawa_docs

- https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/.github/workflows/pull-talawa-mobile-docs.yml 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@gautam-divyanshu 

1. Can you update the talawa-docs repo to have one YAML file for all cron jobs?
2. We also need one YAML file there for all PRs just like the other repositories. The authorized file check functionality must be migrated there too.
3. This will help with consistency and ease of troubleshooting
