### ISSUE TITLE
(Bug) App throws error on Login and gets stuck

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#259]
**Issue Description**
When the user tries logging into the app it throws an error and stops. However, on re-running the app it starts from the Events page which means the user gets logged in successfully. 

**Screen-cast**

https://user-images.githubusercontent.com/56952811/111071315-9831f280-84fb-11eb-9c84-541f9afeaf02.mp4

**Willing to work on this?**
Yes. It would be great if we can discuss this below. I'll open a PR regarding the same.

**Comment by yasharth291** [comment]
@CoderMayhem  please try to run the app by putting the URL first. As it can be seen in the video you are not typing the URL in the given field.

**Comment by CoderMayhem** [comment]
The error persists regardless of the fact that URL is entered or not. 

https://user-images.githubusercontent.com/56952811/111071826-ed6f0380-84fd-11eb-8813-2aab92f671fe.mp4

**Comment by yasharth291** [comment]
the same problem came to me. it is because you are using different URL different for the signup and different for login. That was what i get to know when i was getting same error. Other things @Sagar2366 sir can see

**Comment by CoderMayhem** [comment]
Closing this issue as the related PR has been merged.
