### ISSUE TITLE
Fund raising campaigns (GSoC)

### ISSUE THREAD

**Issue by Dante291** [PalisadoesFoundation/talawa#2593]
**Is your feature request related to a problem? Please describe.**
feature for making pledges/donation 

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dante291** [comment]
@palisadoes please assign

**Comment by palisadoes** [comment]
@Dante291 Can this issue be closed now?

**Comment by Dante291** [comment]
@palisadoes Yes
