### ISSUE TITLE
Write Unittests for `lib/models/user/user_info.g.dart`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2604]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

### PR Acceptance Criteria

1. When complete this file must show **100%** coverage when merged into the code base.
1. [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/?displayType=list)
1. CodeRabbit must approve all your changes to the test file(s) and the file(s) under test
1. The PR will show a report for the code coverage for the file you have added. You can use that as a guide
1. No functionality must be removed to achieve this goal

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by youhaveme9** [comment]
Hey! @palisadoes 
I would like to work on this issue, please assign this to me
Also I have a doubt that what should be the name of the test files for *.g.dart?
Should it be `user_info_g_test.dart`?
