### ISSUE TITLE
Write Unittests for `lib/views/after_auth_screens/feed/organization_feed.dart`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2622]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

### PR Acceptance Criteria

1. When complete this file must show **100%** coverage when merged into the code base.
1. [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/?displayType=list)
1. CodeRabbit must approve all your changes to the test file(s) and the file(s) under test
1. The PR will show a report for the code coverage for the file you have added. You can use that as a guide
1. No functionality must be removed to achieve this goal
1. All tests must be valid and truly test the code base

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by xkaper001** [comment]
I noticed that this issue is unassigned, and I'd love to work on it! 
Could you please assign this issue to me?

Thank you!

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by Cioppolo14** [comment]
@Hemant-05 Have you watched our youtube videos and read the setup guidance on github? https://youtu.be/YpBUoHxEeyg?si=Plzv-p2qyGi6ilTr

**Comment by xkaper001** [comment]
Hey @Hemant-05, I too faced some issues as well during the setup. If you have watched the videos provided above and are still facing the issue. I'll help you out. 
Please be specific for the issues you're facing. Also I am using flutter `3.22.3` with dart `3.4.4`

**Comment by xkaper001** [comment]
@noman2002 pls review #2655
