### ISSUE TITLE
Filepicker plugin causing lot of issues

### ISSUE THREAD

**Issue by AniketSindhu** [PalisadoesFoundation/talawa#264]
Issues like this
![image](https://user-images.githubusercontent.com/57598532/111072379-5eafb600-8500-11eb-89b7-1148ac1cca87.png)

And sometimes it is causing the issue like file called on null.

# Will you be working on it?
Yes creating a PR fixing this

**Comment by Sagar2366** [comment]
@AniketSindhu please follow guidelines while creating issues and pr's.
Add meaningful title, description, observed and expected behaviour, steps to reproduce the issue, fix added, snapshots/video showing visuals of before and after adding changes.

**Comment by AniketSindhu** [comment]
I have submitted a PR for this #276 already
