### ISSUE TITLE
Password strength bar dont update while we type password

### ISSUE THREAD

**Issue by AniketSindhu** [PalisadoesFoundation/talawa#266]
https://user-images.githubusercontent.com/57598532/111072748-ed710280-8501-11eb-8d5e-bb0ce4607711.mov

**Comment by Raunakk02** [comment]
Duplicate of #210. 
I already fixed this issue and already submitted a PR

**Comment by AniketSindhu** [comment]
@Raunakk02 great! There are a lot of issues and your pr was not merged so I got confused
