### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by HiRoaR2002** [PalisadoesFoundation/talawa#2665]
Hey Community 
I am a newbie and wanted to contribute in Palisadoes Foundation's Talawa project but i am encounter an version control error which is needed to be fixed in installation doc as well
The SDK requirement failed as the given range is :
environment:
  sdk: ">=2.17.0 <=3.4.4"

But the error generated requires '3.1.0' version(minimal)

![Screenshot (73)](https://github.com/user-attachments/assets/2227fac7-3d54-4c01-80c2-cf8f40021d06)

**Comment by HiRoaR2002** [comment]
@palisadoes can you please guide me through as well

**Comment by Cioppolo14** [comment]
@HiRoaR2002 We appreciate you being here! Please check our slack channel, that is a great place to ask the community questions.  I am going to close this PR.
