### ISSUE TITLE
[Improve UX] "Set URL" should close the on-screen keyboard

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#269]
### Current Scenario:
The `Set URL` button on the **Home page** doesn't close the on-screen keyboard when pressed. 

### Proposed improvement:
On clicking the `Set URL` button, it should close the on-screen keyboard. Saving user from the time-consumed on pressing the back button on the device to close the keyboard.

_Please assign this to me, I'll be more than happy to work on this issue._

**Comment by CyberWake** [comment]
Resolved the issue and launched the PR.

**Comment by CoderMayhem** [comment]
Which PR @CyberWake ? Kindly mention here.

**Comment by CyberWake** [comment]
I was just pull from the master to avoid merge conflicts.😅
