### ISSUE TITLE
[Enhancement] Optimizing dialog box for iOS

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#270]
Every Dialog Box until now is created with a Ui interface displayed on android. This issue deals with the fact that dialog box can be optimised for making sure of the iOS experience on iOS Devices.

Following dialogue box can be optimized:
1. Logout Dialog
2. Leave organization dialog
3. Join Organization dialog

The enhancement will be great thinking from iOS perspective.

**Comment by sumitra19jha** [comment]
@Sagar2366 Should I reopen this issue and the PR made for this?

**Comment by CyberWake** [comment]
May I correct you with the title currently flutter doesn't support the metal for iOS there is no way to possible to optimize the dialog. I feel what you current might be addressing is change the current material design alert dialog to cupertino style. Correct me if I am not wrong.

**Comment by sumitra19jha** [comment]
If the Platform is iOS then we will be showing showCupertinoDialog instead of showDialog thats why I name the title as optimising dialog box for iOS as PR will deal with showCupertinoDialog.

**Comment by CyberWake** [comment]
I guess this would just change the design from material to cupertino which is preferred design style for iOS.

**Comment by CyberWake** [comment]
BTW there are already dedicated files added by me for alert dialogs. ```alert_dialog_box.dart``` you can reuse this one depending upon the platform.

**Comment by sumitra19jha** [comment]
> I guess this would just change the design from material to cupertino which is preferred design style for iOS. 

That is what the Issue and PR is all about

**Comment by sumitra19jha** [comment]
> BTW there are already dedicated files added by me for alert dialogs. ```alert_dialog_box.dart``` you can reuse this one depending upon the platform.

I checked the current file and it is still using showDialog. So thought about using if else statement based on platform and show dialoge accordingly. But now will surely look into alert_dialogue first and then will decide accordingly.
