### ISSUE TITLE
[Proposal] - Add dropdown for different organizations instead of URL

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#290]
**Description:** What if we can create a dropdown kind of option to select the URL, the different organizations have to register and then their Name will be added as an option to the dropdown, we can create a basic UI in Talawa-Api for this and once an org. registers with their Name and URL, the Org. Name will be shown as n option in the Talawa App

**Comment by Sagar2366** [comment]
I would advise to move discussion topics in slack and take mentors advice in them instead of directly creating issues on GitHub.
