### ISSUE TITLE
Password show/hide button removed from Registration form

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#291]
**Issue Description**
In recently made changes to the registration form someone removed the password show/hide feature from the password field. It needs to be added again and the UI of Login form needs to be updated as per the UI of the Registration form.

**Working on this?**
Fixed. Linking PR below.

**Comment by Sagar2366** [comment]
This is not good. Can you please check which PR reverted this ?

**Comment by CoderMayhem** [comment]
It was done in PR #238 in [this](https://github.com/PalisadoesFoundation/talawa/pull/238/commits/ce789957d0b97a02757871365c638525c0b358a6) commit . @Sagar2366
