### ISSUE TITLE
Etiquette - Low Quality Issues and PR's

### ISSUE THREAD

**Issue by jordanliu** [PalisadoesFoundation/talawa#294]
Hey everyone!

The maintainers of Palisadoes Foundation are very happy and appreciative of the recent influx of interest for Talawa.

We know everyone is anxious and are excited to contribute, but we've noticed an increase in duplicate and low quality issues and PR's.

Please have a look at our [contributing guide](https://github.com/PalisadoesFoundation/talawa/blob/8b47ab1c97c3a7ee1b8352cbcfaad9bf56b89b2e/CONTRIBUTING.md) as reference to how we operate.

Just some reminders:
1. Please refrain from creating a PR without a linked issue. Every PR must have a linked issue.
2. Check to see if the issue you're creating has already been created to reduce duplicates
3. Please be patient if your issue or pr hasn't been reviewed, we're working on getting them reviewed as fast as we can.

For any other questions, feel free to reach out and communicate with other contributors on [Slack](http://slack.palisadoes.org)

Once again, we're grateful for all the support we have been receiving.

Jordan,
Palisadoes Foundation

**N.B:** We'll be flagging accounts that have a consistent pattern of spamming LQ posts

**Comment by sumitra19jha** [comment]
Noted 👍 
Will surely take care of this

**Comment by imraghav20** [comment]
@jordanliu Slack only allows to join the workspace with `@palisadoes.org` domain mail. How can I contact the workspace administrator for an invitaton on my personal mail?

**Comment by imraghav20** [comment]
I am a new contributor. I have managed to set up the repo and even install the app but unable to understand how to log in. I would be glad if someone could guide me.

**Comment by arteevraina** [comment]
Hi @imraghav20 ! You can join slack even if you don't have `@palisadoes.org` domain mail. Checkout this link https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-oz2w954k-xMjzQ4Q3zfEIEJcOF6KdmQ.
Also, remember to read the contributing guidelines before sending patches. Also, discuss any potential issue with the mentors in the slack's `#gsoc-newissues` channel.

For signup you need to verify URL https://talawa-graphql-api.herokuapp.com/graphql use this and you will be good to go.

**Comment by imraghav20** [comment]
Thank you very much @arteevraina

**Comment by mihdas** [comment]
> Hi @imraghav20 ! You can join slack even if you don't have `@palisadoes.org` domain mail. Checkout this link https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-oz2w954k-xMjzQ4Q3zfEIEJcOF6KdmQ.
> Also, remember to read the contributing guidelines before sending patches. Also, discuss any potential issue with the mentors in the slack's `#gsoc-newissues` channel.
> 
> For signup you need to verify URL https://talawa-graphql-api.herokuapp.com/graphql use this and you will be good to go.

even this link does not let you join the slack without a `@palisadoes.org` account

**Comment by palisadoes** [comment]
> > Hi @imraghav20 ! You can join slack even if you don't have `@palisadoes.org` domain mail. Checkout this link https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-oz2w954k-xMjzQ4Q3zfEIEJcOF6KdmQ.
> > Also, remember to read the contributing guidelines before sending patches. Also, discuss any potential issue with the mentors in the slack's `#gsoc-newissues` channel.
> > For signup you need to verify URL https://talawa-graphql-api.herokuapp.com/graphql use this and you will be good to go.
> 
> even this link does not let you join the slack without a `@palisadoes.org` account

@mihdas [Please use this link, as the previous one expired.] (https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-qa1hbp06-GJrilN35oIYfddC9Vf0kRA)

**Comment by Pavel401** [comment]
Hi, I tried tto follow that joining link ,but its asking for verified mail id to join.Can i know how can i join ?.

**Comment by palisadoes** [comment]
> Hi, I tried tto follow that joining link ,but its asking for verified mail id to join.Can i know how can i join ?.

Use the slack link in the original post. The others have expired.

**Comment by umang-sinha** [comment]
Hey @palisadoes , I am facing some difficulties while trying to setup a local development environment. I would need some help from fellow contributors. However none of the slack links here seem to be working. Can you provide some other link?

**Comment by palisadoes** [comment]
The link in the original post works.

**Comment by umang-sinha** [comment]
Thank you. The link wasn't working on my wifi connection for some reason. Changing my network worked.

**Comment by palisadoes** [comment]
- Deleted posts related to an outdated slack link that was causing a lot of confusion. 
- Recreated a new issue with updated information.
