### ISSUE TITLE
[Discussion] [Enhancement] Most of the pages keep loading when data is empty.

### ISSUE THREAD

**Issue by AniketSindhu** [PalisadoesFoundation/talawa#298]
I am thinking of showing some error screen after some fixed time like 10 seconds. Because infinite loading is not good for user experience. 

I am willing to work on this if maintainers are ok with this approach

**Comment by AniketSindhu** [comment]
@CyberWake Should I create pr for this?

**Comment by CoderMayhem** [comment]
Any updates on this @AniketSindhu ?

**Comment by AniketSindhu** [comment]
@CoderMayhem code is on freeze. So if I make PR on this now it will not be merged so I am justing waiting for it to unfreeze.

**Comment by Sagar2366** [comment]
@AniketSindhu you can start working on this issue.

**Comment by AniketSindhu** [comment]
@Sagar2366 PR #456 submitted.
