### ISSUE TITLE
Enhancement in the chat Text field 

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#299]
The chat text Field in the chat navigation bar can be improved so that when the text reached the end of the text Field it moves to the next line, and also add a decoration to the text Field
![Screenshot_20210315-034316](https://user-images.githubusercontent.com/50530242/111097378-aefb3800-8541-11eb-9f8c-f8320efdd95f.png)

**Comment by OnyemaAnthony** [comment]
Please can I work on this?

**Comment by Sagar2366** [comment]
Good observation. You can start working on this. Looking forward to see your contribution to this project.

**Comment by OnyemaAnthony** [comment]
Ok am already working on it,I will send a PR soon

**Comment by CyberWake** [comment]
What's the update on this issue?

**Comment by OnyemaAnthony** [comment]
@CyberWake I have sent a PR already

**Comment by CyberWake** [comment]
thank you @OnyemaAnthony we are revamping the UI. You may look into the designs in the talawa-design channel on slack and this issue will be resolved by the #850

**Comment by CyberWake** [comment]
@palisadoes sir we can close this issue as this will be handled now in #850 for the UI revamp.
