### ISSUE TITLE
[Enhancement] pull to refresh is always on top after scrolling down too. 

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#300]
We can only show pull to refresh when user scrolls up.

Can I work on this issue?

https://user-images.githubusercontent.com/43651504/111097767-2643c280-8568-11eb-8b23-6df220a928fe.mp4

**Comment by GMGOG** [comment]
@Sagar2366 @DeltaHarbinger please assign this to me.

**Comment by Sagar2366** [comment]
Will get fixed in https://github.com/PalisadoesFoundation/talawa/issues/334
