### ISSUE TITLE
[bug] Comment Screen 

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#301]
hint text: "leave a comment..." is not center aligned and text field should be wrapped in intrinsicHeight widget.

Can someone assign this to me?

![WhatsApp Image 2021-03-15 at 8 33 19 AM](https://user-images.githubusercontent.com/43651504/111098450-8424da00-8569-11eb-830d-cdfa9b08e3c2.jpeg)

**Comment by yasharth291** [comment]
hello same issue is being solved by me under #235 . @Sagar2366 please look into this.

**Comment by GMGOG** [comment]
i guess not, I am talking about the post screen here.

**Comment by Sagar2366** [comment]
Will get fixed as part of https://github.com/PalisadoesFoundation/talawa/issues/235
