### ISSUE TITLE
[bug] Event registered with an old date.

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#305]
Event registered with date 19 January 1970.

https://user-images.githubusercontent.com/43651504/111100127-0e227200-856d-11eb-9231-233115a38a2b.mp4

**Comment by Sagar2366** [comment]
Need more information about this issue.

**Comment by GMGOG** [comment]
> Need more information about this issue.

When I logined in my account. It was showing 3 already registered events with old dates. I'm unable to register new events and when I all of them. It's showing a infinite loading spinner and I'm not able to add events also.

**Comment by Sagar2366** [comment]
Will get handled through https://github.com/PalisadoesFoundation/talawa/issues/426
