### ISSUE TITLE
[bug] Not able to switch organisations after leaving one of them. 

### ISSUE THREAD

**Issue by cyber-venom003** [PalisadoesFoundation/talawa#307]
When we are a part of multiple organizations and we leave one of them by using the profile screen attached below, we get next screen which shows organization name = null. We have to manually switch the organizations after that. 

Current organization = Amazon
![Screenshot_1615763155](https://user-images.githubusercontent.com/58390399/111101702-7888e180-8570-11eb-9fbc-54e5352df55b.png)
When we leave it, it doesn't switch automatically to another joined org, organization name shows null. We have to manually switch it by pressing 'Switch organization' 
![Screenshot_1615763174](https://user-images.githubusercontent.com/58390399/111101708-7aeb3b80-8570-11eb-8baa-9c602913e588.png)

**Comment by CyberWake** [comment]
Please look into #249 this is also the same issue.

**Comment by CyberWake** [comment]
Also look into the PR #257

**Comment by cyber-venom003** [comment]
> 
> 
> Please look into #249 this is also the same issue.
@CyberWake 
I guess, not, because I didn't encounter the same output on console after doing this. Both are almost similar bugs but their reproduction procedure is completely different. My side is, we are not able to switch the orgs automatically after leaving one.

**Comment by Sagar2366** [comment]
If user is part of multiple organization and left current set organization, then one of organization should get set out of remaining organization. 
Adding snackbar is not helping here @cyber-venom003.

**Comment by cyber-venom003** [comment]
@Sagar2366 Adding snackbar was a part of issue #176 😅

**Comment by Sagar2366** [comment]
Since we are planning to remove leave organization and switch organization option if user is not part of any organisation, this case will never come.

**Comment by cyber-venom003** [comment]
> 
> 
> Since we are planning to remove leave organization and switch organization option if user is not part of any organisation, this case will never come.

Ok cool, is there any issue opened for it? Or should I open it?

**Comment by pr4nshul** [comment]
I would like to add something, after leaving a particular organization if I switch to another. What I observed is I was part of the same organisation which I left, this maybe this issue is due to all 3 organisation I was part of were named "**test org**". Initially I was part of an organisation which had like 15+ members , But the only organisation I am left with even after leaving it twice is the one in which the same 3 members are there and I left the one with 15+ members even if I didn't intend to.

**Comment by pr4nshul** [comment]
There is also a chance of bad state management here , I was in no organisation but still 3 member showed up until I pulled to refresh.

**Comment by cyber-venom003** [comment]
Ya, this also occured with me @pr4nshul .

**Comment by CyberWake** [comment]
> > Please look into #249 this is also the same issue.
> 
> @CyberWake
> I guess, not, because I didn't encounter the same output on console after doing this. Both are almost similar bugs but their reproduction procedure is completely different. My side is, we are not able to switch the orgs automatically after leaving one.

I have implemented the same. Please review #257

**Comment by CyberWake** [comment]
> There is also a chance of bad state management here , I was in no organisation but still 3 member showed up until I pulled to refresh.

This won't occur I guess as I am updating the preference and the providers do the same everwhere

**Comment by cyber-venom003** [comment]
@CyberWake I reviewed the file changes in PR #257, and I guess it is solved now, @Sagar2366 can you please confirm if this issue needs to be closed?

**Comment by Sagar2366** [comment]
Issue is fixed now.
