### ISSUE TITLE
Enhancement in the profile screen

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#309]
When the user does not belong to any organization yet it's shows null as there organization,I want to display an appropriate message,also on the update profile icon,I want to change it to update icon instead of the person icon
![Screenshot_20210315-053153](https://user-images.githubusercontent.com/50530242/111104201-68f9a080-8550-11eb-8c06-ed84e00980ea.png)

**Comment by CyberWake** [comment]
Please look into issue #256 it's the same.

**Comment by OnyemaAnthony** [comment]
Okay let me close the issue
