### ISSUE TITLE
Improving The UI of Login Page

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#312]
**Description:**
The Borders and Icon Color in the Login page aren't properly visible which is not a good UI design, so for now, it can be changed to a color like white to make it more visible

**Problem:**
<img src="https://user-images.githubusercontent.com/23498248/111121214-60c25500-8592-11eb-871f-833265e0e96b.png" width="150" height="300" />

**Comment by pr4nshul** [comment]
Are you working on this @adithyaakrishna ?

**Comment by SatYu26** [comment]
I would like to work on this.

**Comment by adithyaakrishna** [comment]
@pr4nshul @SatYu26 I'm working on it

**Comment by sumitra19jha** [comment]
Hey @adithyaakrishna if you want to optimize the colors and want to decide which background box color will be good with foreground, you can refer this website - http://colormind.io

**Comment by adithyaakrishna** [comment]
Hi @sumitra19jha , sure I will go through it. I usually refer behance.net or dribbble.com.
Also, we can discuss regarding the revamping of the whole UI.  As for now, I had thought of implementing a complete Design System for the Palisadoes Foundation and creating it in such a way that it can be implemented for other projects like

- https://github.com/PalisadoesFoundation/talawa
- https://github.com/PalisadoesFoundation/talawa-api
- https://github.com/PalisadoesFoundation/talawa-docs
- https://github.com/PalisadoesFoundation/pattoo-mobile

and others also.

**Comment by CoderMayhem** [comment]
@adithyaakrishna this issue has already been addressed in PR #292  opened by me. You can add on to it if you want once it gets merged.

**Comment by adithyaakrishna** [comment]
@CoderMayhem , as for now it doesn't improve the UI by a great extent, just changes the colors and improves the visibility

**Comment by CoderMayhem** [comment]
That's what I am saying, the exact same changes have already been made so there is no point having another issue opened for the same. @Sagar2366 and other maintainers have already mentioned multiple times to avoid duplicate issues. If you want to implement further changes to the UI you can do that once #292 gets merged.

**Comment by Sagar2366** [comment]
Closing this as fix has been added with https://github.com/PalisadoesFoundation/talawa/pull/292 PR.
