### ISSUE TITLE
[ User Experience Improvement] Pages being stacked after switching organisations

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#313]
This is a minor issue. When we switch organisations and save and then hit the back button we are routed back to switch organisations page. Hence, we are not being routed to the homepage but rather the home page is being pushed over switch page.
<img src="https://user-images.githubusercontent.com/51524156/111133776-e77e2e80-85a0-11eb-8d87-0c29aedd2098.png" height="300" width="150">
Press saved
<img src="https://user-images.githubusercontent.com/51524156/111133812-f238c380-85a0-11eb-8e86-d8b5bf0107ce.png" height ="300" width="150">
Hit back on phone
<img src="https://user-images.githubusercontent.com/51524156/111133832-f9f86800-85a0-11eb-9a2e-4fc2b695f987.png" height ="300" width="150">

**Comment by pr4nshul** [comment]
I am working on it, I couldn't find a similar issue hoping it's not a duplicate

**Comment by adithyaakrishna** [comment]
@pr4nshul , `<img src="<YourImageURL>" width="150" height="300" />`
Put the images like this, so that the issue with screenshots can be viewable easily instead of these large Screenshots

**Comment by pr4nshul** [comment]
Ok, thanks for the tip !

**Comment by pr4nshul** [comment]
I am closing this issue, what I found after looking over the app is here persistent_tab_view pkg is used everywhere. So, i went to their documentation and found they don't have anything similar to pushReplaced which is available in core flutter pkg as Navigator.pushReplacedNamed. If we have to use this for making the app more efficient we need to do it everywhere otherwise a different issue will arrive. Hence, working on it really needs full understanding of the code base imo.
