### ISSUE TITLE
[UI Improvement] Using Hero widget for transition between NewsFeed and NewsArtcile.

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#316]
<p float="left">
<img src="https://user-images.githubusercontent.com/47498552/111138997-9a04c000-85a6-11eb-8adc-9436b1372cbb.gif" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/47498552/111139481-2fa04f80-85a7-11eb-8227-2d52c7242e1d.gif" 
width="200" height="400" />
</p>

Current Transition - - - - - - - - - New Transition with Hero widget

Also with the Dynamic Tags (Even works when every post will have its own Image).

**Comment by yasharth291** [comment]
please can you wait for a little just today you can add after i solve #235

**Comment by rutvik11062000** [comment]
Actually, the PR->travis build ✅ is already done.

There is not much change, though, only a few parameters are changed

**Comment by Sagar2366** [comment]
As discussed in PR, this feature is not required.
