### ISSUE TITLE
[bug] Text overflow in Members Page

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#320]
<img src = "https://user-images.githubusercontent.com/47498552/111144429-14384300-85ad-11eb-8252-de2237e4798c.jpeg" widht=200 height=400/>

**Comment by rutvik11062000** [comment]
I've checked other PR's if it is overlapping kindly tell me, I'll remove it.

**Comment by CyberWake** [comment]
Please look into issue #317 and the PR raised for the same #319. You could review it if there's a better approach please add a comment in the review✌✌.
