### ISSUE TITLE
Deprecated Widget Used

### ISSUE THREAD

**Issue by SatYu26** [PalisadoesFoundation/talawa#321]
Hello,
1. I just noticed that many deprecated widgets were used and one of them was "List". (API.dart line 14.)
This is not creating an issue right now but might give someday and there are changes that empty list will be returned many times.
So I think we should change it to:
`var joinedOrgs = List<SwitchOrg>.filled(length, fill);`

2. FlatButton is also deprecated: We should use TextButton instead of that. (addTaskDialog.dart  Line 57 and 61)

3. RaisedButton is deprecated: We should use ElevatedButton instead of that. (events.dart  Line 371)

There are many more like pickImage and autoValidate. If granted permission I would like to start working on this right away.

**Comment by CyberWake** [comment]
Autovalidate for the form is fixed PR under review for register form and create organization form.

**Comment by SatYu26** [comment]
> Autovalidate for the form is fixed PR under review for register form and create organization form.

Yeah sure then I can work on other deprecated widgets.

**Comment by CyberWake** [comment]
I guess the issue is already raised please check
