### ISSUE TITLE
[Bug/Enhancement] Remove Pageview for login screens.

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#322]
**Issue description:** 
As of now on the logic screen, user can swipe between the url screen and login, register pages. This has been implemented with PageView. With the login and create an account buttons on there being on the url screen, it makes more sense to let only those buttons navigate to those screens rather than the swipe. This will also include fixing the bug that there is no back button on login and signup pages to get back to the url screens.
**Issue severity:** 
medium
**Environment details:** 
would require major changes in the file https://github.com/PalisadoesFoundation/talawa/blob/master/lib/views/pages/login_signup/login_page.dart and also other changes in the login_signup folder.
**Observed behaviour:** User can wipe on the login url setting screen to login and signup pages though there are buttons present to navigate to them; there are no back buttons on the login/singup screens to reach back to the url setting screen.
**Expected behaviour:** 
after the change, the user will no longer be able to swipe, and would be able to reach back to the Url screen with back buttons only. 
I am willing to work on this issue.

**Comment by adithyaakrishna** [comment]
This is a great one @Swayam221 🎉

**Comment by jordanliu** [comment]
Assigned

**Comment by Sagar2366** [comment]
@Swayam221 instead of saving form details.
Can you disable swipe for signup/login ? 
Flow should be : Provide valid organization URL -> Click on Set URL -> Click on signup/login button to proceed.
Also update issue description for the same.

**Comment by Swayam221** [comment]
> @Swayam221 instead of saving form details.
> Can you disable swipe for signup/login ?
> Flow should be : Provide valid organization URL -> Click on Set URL -> Click on signup/login button to proceed.
> Also update issue description for the same - issue template (https://github.com/PalisadoesFoundation/talawa/tree/master/templates)

@Sagar2366 are we sure we want the wipe disable? because if we do that, once the URL is set and we press, lets suppose, the signup button, we wont be able to navigate back to the setURL page at all, which means it will be impossible to change the URL once set!

**Comment by Sagar2366** [comment]
> > @Swayam221 instead of saving form details.
> > Can you disable swipe for signup/login ?
> > Flow should be : Provide valid organization URL -> Click on Set URL -> Click on signup/login button to proceed.
> > Also update issue description for the same - issue template (https://github.com/PalisadoesFoundation/talawa/tree/master/templates)
> 
> @Sagar2366 are we sure we want the wipe disable? because if we do that, once the URL is set and we press, lets suppose, the signup button, we wont be able to navigate back to the setURL page at all, which means it will be impossible to change the URL once set and navigated to another page

Based on current flow, yes it is difficult. We should add back functionality in signup page and login page to go back to the URL setting page and try signing up or login again. I will create new issue for that.
For now please proceed with this issue.

**Comment by Swayam221** [comment]
> > > @Swayam221 instead of saving form details.
> > > Can you disable swipe for signup/login ?
> > > Flow should be : Provide valid organization URL -> Click on Set URL -> Click on signup/login button to proceed.
> > > Also update issue description for the same - issue template (https://github.com/PalisadoesFoundation/talawa/tree/master/templates)
> > 
> > 
> > @Sagar2366 are we sure we want the wipe disable? because if we do that, once the URL is set and we press, lets suppose, the signup button, we wont be able to navigate back to the setURL page at all, which means it will be impossible to change the URL once set and navigated to another page
> 
> Based on current flow, yes it is difficult. We should add back functionality in signup page and login page to go back to the URL setting page and try signing up or login again. I will create new issue for that.
> For now please proceed with this issue.

@Sagar2366 okay sure! I could take up that new issue too.
