### ISSUE TITLE
Improving Code Quality

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#325]
**Description:** The Import statements on projects need to be organized which can be helpful in the future if someone wants to go through the codebase and can be helpful for future developments

Fixing this issue will add comments on all .dart files regarding import statements and improve the code quality.

@jordanliu @Sagar2366 I'll create a separate branch and PR,  if this issue is approved as it changes all the .dart files specifically adds comments in the import statement or else will close this issue :)

**Problem:**
<img src="https://user-images.githubusercontent.com/23498248/111157952-80bb3e00-85bd-11eb-8263-be197f4c32d0.png" width="50%" height="50%" />

**Solution:** 
<img src="https://user-images.githubusercontent.com/23498248/111157848-5e292500-85bd-11eb-8b8a-43ea5a9a0129.png" width="50%" height="50%" />

**Future Work:**
We can also implement,
- https://pub.dev/packages/pedantic
- https://pub.dev/packages/dart_code_metrics

**Comment by CyberWake** [comment]
We can have a single export file for all similar category imports that would we much more optimised solution to reduce redundancy and fast development.

**Comment by adithyaakrishna** [comment]
@yasharth291 Sure man you can go ahead, also I would love to discuss with you and work on it together if its okay :)

**Comment by jordanliu** [comment]
Seeing how @yasharth291 is working on some aspects of improving code quality, could you guys sync up and see what can be collaborated on?

**Comment by adithyaakrishna** [comment]
> Seeing how @yasharth291 is working on some aspects of improving code quality, could you guys sync up and see what can be collaborated on?

Yes sure @jordanliu , @yasharth291 can we discuss about the same?

**Comment by Sagar2366** [comment]
Will get fixed as part of https://github.com/PalisadoesFoundation/talawa/issues/103
