### ISSUE TITLE
Improve unit/ widget testing of the App.

### ISSUE THREAD

**Issue by arteevraina** [PalisadoesFoundation/talawa#326]
Improving unit/widget testing of the app. Currently, the tests have been only been written for validators used in `Register` and `Login `Screens. I will help to improve the testing of the app and which would help to avoid any breaking changes in the future. 

Folder: https://github.com/PalisadoesFoundation/talawa/tree/master/test

### Other Information.
If mentors/ participants have anything to add to this issue. Please provide your valuable suggestions. I would keep that in mind while sending the patches. **If you want to add any widget/unit test please update here before working.**

**Comment by piyushpradhan** [comment]
I can help with writing widget tests. 
If no one's currently working on it, can I take this up ?

**Comment by arteevraina** [comment]
Hey @piyushpradhan ! Let's wait for the issue to get approved. If it gets approved, as I will be also working on this  please update with widget are you working on in order to avoid any duplicate work.

**Comment by piyushpradhan** [comment]
Yeah, sure. We'll do that.

**Comment by jordanliu** [comment]
Agreed, let's add some overflow tests as well. Assigning @arteevraina

**Comment by arteevraina** [comment]
@jordanliu Should I add overflow tests for all the screen in a single PR or handle create different PRs for different screens?

**Comment by Sagar2366** [comment]
@arteevraina app testing is much needed issue to be fixed.
We should break down testing of each functionality in app. 
For example - login screen test, sign up page tests, event page tests, etc. 
It would also help to involve more students in the project.

**Comment by arteevraina** [comment]
Looks good ! I am currently writing widget tests for `login_page.dart`

**Comment by shikharsaurav** [comment]
can i help @arteevraina @Sagar2366 ?
i will love to help

**Comment by arteevraina** [comment]
Hi @shikharsaurav! You can contribute unit/widget tests but make sure to update here to avoid any duplicacy of work. I am waiting for #462 to merge after that I will add some more tests for `url_page.dart`.

**Comment by utkarshshendge** [comment]
Hi @arteevraina , I am trying to write tests for newsArticle.dart and newsfeed.dart.

**Comment by arteevraina** [comment]
Hi @utkarshshendge ! It would be better if you handle one widget in a single PR. So that other participants can also get involved :)

**Comment by utkarshshendge** [comment]
Il'l send a PR for  newsfeed.dart. test

**Comment by utkarshshendge** [comment]
In order to write tests for `newsfeed.dart` we will have to write test for `addPost.dart.`
I'm writing for `addPost.dart.`
if anyone wants to write tests for` newsfeed.dart` feel free to do after tests for` addPost.dart` get merged.

**Comment by Jaideep-C** [comment]
Do we need to write unit tests for the `controllers` [`auth_controller.dart`, `org_controller.dart`]?

**Comment by utkarshshendge** [comment]
Hey @arteevraina could you please add link to the test folder in this comment https://github.com/PalisadoesFoundation/talawa/issues/326#issue-831801725 ?

**Comment by utkarshshendge** [comment]
Im  adding widget tests for` home_page.dart`

**Comment by dhushyanth-s** [comment]
I'm adding tests for `newsfeed.dart` file.

**Comment by arteevraina** [comment]
I will be working on the widget test for ` join organization` page.
