### ISSUE TITLE
Ui/Ux Upgradation - On Hold

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#330]
**Description:** The current Nav Bar uses `persistent_bottom_nav_bar` and from a UI/UX point of view is kind of outdated so had to rework and revamp this into `CurvedNavigationBar` with animation Support

**Problem:** The current nav bar looks like this,

![image](https://user-images.githubusercontent.com/23498248/111208966-6bf89d80-85f1-11eb-8dae-4e6df675cc9a.png)

**Comment by Sagar2366** [comment]
@adithyaakrishna please let us know why are you creating different issues for this ? #330, #331, ₹332

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna please let us know why are you creating different issues for this ? #330, #331, #332
> 
> Is it possible to combine all of them into single issue ?
> Also, we have already send out guidelines in slack channel about discussing in channel before creating issues. Please check them once.

I created the issues separately as it deals with different aspects of the App. I'll keep that in mind before opening another issue in the future and also will make sure to discuss regarding the same :)

**Comment by jordanliu** [comment]
Hey @adithyaakrishna, seeing how we're in the process of redesigning the app I think we should hold off on certain UI/UX changes for now

**Comment by Sagar2366** [comment]
Consider UI/UX upgradation issues as part of this -
https://github.com/PalisadoesFoundation/talawa/issues/330
https://github.com/PalisadoesFoundation/talawa/issues/331, https://github.com/PalisadoesFoundation/talawa/issues/332
