### ISSUE TITLE
Ui/Ux - Upgrading Loader Used Across the App

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#332]
**Description:** The current Loader/Progress indicator uses `CircularProgressIndicator and this can be improved/reworked on to create a better looking loader for the app

**Problem:** The currentloader looks like this,
![image](https://user-images.githubusercontent.com/23498248/111209804-7e270b80-85f2-11eb-855c-a6848374c1b9.png)

or instead of using Loader on News Feed, Event and other pages, we can also use [flutter_shimmer](https://github.com/hnvn/flutter_shimmer) for the same

**Comment by jordanliu** [comment]
Hey @adithyaakrishna, seeing how we're in the process of redesigning the app I think we should hold off on certain UI/UX changes for now

**Comment by adithyaakrishna** [comment]
@jordanliu Yes, I completely agree with you. I won't work on this issue for now and would proceed with it in the future once the requirements document has been shared or after thorough discussion

**Comment by Sagar2366** [comment]
Should get fixed in https://github.com/PalisadoesFoundation/talawa/issues/330
