### ISSUE TITLE
Ui/Ux - Upgrading the current splash screen to a animated one

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#333]
**Description:** The current splash screen has only one icon and it can be improved by animating the splash screen i.e. using some animated gifs or through some other way.

**Problem:** The below image shows the current splash screen which can be completely revamped to a animated one,

![image](https://user-images.githubusercontent.com/23498248/111210291-1624f500-85f3-11eb-9e82-3c7aeb4afd23.png)

**Comment by ishan0805** [comment]
actuall this PR is Still not accepted

**Comment by adithyaakrishna** [comment]
@ishan0805 We can use flare for creating a better splash screen, the implementation is also very easy for this
I thought the PR was accepted already 😶
As its not accepted, we can discuss about it and push a commit to the same PR

**Comment by ishan0805** [comment]
@adithyaakrishna  Flare is used to animate widgets . Splash screen is Provided before any widget even starts to initialized .
You **cannot** animate the splash screen it has to be a static image as mentioned [here](https://stackoverflow.com/questions/57592492/flutter-animated-splash-screen-gif)
But you can trick the user to think it is an animation by providing the first screen  UI same as of splash screen and animating it .

**Comment by CyberWake** [comment]
> @adithyaakrishna Flare is used to animate widgets . Splash screen is Provided before any widget even starts to initialized .
> You **cannot** animate the splash screen it has to be a static image as mentioned [here](https://stackoverflow.com/questions/57592492/flutter-animated-splash-screen-gif)
> But you can trick the user to think it is an animation by providing the first screen UI same as of splash screen and animating it .

Correctly said we can only create the illustration that the launch screen is animated.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna Flare is used to animate widgets . Splash screen is Provided before any widget even starts to initialized .
> You **cannot** animate the splash screen it has to be a static image as mentioned [here](https://stackoverflow.com/questions/57592492/flutter-animated-splash-screen-gif)
> But you can trick the user to think it is an animation by providing the first screen UI same as of splash screen and animating it .

Exactly, that's what I meant to say but couldn't put it out properly

**Comment by Sagar2366** [comment]
Should get fixed as part of https://github.com/PalisadoesFoundation/talawa/issues/330
