### ISSUE TITLE
App should inform users that why are they no getting any data on their screen. 

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#340]
API Response:
![image](https://user-images.githubusercontent.com/43651504/111258431-f9b0a900-8642-11eb-9a1d-56464e2fa0b2.png)

https://user-images.githubusercontent.com/43651504/111258614-5613c880-8643-11eb-861e-789f4aa042f2.mp4

**Comment by CyberWake** [comment]
Please look into issue #298 it is correlated the issue stated by you.

**Comment by CyberWake** [comment]
Better to update the existing issue rather than creating multiple.😎😎

**Comment by GMGOG** [comment]
Okay, you should mention issues clearly so that if someone search issues with keywords. It should appear.

**Comment by Sagar2366** [comment]
Duplicate issue - https://github.com/PalisadoesFoundation/talawa/issues/298
