### ISSUE TITLE
[Bug]App is not showing that user is not connected to Internet or their Internet is not working.

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#341]
App must informs users when they get connected or disconnected to internet.

https://user-images.githubusercontent.com/43651504/111259315-aa6b7800-8644-11eb-8ce2-ed94cd66ae51.mp4

**Comment by palisadoes** [comment]
@GMGOG Please use our template to explain how you propose to fix the issue. For example do you have a screen shot of what the user experience would be if there is a loss of communication?

**Comment by CyberWake** [comment]
@GMGOG we are having plans for the same to be implemented via state management and will handle the same in #850 we may close this issue.
