### ISSUE TITLE
[New Feature] Change organizations from newsfeed page

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#342]
Description:
current: **Changing** / **Joining** organizations require to jump to the profile section and then paginate to the respective page.
Proposing:
<p>
<img src="https://user-images.githubusercontent.com/47498552/111260032-1c908c80-8646-11eb-82a0-05441b240595.png" 
width="200" height="400"/>
<img src="https://user-images.githubusercontent.com/47498552/111260093-36ca6a80-8646-11eb-8181-93ba08120b16.png" 
width="200" height="400"/>
</p>

Step1 --------   -------- ------- ---------> Step2

Modification:
Code will be changed on the "Newsfeed" page.

Action:
Taping on the Organisation icon in AppBar--> will Show the bottom modal sheet.

**Comment by piyushpradhan** [comment]
I can take this up, if no one else is working on it.
