### ISSUE TITLE
 [ Bug ] Validation needed in adding News

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#343]
### Description
While adding a news two fields are required , but validation is not given to any of them . Thus a user can post a news but it will not display . 

https://user-images.githubusercontent.com/57336738/111267191-a2fe9b80-8651-11eb-9783-58d046635bdc.mp4

## Additional Validation  
Validation to the length of Title and description can also be given . As of now any long text can be added . This can create issue of overflow to data and the database can be easily be spammed with long texts  .

## Solution
Simple form validation can be added to solve this issue

**Comment by ram2939** [comment]
I would like to work on this issue

**Comment by ishan0805** [comment]
@ram2939  sorry I have already asked the mentor to allot this to me .

**Comment by shikharsaurav** [comment]
is this problem solved?

**Comment by ishan0805** [comment]
Yes the PR is already generated you can review it 😊
