### ISSUE TITLE
[bug] pixel overflow in sign up screen

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#344]
When the user wants to sign up and there is an error of any kind, the snack bar displayed at the bottom produces an overflow error
![IMG-20210316-WA0004](https://user-images.githubusercontent.com/50530242/111272681-38d6fe00-8633-11eb-8983-383994e69e11.jpg)

**Comment by OnyemaAnthony** [comment]
@Sagar2366 please can I work on this?

**Comment by pr4nshul** [comment]
duplicate #223

**Comment by OnyemaAnthony** [comment]
Duplicate issue
