### ISSUE TITLE
[Feature] implementing chat functionality

### ISSUE THREAD

**Issue by guptapriyanshu7** [PalisadoesFoundation/talawa#346]
Right now the chat section has no functionality.
No one can send messages in a particular event.
![WhatsApp Image 2021-03-16 at 2 07 20 PM](https://user-images.githubusercontent.com/60141300/111280239-9d10b680-8661-11eb-80fa-28143333fa83.jpeg)

I am willing to do this:-
@Sagar2366 @DeltaHarbinger could you assign this to me.

**Comment by yasharth291** [comment]
i have already opened the same issue please look

**Comment by guptapriyanshu7** [comment]
Could you please tag it?

**Comment by yasharth291** [comment]
#187

**Comment by yasharth291** [comment]
you can close this one and ask the mentors to assign you that to you

**Comment by CyberWake** [comment]
This is a GSoC labelled issue @guptapriyanshu7 you may close this one or we may take this up. If needed we'll ask for help.
