### ISSUE TITLE
[Enhancement] Add package_info plugin

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#347]
- **Issue Description:** Add [package_info](https://pub.dev/packages/package_info) plugin as it  enables us to query information about an application package.
- **Issue Severity:** Low
- **Environment Details:** The current version of app is 1.0.0 (which is also the default version) but, in [lib/views/widgets/about_tile.dart](https://github.com/PalisadoesFoundation/talawa/blob/master/lib/views/widgets/about_tile.dart) the applicationVersion  is set to "1.0.1".
- **Observed Behaviour:** There is a need to hardcode package information inside app.
- **Expected Behaviour:**  Should automatically get package information .
- **Snapshots/Videos:**     Not needed for this issue, because it does not bring change to UI.
- **Does this issue need immediate attention?**  No
- **Are you willing to work on this issue:**   Yes

**Comment by utkarshshendge** [comment]
@Sagar2366 Sir, I'd like to know your opinion on this.
Also can you assign me this issue?

**Comment by utkarshshendge** [comment]
Thank you very much!!

**Comment by yasharth291** [comment]
can i work on this @Sagar2366

**Comment by Sagar2366** [comment]
@utkarshshendge please send PR to resolve this issue.

**Comment by utkarshshendge** [comment]
@Sagar2366  Sir, I did the changes to my local repository as soon as I created the issue. I did not create a PR because of Code Freeze.
Creating a PR in few minutes :)
