### ISSUE TITLE
Organization Settings Page

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#355]
I encountered an issue with the new organization settings page implemented.

 1.   It doesn't allow me as a member to leave any organization. **[Bug]**
 https://thepalisadoes-dyb6419.slack.com/files/U01QZEFJSCE/F01QYUR2A3H/t_video6235250589085729285__1_.mp4
 2.   As a member this page should be adaptive accordingly like it should either show me the toast in remove member page on marking any member for remove or it should not show me the options to remove member in the organization page. **[Enhancement]**
 https://thepalisadoes-dyb6419.slack.com/files/U01QZEFJSCE/F01RDN4F57U/photo6235250589541969025.jpg
 3.   Accept membership request should only be visible to private organizations that too only if the user is admin. Adding to this one the page loads empty if there are no member join requests, displaying a proper message would be a better choice. **[Enhancement]**
 4.   As a organization admin, if a remove a user and if the user happens to be a admin then there's a feature which prevents this to happen but I feel this could be enhanced by either displaying a proper toast or we can show on the member name tile itself if the user is admin similar to whatsapp. This could also help other members as well to know who are there organization's admins. **[Feature/Enhancement]**
 https://user-images.githubusercontent.com/44184786/111338728-2c878b00-869d-11eb-822d-88f3bbd9d1ae.jpg
 5.   Update organization option should only be visible if the user is admin **[Feature]**
 https://thepalisadoes-dyb6419.slack.com/files/U01QZEFJSCE/F01RDN4F57U/photo6235250589541969025.jpg

**Console log for the same:**
![image](https://user-images.githubusercontent.com/44184786/111340923-0ebb2580-869f-11eb-81f8-c9947ad04b5e.png)
**Video of the same:**

[![Watch the video](https://user-images.githubusercontent.com/44184786/111345100-f6e5a080-86a2-11eb-9a59-30fba6ddb8cd.jpg)](https://user-images.githubusercontent.com/44184786/111341136-3e6a2d80-869f-11eb-9b71-13839b1a2cc6.mp4)

**Comment by CyberWake** [comment]
@Sagar2366 @jordanliu can you please assign me this issue. I would be very happy to contribute on the following issue.

**Comment by CyberWake** [comment]
Thank you @Sagar2366 sir. Working on it.😊

**Comment by shikharsaurav** [comment]
@Sagar2366 @jordanliu can i work on 1st bug i would love to contribute

**Comment by CyberWake** [comment]
@shikharsaurav sorry to interrupt but the point you are taking about is dependent on backend. We have a issue raised over there on tawala-api once we have that fixed we'll be able to eradicate that thing. ✌

**Comment by Sagar2366** [comment]
@CyberWake some of these are actually good suggestions.
Can you create 5 different issues ? Let me know if you have started already working on any of them.

**Comment by CyberWake** [comment]
@Sagar2366 this is a PR already made to resolve all these issues. Please review it, added I have provided the screenshot/recordings for the requested changes that would arrive after the merge.

**Comment by Sagar2366** [comment]
> @Sagar2366 this is a PR already made to resolve all these issues. Please review it, added I have provided the screenshot/recordings for the requested changes that would arrive after the merge.

@CyberWake I am doing it for now and last time.
Please follow the guidelines, break down issues if possible. Send small PR's for review, don't mix fox for all issues in same PR.
I'm future if anything breaks it will be difficult to analyse the issue.
As suggested in PR remove changes which should not be added to fix the issue, any code formatting, re-factoring, etc.

**Comment by CyberWake** [comment]
ok sir. will take care this isn't repeated again.

**Comment by yasharth291** [comment]
i think this is duplicate #230
