### ISSUE TITLE
[Bug] Bug in the login page

### ISSUE THREAD

**Issue by TusharGupta05** [PalisadoesFoundation/talawa#363]
There is a bug in the login page.
When the value of dropdown button is changed, the text of 'URL SAVED!' button does not change to 'Set URL'. It changes only when the text of textfield changes and it does not change when the value of dropdown changes. Not only that after the value of dropdown changes, the 'Create an Account' and 'Login' buttons should also be disabled until the user presses the 'Set URL' button again.

https://user-images.githubusercontent.com/56271252/111479533-0e7e6100-8757-11eb-8ec6-88984a270968.mp4

One more thing I would like to add is that when the user long presses the enabled 'Create an Account' and/or 'Login' button some weird lines are displayed on the button. 

https://user-images.githubusercontent.com/56271252/111479985-8056aa80-8757-11eb-970d-e59cc192f4dc.mp4

I would like to work on both bugs.
1) I will fix the first bug by adding the required piece of code at the correct place.
2) I will remove those ugly looking lines from the button so that the button will look and behave perfectly.
@Sagar2366 sir, please assign me this issue.

**Comment by Sagar2366** [comment]
@TusharGupta05 you can start working on this issue. 
Note: We don't have support for https URL currently.
