### ISSUE TITLE
Mandatory fields must get highlighted when user doesn't input data.

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#364]
- [ ] Mandatory fields must be highlighted and should prompt user to input in the field.

- [ ] Should inform if user enters a irrelevant data.

Error logs while creating a event.
![image](https://user-images.githubusercontent.com/43651504/111506927-24e4e680-8770-11eb-9a27-4b795d29972e.png)

UI of app while creating a new event.
https://user-images.githubusercontent.com/43651504/111507431-a89ed300-8770-11eb-8270-b94adf08f7a9.mp4

**Comment by CoderMayhem** [comment]
Kindly assign @Sagar2366 .

**Comment by kavinkumar999** [comment]
hello  @Sagar2366   i would to like to working on the issue

**Comment by Sagar2366** [comment]
> Kindly assign @Sagar2366 .

@CoderMayhem you can start working on this issue.
