### ISSUE TITLE
[enhancement] if API field is null then login button must inform user.

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#365]
attached screen recording for the same.

https://user-images.githubusercontent.com/43651504/111508739-0d0e6200-8772-11eb-823a-be60fe732e0f.mp4

**Comment by Sagar2366** [comment]
@GMGOG this is incomplete information. Please use issue template https://github.com/PalisadoesFoundation/talawa/tree/master/templates and add more details to this issue.

**Comment by Sagar2366** [comment]
This issue will get handled through https://github.com/PalisadoesFoundation/talawa/issues/435.
