### ISSUE TITLE
PassWord Validator in signup page

### ISSUE THREAD

**Issue by shikharsaurav** [PalisadoesFoundation/talawa#366]
password must have:
minimum 1 Upper case alphabet
minimum 1 lower case alphabet 
minimum 1 numeric character
minimum 1 special character
Password string should not have user first name or last name in it

**Comment by shikharsaurav** [comment]
@heyjordn @jordanliu
plz assign me for this issue

**Comment by Sagar2366** [comment]
@shikharsaurav follow this templates for issue and PR creation - https://github.com/PalisadoesFoundation/talawa/tree/master/templates
