### ISSUE TITLE
Comment page will be open even we click right or left of comment button even left of like button

### ISSUE THREAD

**Issue by shikharsaurav** [PalisadoesFoundation/talawa#368]
@heyjordn @jordanliu 
plz assign me to solve this i will love to solve this

**Comment by yasharth291** [comment]
Sorry but i am already working on this

**Comment by shikharsaurav** [comment]
ok @yasharth291

**Comment by shikharsaurav** [comment]
plz let me know if i can help

**Comment by yasharth291** [comment]
ok for now you can close this issue
