### ISSUE TITLE
[enhancement] update the launcher icon to organization logo

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#380]
Right now the application still uses default flutter launcher icon,I want to update it to the Palisadoes foundation logo
![Screenshot_20210318-165119~2](https://user-images.githubusercontent.com/50530242/111656599-f9630a00-880a-11eb-9408-f7e5ec6893ba.png)

**Comment by OnyemaAnthony** [comment]
@Sagar2366 please can I work on this?

**Comment by Sagar2366** [comment]
@OnyemaAnthony are you using latest code ? Change for this issue is already added into master.

**Comment by OnyemaAnthony** [comment]
@Sagar2366 well I just switched to master branch and pulled,but my code is up to date

**Comment by OnyemaAnthony** [comment]
@Sagar2366  thanks i have seen the latest code and the laucher icon has been updated
