### ISSUE TITLE
Leave Organization Even you Are not in one

### ISSUE THREAD

**Issue by shikharsaurav** [PalisadoesFoundation/talawa#382]
Even we are not in any organization when we click on leave organization it shows us are u sure?

**Comment by shikharsaurav** [comment]
Plz assign me for this issue

**Comment by Raunakk02** [comment]
@shikharsaurav if you are working on another issue then can I work on this one?
If the mentors are also fine with it!
This would help to solve the issues faster!

**Comment by Sagar2366** [comment]
@shikharsaurav, are you on master ? 
With latest changes added, if user is not part of any organization we simply don't show Leave organization option.
Consider that fact not sure how you come across this issue, help us with more information.
Please follow Issue and PR templates to define issue https://github.com/PalisadoesFoundation/talawa/tree/master/templates - it will help others to understand more about issue.

**Comment by shikharsaurav** [comment]
yes it is removed
sry for that

**Comment by Sagar2366** [comment]
> yes it is removed
> sry for that

No problem. Keep contributing to the project.
