### ISSUE TITLE
Found Deprecated Widgets 

### ISSUE THREAD

**Issue by Ravig786** [PalisadoesFoundation/talawa#393]
Issue Description:  Fixed Deprecated Code for example changed FlatButton to TextButton.
Issue Severity: Medium
Environment Details: Development Environment
Observed Behaviour :  Chunks of Deprecated  
Expected Behaviour : Code upto date
Does this issue need immediate attention? Yes
Are you willing to work on this issue: Yes

**Comment by Sagar2366** [comment]
Please check open issues and PR's. 
Open issues only after discussing in slack channel and only if similar issue is not open.
