### ISSUE TITLE
[BUG] All comments are not visible 

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#399]
### Description 
While loading comments only the top 4 comments are visible to the user .

### Issue Severity
Moderate 

### Observed Behaviour:
The comments section is not  scrollable so only top 4 comments are visible .

### Expected Behaviour
The comments section should be scrollable

### Steps to reproduce issue:
I think using `singlechildscrollableview` or `listview` might solve the problem .

### Snapshots/Videos:
https://user-images.githubusercontent.com/57336738/111748811-00dfed00-88b7-11eb-99bc-3c16046ac52b.mp4

### Does this issue need immediate attention?
Yes 

### Are you willing to work on this issue:
Yes

**Comment by shikharsaurav** [comment]
can u assign me to this ?i will try to solve this issue
