### ISSUE TITLE
Add Lint dependency

### ISSUE THREAD

**Issue by Neha62-lit** [PalisadoesFoundation/talawa#400]
I would like to work on this issue. Kindly assign this issue to me @Sagar2366.

**Comment by Sagar2366** [comment]
@Neha62-lit follow issue template from here and add more details for this issue - https://github.com/PalisadoesFoundation/talawa/blob/master/templates/issue-template.md

**Comment by Neha62-lit** [comment]
> @Neha62-lit follow issue template from here and add more details for this issue - https://github.com/PalisadoesFoundation/talawa/blob/master/templates/issue-template.md

Okay

**Comment by Neha62-lit** [comment]
- **Issue Description:** 
 This issue is about the whole code in the project. Linting is the process of checking the source code for programmatic as well as Stylistic errors and unformatted code. It's helpful in identifying some common and uncommon mistakes that are made during coding like logical errors, unused variables etc.
- **Issue Severity:** 
Medium
- **Environment Details:** 
Issue found in whole code. 
- **Observed Behaviour:** 
As we can see in the whole code, there are some stylistic errors and common mistakes.
- **Expected Behaviour:** 
After adding the Lint dependency, there are no such type of common errors are occur.
- **Does this issue need immediate attention?** 
Yes, after adding Linting rules, it increases our code readability.
- **Are you willing to work on this issue:** 
Yes, I'm willing to work on this issue.
- **Other information:** 
Lint package.
https://pub.dev/packages/lint

**Comment by palisadoes** [comment]
@Neha62-lit How would adding this PR into #691 help? 

What I'd like is a way for:

1. Linting to occur prior to PR submission
2. A final linting afterwards upon doing the PR. Preferrably the same rules being applied in both cases.

Having two two different linters could get us back to the same issue that prompted the freeze.

[I've seen this approach too.](https://github.com/PalisadoesFoundation/talawa/issues/691) Could this issue be modified to meet the goals stated above?

@sumitra19jha what do you think? I'd prefer a unified approach.

**Comment by sumitra19jha** [comment]
@palisadoes I think @Neha62-lit needs to do some modifications. The PR need some changes. The `analysis_options.yaml` need to include `anylzer: errors` also as the requirement is to make sure that linting occur both prior and afterwards. Also the error and style rules needs changes

**Comment by sumitra19jha** [comment]
The PR is breaking that needs to be fixed too. Also the first thing first Dart Analyser issues need to be resolved.

**Comment by Sagar2366** [comment]
@Neha62-lit we really appreciate your efforts to solve this issue and research done by you.
This come as priority for us and need to get it resolved by tonight to lift up code freeze amd allow students to contribute in fully lint code base.

As we discussed you have some college work that's why won't be able to fix this issue immediately.
@sumitra19jha can you spend some time on this and get it fix asap ?

**Comment by Neha62-lit** [comment]
Okay, No problem!!
and Thank you for giving me this opportunity.

**Comment by sumitra19jha** [comment]
@Neha62-lit The work on this issue is done. Please close the issue
