### ISSUE TITLE
[BUG] Displaying Null Values in Tasks Tab of User Info

### ISSUE THREAD

**Issue by ayushs136** [PalisadoesFoundation/talawa#409]
Issue Description: 
   Displaying Null Values in Tasks Tab of User Info

Issue Severity:
Medium

Observed Behavior:
Was getting no values from GraphQL. 

Expected Behavior:
 Should be filled with user selected data.

Steps to reproduce issue:
 * Open Members Tab,
 * Select User Info Page
 * Go to Tasks Tab

Snapshots/Videos:
![image](https://user-images.githubusercontent.com/30320414/111782197-c0946500-88de-11eb-890f-7f61a4006cf3.png)

Does this issue need immediate attention?
No

Are you willing to work on this issue:.
Yeah

**Comment by Sagar2366** [comment]
@ayushs136 please discuss issue in #gsoc-newissues slack channel and follow guidelines for opening issues/pr's.
Read contribution guidelines. Assigning this issue to you to work on.

**Comment by palisadoes** [comment]
@ayushs136  Can we close this? A related issue by you was merged into the code base.

**Comment by ayushs136** [comment]
Yeah sure
