### ISSUE TITLE
[Enhancement] Scaling UI to different device sizes

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#413]
## Issue Description:
The entire padding, margin and white space (mostly through the sized box) contains a constant value. While building the screen, those values give a better outlook of UI on developer device (having a given height & width) but as the device changes (i.e height & width change) those constant space, in general, doesn't give a better UI outlook.

## Issue Severity:
Medium

## Observed Behavior:
Ui doesn't look effective for large device size.

## Expected Behavior:
The UI should be capable to automatically scale itself up based on device size

## Steps to reproduce the issue:
Launch app on screen size
1. 4.0"
2. 5.5"
2. 5.6"
3. 6.0"
4. 6.3"

You will notice the device UI outlook destruction.

## Does this issue need immediate attention?
Yes

## Are you willing to work on this issue:
Yes, this issue seems very interesting to me and I would like to devotee my time here.

**Comment by abhishekak048** [comment]
Can I work on this issue ?

**Comment by sumitra19jha** [comment]
Due to code freeze it's currently under hold
