### ISSUE TITLE
[Docs] Link for Issue-template doesn't work

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#414]
**issue description:**
in the issue-guidelines.md, the link to issue template in the line https://github.com/PalisadoesFoundation/talawa/blame/master/issue-guidelines.md#L11
doesn't work.
**issue severity:**
Low
**Environment Details:**
talawa/templates/issue-template.md
I am willing to fix this.

**Comment by Sagar2366** [comment]
@Swayam221 PR is already created for this issue - https://github.com/PalisadoesFoundation/talawa/pull/394
