### ISSUE TITLE
[Enhancement] - Reduce APK Build Size

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#416]
- **Issue Description:** 
The apk file when the app builds for android is significantly large ~90mb and this can be issue when the app is used in lower-end devices.
- **Issue Severity:** Medium
- **Environment Details:** Android Running on Pixel 3 API 28 
- **Observed Behaviour:** The app size is ~90mb
- **Expected Behaviour:** Reduce the app size to <40mb
- **Steps to reproduce issue:** Build the app for android
- **Does this issue need immediate attention?** 
Not much, but this would be a factor to consider when the app is released in the future
- **Are you willing to work on this issue:** Yes, I'm willing to work on this issue and can optimize the app especially the assets which occupy a major size of the app
- **Other information:** The app size can be reduced through optimizing the images and converting the icons to .svg files and for images into compressed .png

**Comment by yasharth291** [comment]
it automatically decreases once it is released for  market version. Second way is to make App bundle @adithyaakrishna

**Comment by adithyaakrishna** [comment]
> it automatically decreases once it is released for market version. Second way is to make App bundle @adithyaakrishna

I made the app bundle, and I completely agree with you that the market version will be a bit smaller in size but the size of assets can be reduced even further and also using Google Font APIs instead of font assets

**Comment by yasharth291** [comment]
yeah right and we can use @imgbot to further reduce the size of the images used @Sagar2366

**Comment by yasharth291** [comment]
can you please add imgbot in the repository

**Comment by yasharth291** [comment]
I can help here @adithyaakrishna  @Sagar2366

**Comment by CyberWake** [comment]
@adithyaakrishna we are certainly looking into it with flutter 2.0 #834 , upgraded dependencies #835  and making a full re write to maximize the efficiency and reduce the app size #850 .

**Comment by CyberWake** [comment]
@palisadoes sir this issue will get resolved in #850 please close this one
