### ISSUE TITLE
Events Page Data is not loading 

### ISSUE THREAD

**Issue by ayushs136** [PalisadoesFoundation/talawa#417]
Issue Description:
After app launch, the events page just displays a CircularProgressIndicator, and not the events, even after creating a new event, it displays same result.

Issue Severity:
High

Environment Details:
Development

Observed Behaviour:
Displaying  Circular Progress Indicator

Expected Behaviour:
Should Display Events Created and Calendar.

Steps to reproduce issue:
Just Launch the app and it will land on Events Screen.

Snapshots/Videos:
https://www.loom.com/share/c5119a5d68f54f22a2be5cadf316cbc1

Does this issue need immediate attention?
Yeah

Are you willing to work on this issue:
Yeah

**Comment by CoderMayhem** [comment]
Duplicate #298

**Comment by Sagar2366** [comment]
This issue will get handled as part of https://github.com/PalisadoesFoundation/talawa/issues/426.
