### ISSUE TITLE
[Enhancement] Changing built-in widget constructors to corresponding const constructors wherever necessary

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#419]
- **Issue Description:** In most part of the code, currently we don't use const constructor for widgets having static data in their constructor like:

> `Text("create an account")`
> `SizedBox(height:5)`
> `AlignmentDirectional(0.0,0.0)`
> `Icon(Icons.arrow_downward,...)` and more widgets like this.....

Thus whenever a build method is called all these non-constant constructors rebuild their objects thereby consuming some processing time.

- **Issue Severity:** Low
- **Environment Details:** Issue found mostly in the `talawa\lib\views`
- **Observed Behaviour:** Currently we don't use const constructor for widgets having static data in their constructor like:

> `Text("create an account")`
> `SizedBox(height:5)`
> `AlignmentDirectional(0.0,0.0)`
> `Icon(Icons.arrow_downward,...)` and more widgets like this.....

- **Expected Behaviour:** To use const constructor for widgets having static data in their constructor
> `const Text("create an account")`
> `const SizedBox(height:5)`
> `const AlignmentDirectional(0.0,0.0)`
> `const Icon(Icons.arrow_downward,...)`

Then we can prevent their unnecessary rebuilds incase the build method re-runs. Thereby saving some processing time.

- **Does this issue need immediate attention?** No.
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue. Please assign this to me!

**Comment by Raunakk02** [comment]
@Sagar2366 please assign this to me!

**Comment by palisadoes** [comment]
@Raunakk02 Please proceed, the freeze is now lifted.
