### ISSUE TITLE
[bug] application version should not be hardcode

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#421]
Application version on the about dialogue should be gotten dynamically using a package so that when the there is an update we don't need to manually update the version it will automatically detect the new version,but right now the version is hard coded String
![Screenshot_20210320-120729](https://user-images.githubusercontent.com/50530242/111868095-38fb3480-8978-11eb-9179-5bf75745eb34.png)

**Comment by OnyemaAnthony** [comment]
@Sagar2366 I will like to work on this if you assign it to me

**Comment by utkarshshendge** [comment]
Hi @OnyemaAnthony  there is already an issue regarding this.
 See #347 .  
I'm not creating  a PR because of code freeze.

**Comment by OnyemaAnthony** [comment]
okay @utkarshshendge  let me close it
