### ISSUE TITLE
Deprecated RaisedButtons and FlatButtons across the app

### ISSUE THREAD

**Issue by Enigma04** [PalisadoesFoundation/talawa#422]
The app contains RaisedButtons and FlatButtons that are depreciated now. I would like to replace those if I get the permission to do it. @DeltaHarbinger @palisadoes @Sagar2366

**Comment by palisadoes** [comment]
@Enigma04 please proceed.

**Comment by CyberWake** [comment]
@Enigma04 thanks for marking the issue. We are under code freeze to migrate the codebase we will make sure to update these hence we may close this one as #834 does this.
