### ISSUE TITLE
(Bug) Add Events page not creating new events

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#426]
**Issue Description**
At present the Add Events page is not capable of adding new events. On clicking the button only the screen gets popped by the navigator but a new event is not created. The createEvent() function does not contain the code to make a request to the api.

**Issue Severity :** High

**Environment Details :** Issue in `addEventPage.dart`

**Observed Behaviour:** Screen pops off on clicking the button but new event is not created.

https://user-images.githubusercontent.com/56952811/111873613-30761e80-89b7-11eb-8bb3-ed51f56d63a8.mp4

**Expected Behaviour:** A new event must get added.

**Does this issue need immediate attention?** Yes.

**Are you willing to work on this issue:** Yes. Kindly assign this to me @Sagar2366 @DeltaHarbinger

**Comment by Sagar2366** [comment]
@CoderMayhem please fix the issue https://github.com/PalisadoesFoundation/talawa/issues/417 as part of this issue only.
Please update issue description if required.

**Comment by ayushs136** [comment]
I can work on this issue as a part of #417 @Sagar2366

**Comment by CoderMayhem** [comment]
@Sagar2366 417 was a duplicate issue. Someone is already working on this in #298.

**Comment by Sagar2366** [comment]
@CoderMayhem issue #298 will show only error screen after 10 sec of waiting if no data is available to display.
We still need this issue to get fixed.
