### ISSUE TITLE
[Enhancement] Add Logs for Exception/Error/ Crash in the App

### ISSUE THREAD

**Issue by StrangeNoob** [PalisadoesFoundation/talawa#427]
**Issue Description:**
 Add Logs for the Exception/Error/Crash in the App. As in the production, we won't be able to have every device to debug. It would  be easy to keep log of these errors, exception and rectify in the following build. Having a scheduler to update the logs in our server for the last 24-36 hours will be helpful for the developers to know the bugs and its seriousness. 
**Issue Severity:** 
It's an Enhancement. 
**Environment Details:** 
It can be implemented in both Android and IOS App. 
**Does this issue need immediate attention?** 
No, It's not that important but a good to have feature in the next updates.
**Are you willing to work on this issue:**
Sure why not. 
**Other information:**
It would be better to implement [f_logs](https://pub.dev/packages/f_logs) and [Firebase Crashlytics](https://pub.dev/packages/firebase_crashlytics).  
I would suggest implementing [cron](https://pub.dev/packages/cron) for scheduling purpose.

**Comment by yasharth291** [comment]
hey @StrangeNoob  you should join slack channel first because i have already asked for permission regarding this. The code is in code freeze so no new enhancement. So i was holding the same issue

**Comment by yasharth291** [comment]
please join slack channel first

**Comment by StrangeNoob** [comment]
I am in Slack and I have talked about this @Sagar2366 a couple of minutes about this error. I am not sure what you and @Sagar2366  have discussed.  But I didn't anything about this talawa channel.

**Comment by yasharth291** [comment]
![Capture](https://user-images.githubusercontent.com/55004621/111881087-04699600-89d5-11eb-9439-9a55cfdd0ef0.JPG)

**Comment by yasharth291** [comment]
As  the talawa api is in code freeze there is nothing we can do in it

**Comment by StrangeNoob** [comment]
I know @yasharth291 about the code freeze. I will be working on it after the code freeze. It's just an enhancement.

**Comment by Sagar2366** [comment]
@StrangeNoob please update issue description by following issue template and starting working on this issue.
