### ISSUE TITLE
There is nothing showing if there are no request in the member page.(Bug)

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#430]
![image](https://user-images.githubusercontent.com/55004621/111882125-d20e6780-89d9-11eb-99f2-fbd761c26ce3.png)
observed behavior :  Nothing is showing if there is no member request.
expected behavior :  there should a message showing that there is nothing to be shown.
priority : low
would i like to work: yes i love to work on it.

**Comment by CyberWake** [comment]
There is already an existing issue for this one #355 which has a PR #424 made to resolve all the issues related to organization.👍wait for the merge all those issues will we eradicated forever.

**Comment by yasharth291** [comment]
#355 is duplicate of #230
