### ISSUE TITLE
Pickimage method is deprecated use imagepicker.getimage method instead.(Bug)

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#431]
In the ***Events*** and other pages , Image picker method is used. ***It is Deprecated in the Current stable Flutter version. We need to migrate it to Imagepicker.getimage method.*** .Since it's a bug it can be corrected during code freeze.
i hope @Sagar2366 can assign this to me.

**Comment by i-anuragmishra** [comment]
The PR #440 is now created to resolve this Issue.

**Comment by Sagar2366** [comment]
@i-anuragmishra this is same issue as https://github.com/PalisadoesFoundation/talawa/issues/264, right ?

**Comment by i-anuragmishra** [comment]
> @i-anuragmishra this is same issue as #264, right ?

I guess but the PR mentioned there has not solved it.

**Comment by i-anuragmishra** [comment]
i have closed the last PR and now the New PR with only the required changes are present. The new PR #445  Resolves this issue.
