### ISSUE TITLE
Quality of life UI Enhancement

### ISSUE THREAD

**Issue by Ujjwal-Sumesh** [PalisadoesFoundation/talawa#435]
<h2> Issue Description </h2>
To change the UI of the Login/Registration screen to better define the flow to new users, which in this case is to keep the Login/Register buttons invisible until input URL of organization is recieved.
<h2> Issue severity </h2>
Minimal
<h2> Observed Behaviour </h2>
Both the create account and login button are visually present but has no functionality until URL is inputted by user
<h2> Expected Behaviour </h2>
The create account and login button need to be hidden from UI unitil URL is inputted so as to define flow to user
<h2> Does this issue need immediate attention? </h2>
No
<h2> Are you willing to work on this issue </h2>
Yes

**Comment by Sagar2366** [comment]
@Ujjwal-Sumesh use issue and PR template to create issue/pr.
