### ISSUE TITLE
[Bug] - Privilege not displayed in user info page under members tab.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#436]
- **Issue Description:** 
- [x] User privilege's not shown in user info page. [Bug]

- **Issue Severity:**
Medium

- **Environment Details:** 
Homepage -> Members Tab -> Pick any member tile -> particular member info.

- **Observed Behavior:** 
Privilege's not displayed on the page under the privileges field.

- **Expected Behavior:** 
Privilege's showed be visible like (Member, Admin, Creator)

- **Steps to reproduce issue:** 
Navigate to members tab and select any member. 
Privilege field is empty.

 
- **Snapshots/Videos:** 
<img title="Issue Points 1,3" src="https://user-images.githubusercontent.com/44184786/111895028-cfd9f680-8a35-11eb-8549-3737a7c73542.jpg" width="200">

- **Does this issue need immediate attention?**
Yes, this could help in using the resources wisely. As while developing some times the app got crashed due to heavy handling of data and not being able to attain the state. **(Which did in my case a few time)**

- **Are you willing to work on this issue:** 
Yes, I will to work on this one.

**Comment by yasharth291** [comment]
please @CyberWake try to divide the points. It is very difficult to understand. As i can see point number 2 is already discussed on slack and I considered it to work. And it can't be applied now as it is enhancement. So please can you remove 2nd point as i am  waiting for the code freeze to get over.

**Comment by CyberWake** [comment]
@yasharth291 I guess the points are already there and pretty much clear. And I see some of the issues you are already assigned to please leave this one for me. As well as there's no issue for the same reported till now. All should get equal opportunities after all it's open source.

**Comment by CyberWake** [comment]
@Sagar2366 can you please assign this one to me. Waiting to contribute on some new bugs. This one would be nice to work with.
