### ISSUE TITLE
[Enhancement] Using local storage to reduce the server load.

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#438]
Issue Description: The constant calling of api for details that are going to be used for longer time periods causes extra calls to api making the app slower so adding a local storage will help us.
Issue Severity: high
Environment Details: Issue found mostly in whole app
Observed Behaviour: The app is slow
Expected Behaviour: The app should be fast
Does this issue need immediate attention? yes
Are you willing to work on this issue: Yes, I am willing to work on this issue. Please assign this to me!

**Comment by Sagar2366** [comment]
@yasharth291 if you haven't already please read our contribution guidelines. Use issue and pr templates to create new issues and PR.
We also advice to discuss issue in slack channel first before creating it directly.

**Comment by yasharth291** [comment]
Sorry for creating the issue but sir everyone takes the issues discussed in the slack and creates are here

**Comment by Sagar2366** [comment]
> Sorry for creating the issue but sir everyone takes the issues discussed in the slack and creates are here

We are trying to give credit to everyone who is finding bugs/issues, suggesting new features, contributing any way to the project. If you felt someone else took credit for your hard work please reach out to us but not following guidelines is not good solution to this.

Now, can you please update issue description ?

**Comment by yasharth291** [comment]
yes sir sure i am updating it and can you please assign me to do this

**Comment by yasharth291** [comment]
@Sagar2366 it is done

**Comment by yasharth291** [comment]
thanks sir i am starting working on it now

**Comment by palisadoes** [comment]
@yasharth291 As this is a feature. Apply the PR to the develop branch

**Comment by yasharth291** [comment]
Sure Sir working on this now

**Comment by yasharth291** [comment]
As i can see someone already has used and solved this problem using shared preferences. I am closing this issue
