### ISSUE TITLE
[BUG] The message in shown in the toast is different from which is shown in the terminal

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#441]
Issue Description: The message in shown in the toast is different from which is shown in the terminal [BUG]
Issue Severity: low
Environment Details: Issue found mostly in the talawa\lib\views\pages\login_page
Observed Behavior: the message is shown in the toast is different
Expected Behavior: the message should be email taken. 
Does this issue need immediate attention? yes
Are you willing to work on this issue: Yes, I am willing to
![WhatsApp Image 2021-03-21 at 1 39 41 PM](https://user-images.githubusercontent.com/55004621/111898300-29005500-8a4b-11eb-85ce-1d282831f558.jpeg)
 work on this issue. Please assign this to me!

![Capture](https://user-images.githubusercontent.com/55004621/111898320-3fa6ac00-8a4b-11eb-9605-8b9d3b950782.JPG)

**Comment by Sagar2366** [comment]
This issue will get handled from https://github.com/PalisadoesFoundation/talawa/issues/434.
Thanks for reporting the issue.

**Comment by yasharth291** [comment]
@Sagar2366 as the issue is still there can you open this and give this to me please

**Comment by yasharth291** [comment]
thanks sir

**Comment by yasharth291** [comment]
@Sagar2366 solved sir

**Comment by Sagar2366** [comment]
will get close as part of https://github.com/PalisadoesFoundation/talawa/pull/481
