### ISSUE TITLE
[Bug] - not able to auto login or hot restart the app.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#448]
- **Issue Description:**
On reopening the app after closing nothing works it show the No host specified in URI.

- **Issue Severity:** 
Very High as this is hindering the further task due to not being able to do hot reload which is also a kind of reopening the app.

- **Environment Details:** 
Verify the latest commit on talawa/master.
<img src="https://user-images.githubusercontent.com/44184786/111906860-cb82fd00-8a78-11eb-9685-9c4744c3d3fc.PNG" width="800">
Flutter environment
<img src="https://user-images.githubusercontent.com/44184786/111906936-24eb2c00-8a79-11eb-9d5e-d77aaf287151.png" width="800">

- **Observed Behaviour:** 
Not being able to auto login user.

- **Expected Behaviour:**
user should be auto logged in with no issues.

- **Steps to reproduce issue:** 
Go through the demo or open the app again.

- **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
Here is the demo video of the issue with logs priority once are the last few logs.
https://user-images.githubusercontent.com/44184786/111907125-fa4da300-8a79-11eb-9686-a1da7e7a7e0f.mp4

- **Does this issue need immediate attention?**
Yes, causing delays in other tasks. as not being able to do hot restart.

- **Are you willing to work on this issue:** 
Busy on other task assigned to me.

**Comment by rutvik11062000** [comment]
Let me fix this.

**Comment by CyberWake** [comment]
sure ask @Sagar2366 sir to assign this one to you.😉

**Comment by rutvik11062000** [comment]
Okay! 👍

**Comment by CyberWake** [comment]
Any updates in this issue?
