### ISSUE TITLE
switch organization page

### ISSUE THREAD

**Issue by shauravshikhar** [PalisadoesFoundation/talawa#451]
Issue Description:
in Switch Organiztion page it shold shold show the organisations organised by me

Observed Behaviour:
shows all organisations
Expected Behaviour:
show which organisation are organised by me & which are not
Snapshots/Videos:
![Screenshot_1616345138](https://user-images.githubusercontent.com/47968768/111913184-0003b280-8a93-11eb-93df-bf4de7841e07.png)

Does this issue need immediate attention?
yes
Are you willing to work on this issue:
yes

**Comment by Sagar2366** [comment]
@shikharsaurav switch organisation page will show you all organisation which you have joined and give option to switch to any of those organisation.

**Comment by Sagar2366** [comment]
Add more detailed explanation in issue about your requirement

**Comment by shikharsaurav** [comment]
it does not show which organization is organized by you
