### ISSUE TITLE
[BUG] Image selection from library 

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#453]
## Issue Description
The error occurs while returning back from the image library without selecting the image. 

## Issue Severity
Low

## Observed Behaviour
Nothing happens if the user returns back without an image but the console log shows an error.

## Expected Behaviour
No error should occur

### Steps to reproduce the issue
1. Open the app
2. Go to the signup page
3. Press the camera icon
4. Press photo library
5. Return back without selecting an image
6. Console log will show the error

### Snapshots/Videos
![Screenshot 2021-03-21 at 11 15 17 PM](https://user-images.githubusercontent.com/35868598/111915273-570d8580-8a9b-11eb-8d9f-88421f3ae461.png)

## Does this issue need immediate attention
No

## Are you willing to work on this issue
Yes

**Comment by shikharsaurav** [comment]
@sumitra19jha  can i work on this?

**Comment by sumitra19jha** [comment]
Actually I fixed the issue and made the pull request😅

**Comment by Jaideep-C** [comment]
Is this issue still open?

**Comment by sumitra19jha** [comment]
No it has been resolved
