### ISSUE TITLE
Travis build is failing because of invalid unit tests

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#457]
Issue Description: New changes are added to master and previously written unit tests are now failing because of changed workflow in application

Issue Severity: High

Observed Behaviour: Travis build is failing because unit tests are failing

Expected Behaviour: All test cases needs to be fixed for successful run of TravisCI

Snapshots/Videos: Check this URL for understanding more why travisCI is failing : https://travis-ci.org/github/PalisadoesFoundation/talawa/builds/763864139 
<img width="941" alt="Screenshot 1943-01-01 at 9 22 38 AM" src="https://user-images.githubusercontent.com/26805882/111938511-2dcb1480-8af0-11eb-99fb-c618f37683c7.png">

Does this issue need immediate attention? Yes

Are you willing to work on this issue: Any GSoC student can take a look and fix failing unit tests

**Comment by Sagar2366** [comment]
@adithyaakrishna start working on this issue.

**Comment by CyberWake** [comment]
Sir is this issue assigned to @adithyaakrishna. If not please assign this one to me. I am very much excited to get my PR #424 to get merged after the fix of this issue.😊
