### ISSUE TITLE
[Enhancement] Changing generating mutation strings using interpolation to  using graphql variables for sending data with mutations

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#463]
Issue Description: [Enhancement]
Changing generating mutation strings using interpolation to  using graphql variables for sending data with mutations. Using this will ease the process of sending data to the server weather it is a multiline input or other type of input. One example of such i am pasting here.

```
String createComments(String postId, var text) {
  const createCommentMutation = """
      mutation createComment(\$postId: String, \$comment:String) { 
        createComment(postId: \$postId, 
          data:{
            text: \$comment,
          }
        ){
          _id
        }
      }
  """;

  dynamic _resp = await _graphClient
          .mutate(MutationOptions(
              document: gql(createCommentMutation),
              variables: {
                'postId': postId, //Add your variables here
                'comment':text
              },
          ));

}
```

this is the function create post in variable sending way it is also able to send multi line input which your interpolation method is unable to do.
Issue Severity: high
Environment Details: Issue found mostly in whole app
Observed Behaviour: Multiline input is not taken
Expected Behaviour: Multiline input will be taken
Does this issue need immediate attention? yes
Are you willing to work on this issue: Yes, I am willing to work on this issue. Please assign this to me!

**Comment by CyberWake** [comment]
Have you tried trimming the user input. I guess that resolves the problem as well.

**Comment by CyberWake** [comment]
Faced similar one on the create organization page for multiline description. Adding a reference of it.
![Snippet](https://user-images.githubusercontent.com/44184786/112035832-f4cd8700-8b65-11eb-9dbb-3043edf86bfd.PNG)

**Comment by yasharth291** [comment]
Thats why it is not a bug its an enhancement. we have to trim whenever we will take input but if we are doing this we dont have to change everywhere changing in the main function will work so instead of writing once is better than writing everywhere.

**Comment by yasharth291** [comment]
> Have you tried trimming the user input. I guess that resolves the problem as well.

I never said it is a bug its just and enhancement brother

**Comment by yasharth291** [comment]
@Sagar2366  Sir can i work on it
