### ISSUE TITLE
Proposing a Code of conduct.md file in the project description.

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#467]
Mostly all Project with huge participation requires a code of conduct .md file in project description. I can help write that.  i hope mentors @Sagar2366  can assign it to me.

**Comment by Sagar2366** [comment]
@i-anuragmishra there is similar issue opened earlier, if you are interested to work on, claim on that.

Please do not open duplicate issues and follow contribution guidelines.

**Comment by i-anuragmishra** [comment]
sorry @Sagar2366  i didn't realise there was already a similar issue opened.
