### ISSUE TITLE
Entry screen after sign up

### ISSUE THREAD

**Issue by shauravshikhar** [PalisadoesFoundation/talawa#474]
Issue Description:
After sign up screen user should be shown intro about app

Observed Behaviour:
None

Expected Behaviour:
intro slides or pages

Does this issue need immediate attention?
yes

Are you willing to work on this issue:
yes 

Other information:
@Sagar2366  plz assign me this

**Comment by CyberWake** [comment]
Is it that needed one right now?

**Comment by shikharsaurav** [comment]
it can be gud to have intro for app
like
u can join organisations or create one
join event or make of ur own
etc

**Comment by Sagar2366** [comment]
Good suggestion, we may actually need it before directly landing to the join/create organisation page.

**Comment by shikharsaurav** [comment]
ok sir

**Comment by arteevraina** [comment]
> it can be gud to have intro for app
> like
> u can join organisations or create one
> join event or make of ur own
> etc

How about adding onboarding screens?

**Comment by nayakastha** [comment]
We can have animated onboarding screens for the tour through the app. 
Can be a really nice way to familiarise the app for the new users. These screens can also be used later for guiding the users when they need help. It can serve as a guide to use various features considering the designs are not very intuitive.

**Comment by palisadoes** [comment]
@shikharsaurav Please proceed. The freeze has been lifted.
