### ISSUE TITLE
Fix the Alphabet Floating over the Member profile in Member's list.

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#476]
Issue Description: The Alphabet in member list Foat over the Member Profile , As shown in the attached Pic. If assigned i can provide fix for this.

Issue Severity: Moderate

Expected Changes: I suggest that Alphabet should be static at a place and Mber card sixes should be reduced as well to make it look good and Less cluttered.
![Screenshot 2021-03-23 at 7 37 02 PM](https://user-images.githubusercontent.com/50531324/112161744-6f9fac00-8c11-11eb-934b-c2544cb9b2ba.png)

**Comment by Enigma04** [comment]
@i-anuragmishra if you are having any issue solving this then I would like to help you

**Comment by i-anuragmishra** [comment]
Thanks for your concern @Enigma04 . I really appreciate it. The PR is almost ready as of now .  But still Please feel free to contact if u need any help with this code base Thanks again.

**Comment by CyberWake** [comment]
@i-anuragmishra I would like to work on this one if you are busy with some other issue. 😊

**Comment by i-anuragmishra** [comment]
Hey @CyberWake thanks for your interest. I had some issue with my git branch , that's why a PR was not able to be pushed for this. Its resolved now . I will surely contact if i can't push a PR . Thanks again.

**Comment by CyberWake** [comment]
thank you @i-anuragmishra for give a quick update. BTW good luck 👍

**Comment by CyberWake** [comment]
Any luck @i-anuragmishra on this one🙂

**Comment by i-anuragmishra** [comment]
Hey @Sagar2366 PR #530 Solves this.
