### ISSUE TITLE
[Bug] Backslash(\) and double quotes(") error in graphql queries

### ISSUE THREAD

**Issue by TusharGupta05** [PalisadoesFoundation/talawa#477]
**Issue Description:**
Whenever the user enters a backslash or double quotes and we try to put the same text in the graphql query, it throws an error.
**Issue Severity:**
High
**Observed Behaviour:**
Error on passing double quotes(") and backslash(\\) in graphql query. One more thing is that only when the user enters backslash 4 times, there is no error but then there is a bug that instead of passing the backslash 4 times it considers it for 1 time only.
**Expected Behaviour:**
There should not be any error in case of \ and double quotes.
**Steps to reproduce issue:**
Go to login page/ sign up page/ create organization page or basically any such page where the user's entered text is passed into graphql query directly and enter a backslash or double quotes in the textinputfield and hit the submit button. In the console you can see an (syntax) error. 
**Snapshots/Videos:**
**Error when passing backslash:**
![Screenshot (276)](https://user-images.githubusercontent.com/56271252/112168715-8c3ee280-8c17-11eb-8195-c7f8dc6d7b2f.png)

**Error when passing double quotes:**
![Screenshot (277)](https://user-images.githubusercontent.com/56271252/112168908-b85a6380-8c17-11eb-96de-d01b354bb7f1.png)

**Does this issue need immediate attention?**
Yes.
**Are you willing to work on this issue:**
Yes.
**Other information:**
Please assing me this issue.

**Comment by yasharth291** [comment]
Hey @TusharGupta05 the backend will be changed to Restapi soon so it is not a matter of big importance

**Comment by utkarshshendge** [comment]
> Hey @TusharGupta05 the backend will be changed to Restapi soon so it is not a matter of big importance

Hey @yasharth291, where can I find this news?

**Comment by yasharth291** [comment]
> > Hey @TusharGupta05 the backend will be changed to Restapi soon so it is not a matter of big importance
> 
> Hey @yasharth291, where can I find this news?

Sorry i messed up. It was the news of some other project. Sorry @utkarshshendge
