### ISSUE TITLE
[Enhancement] Restructuring , seperating views and applying state-management 

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#478]
- **Issue Description:**
  The current folder structure suggests that the project is made to implement MVVM architecture.
  What are missing:
  1. respective view models for pages.
  2. locator not used for dependency injection.
  3. No implementation of pages with "BaseView" and "BaseViewModel".
  4. No separation between the UI and business logic.
  4. setstates used everywhere in the form of statemanagement.
  5. Currently we don't posses the services so writing test for dynamic and async responses can;t be done.
  
- **Issue Severity:** Medium
- **Environment Details:** <Add details about environment where this issue is found.>
- **Observed Behaviour:** No state-management and testing is difficult.
- **Expected Behaviour:** Proper structured and testable code should be written to have a logical flow.
- **Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.>
- **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
- **Are you willing to work on this issue:** Yes
- **Other information:** We need to restructure and separate services to follow the desired architecture.

**Comment by palisadoes** [comment]
FYI - @rutvik11062000 We also have a parent issue  #715 for a general refactoring of the code
