### ISSUE TITLE
[Bug]Invalid password validation error

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#480]
When I want to create an account after providing my details when I click on sign up button it shows that validation error on the password field, saying invalid password
![Screenshot_20210323-211017](https://user-images.githubusercontent.com/50530242/112252197-eb731600-8c5c-11eb-93be-dbcc4638beb2.png)

**Comment by shikharsaurav** [comment]
@OnyemaAnthony  can u share  screen shot with password shown

**Comment by OnyemaAnthony** [comment]
@shikharsaurav yes I can, though am working on this issue already

**Comment by shikharsaurav** [comment]
plz share once i think it will be in special char thats why @OnyemaAnthony

**Comment by shikharsaurav** [comment]
i can help u to debug it

**Comment by OnyemaAnthony** [comment]
@shikharsaurav I don't need help I have already found the cause of the error I will send a PR soon thanks

**Comment by shikharsaurav** [comment]
ok

**Comment by Sagar2366** [comment]
@OnyemaAnthony what password are you trying for testing this issue ?

**Comment by OnyemaAnthony** [comment]
@Sagar2366 the passyi used was Testing.12345

**Comment by OnyemaAnthony** [comment]
The password passed the validation of flutte_pw_validator plugin but didn't pass the regular expression validation because the regular expression does not recognize a dot so I have to add the dot in the regular expression so that the user would not be frustrated since the validation was ticked good

**Comment by Sagar2366** [comment]
great.  can you please also do some UI modification. Add some spacing in password strength bar and password text field.

**Comment by OnyemaAnthony** [comment]
Okay I will do that quickly,if I get you correctly you want me to shift the strength bar down from the password texfied, @Sagar2366 please confirm if this is what you mean

**Comment by OnyemaAnthony** [comment]
@Sagar2366 is this okay?
![Uploading Screenshot_20210324-144514.png…]()

**Comment by OnyemaAnthony** [comment]
@Sagar2366 is this okay?
![Uploading Screenshot_20210324-144514.png…]()

**Comment by OnyemaAnthony** [comment]
@Sagar2366 is this okay?
![Screenshot_20210324-144514](https://user-images.githubusercontent.com/50530242/112322187-fbb4e080-8cb0-11eb-871e-6f8b17fd9aa0.png)

**Comment by OnyemaAnthony** [comment]
![Uploading Screenshot_20210324-145941.png…]()

**Comment by OnyemaAnthony** [comment]
![Screenshot_20210324-145941](https://user-images.githubusercontent.com/50530242/112323207-dbd1ec80-8cb1-11eb-9227-3474045ae4b9.png)
It

**Comment by Sagar2366** [comment]
@OnyemaAnthony add commit to PR directly, I'll review there.

**Comment by OnyemaAnthony** [comment]
@Sagar2366  i have sent the commit

**Comment by pr4nshul** [comment]
@OnyemaAnthony @Sagar2366  Close this issue, as the PR is merged :)

**Comment by adithyaakrishna** [comment]
@pr4nshul Ig it was not updated, because when I wanted to fix Issue #538 , the gap between validation and password field was same i.e. it didn't have any spacing
So I added this between them,
```
SizedBox(
    height: 20,
),
```

**Comment by OnyemaAnthony** [comment]
Okay I will close the issue right away
