### ISSUE TITLE
[Bug]- Create post page

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#487]
- **Issue Description:** 
On add new post screen with the text form fields there is a bug that as soon as we start entering the data in title field the description field shows me the error that description can't be null.

- **Issue Severity:** 
Medium, though this is a trivial one.

- **Environment Details:** 
This bug can be encountered on the add post page. Just go with a normal flow to create a post and you'll notice it.

- **Observed Behaviour:** 
Validation is thrown before the user clicks on the check mark to upload the post.

- **Expected Behaviour:**
The validation show only we thrown if user tend to click the check mark and any field is left empty.

- **Steps to reproduce issue:** 
Refer to the demo attached

- **Snapshots/Videos:**
https://user-images.githubusercontent.com/44184786/112269604-98ba4e00-8c9e-11eb-9c8c-be80f1d773e2.mp4

- **Does this issue need immediate attention?**
Yes, this bug should be resolved in code freeze.

- **Are you willing to work on this issue:** 
Yes, I will to work on this issue.

- **Other information:** 
@Sagar2366 @heyjordn sir please assign this to me.

**Comment by yasharth291** [comment]
@Sagar2366 i think this issue is resolved. But he hasn't joined the issue with pr
