### ISSUE TITLE
[bug] send button in comment not responsive

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#495]
the send button for the comment is not responsive, when the comment becomes bigger then comment button will move to the top,I want to fix this

**Comment by OnyemaAnthony** [comment]
![Screenshot_20210324-132058](https://user-images.githubusercontent.com/50530242/112309624-d5d50f00-8ca3-11eb-9a9c-f639aa499f93.png)

**Comment by OnyemaAnthony** [comment]
@Sagar2366 please assign this to me

**Comment by KeyurBarot** [comment]
Can you assign me this?

**Comment by OnyemaAnthony** [comment]
@KeyurBarot I am already requesting he should assign it to me so I can start working on it
