### ISSUE TITLE
[BUG] Profile Picture of member not displaying

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#498]
Description
profile picture of member on the member's page is not displayed 

Issue Severity
Moderate

Observed Behavior:
Profile Picture of user is not  displayed 

Expected Behavior:
Profile Picture of user is should be  displayed 

Steps to reproduce issue:
I think there is an error in the url that is being called to fetch the picture

Snapshots/Videos:
![IMG_20210324_192737](https://user-images.githubusercontent.com/57336738/112322759-2f0a6600-8cd7-11eb-82bc-4a85ed96d15f.jpg)

![errorinflutter](https://user-images.githubusercontent.com/57336738/112322858-447f9000-8cd7-11eb-983e-d10d6fab0a2e.PNG)

 
Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by nerdynikhil** [comment]
I can fix this.

**Comment by CyberWake** [comment]
Have you tried checking it again. It's resolved I guess after the merge of #466

**Comment by ishan0805** [comment]
@CyberWake are the pictures  available , because when I run the code it is still showing this error .
My branch is up to date with the upstream .

**Comment by ishan0805** [comment]
@CyberWake I have also checked manually all the changes introduced in #466 are present in my origin also . Yet it is not showing the pictures .

**Comment by CyberWake** [comment]
@ishan0805 can you once compare the git log of current working branch with talawa/master. I tried replicating but couldn't.

https://user-images.githubusercontent.com/44184786/112622217-be875480-8e50-11eb-8a76-4f8e99b73f57.mp4

**Comment by ishan0805** [comment]
I don't know why it is showing error in my  version but If it is correct in all other versions I should close the issue

**Comment by ishan0805** [comment]
@CyberWake  what version of flutter are you using

**Comment by CyberWake** [comment]
> @CyberWake what version of flutter are you using
> also can you post the url used to fetch image
image url
```
Provider.of<GraphQLConfiguration>(
                        context)
                        .displayImgRoute +
                        _imgSrc
```
get ```_imageSrc from the image field of organisation

**Comment by ishan0805** [comment]
@CyberWake but in the main branch `Provider.of<GraphQLConfiguration>(context).displayImgRoute +
                  member['image']`  this is written

**Comment by CyberWake** [comment]
> @CyberWake but in the main branch `Provider.of<GraphQLConfiguration>(context).displayImgRoute +
>                   member['image']`  this is written

Can you please specify the file name?

**Comment by ishan0805** [comment]
members.dart line no. 250

**Comment by CyberWake** [comment]
> @CyberWake but in the main branch `Provider.of<GraphQLConfiguration>(context).displayImgRoute +
>                   member['image']`  this is written

Basically there is image field in user, organization and member.

**Comment by ishan0805** [comment]
Yes I was saying can you print the result of `Provider.of<GraphQLConfiguration>(context).displayImgRoute + member['image']`
like what url is being used to fetch pictures

**Comment by CyberWake** [comment]
> Yes I was saying can you print the result of `Provider.of<GraphQLConfiguration>(context).displayImgRoute + member['image']`
> like what url is being used to fetch pictures 

It's absolutely ok bro. You can check on line 222 a map containing member details is passed.

**Comment by CyberWake** [comment]
> > Yes I was saying can you print the result of `Provider.of<GraphQLConfiguration>(context).displayImgRoute + member['image']`
> > like what url is being used to fetch pictures 
> 
> It's absolutely ok bro. You can check on line 222 a map containing member details is passed to the function with argument name member. And hence the member map contains the detail of single member with image field in it.
