### ISSUE TITLE
(Bug) All days in the month get marked in the calendar on creating a 'daily' event

### ISSUE THREAD

**Issue by CoderMayhem** [PalisadoesFoundation/talawa#501]
- **Issue Description:** Right now all days in the calendar get marked if a daily recurring event is created, rather only those days should be marked which lie between the timeline of the event. 

- **Issue Severity:** Medium

- **Environment Details:** Bug in events.dart

- **Observed Behaviour:** Problem exists in both daily and weekly events as even the days before the starting of events end up getting marked.

- **Expected Behaviour:** Only those events which lie within the `Start Date` and `End Date` should end up getting marked.

- **Snapshots/Videos:** 
![calendar](https://user-images.githubusercontent.com/56952811/112355478-b1a11e80-8cf3-11eb-8f5a-8e672e3177f1.png)

- **Does this issue need immediate attention?** Yes.
- **Are you willing to work on this issue:** Yes. Opening a PR which fixes this shortly.

**Comment by nerdynikhil** [comment]
I want to work on this.
