### ISSUE TITLE
Just After Sign up

### ISSUE THREAD

**Issue by shikharsaurav** [PalisadoesFoundation/talawa#503]
Issue Description:
if we signup for  & without selecting any organization & click on back we go just exit it the app & goes to entry page of app

Observed Behaviour:
Goes to entry page of App

Expected Behaviour:
Go to profile page

Snapshots/Videos:
https://thepalisadoes-dyb6419.slack.com/files/U01RQUQE2TW/F01SF51MADS/pehla_signup.mp4

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by shikharsaurav** [comment]
@Sagar2366  plz assign me this issue

**Comment by Sagar2366** [comment]
@shikharsaurav think of better solution for this scenario from end user perspective.
If user is signed in and not joined to any organisation, first message he should get is "Please join organisation to proceed" or something similar. 
By allowing user to scroll through newsfeed, events page when it is not part of any organisation and specially when there is no data available for user it doesn't look nice.
I am sure we can provide user better redirection in this scenario.

**Comment by CyberWake** [comment]
@shikharsaurav i guess this is no longer a issue on master branch itself. please close this issue.
