### ISSUE TITLE
[Bug] Error data!=null after adding a tasks to an event . 

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#507]
Issue Description:
I tried to add a task in an already created event and when I tried to load it this error came up. This might be due to not returning the correct type of value.
Also, nothing is being displayed if no tasks are there. It would be a better if user gets something like "No Tasks Found" that would be more intuitive for them. 

Observed Behaviour:
Error shows up

Expected Behaviour:
List the tasks created

Snapshots/Videos:
![Screenshot_20210325-151857](https://user-images.githubusercontent.com/51524156/112454225-7992ed80-8d7e-11eb-8edf-12900f4e87ca.png)

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes, and I have worked on a similar issue. This issue came up while I was working on  issue #188 .

P.S - Is there another syntax through which I can make these photos smaller? The HTML work isn't working on me it makes the image corrupted.

**Comment by pr4nshul** [comment]
@Sagar2366  can you assign me this?

**Comment by Sagar2366** [comment]
@pr4nshul one issue at a time - I have already assigned 
https://github.com/PalisadoesFoundation/talawa/issues/188 to you.

**Comment by pr4nshul** [comment]
Ok, Though the button is working as I have checked we need to pull to refresh on events page, and go out of members to display the registered events of a member. It's working as intended. The only issue is with displaying it. I will probably solve it by tonight.

**Comment by Sagar2366** [comment]
Need more clarity - which issue you want to work on ?
Issue number - 188 or 507 ?

**Comment by pr4nshul** [comment]
What i meant was issue #188 looks like an issue on the front end but on the back end it is working as it should . So , that won't consume anytime. Well , I am going to give you an update on that issue in the next 10 min. You will get it , what I was trying to say. Sorry if it got a little confusing here.

**Comment by pr4nshul** [comment]
@Sagar2366  I have updated the issue #188 and created a PR for the same #509, I think you might get what I was trying to say. I would also like to work on this issue.

**Comment by shardulinamdar4** [comment]
@Sagar2366 can you assign me this issue?

**Comment by pr4nshul** [comment]
@shardulinamdar4  This issue is already resolved :)
