### ISSUE TITLE
[Bug] - Tab bar pages not refreshed automatically on org switching and edge case not handled

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#514]
- **Issue Description:**
State not handled properly in members page. And inappropriate message.
On suggestions as asked by @Sagar2366 sir [here](https://github.com/PalisadoesFoundation/talawa/pull/607#issuecomment-817335868)
Auto refreshing of event page, feeds page, and chats 

- **Issue Severity:**
High.

- **Environment Details:**
Home page-> Members tab
Visit it directly on app launch. Now go to the profile page switch the organization again visit members tab page is not refreshed.
Now leave/remove all the organizations than visit member page page doesn't get refreshed automatically as well as on pulling down to refresh refresh button is visible which should not be there as the user in not in any organization.
Switch the current org to new one still the tab bar pages show data relevant to previous organization. 
Not specific to members page all the pages on tab bar don't refresh automatically on change in current organization data

- **Observed Behaviour:**
Even if the user is not in organization he see a refresh button which is of no use to him. Comes handy only in case of internet connectivity that to for the user who has joined at least on organization. The all tab bar page doesn't update automatically on change in current organization.

- **Expected Behaviour:**
There should not me refresh button if the user is not joined any organization something more meaning full should be displayed.
tab bar page should automatically update on change with current organization.

- **Steps to reproduce issue:**
Follow the video and it has more ways as well you may direct visit without joining any organization or vice versa.

- **Snapshots/Videos:** 
Attaching a demo video.
<kbd><img src="https://user-images.githubusercontent.com/44184786/112527539-2e51fc80-8dc9-11eb-82a4-1f2bfa7de748.gif" width="250"></kbd>

- **Does this issue need immediate attention?**
Yes, this need to be resolved so that the user doesn't see inappropriate data.

- **Are you willing to work on this issue:**
Yes, I am will to work on this issue.

- **Other information:**
@Sagar2366 sir please assign this issue to me.

**Comment by pr4nshul** [comment]
Yes, this needs to be worked on. This issue in the comments of issue #307. As mentioned there, this could give user a feeling of not being a able to switch org or even leave org. Because this issue is still there even if user leaves a org.

**Comment by CyberWake** [comment]
i have fixed this one. need to make a PR after getting assigned

**Comment by pr4nshul** [comment]
Nice 👍 , I am not looking to work on it. I was just mentioning I faced a similar issue. And this needs immediate attention 💯

**Comment by CyberWake** [comment]
can you fetch the master the issue marked in #307 was resolved with the merge of #355

**Comment by pr4nshul** [comment]
That's not what I meant if you would read the comments. I mentioned something similar to your issue. I am on the latest master. Appreciate your effort to help though! 👍

**Comment by CyberWake** [comment]
@Sagar2366 please review the PR #519 . Don't know why it didn't got linked with the issue.🙂
