### ISSUE TITLE
[exception]User is not authenticated when trying to register for event.

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#515]
Issue Description:
User is not authenticated exception is thrown on the console when you try to register for an event if logged in for some decent time  and you have build and rebuild app multiple times with the same login state. You need to logout and login again to register for an event.

Issue Severity:
Medium

Observed Behavior:
Can't register for an event even if you are logged in according to the app.

Expected Behavior:
Should be authenticated and should be able to register for the event

Steps to reproduce issue:
Login into the app and build and rebuild multiple times without logging out and be logged in for like 10-15 min try to register for an event on the events page , I think probably it would be thrown on a real device as in an emulator the login state is always initialized.

Snapshots/Videos:
Attaching a console screenshot
![Screenshot (228)](https://user-images.githubusercontent.com/51524156/112532910-65c3a780-8dcf-11eb-94c0-df24c31d9f48.png)

Does this issue need immediate attention?
Yes, this need to be resolved otherwise user would feel like the button is not working or the app has hanged.

Are you willing to work on this issue:
Yes, I am willing to work on this issue.

**Comment by CyberWake** [comment]
While restarting the app we still see the is error marked in #448 though the restart now doesn't get the app stuck with progress indicators and only the nav bar. But once we do an hot restart there is still a graphql error displayed displayed. Resolving that might solve this problem as well.🙂

**Comment by pr4nshul** [comment]
Yes, so are you on anyone working on that issue?

**Comment by CyberWake** [comment]
You can work on this one busy with other one.👍

**Comment by pr4nshul** [comment]
Though if we have to work on Talawa-API for this , then you can assign someone else @Sagar2366 . Because , I am not familiar with JS.

**Comment by pr4nshul** [comment]
I will update the issue description accordingly :)

**Comment by pr4nshul** [comment]
> 
> 
> Though if we have to work on Talawa-API for this , then you can assign someone else @Sagar2366 . Because , I am not familiar with JS.

Hey @Sagar2366  can you approve this issue? And tell me about whether we need to work on Api for this. If , not I would like to be assigned as my other PR is on hold right now due to Travis CI build fail
