### ISSUE TITLE
[Enhancement] Improving response of validators and reducing unnecessary calls to API server

### ISSUE THREAD

**Issue by arteevraina** [PalisadoesFoundation/talawa#516]
### Issue Description.
1. In `Register Page`, when `text field` is empty (for example: First Name , the validator responds with message like First Name cannot be left blank, But when the email field is empty it does not respond with `Email cannot be left blank` but rather it shows `Not a valid Email Address`). I think `Not a valid Email Address`  should be shown when actually email address is invalid not when it is left blank.
       **Possible Solution:**  Play with some conditions in the `validator` class.
2. `In Login Page`, we are not even validating the fields, though we are doing a check `_formKey.currentState.validate()`  before hitting the API but that is not doing anything good since it is always validating to` true`. This is resulting in unnecessary API calls on the server.
      **Possible Solution:** use TextEditingController and `validators` in Text Fields in `Login Page`.
After doing these changes some changes also need to be made in the unit tests for `validators` to test the new behaviour. If this gets approved, I am happy to chime in and fix this up.

### Issue Severity
Medium

### Does this issue needs immediate attention ?
Yes.

### Are you willing to work on this issue ?
Yes.

**Comment by Sagar2366** [comment]
@arteevraina please use issue template and update all the required details.
