### ISSUE TITLE
Caution Words not visible clearly

### ISSUE THREAD

**Issue by sainiteshb** [PalisadoesFoundation/talawa#526]
# Issue Description
-When an invalid or a wrong org URL link is given, the app returns a caution or a reminder saying that 
"PLEASE ENTER AND SAVE URL  TO CONTINUE".
-As you can see in the picture provided, the words are not clear which cannot be seen as they get mixed with the picture.

-You can assign me this issue, I can fix this problem. And make this make User friendly.

#Steps to reproduce issue
-Open the app
-Leave the ORG URL link empty and press enter or set Url

# Does this issue need immediate attention?
-Yes

#Are you willing to work on this issue?
-Yes

# Snapshots
![2021-03-26 (6)](https://user-images.githubusercontent.com/67225871/112629465-5f2e4200-8e5a-11eb-9439-32f6ddd137fa.png)

**Comment by Sagar2366** [comment]
@sainiteshb do you see this error on latest master ?

**Comment by sainiteshb** [comment]
Yes

**Comment by palisadoes** [comment]
@sainiteshb Please work on this as the freeze has been removed.

**Comment by sainiteshb** [comment]
Yes, I will be working on this. Happy to say that looking forward to the chance to work with you guys through GSoC 😊
