### ISSUE TITLE
Search Organisation page shows a gray patch

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#528]
Issue Description:
When we search for an organisation, a grey area shows up and the data is not shown.

Observed Behaviour:
A grey area is shown when we search for an organisation.

Expected Behaviour:
A listview of organisations must be shown cleanly

Snapshot:
https://drive.google.com/file/d/1EhpuMAdnl3rzPkMLpHGcvBdqq_uwMxdV/view?usp=sharing

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by CyberWake** [comment]
Can you please elaborate on how to replicate this one.🙂

**Comment by Hrishikesh-Bhagwat** [comment]
Just search and you will get an eternally long listview with grey patch. Search testy.... results will be less and grey patch will come

**Comment by CyberWake** [comment]
> Just search and you will get an eternally long listview with grey patch. Search testy.... results will be less and grey patch will come

are you running the app in release mode 🤔

**Comment by CyberWake** [comment]
So basically the exact issue is the filtered list has some invalid index which is being rendered and causing grey patch in release mode and red one on debug mode.
