### ISSUE TITLE
[BUG] Comment count is not updated in newsfeed page

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#535]
- **Issue Description:** <Add brief description about issue or feature you want to add.>
 After adding comments to a post the comment count in not updated on Newsfeed Page .
- **Issue Severity:**  Medium 
- **Environment Details:**  Found in `newsfeed.dart`, `newsArticle.dart`
- **Observed Behaviour:** The Comment count is not updated .
- **Expected Behaviour:** The Comment count should be updated.
- **Steps to reproduce issue:** Add a comment to the post , its comment count wont be updated on newsfeed page
- **Snapshots/Videos:** 
   This is the expected behaviour:
  https://user-images.githubusercontent.com/57677520/111905684-ea7e9080-8a72-11eb-81de-648d01a4c0dc.mp4

- **Does this issue need immediate attention?** No
- **Are you willing to work on this issue:** Yes

**Comment by pr4nshul** [comment]
Hey , I am sure you are not on the latest master as in the video your profile image in the comments is not being shown. Please pull the latest master.

**Comment by utkarshshendge** [comment]
Hey @pr4nshul , the video was captured few days back.
