### ISSUE TITLE
Time of comment updated on UI for every single second

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#536]
- **Issue Description:** Time of comment updated on UI for every single second
- **Issue Severity:** Low
- **Environment Details:** Found in `talawa\lib\views\pages\newsfeed\newsArticle.dart`
- **Observed Behaviour:** Time of comment updated on UI for every single second
- **Expected Behaviour:** If the comment is added less than a minute ago, then it should show `Less than a minute ago.` else it should show for eg: `1 min ago`.
- **Steps to reproduce issue:** Add multiple comments for a post and see their times.
- **Snapshots/Videos:** 

> 
<img src="https://user-images.githubusercontent.com/56073198/112715443-395e7700-8f06-11eb-98be-f1ce9a64c650.png" width="300" height="600">
<img src="https://user-images.githubusercontent.com/56073198/112715446-3c596780-8f06-11eb-976e-4fa08d1e4d99.png" width="300" height="600">

- **Does this issue need immediate attention?** No
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

**Comment by sudo-vergil** [comment]
Isn't this an enhancement?
I also don't understand why this needs immediate attention.

**Comment by Raunakk02** [comment]
Since it is re-rendering the UI multiple times and also causing UI to look
ugly therefore I was unable to clearly differentiate whether it's a bug or
an enhancement and for the same reason I felt that this needs immediate
attention. But if that's not the case then I'll change this to an
enhancement and also change the attention status.
Requesting your views on this!

**Comment by Raunakk02** [comment]
@Sagar2366 can you assign this to me!
