### ISSUE TITLE
Events, newsfeed, etc. should be blank for newly created organizations

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#537]
- **Issue Description:** Events, newsfeed, etc. should be blank for newly created organizations
- **Issue Severity:** Low
- **Environment Details:** Almost in the whole app
- **Observed Behaviour:** Currently default data is getting loaded for newly created organizations.
- **Expected Behaviour:** It should be blank for newly created organizations
- **Steps to reproduce issue:** Create an organization and switch to members or events tab.
- **Does this issue need immediate attention?** Yes
- **Are you willing to work on this issue:** Yes, I am willing to work on this issue!

**Comment by CyberWake** [comment]
@Raunakk02 members screen can't be blank for newly created organizations as logically there would be at least one member present if the organization is present.

**Comment by Raunakk02** [comment]
Thanks for pointing this out @CyberWake. I will just modify the issue title and description. Since it was something that we discussed on slack so I put it up here. But now I noticed that the member page won't be blank, but default data should also not get loaded for the same.

**Comment by harshkumarkhatri** [comment]
Hey Raunak, can you specify in which screen the default data is being loaded?

**Comment by Raunakk02** [comment]
In the events screen, the events from another user, who is not in an organization that I created, are being displayed. Currently, I am the only member of that organization. Also, the newsfeed screen was showing an infinite loading spinner for the newly created organization.

**Comment by harshkumarkhatri** [comment]
Have you tried printing the data which you get from the event which are being displayed in the event screen from the user, not in the organization?
If yes, can you please provide a snippet from it?

**Comment by Raunakk02** [comment]
Closing this issue since it was solved by the earlier created PRs.
