### ISSUE TITLE
Incorrect Validation for Password on SignUp page

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#538]
- **Issue Description:** The Validator used does not take _ as a special character
- **Issue Severity:** Medium-Low
- **Environment Details:** When the app is run, and orgURL is added, _ isn not taken as a special character
- **Observed Behaviour:** _ (Underscore) Not a special Character
- **Expected Behaviour:** Underscore is to be considered as a special character for the password
- **Snapshots/Videos:** ![image](https://user-images.githubusercontent.com/23498248/112722445-9fabbf80-8f2f-11eb-8c8b-d7816b2dbc3b.png)
- **Does this issue need immediate attention?** Yes, as it deals with security
- **Are you willing to work on this issue:** Yes

**Comment by harshkumarkhatri** [comment]
I have gone through the code. It is not considering '(', ')', '{', '}' and many more. Can you please add them as well, if you are assigned with this issue?

**Comment by adithyaakrishna** [comment]
> I have gone through the code. It is not considering '(', ')', '{', '}' and many more. Can you please add them as well, if you are assigned with this issue?

Sure @harshkumarkhatri 
This is a package issue so I had a talk with the maintainer of the repo and had to get it fixed from the root so that future users do not face the similar issue. You can view the progress here at, https://github.com/ArefMozafari/flutter_pw_validator/issues/1

**Comment by harshkumarkhatri** [comment]
Cool, Thanks for the consideration.

**Comment by adithyaakrishna** [comment]
This package was added by @shikharsaurav 
As he was working on Issue #366 
The validator which exists as a function cannot be seen visually whether the password is weak, medium or strong and the package helps in that basically😶
