### ISSUE TITLE
[Bug] - Login and Signup buttons take gestures even on a pending API result.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#542]
- **Issue Description:**
Login and Signup buttons on the respective pages take user taps even when the API result is being waited upon for the respective data to be displayed. This causes the next API call made and the buttons again turning to text. For more look through the demo snapshots attached.

- **Issue Severity:**
Medium, as it is a edge case

- **Environment Details:**
Login and signup buttons on respective pages.

- **Observed Behaviour:**
The button make repeated calls to the API on picking multiple taps while the previous call is waiting for the result.

- **Expected Behaviour:**
Buttons show have a flag value such that the button does not picks up ontap geture only when the we are waiting for the API result to fetched.

- **Steps to reproduce issue:**
Hit the respective buttons after filling desired credentials required and than click the button multiple times.

- **Snapshots/Videos:**

 | [**Login**](https://user-images.githubusercontent.com/44184786/112734637-03081280-8f6d-11eb-8f64-d79d2134e78b.gif)      | [**Sign Up**](https://user-images.githubusercontent.com/44184786/112734657-2f239380-8f6d-11eb-8618-77d63abec24e.gif)     | 
|------------|-------------| 
|  <kbd><img title="Earlier" src="https://user-images.githubusercontent.com/44184786/112734637-03081280-8f6d-11eb-8f64-d79d2134e78b.gif" width="250"></kbd> |  <kbd><img title="Now" src="https://user-images.githubusercontent.com/44184786/112734657-2f239380-8f6d-11eb-8618-77d63abec24e.gif" width="250"></kbd> |

- **Does this issue need immediate attention?**
Yes, being a edge case this could be possible for some user.

- **Are you willing to work on this issue:**
Yes, I am willing to work on it.

- **Other information:**
Please assign this issue to me. @Sagar2366 @DeltaHarbinger sir

**Comment by 01mahdivalipoor** [comment]
Has anyone solved this problem?

**Comment by CyberWake** [comment]
> Has anyone solved this problem?

Yes this issue is been solved as soon as the PR gets merged.
