### ISSUE TITLE
[Bug]State not handled properly in events page

### ISSUE THREAD

**Issue by Gourav2000** [PalisadoesFoundation/talawa#543]
- **Issue Description:** State not handled properly in events page. the new event does not get updated after event creation same with deletion
- **Issue Severity:** High
- **Environment Details:** Home page-> events tab
Visit it directly on app launch. Now go to the event page , create a new event, again visit events tab page is not refreshed.
it gets updated only when the app restarts, its result of poor state management 
- **Observed Behaviour:**after successful creation of new event, the new event does not appear on the events tab unless the app restarts
- **Expected Behaviour:**  after successful creation of new event,  the event tab should get immediately updated   
- **Steps to reproduce issue:** go to events tab create a new event then view the events tab again
- **Snapshots/Videos:**
  ![image](https://drive.google.com/uc?export=view&id=1pgcxmczB0zLcnH_a_qYEfUDZxU-f4avr)
- **Does this issue need immediate attention?** yes event management is a very important task in any app
- **Are you willing to work on this issue:** yes i want to work on this issue
- **Other information:** @Sagar2366  sir please assign this issue to me

**Comment by harshkumarkhatri** [comment]
Hey, in the call yesterday that currently, the mentor is thinking of going with the basic setState thing for updating the parts of the app. I don't think we can re-fetch the list of events again while being on the same screen.
We can consider using the pull-to_erefresh packages to add a pull option to re-fetch the list and dynamically update it on the go. But that would add one more dependency to the list of dependencies.

**Comment by palisadoes** [comment]
@Gourav2000 The code freeze is lifted. Are you still able to work on this?
