### ISSUE TITLE
[BUG] Validation needed in  add task popup 

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#545]
Description
 Validation is missing in add task . A user can try to add the task without any title and it will give error .

Issue Severity
medium

Observed Behavior:
Validation is not added when we add the task . 

Expected Behavior:
Validation should be present while adding tasks .

Steps to reproduce issue:
Adding Validation on add task popup .

Snapshots/Videos:
https://user-images.githubusercontent.com/57336738/112755716-9558f680-8fff-11eb-9e18-faf920ce0bb7.mp4

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by pr4nshul** [comment]
Hey, can you refresh the event page and then try it again?

**Comment by pr4nshul** [comment]
Hey , can you check your console log , does it show user is not authenticated when you try to add task?

**Comment by pr4nshul** [comment]
Because if I logout and login again it is working for me on the latest master. The only time I am facing it is due to the exception being thrown mentioned in the issue #515

**Comment by ishan0805** [comment]
In my case registration was working perfectly .

**Comment by ishan0805** [comment]
But I will check again

**Comment by ishan0805** [comment]
@pr4nshul you were right I have changed the error

**Comment by pr4nshul** [comment]
Close this issue @ishan0805 . As it is resolved 👍
