### ISSUE TITLE
[Enhancement] Stable user entry, removing unwanted multiproviders

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#547]
- **Issue Description:** <Add brief description about issue or feature you want to add.>
1. Unstabalise user entry.
![image](https://user-images.githubusercontent.com/47498552/112749373-9ed26680-8fdf-11eb-9154-ebe31c4b8f10.png)
 2. Currently we are making main function async just to load the userID.
![image](https://user-images.githubusercontent.com/47498552/112749350-6cc10480-8fdf-11eb-82f5-da8ba10799e4.png)
3. Useless duplication of multi providers in homePage.
![image](https://user-images.githubusercontent.com/47498552/112749432-dfca7b00-8fdf-11eb-86dc-d4f67c99d367.png)
4. Unused Function on HomePage.dart
![image](https://user-images.githubusercontent.com/47498552/112749476-fec90d00-8fdf-11eb-8a12-8d8891702c4f.png)

- **Issue Severity:** Medium
- **Environment Details:** <Add details about environment where this issue is found.>
- **Observed Behaviour:** <Add details about your observation related to this issue.>
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
- **Steps to reproduce issue:** 
- **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
- **Does this issue need immediate attention?** <If yes. Please explain in detail>Yes, Securing the entry point is an important aspect of the app.
- **Are you willing to work on this issue:** <Yes or No. If you are working on other issue then issue will get assigned to someone else for getting work done faster.>Yes
- **Other information:** <Add extra information about this PR here>
This issue fix will lead to more stabilise entry points and prepare the app for state-management.

**Comment by palisadoes** [comment]
@rutvik11062000 The code freeze has been lifted. Please proceed.
