### ISSUE TITLE
[BUG] Wrong logic of liking and disliking a post

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#549]
- **Issue Description:** <Add brief description about issue or feature you want to add.>
    We have a major bug in liking and disliking a post.
    What we are currently doing is
    1. When we like a post, we are adding {userId} at the end of the ['likedBy'] array.
    2. We are displaying the color of the like button just by checking if the lastEntry of ['likedBy'] array matches the user's ID.
    If any other user (User B)likes the same post after User A has liked the post, our logic fails here.
    Even though UserA has liked a post we are not showing.
    And hence userA is also not allowed to dislike these kind of post.
- **Issue Severity:** HIGH
- **Environment Details:** <Add details about environment where this issue is found.>
- **Observed Behaviour:** <Add details about your observation related to this issue.>
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
    Display Like Button with like color and have unlike functionality no matter where the userID is in ['likedBy']
- **Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.>
- **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
![image](https://user-images.githubusercontent.com/47498552/112753578-a7ce3280-8ff5-11eb-8191-f02d1804f1ae.png)
this 
- **Does this issue need immediate attention?** <If yes. Please explain in detail> Yes
It is the one of the most important function of the app and requires immediate rewriting of logic.
- **Are you willing to work on this issue:** <Yes or No. If you are working on other issue then issue will get assigned to someone else for getting work done faster.>Yes
- **Other information:** <Add extra information about this PR here>
We need to fix it ASAP.

**Comment by CoderMayhem** [comment]
@rutvik11062000 any updates on this issue?

**Comment by CoderMayhem** [comment]
@Sagar2366 @DeltaHarbinger this issue can be closed now. The associated PR has been merged.
