### ISSUE TITLE
User taken from Join org screen to Login sign up screen

### ISSUE THREAD

**Issue by harshkumarkhatri** [PalisadoesFoundation/talawa#559]
**Issue Description**: When the user has registered in the app, he is taken to the screen where he is supposed to select an organization or create one. If we click on the back button it takes us back to the login/create an account screen and the user has to now login with the credentials he has created the account with. This spoils the user experience.

**Issue Severity**: Moderate

**Environment Details**: App Opens->Login/Create an account screen->Choosing any of the two->Successful login/successful register->Join organization screen->Click back arrow or back button->Takes us back to Login/Create an account screen

**Observed Behaviour:** The user is taken back to the Login/signup screen.

**Expected Behaviour:** As the user has already logged in/ signed up successfully and his creds are stored he should not be sent to the login/signup screen. Rather than back-click, he should be exited out of the app.

**Does this issue need immediate attention?**
Yes as another [issue](https://github.com/PalisadoesFoundation/talawa/issues/561) depends on it.

**Are you willing to work on this issue:**
Yes, I am willing to work on this issue.

**Other information:**
Discussion link: https://thepalisadoes-dyb6419.slack.com/archives/C01RG2P5WLU/p1616872036418200
@Sagar2366 sir, please assign the issue to me.

**Comment by Hrishikesh-Bhagwat** [comment]
But I made a PR to it. And it was assigned to me later on. I did not solve anything where I was not assigned. The title samed vague. Trust me. It was not done deliberately.
