### ISSUE TITLE
[Enhancement]-Features after joining an organization not updated dynamically & Exception occurs when snackbar is displayed.

### ISSUE THREAD

**Issue by harshkumarkhatri** [PalisadoesFoundation/talawa#562]
**Issue Description:**
* When a user is joining an organization, he is displayed with the snackbar and is taken back to the profile screen but the options which should be there in the profile section are not there instantly because we are not using an efficient state management technique to update things dynamically. Watch [video 1](https://thepalisadoes-dyb6419.slack.com/files/U01SZJ0U6SD/F01T0MTHU01/video_1.mp4) for more light on this.
* When we have already joined an organization and we are trying to join the same organization again a snackbar is displayed which tells us that we are already a part of this but it also shows an exception related to rendering in the debug console. Watch [video 2](https://thepalisadoes-dyb6419.slack.com/files/U01SZJ0U6SD/F01SN9YKB3M/video_2.mp4) for more info on the exception.

**Issue Severity:** Medium

**Observed Behaviour:** 
* When we join the organisation, the features which are displayed when an organisation is joined are not updated dynamically.
* An exception in debug console when someone tries joining the same organization they are a part of and a snackbar is displayed. [Not sure but the exception occurs because the keyboard is active]

**Expected Behaviour:**
* Features like switch organisation, leave, organisation name, etc should be updated dynamically.
* The exception should not occur when the snackbar is displayed.

**Steps to reproduce issue:**
Watch the linked videos.

**Snapshots/Videos:**
* https://thepalisadoes-dyb6419.slack.com/files/U01SZJ0U6SD/F01T0MTHU01/video_1.mp4
* https://thepalisadoes-dyb6419.slack.com/files/U01SZJ0U6SD/F01SN9YKB3M/video_2.mp4

**Does this issue need immediate attention?**
No

**Are you willing to work on this issue:**
No

**Comment by Sagar2366** [comment]
@harshkumarkhatri you are referring two issues here -
1. dynamically updating organisation name : this is duplicate issue and should get fixed in another PR.
2. User trying to join same organisation - can you work on this ?

**Comment by arteevraina** [comment]
@harshkumarkhatri Since you are not willing to work on this issue. Can I take up this issue I have already fixed the 2nd part of the issue you described in the issue description ?

**Comment by harshkumarkhatri** [comment]
Cool you can work on this,
