### ISSUE TITLE
[Bug] Membership requests are not being displayed on the Accept Membership Requests page

### ISSUE THREAD

**Issue by Raunakk02** [PalisadoesFoundation/talawa#563]
- **Issue Description:** Membership requests are not being displayed on the Accept Membership Requests page
- **Issue Severity:** High
- **Environment Details:** Issue found in `talawa\lib\views\pages\organization\accept_requests_page.dart`
- **Observed Behaviour:** No request is displayed even if they are present.
- **Expected Behaviour:** Membership requests should be displayed
- **Steps to reproduce issue:** 
   

> 1. create a new private organization with one ID.
> 2. now login with another ID and send a membership request to the above-created organization and after that log out from this ID.
> 3. now log in again with the ID which was used to create the private org and visit the  Accept membership requests  section of the Organization Settings  page. 
> 4. Wait for the requests to load.

- **Snapshots/Videos:**
  

>    parentData: <none> (can use size)
>     constraints: BoxConstraints(0.0<=w<=352.7, 0.0<=h<=Infinity)
>    size: MISSING
>     axisDirection: down
>     crossAxisDirection: right
 >    offset: ScrollPositionWithSingleContext#e9d0f(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#2922d, ScrollDirection.idle)
>     anchor: 0.0
>    center child: RenderSliverPadding#08024 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
>         parentData: paintOffset=Offset(0.0, 0.0)
>         constraints: MISSING
>         geometry: null
>         padding: EdgeInsets.zero
>         textDirection: ltr
>         child: RenderSliverList#d7a24 NEEDS-LAYOUT NEEDS-PAINT
>             parentData: paintOffset=Offset(0.0, 0.0)
>            constraints: MISSING
>             geometry: null
>             no children current live
> > ════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by rendering library ═════════════════════════════════
> RenderBox was not laid out: RenderViewport#1d699 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
> 'package:flutter/src/rendering/box.dart':
> Failed assertion: line 1940 pos 12: 'hasSize'

> The relevant error-causing widget was
> ListView
> lib\…\organization\accept_requests_page.dart:195
> >════════════════════════════════════════════════════════════════════════════════
> 
> 
- **Does this issue need immediate attention?** Yes, because without resolving this issue private organizations will not be able to accept membership requests.
- **Are you willing to work on this issue:** Yes, I would love to work on this issue. Please assign this to me!

**Comment by CyberWake** [comment]
Please check the status of [file](https://github.com/PalisadoesFoundation/talawa/commits/master/lib/views/pages/organization/accept_requests_page.dart) on commit history on ```22cb53b``` changes made after it are causing problem thing have been copy pasted without check need to restore the changes made.
