### ISSUE TITLE
Upgrade node-notifier package to > version 8.0.1 in package-lock.json

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#565]
We need to remedy the following known vulnerability: https://github.com/advisories/GHSA-5fw9-fq32-wv5p

GitHub cannot automatically do the required update to > 8.0.1 because:

```
The latest possible version that can be installed is 7.0.2 because of the following conflicting dependency:

jest@26.0.1 requires node-notifier@^7.0.0 via a transitive dependency on @jest/reporters@26.0.1
The earliest fixed version is 8.0.1.
```

This update needs to be implemented and tested.

**Comment by palisadoes** [comment]
Assigned to @Hrishikesh-Bhagwat

**Comment by yasharth291** [comment]
if this work is not complete @palisadoes can I work on it @Sagar2366

**Comment by Hrishikesh-Bhagwat** [comment]
I am working on it.I know it was not complete facebook has not made a change in their official package yet. I had mentioned that to the mentors. As soon as it is done I will fix it.

**Comment by yasharth291** [comment]
okay i understood you can carry on

**Comment by Hrishikesh-Bhagwat** [comment]
Yeah but the strange part is npm does not show vulnerabilities in that package.
