### ISSUE TITLE
Organization creator can't delete said organization

### ISSUE THREAD

**Issue by dsantistevan** [PalisadoesFoundation/talawa#568]
- **Issue Description:** A user that just created an organization is unable to delete it.

- **Issue Severity:** Medium

- **Environment Details:** Running the backend API locally with Docker and the app on my own phone via Android Studio ver. 4.1.2. 
Platform: Windows 10 version 20H2.
- **Observed Behaviour:** The query to delete the organization throws an error saying that the user is not the creator of the organization and is unable to delete it, although the user is indeed the one who created the organization. The error showsin the screenshot
- **Expected Behaviour:** User is able to delete an organization

- **Steps to reproduce issue:** 
    0. Add ```print(result.exception.toString());``` at line 118 of the ```lib\views\organization\organization_settings.dart``` file to see the GraphQL error.
    1. Log In with a user without organizations joined or created
    2. Create an organization
    3. Log Out
    4. Log In again with the same user
    5. Profile Tab
    6. Organization Settings
    7. Remove this Organization
    8. Confirm
    9. If not updating, log out and in again, still, no changes will be made. 

- **Snapshots/Videos:** 
The following is the console for all the steps in the screenshots
![Delete Organization_Flutter Console](https://user-images.githubusercontent.com/43758544/113054696-5ba6fd80-916f-11eb-89c6-612e5626e8f4.png)

`

**Creation of the organization:**

https://user-images.githubusercontent.com/43758544/113205317-c3bf1780-9233-11eb-9fdb-61dc0c01e653.mp4

**Attempt to delete said organization after logging back in:**

https://user-images.githubusercontent.com/43758544/113205920-6a0b1d00-9234-11eb-8209-13df7f748d65.mp4

After this, the GraphQL error message is still the same as the one in the first picture.

- **Does this issue need immediate attention?** Yes, because if not fixed, an organization administrator would have problems having a dead organization that is unable to be deleted.
- **Are you willing to work on this issue:** Yes, I'm willing to do a PR to solve this problem.
- **Other information:** If needed, this might require a PR in the API, I haven't reached the source of the problem yet.

Edit: Changed screenshots to videos

**Comment by CyberWake** [comment]
hey @dsantistevan can you please share a demo video or something. 😊

**Comment by dsantistevan** [comment]
> hey @dsantistevan can you please share a demo video or something. 😊

Sure, I'll be uploading one in a couple hours

**Comment by dsantistevan** [comment]
@CyberWake I've just updated the original comment with the videos

**Comment by Sagar2366** [comment]
@dsantistevan thanks for opening this issue. We are planning to remove admin features to new portal (talawa-admin). Considering it we may not require to add this change here in talawa project.
