### ISSUE TITLE
[Bug] Organization Name not showing in profile page.

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#572]
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Organization name is shown as "No organization joined"
- **Issue Severity:** <High or Medium orLow> Medium
- **Environment Details:** <Add details about environment where this issue is found.>
- **Observed Behaviour:** <Add details about your observation related to this issue.>
  Imporpoper initialization of orgName
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
  Must be on a state function.
- **Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.>
  Set orgName inside build()
- **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
<img src = "https://user-images.githubusercontent.com/47498552/113087005-61005880-9200-11eb-8222-c90b94c2d541.jpeg" height=400 width=200></img>
- **Does this issue need immediate attention?** <If yes. Please explain in detail>Yes. It is displayed in profile page and it gives the visual representation to a user about in which organization is he into.
- **Are you willing to work on this issue:** <Yes or No. If you are working on other issue then issue will get assigned to someone else for getting work done faster.> No.
- **Other information:** <Add extra information about this PR here>

**Comment by theRoushan** [comment]
Can i work on this issue
