### ISSUE TITLE
Enhancement: Unselect an image

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#577]
Issue Description:
If a user selects an image, he must be able to unselect it too.

Observed Behaviour:
User cannot unselect image without back navigating

Expected Behaviour:
A user must be able to undo his image selection.

Steps to Reproduce:
Select an image and you cannot undo your selection.

Snapshot:
https://drive.google.com/file/d/1CxTj4arJYwTjvJLRMGacHLU8lbC7aoJg/view?usp=drivesdk

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by Sagar2366** [comment]
@Hrishikesh-Bhagwat use issue template and for everyone's understanding explain issue with sample video/screenshot or with example.

**Comment by Sagar2366** [comment]
Please add details while creating issue. On which screen your are seeing this issue, steps to reproduce issue, etc

**Comment by Hrishikesh-Bhagwat** [comment]
Yes sir I updated it.
