### ISSUE TITLE
Separate UI design and message for no results found and error occurred

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#578]
Issue Description:
If there is an error, an error page must be shown. But here a page is shown 'No data or an error occurred'

Observed Behaviour:
The user will not know if an error has occurred or the list is really empty

Expected Behaviour:
There must be a separate error page

Snapshot:
https://drive.google.com/file/d/1BVqLc5Qra62x2p5aTKjpIPgcBeCbvxOI/view?usp=sharing

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by Sagar2366** [comment]
@Hrishikesh-Bhagwat use issue template and for everyone's understanding explain issue with sample video/screenshot or with example.

**Comment by Sagar2366** [comment]
@Hrishikesh-Bhagwat can you spend time on this issue - update issue details by following our template and provide video demo to understand what you are pointing out ?

**Comment by sumitra19jha** [comment]
@Sagar2366 Can I work on this issue and come up with a solution to separate the error message with the empty list message?

**Comment by Sagar2366** [comment]
Let me send reminder one more reminder to @Hrishikesh-Bhagwat , are you willing to continue working on this issue ?
