### ISSUE TITLE
[Enhancement] Background got changed slightly while focusing and un-focusing from registration page

### ISSUE THREAD

**Issue by Jd-rathod** [PalisadoesFoundation/talawa#580]
## Description
When we start the app for the first time and try to register details, while input field get focused background changes or Zoomed out slightly as seen in the screenshots.

- when focused

![WhatsApp Image 2021-04-01 at 6 34 24 PM (1)](https://user-images.githubusercontent.com/57349543/113298047-0575be00-9319-11eb-9822-35dc6260d619.jpeg)

- Before focus

![WhatsApp Image 2021-04-01 at 6 34 24 PM](https://user-images.githubusercontent.com/57349543/113298080-0dcdf900-9319-11eb-99a8-199ae111b5bd.jpeg)

### Desired functioning
It should remain stable through out the process.

### Are You Willing to Work On This
yes

@Sagar2366  please assign this to me.

**Comment by Sagar2366** [comment]
@Jd-rathod not sure what you are pointing in this issue.
Can you provide video demo for this ?
