### ISSUE TITLE
[Bug] Loading spinner during organisation selection is not working properly

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#581]
## Issue Description:
Loading spinner is active for all organisation instead of selected organisation.

## Issue Severity:
No

## Observed Behaviour:
Loading spinner active for all organisation.

## Expected Behaviour:
Loading spinner should be active for selected organisation only.

## Steps to reproduce issue:
1. Signup
2. Select Organisation
3. See the spinner

## Snapshots/Videos:
https://user-images.githubusercontent.com/35868598/113311834-542a5480-9327-11eb-8f91-91b9dcffc29a.mp4

## Does this issue need immediate attention?
No

## Are you willing to work on this issue:
Yes

**Comment by adithyaakrishna** [comment]
@sumitra19jha Can I take this up and work on it?

**Comment by sumitra19jha** [comment]
Sure. Ask mentor to assign you this issue

**Comment by sumitra19jha** [comment]
Is this issue has been resolved?

**Comment by Sagar2366** [comment]
> Is this issue has been resolved?
> Can I work on this @adithyaakrishna

Yes it is, since there is no update from @adithyaakrishna someone else can work on this.

**Comment by sumitra19jha** [comment]
Can I work on this issue?

**Comment by adithyaakrishna** [comment]
@Sagar2366 Sorry I had been held up with some work from College regarding my Final Year Project. I was going to work on it today😶
