### ISSUE TITLE
[Bug] Login/ Signup Error due to URL link update

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#582]
## Issue Description
Current Url entry leads to error because url input takes additional keywords in the end.

## Issue Severity:
Low

## Observed Behaviour:
Entry format is: `<URL-INPUT>/talawa/graphql`

## Expected Behaviour:
Entry format should be: `<URL-INPUT>/`

## Steps to reproduce issue
1. Open App
2. Enter Url
3. Try to login/signup

## Does this issue need immediate attention?
Yes

## Are you willing to work on this issue:
Yes

## Other information:
Solution:
1. Go to `lib/views/pages/login_signup/set_url_pages.dart`
2. Change the following code: ```orgUrl =     "${dropdownValue.toLowerCase()}://${urlController.text}/";```

**Comment by StrangeNoob** [comment]
Just a suggestion, @sumitra19jha You can change the format to the <URL-INPUT>/grapql. I think it would be better for user perceptive.  What's your view on this ?

**Comment by sumitra19jha** [comment]
We will definitely have to do that as we need to have image url also accordingly.
