### ISSUE TITLE
It is still possible to go back to set url page by backpressing even on logging in.

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#584]
Issue Description: The user must not be able to go back to set url page on back pressing when logged in.
Issue Severity: Medium
Environment Details: Found in talawa\lib
Observed Behaviour: User reaches back to set url page on back pressing
Expected Behaviour: Once the user is logged in he must not go back to set url page
Steps to reproduce issue: Login and keep back pressing
Are you willing to work on this issue? : Yes I am willing to work on this issue

**Comment by CyberWake** [comment]
Similar one is #559 this will resolve the same issue you marked here.😉
