### ISSUE TITLE
[help wanted] I am getting this error after running " flutter run"

### ISSUE THREAD

**Issue by theRoushan** [PalisadoesFoundation/talawa#586]
- **Issue Description:** Installation help Required #helpwanted
- **Issue Severity:** Low
- **Environment Details:** after running - "flutter run"
- **Observed Behaviour:** BUILD FAILED  - Gradle task assembleDebug failed with exit code 1
- **Expected Behaviour:** NORMAL EXECUTION
- **Steps to reproduce issue:** 
- **Snapshots/Videos:** 
![Screenshot from 2021-04-01 21-17-48](https://user-images.githubusercontent.com/52878060/113373558-b3d92d80-9330-11eb-8e2c-7bee998e3f7b.png)

- **Does this issue need immediate attention?** - YES, i am unable to run the app for the first time.
- **Are you willing to work on this issue:** No

**Comment by harshkumarkhatri** [comment]
https://thepalisadoes-dyb6419.slack.com/archives/CSW3ETABE/p1616853462478400
Can you try the solutions which are listed in this thread?

**Comment by theRoushan** [comment]
Reinstalling flutter from snapd store in ubuntu solved this issue.
[issue_closed #586]

**Comment by theRoushan** [comment]
Reinstalling flutter from snapd store in ubuntu solved this issue.
[issue_closed #586]
