### ISSUE TITLE
Add fields like phone number, serial number, model, etc while registering

### ISSUE THREAD

**Issue by vrushti-mody** [PalisadoesFoundation/talawa#590]
It would be good to determine a way to register not just users but also their devices with the API. A method that tracks the phone number, serial number, make, model etc that uniquely identifies the device.

We may want a way to track not just the number of users but also the number of devices logged in, and unique user/device combinations. Active devices versus registered devices etc.

This could be useful for reporting and our plugin requirement

**Comment by vrushti-mody** [comment]
Please assign this issue to me

**Comment by yasharth291** [comment]
hello @vrushti-mody i think this is not a bug but this is an enhancement and because of code freeze it should be kept on hold. 😊

**Comment by vrushti-mody** [comment]
> hello @vrushti-mody i think this is not a bug but this is an enhancement and because of code freeze it should be kept on hold. 😊

I had a discussion with Peter regarding this. He suggested I open the issue and work on it. While I wait, is there anything I can work on?

**Comment by yasharth291** [comment]
for this you have to ask @Sagar2366 sir

**Comment by vrushti-mody** [comment]
@Sagar2366 Hey! Can you help?

**Comment by theRoushan** [comment]
> It would be good to determine a way to register not just users but also their devices with the API. A method that tracks the phone number, serial number, make, model etc that uniquely identifies the device.We may want a way to track not just the number of users but also the number of devices logged in, and unique user/device combinations. Active devices versus registered devices etc.This could be useful for reporting and our plugin requirement

Yes I agree. But instead of taking input from User itself, will make user more difficult to Singup/Register for this app. So we need to automate this, In flutter , you can fetch device information using followed dependency.
```dependencies:
  device_info: ^0.4.1+5 //add this in pubspec.yaml
```

#### I hope this will help you.
