### ISSUE TITLE
Shared Preferences is not secure enough to store tokens

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#593]
Issue Description: Sensitive information such as user tokens must not be stored in shared preferences. Some encryption is desirable.
Issue Severity: Medium but can be a big vulnerability
Observed Behavior:  Shared preferences stores user tokens in plain text
Expected Behavior: Tokens must be stored using some encryption
Does this issue need immediate attention? Yes
Are you willing to work on this issue: Yes, I will work.

**Comment by Hrishikesh-Bhagwat** [comment]
@Sagar2366 please assign me this issue

**Comment by amul-dhungel** [comment]
Hello @Hrishikesh-Bhagwat you can use crypto package from flutter pub dev

import 'dart:convert';
import 'package:crypto/crypto.dart';

void main() {
  var key = utf8.encode('token');
  var bytes = utf8.encode("foobar");

  var hmacSha256 = Hmac(sha256, key); 
  var digest = hmacSha256.convert(bytes);
  
  print(hmacSha256);
  print(digest);

}

**Comment by Hrishikesh-Bhagwat** [comment]
Hi Amul Dhungel! We can use flutter_secure_storage it uses keystore in IOS and AES in android. It will be much better according to me. Thanks for telling me about this too. Actually I have solved this on my end already. There are some conflicts in merging, trying to rectify those!

**Comment by amul-dhungel** [comment]
@Hrishikesh-Bhagwat That's great
