### ISSUE TITLE
[Bug] Toast text RenderFlex overflowed issue

### ISSUE THREAD

**Issue by Udit-singh** [PalisadoesFoundation/talawa#594]
- **Issue Description**
    At Create Organization page, Toast text RenderFlex overflowed issue

- **Issue Severity**
     Low

- **Observed Behaviour:**
     Toast text was overflowing by 303 pixels

- **Expected Behaviour:**
      Wrap text on overflow, like insert ellipsis or fade 

- **Steps to reproduce issue:**
      1. Open App
      2. Enter Url
      3. Try to Create organization

- **Snapshots/Videos:**
<img src="https://user-images.githubusercontent.com/55452299/113471005-26ecbc00-9477-11eb-889c-dae298e6dc2f.jpeg" width="300" height="500">

- **Does this issue need immediate attention?**
      Yes

- **Are you willing to work on this issue:**
     Yes

- **Other information:**
     Please assign this issue to me. @Sagar2366 @DeltaHarbinger sir

**Comment by amul-dhungel** [comment]
@Udit-singh  Please assign this to me

**Comment by Udit-singh** [comment]
> @Udit-singh  Please assign this to me

@amul-dhungel Has I have raised the issue it was supposed to assigned me, and I was waiting for the response !!

**Comment by amul-dhungel** [comment]
@Udit-singh , if you really want to merge it then I will help you. I was just here to solve problem and we are here to solve problems :). Go to create_organization.dart
then, paste this code
  _exceptionToast(String msg) {
    Widget toast = Container(
        padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 14.0),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
          color: Colors.red,
        ),
        child: Text(msg));

    fToast.showToast(
      child: toast,
      gravity: ToastGravity.BOTTOM,
      toastDuration: Duration(seconds: 1),
    );
  }

replacing it to the orginal method

**Comment by Udit-singh** [comment]
@amul-dhungel I am also a participant, And I have clearly mentioned in the issue
`Are you willing to work on this issue: Yes`
So please read issue properly.

**Comment by amul-dhungel** [comment]
Sorry man, I know, I read it. Its okay, it is all yours :)

**Comment by Sagar2366** [comment]
@Udit-singh please start working on this issue.

**Comment by Udit-singh** [comment]
Sure @Sagar2366 , Thanks.
