### ISSUE TITLE
Displaying No org joined when part of an org

### ISSUE THREAD

**Issue by pr4nshul** [PalisadoesFoundation/talawa#597]
Issue Description: On profile page current organisation is showing no org joined but I am part of 2 organisations.
    Issue Severity: Low
    Observed Behaviour: Displaying no organisation joined
    Expected Behaviour: Display current org name
    Steps to reproduce issue: Go to your profile page

    Snapshots/Videos:
![Screenshot_20210403-203933](https://user-images.githubusercontent.com/51524156/113482769-be74fd80-94bd-11eb-8e6f-31f75edf5d67.png)

    Does this issue need immediate attention? No
    Are you willing to work on this issue: Yes
    Other information:
    @Sagar2366 can you assign me this?

**Comment by Sagar2366** [comment]
Duplicate issue - https://github.com/PalisadoesFoundation/talawa/issues/572
