### ISSUE TITLE
While searching for organisations, if there are no results found, the entire list of present organisations is displayed.

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#598]
Issue Description: If no organisations can be found, a page saying no results found must be displayed and not the entire list.
Observed Behavior: The whole list of organisations is displayed when search does not yeild results.
Expected Behavior: An empty page saying no results found must be displayed.
Does this issue need immediate attention? Moderate attention
Are you willing to work on this issue: Yes, I will work.

**Comment by amul-dhungel** [comment]
@Hrishikesh-Bhagwat  Would you please assign this to me?

**Comment by Hrishikesh-Bhagwat** [comment]
Bro I am a student. 😂. You can find more issues report them and solve them

**Comment by amul-dhungel** [comment]
Thats fine yar.
