### ISSUE TITLE
Login form using same validations as Registration form.

### ISSUE THREAD

**Issue by Enigma04** [PalisadoesFoundation/talawa#600]
@Sagar2366 approve of this.
Issue Description:
While logging in, The password TextFormField shows that the written password is invalid. It is using the same form of validation that the Registration page is using. Eg: A password should have:

At least one numeric character
At least one uppercase letter
At least one special character
Should have at least 8 characters long
Expected Behaviour:
It should show nothing but a toast message just in case the user credentials don't match what is in the database and it should show "Field required" if the user tries to submit without entering anything.
Does this issue need immediate attention?
yes

Are you willing to work on this issue:
Yes

**Comment by arteevraina** [comment]
Hi @Enigma04! I think it is the desired behaviour in the login page. Since, we have already followed the guidelines in the Register Page and created the password. Now, in the login page if the user does not follow these guidelines (At least one numeric character, At least one uppercase letter, At least one special character, Should have at least 8 characters long) the password is invalid implicitly. I think it would not be a good idea to hit the API with a password that does not follow guidelines.  Hope you understand what I am trying to convey :)

**Comment by Enigma04** [comment]
Hey, @arteevraina! I got what you're trying to say and thanks for bringing that to our attention, but I still don't think we are actually supposed to hint at how a password should be if we're logging in. In fact, I have never seen validations from the registration page being used on a login page in almost any deployed software. Also, we discussed about this on Slack and Sagar has given permission to make changes. Thanks again :)

**Comment by arteevraina** [comment]
ok cool! No worries

**Comment by Sagar2366** [comment]
@arteevraina @Enigma04 this issue come for old users(created before introducing password validator). From now on if user is not following password creation guidelines then they will not be able to create account. Thus no need to add password validation at login page.

**Comment by theRoushan** [comment]
I think this issue is resolved now. Please close this issue.

**Comment by AniketSindhu** [comment]
@Sagar2366 so what will old users do there is also no option to reset password

**Comment by theRoushan** [comment]
@AniketSindhu I think there will be no issue, because this app is under development phase. No real users will be impacted from this🙂.
So don't worry.

**Comment by AniketSindhu** [comment]
@theRoushan problem is the I am not able to log in now

**Comment by theRoushan** [comment]
Try with another gmail bro.😂 You can reset your password once the reset password feature comes live.
