### ISSUE TITLE
Freezing of an App when navigated between member details "Registered Event" and "Task"

### ISSUE THREAD

**Issue by amul-dhungel** [PalisadoesFoundation/talawa#609]
Issue Description
App freezes in debug mode as soon as the user navigates between tab of members details. This mainly because of calling set state between. And registered event are also not shown when app freezes. This might causes, future developer to handle the
unnecessary bug during development. Some bugs can only be detected in debug mode, but works fine in launch mode.

Issue Severity: Medium but can be a big vulnerability

Observed Behavior: App freezes viewing member details

Expected Behavior: Members details like registered events and tasks should be shown.

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes, I will work.

https://user-images.githubusercontent.com/51743296/113536077-e7e47500-95f4-11eb-9483-09aaee033dc8.mp4

@Sagar2366  Please assign this to me sir.

**Comment by Sagar2366** [comment]
@amul-dhungel add detailed steps to reproduce this issue.
Do you see this error for newly created organization or on joining existing organization ?

**Comment by amul-dhungel** [comment]
@Sagar2366 Hello sir,  I saw this error in both organization. The thing is the error throws up in debug mode, but in launch mode it wont freeze. This bug is specially focused for future developer. So that they wont have to bug around for fixing this simple bug instead of focusing on making app more robust and almost in production.
