### ISSUE TITLE
Confusing Buttons before Setting Organisation URL

### ISSUE THREAD

**Issue by theRoushan** [PalisadoesFoundation/talawa#611]
- **Issue Description:** 
  The Main Goal of User should be to set Organisation URL.
 But "Create an Account" button and Login Button, confuses the user. 
**Both buttons donot have any value before setting URL**.
- **Issue Severity:** 
  Low
- **Environment Details:** 
  Visual Studio Code
- **Observed Behaviour:** 
  Create an Account button visible before entering Organisation URL. And It doesn't have any action at that time.
- **Expected Behaviour:**
  Both Buttons should be visible after the user enter's Organisation URL.
- **Steps to reproduce issue:** 
  1. Open talawa app (User must be logged out.)
  2. Observe the first Screen(i.e Set Org URL Page)
- **Snapshots/Videos:**
![WhatsApp Image 2021-04-05 at 12 52 21 AM](https://user-images.githubusercontent.com/52878060/113542123-379d4f00-95a9-11eb-8938-b69add407844.jpeg)
  Both buttons confuses the user before submitting url. So it must be visible after entering Organisation URL.
- **Does this issue need immediate attention?**
  No, But very important as per User Experience.
- **Are you willing to work on this issue:** 
  Yes, I am willing to work on this issue.
- **Other information:** <Add extra information about this PR here>
  Please let me know, if I am wrong. Or there could be any better option.

**Comment by Sagar2366** [comment]
Please do not create duplicate issues - https://github.com/PalisadoesFoundation/talawa/issues/435
