### ISSUE TITLE
New look to Talawa app with UI/UX Revamping

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#614]
Issue Description: We need to upgrade UI/UX of Talawa app during GSoC period. 
Issue Severity: High
Environment Details: Android and iOS devices

This is pre-GSoC activity for students to come up with better UI/UX ideas for Talawa app.
Factors to consider while proposing new UI/UX:
1. Color scheming - Consider colors which should be globally adaptive across all communities. Multiple factors needs to be considered while proposing new color schems - different age groups, different communities, different country rules, etc.
2. Fonts - It should look clean and clear to everyone and can be adjustable through settings.
3. Components positions on screen
4. Should be consistent through out app and for all devices.
5. Add support for dark theme

We need someone to go through and evaluate the UI workflow. In some cases, such as the creation of events, it isn’t easy to see what the next steps are such as assigning persons to roles, responsibilities and target deadlines. The bright yellow color scheme is not attractive, and a dark mode option would be useful. Older people may need the ability to adjust the size of fonts in the settings to be able to see without glasses. An option for larger icons would be useful for similar reasons. If people are not fully literate, then we'll need the ability for them to easily send audio and/or video messages which will need to be incorporated in the UI. The UI/UX will need to be able to support multilingual capabilities which is has a more detailed description in another section. A thorough review needs to be done and the resulting improvements implemented in code.

The application will be used in many countries by people from different cultures, religious and political beliefs, and geographic regions. The color scheme will need to be as globally neutral as possible. It will be best to limit the color palette and remember that it must easily blend with the current logo.

Sub-issues links :
1. https://github.com/PalisadoesFoundation/talawa/issues/615
2. https://github.com/PalisadoesFoundation/talawa/issues/616
3. https://github.com/PalisadoesFoundation/talawa/issues/617
<Will update here>

**Comment by arteevraina** [comment]
@Sagar2366 Can you please tell us how will be the workflow of this issue?

**Comment by yasharth291** [comment]
Yeah Sir same question will anyone will be assigned or anyone can reply on this

**Comment by Sagar2366** [comment]
Students,
Here is a brief update on the GSoC submission process. The code is now relatively stable and we feel we can begin to consider a partial lifting of the pull request feature freeze. Please read more for details.
All draft submissions made up to April 2 will have responses with feedback within the next 24 hours. In cases where you have submitted a draft proposal after April 2, please ask for an update on the status of your draft proposal after this 24 hour period has expired.
The feedback procedure will also include mentors creating feature issues that can be worked on.
These GSoC feature issues will have a yellow gsoc-parallel label. We have received many draft proposals. In many cases there is partial duplication of the ideas between students. This label will help identify issues that may have to be worked in parallel for all student proposals to be evaluated with valid code.
Only issues with the gsoc-parallel label will be allowed to be worked on in parallel.
Issues with the gsoc-parallel label will need mentors to approve student work in the issue’s comments. This approval will be solely based on student draft submissions.
All pull requests must be made against development branches
All pull requests for feature issues without the gsoc-parallel label assigned by a mentor will be closed.
A merge freeze for ALL feature issues will be maintained.
Here is some further background information:
We have added two more mentors to help handle the volume of students requesting feedback on their draft submissions. The Talawa draft submissions process can be found here: https://palisadoesfoundation.github.io/talawa-docs/docs/gsoc/gsoc-application-process
Check our YouTube playlist for details on Talawa for GSoC: https://www.youtube.com/watch?v=hKLeU3MlGwY&list=PLv50qHwThlJVTUZsVz2CbRSi2f8uF9XE6
We have very high interest in the project. We know we won’t have GSoC slots for everyone. In our YouTube presentation we mentioned that we will work with students to see how their contributions to our open source project can be recognized as part of a pre-existing workstudy coursework program. Page 16 of the presentation has some more details. http://www.palisadoes.org/wp-content/uploads/2021/03/gsoc-2021-talawa.pdf
We feel this process will help create an orderly evaluation process for pull requests related to GSoC where we can more easily review the quality of your code.

**Comment by yasharth291** [comment]
okay sir understood

**Comment by sakshiisaxena** [comment]
hello @Sagar2366 i just came to know about this. How can I still contribute to this? please let me know.
