### ISSUE TITLE
UI/UX enhancements for Home Page

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#615]
Issue Description: We need to upgrade UI/UX of home page/set URL page
Issue Severity: High
Environment Details: Android and iOS devices
Expected Behaviour :
1. Consider changes to fonts, colors, widget locations on screen as mentioned in https://github.com/PalisadoesFoundation/talawa/issues/614
2. Login/Signup process for user should be very smooth - If it requires change in loading of different widgets then add those changes. For example - Do not load login and signup buttons until URL is entered. 
3. Add meaningful alert messages on success/failure cases.
4. Suggest better way to enter organisation URL's.
5. Additional ideas

**Comment by yasharth291** [comment]
Sir how can we work on this issue

**Comment by theRoushan** [comment]
Hello @Sagar2366 Sir, I am working on UI and UX of app. and Will send you my work with proposal. In that design, I will try to cover all the requirements. So Better will be to design first and then build code or change code.

**Comment by AniketSindhu** [comment]
@Sagar2366 How should we work on this issue should I create a pull request for this or make separate branch for UI work?

**Comment by adithyaakrishna** [comment]
> Issue Description: We need to upgrade UI/UX of home page/set URL page
> Issue Severity: High
> Environment Details: Android and iOS devices
> Expected Behaviour :
> 
> 1. Consider changes to fonts, colors, widget locations on screen as mentioned in #614
> 2. Login/Signup process for user should be very smooth - If it requires change in loading of different widgets then add those changes. For example - Do not load login and signup buttons until URL is entered.
> 3. Add meaningful alert messages on success/failure cases.
> 4. Suggest better way to enter organisation URL's.
> 5. Additional ideas

@Sagar2366 I had thought of a better way for the OrgURL thing, it's related to dropdowns and searching Organization Names in a dropdownmenu with a search bar, in this case the Org Members do not need to remember the URL at all, here's the link to the Issue [#143](https://github.com/PalisadoesFoundation/talawa-api/issues/143) regarding that

**Comment by AniketSindhu** [comment]
@adithyaakrishna Great idea! but I am not sure that it will be good to show all organizations to everyone (Privacy reason).

**Comment by pr4nshul** [comment]
Yes, rather we can create a list of a previously entered URL's and give an option to delete them in case they typed it wrong.

**Comment by adithyaakrishna** [comment]
@pr4nshul That's a good one too 🚀

**Comment by Sagar2366** [comment]
> > Issue Description: We need to upgrade UI/UX of home page/set URL page
> > Issue Severity: High
> > Environment Details: Android and iOS devices
> > Expected Behaviour :
> > 
> > 1. Consider changes to fonts, colors, widget locations on screen as mentioned in #614
> > 2. Login/Signup process for user should be very smooth - If it requires change in loading of different widgets then add those changes. For example - Do not load login and signup buttons until URL is entered.
> > 3. Add meaningful alert messages on success/failure cases.
> > 4. Suggest better way to enter organisation URL's.
> > 5. Additional ideas
> 
> @Sagar2366 I had thought of a better way for the OrgURL thing, it's related to dropdowns and searching Organization Names in a dropdown menu with a search bar, in this case the Org Members do not need to remember the URL at all, here's the link to the Issue [#143](https://github.com/PalisadoesFoundation/talawa-api/issues/143) regarding that

@adithyaakrishna do not share your solutions for issues in public. 
These are pre-GSoC activities for student's work evaluation.
