### ISSUE TITLE
UI/UX enhancements for Login Page

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#616]
Issue Description: We need to upgrade UI/UX of Login page
Issue Severity: High
Environment Details: Android and iOS devices
Expected Behaviour :

Consider changes to fonts, colors, widget locations on screen as mentioned in https://github.com/PalisadoesFoundation/talawa/issues/614
Login process for user should be very smooth - 
a. Suggest better way to add authentication considering different categories of users -  finger print, gmail, audio based authentication to app
b. Messages should be more clearer when not provided valid information.
c. Color change on clicking on any widgets, success or failure case color change for any widgets
d. Smooth transition from login page to other screens
e. Additional ideas

**Comment by Hrishikesh-Bhagwat** [comment]
Can you assign me this Issue? @Sagar2366

**Comment by pr4nshul** [comment]
@Hrishikesh-Bhagwat this is a gsoc-parallel issue. Please refer slack or the issue #614 for further explanation.

**Comment by pr4nshul** [comment]
@Sagar2366  Do we also need to add google sign-in flow? Or can we just display the button right now?

**Comment by adithyaakrishna** [comment]
@pr4nshul Ig adding google sign-in requires some changes in the backend. Which we can do it by using [passport.js](http://www.passportjs.org/)
I had created a issue regarding this here, https://github.com/PalisadoesFoundation/talawa-api/issues/138

**Comment by yasharth291** [comment]
@adithyaakrishna its not like this we can do without backend too go to my profile and see notenexus i have done this without any backend this google signin

**Comment by CyberWake** [comment]
@adithyaakrishna they way stated seems a much better flow of implementing google signin. Unlike doing it without taking backend stuff as in that case we are just using google auth to take in simply a mail and than asking for a password this does not come handy on login in that case he still has to give the password were as social auth themselves state logging in or signing up without a password.

**Comment by adithyaakrishna** [comment]
I completely agree its a good way, I never said it's the only option. If we have a better one, we can go ahead with that itself or whichever the mentors agree with
