### ISSUE TITLE
UI/UX enhancements for Signup Page

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#617]
Issue Description: We need to upgrade UI/UX of Signup page
Issue Severity: High
Environment Details: Android and iOS devices
Expected Behaviour :

Consider changes to fonts, colors, widget locations on screen as mentioned in https://github.com/PalisadoesFoundation/talawa/issues/614

Signup process for user should be very smooth -
a. Suggest better way to add authentication considering different categories of users - finger print, gmail, audio based authentication to app
b. Messages should be more clearer when not provided any valid information.
c. Color change on clicking on any widgets, success or failure case color change for any widgets
d. Smooth transition from signup page to other screens
e. APP theme should be consistent 
f. Additional ideas

**Comment by RukshanJS** [comment]
@Sagar2366 can I work on this issue?
