### ISSUE TITLE
Overflow issue in AddPost Page.

### ISSUE THREAD

**Issue by arteevraina** [PalisadoesFoundation/talawa#624]
### Issue Description
When the multiline line `textfield` is expanded. It goes out of the screen creating overflow in rendering.

### Screenshot
![Screenshot_2021-04-06-08-56-06-69_b0d79c17f76dc7231206b6364e70b267](https://user-images.githubusercontent.com/43968121/113706844-c2db2980-96fc-11eb-9348-a81d5ec280c0.jpg)

### Issue Severity 
Light

### Are you willing to work on the issue?
Yes

**Comment by divs4799** [comment]
Can I work on this issue??

**Comment by arteevraina** [comment]
Sure no worrries ! @Sagar2366 please unassign me and assign this to @divs4799

**Comment by divs4799** [comment]
@arteevraina  oh you were assigned to this? i thought you were assigning someone. No worries to me you can keep working on that.  One more thing this issue is not for a website? it is an app ? am i right?

**Comment by arteevraina** [comment]
@divs4799 Talawa app is written in Flutter Framework with Dart Language.

**Comment by yasharth291** [comment]
@Sagar2366  can i work on this if he is not working on this

**Comment by divs4799** [comment]
yeah sure @yasharth291  you can have this one I was working but couldn't find this to work. I hope you can😁

**Comment by yasharth291** [comment]
thanks @Sagar2366  sir please assign me this
