### ISSUE TITLE
Create Organization direct hit API validation error with tricky data along with Render flex overflow issue

### ISSUE THREAD

**Issue by amul-dhungel** [PalisadoesFoundation/talawa#625]
Issue Description
Create organization view page. Steps to create this issue, go to create organization page, and input null details in text field, it throw API toast validation message, but input some detail in first field and for remaining two fields just, press enter, will accept the data and rather than usual validation  it will treat it as data and throws toast message which also overflow.

Issue Severity: Medium but can be a big vulnerability

Observed Behavior: Unusual validation with tricky data and overflow of toast widget

Expected Behavior: The normal validation error should be thrown when there is no string in text fields.

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes, I will work.

Screen record

https://user-images.githubusercontent.com/51743296/113720789-b52e9f80-970e-11eb-9367-ee88d92f632f.mp4

@Sagar2366 Hello sir, Please assign this to me

**Comment by Sagar2366** [comment]
https://github.com/PalisadoesFoundation/talawa/issues/594 duplicate issue.
