### ISSUE TITLE
[bug] unable to login to the application

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#629]
When you try to login to the application it show an error saying failed to connect

**Comment by OnyemaAnthony** [comment]
![Uploading Screenshot_20210407-205100.png…]()

**Comment by OnyemaAnthony** [comment]
![Uploading Screenshot_20210407-205100.png…]()

**Comment by OnyemaAnthony** [comment]
![Uploading Screenshot_20210407-205100.png…]()

**Comment by OnyemaAnthony** [comment]
![Uploading Screenshot_20210407-205100.png…]()

**Comment by OnyemaAnthony** [comment]
![Screenshot_20210407-205100](https://user-images.githubusercontent.com/50530242/113927449-699af500-97e5-11eb-88da-4e6fbc53f67d.png)

**Comment by OnyemaAnthony** [comment]
@Sagar2366 please assign this to me

**Comment by Sagar2366** [comment]
@OnyemaAnthony please use issue template for creating new issues and all necessary details.

**Comment by sakshiisaxena** [comment]
Hey, @Sagar2366 I am a newbie and want to start my contribution via GSoC. Could you please assign this to me so that I can solve the issues.

**Comment by Sagar2366** [comment]
> Hey, @Sagar2366 I am a newbie and want to start my contribution via GSoC. Could you please assign this to me so that I can solve the issues.

@sakshiisaxena this issue is already assigned to @OnyemaAnthony
