### ISSUE TITLE
error: The argument type 'String' can't be assigned to the parameter type 'Uri'. (argument_type_not_assignable at [talawa] lib\views\pages\login_signup\set_url_page.dart:37)

### ISSUE THREAD

**Issue by gourav1486** [PalisadoesFoundation/talawa#632]

**Comment by Sagar2366** [comment]
@gourav1486 use our issue template for describing issue.

**Comment by palisadoes** [comment]
@gourav1486 

1. Are you still working on this?
1. Has it been resolved since you submitted the issue? 

Please close if resolved or have decided to abandon it.
