### ISSUE TITLE
[BUG] Home Screen hero animation error

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#634]
## Issue Description
Error occur in comment screen due to the user of hero animation

## Issue Severity
Low

## Observed Behaviour:
Error displayed in the console

## Expected Behaviour:
Either Hero animation should not be used or its implemented should be corrected

## Steps to reproduce issue:
1. Press on event page
2. Press on Home Page
3. Press comment
4. Navigate Back

## Snapshots/Videos:
```
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
Here is the subtree for one of the offending heroes: Hero
    tag: <default FloatingActionButton tag>
    dependencies: [_ModalScopeStatus]
    state: _HeroState#18757
When the exception was thrown, this was the stack
#0      Hero._allHeroesFor.inviteHero.<anonymous closure>
package:flutter/…/widgets/heroes.dart:256
#1      Hero._allHeroesFor.inviteHero
package:flutter/…/widgets/heroes.dart:267
#2      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes.dart:295
#3      SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:5961
#4      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes.dart:301
```

## Does this issue need immediate attention?
No

## Are you willing to work on this issue
Yes.

## Other information:
It is a very minor issue and hero animation in the home screen is needed to be replaced

**Comment by Sagar2366** [comment]
@sumitra19jha assigned another issue to you.
Let someone else work on this issue, preferably newly joined students for GSoC.

**Comment by sumitra19jha** [comment]
Sure

**Comment by sandeep-v1404** [comment]
@Sagar2366 Can I work on this issue ?

**Comment by yasharth291** [comment]
is this issue still open if yes I want to work on it @Sagar2366  sir

**Comment by sandeep-v1404** [comment]
@yasharth291 I am new to Flutter, u can take up this task .

**Comment by yasharth291** [comment]
thanks sandeep @Sagar2366 sir could you assign me this

**Comment by yasharth291** [comment]
thank u so much sir working on it now
