### ISSUE TITLE
[Bug] UI hidden due to device design

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#636]
## Issue Description:
Ui gets hidden in the back due to the design of device

## Issue Severity:
Low

## Observed Behaviour:
Hidden Ui at the top

## Expected Behaviour:
Shouldn't be hidden

## Steps to reproduce issue:
Open Signup Page or Individual Post Page

## Snapshots/Videos:
![WhatsApp Image 2021-04-09 at 9 06 51 AM](https://user-images.githubusercontent.com/35868598/114124892-07d8a900-9913-11eb-8d5c-b220ca4e1597.jpeg)

## Does this issue need immediate attention?
No

## Are you willing to work on this issue:
I already am working on few issues

**Comment by sandeep-v1404** [comment]
Hello @Sagar2366 . I want to solve this issue . Already I have the solution ready. Can I get some suggestions? Should I hide the status bar completely or make the status bar Transparent ?

**Comment by sakshiisaxena** [comment]
can I do it? @Sagar2366

**Comment by Sagar2366** [comment]
> can I do it? @Sagar2366

@sakshiisaxena let @sandeep-v1404 work on this issue.

**Comment by sumitra19jha** [comment]
@Sagar2366 Can I fix this bug?

**Comment by Sagar2366** [comment]
@sandeep-v1404 is working on this issue. He will open new PR to fix the issue.

**Comment by sumitra19jha** [comment]
Ok sir

**Comment by CyberWake** [comment]
@sandeep-v1404 we are going to fix this one in the UI revamp and scaling under #850 we can close this issue.
