### ISSUE TITLE
Anonymous Sign In as well as weak input signature validation in password.

### ISSUE THREAD

**Issue by amul-dhungel** [PalisadoesFoundation/talawa#637]
Issue Description
Steps to create this bug. Go to register page. Input nothing except "space" in both first name and last name input fields. Then in password too input nothing just press "space" and any single A capital Letter and One extra character and One number. Then Signup. You can be completely anonymous in the app in such a way no details of your will be present to an organization weather valid or invalid. I can fix this and make validation for both password and input signatures strong.

Issue Severity: High

Observed Behavior: Anonymous Login and invalid password input signature.

Expected Behavior: Based on users choice, user must have some information after registration. And the password must match with proper expected format.

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes, I will work.

![image](https://user-images.githubusercontent.com/51743296/114256950-6fa6f680-99dc-11eb-98c5-564b39bcbc6c.png)

@Sagar2366  Hello sir, Please assign this to me. And sorry for delay issue posting.

**Comment by adithyaakrishna** [comment]
@amul-dhungel Is the flutter_pw_validator package accepting spaces as characters? 😶

**Comment by amul-dhungel** [comment]
@adithyaakrishna  Yes, Its okay. We can fix this.
