### ISSUE TITLE
[Bug]- Breaking changes introduced due to latest image picker package.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#638]
- **Issue Description:**
After the update in the packages versioning. Image picker now fetches the latest package due to with the function like ```getImage()``` not been found in the package. Added these functions are now made static as well enabling their call without a constructor. All the breaking changes also need to be fixed made in the latest version. It also needs to have some changes in android manifest relating to permissions.

- **Issue Severity:**
High as this causes the build to fail.

- **Environment Details:**
```register_form.dart```

- **Observed Behaviour:**
On android 10 and above the package disen't work properly.

final pickImage = await ImagePicker().getImage(source: ImageSource.camera);
final pickImage = await ImagePicker().getImage(source: ImageSource.gallery);

- **Expected Behaviour:**
Addition of new permissions as per package.
Use of new function defined in the package to pick image.

- **Steps to reproduce issue:**
Switch to master, get the latest update then build or check dart analysis.

- **Does this issue need immediate attention?**
Yes, with the fix of this one build failure would also be fixed.

- **Are you willing to work on this issue:**
Yes, I do will to work on this. If new contributors will they can take over this one as well.

**Comment by CyberWake** [comment]
@Sagar2366 sir please assign this issue to me.

**Comment by utkarshshendge** [comment]
Hi @CyberWake,  adding an organization image while creating an organization throws an error, maybe it's related to this issue.

**Comment by CyberWake** [comment]
>  Hi @CyberWake,  adding an organization image while creating an organization throws an error, maybe it's related to this issue.

It's is a problem pertaining to the API I guess because the error is perceived from the graphql.
Added if there was something causing problem due to the package then the image would have also been not displayed on the page itself. After the path to the file is same. For both display image.file and the path passed in the graphql mutation in the variable field.
