### ISSUE TITLE
looking to resolve an issue. 

### ISSUE THREAD

**Issue by sakshiisaxena** [PalisadoesFoundation/talawa#643]
hey @Sagar2366 could you please assign an issue to me? I really want to collaborate on this project.

**Comment by Sagar2366** [comment]
@sakshiisaxena we understand your enthusiasm to contribute to our project.
Please join slack workspace first and in #gsoc-newissues channel let me know which issue you would like to work on.

Please, Do not open any new issue and comment on all issues without discussing.
