### ISSUE TITLE
Issue with wrong Event Timings- Future events are being shown in Today category

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#644]
Issue Description:
After creating an event scheduled in the future, it is shown in the 'Today' section

Issue Severity:
Medium- users might be misguided

Observed Behaviour:
User will find future events in today section and not all section

Expected Behaviour:
Only today's events must be in today section

Steps to reproduce issue:
Create an event in the future and go back to the events page, it will be shown as events today

Are you willing to work on this issue?
Yep :)

**Comment by Arnold2381** [comment]
Can i work on this @Sagar2366  if no one is.
