### ISSUE TITLE
[Bug] Calendar display and chosen display option do not match

### ISSUE THREAD

**Issue by imraghav20** [PalisadoesFoundation/talawa#646]
### Issue Description:
In the Events section, the type of calendar view selected, does not match with actual display of calendar.

### Issue Severity:
Low

### Observed Behaviour:
In the Events section, when "Month" display is selected, calendar is displayed only for a Week. 
Similarly, when "Week" display is selected, calendar is displayed for 2 weeks. 
And when "2 weeks" display is selected, calendar is displayed for a month.

### Expected Behaviour:
The calendar should be displayed as per the selected view type i.e. it should be displayed for a month when "Month" is selected, displayed for 2 weeks when "2 weeks" is selected and displayed for a week when "Week" is selected.

### Steps to reproduce issue:
Open Events Tab.

### Snapshots/Videos:
![WhatsApp Image 2021-04-13 at 6 22 07 AM](https://user-images.githubusercontent.com/59257038/114481505-4d061f00-9c22-11eb-9355-fa4ded1173e2.jpeg)
![WhatsApp Image 2021-04-13 at 6 22 06 AM (1)](https://user-images.githubusercontent.com/59257038/114481510-4ecfe280-9c22-11eb-99a1-ee07949f9588.jpeg)
![WhatsApp Image 2021-04-13 at 6 22 06 AM](https://user-images.githubusercontent.com/59257038/114481511-4ecfe280-9c22-11eb-81e5-aa02c6727de5.jpeg)

### Does this issue need immediate attention?
No

### Are you willing to work on this issue?
Yes

**Comment by arteevraina** [comment]
Hi @imraghav20 ! This is actual behaviour. Please refer : #631

**Comment by imraghav20** [comment]
Ok @arteevraina Thanks for clarification.
Closing this issue.
