### ISSUE TITLE
No validation of input URL whether it an endpoint to Talawa server or not

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#649]
Issue Description:
When a user enters a URL to a Talawa server, there is no verification to check if this is a valid URL. For example, even google's URL may be considered valid when it is not a Talawa endpoint

Issue Severity:
Slight- as users who do not know about the app might not know what is happening

Observed Behaviour:
Any link is accepted as a URL whether it is associated with Talawa or not

Expected Behaviour:
Only a Talawa URL must be accepted as a valid URL.

Steps to reproduce issue:
Enter any URL and it will be accepted as a valid URL.

Are you willing to work on this issue?
Yep :)

**Comment by Sagar2366** [comment]
As discussed in slack channel, we do not need this feature.
Please follow community guidelines and discuss in slack channel before creating any new issue.
