### ISSUE TITLE
Sort the Organization Names in Join_Organization Page

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#654]
**Issue Description:** The Organization names aren't sorted in the `join_organization` page

**Issue Severity:** Low

**Observed Behaviour:** The names or the organization are sorted randomly as we can see in the below image

<img src="https://user-images.githubusercontent.com/23498248/114608024-dbc67a80-9cba-11eb-85c5-ebc20e09f3ff.png" width="200" height="400" />

**Expected Behaviour:** The names of the organization should be sorted in one order

**Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.> 

1. Go to Profile Screen
2. Select Join or Create New Organization Option

**Does this issue need immediate attention?** No

**Are you willing to work on this issue:** Yes, I'm willing to work on this issue

**Comment by Arnold2381** [comment]
Can I work on this issue @Sagar2366 ?

**Comment by Arnold2381** [comment]
@Sagar2366 I am unable to create an account or login into the app.

**Comment by Sagar2366** [comment]
> @Sagar2366 I am unable to create an account or login into the app.

@Arnold2381 please join slack if not already and discuss this issue over there

**Comment by Arnold2381** [comment]
@Sagar2366 My issue isn't solved yet, I discussed it in Slack but got no solutions can you please help?
I am unable to create an account in the app. Every time I get some exception.

**Comment by Sagar2366** [comment]
> @Sagar2366 My issue isn't solved yet, I discussed it in Slack but got no solutions can you please help?
> I am unable to create an account in the app. Every time I get some exception.

@Arnold2381 slack is right place to discuss issues in more detail. Please take this discussions on slack.
