### ISSUE TITLE
[Enhancement] User's created & Joined Organizations showing in Join Organization List

### ISSUE THREAD

**Issue by arteevraina** [PalisadoesFoundation/talawa#655]
## Issue Description.
Join Organization ListView is also showing the name of the organization that I created. Also, the already joined organizations by me are also shown in the ListView.

## Issue Severity
Low

## Expected Behaviour
Only organizations that are not joined or not created should be shown in the ListView.

## Screenshot
![image](https://user-images.githubusercontent.com/43968121/114646102-4518ae80-9cf8-11eb-9f4a-456280b5d086.png)

## Are you willing to work on this?
Yes

## Possible Fix
Tweaking the functions.

**Comment by Sagar2366** [comment]
@arteevraina are you considering scenario - User left Organization created by them, joined another organization, left the organisation and want to join back organization created by them.

**Comment by arteevraina** [comment]
@Sagar2366 I will test this case against my PR and update you.

**Comment by arteevraina** [comment]
@Sagar2366 The scenario you mentioned cannot be tested because the user cannot leave the created organization. Instead, it can only be removed. In other scenarios, my PR is working fine.
