### ISSUE TITLE
The last event is blocked by floating action button

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#666]
Issue Description: For big lists the event is blocked by the FAB.
Observed Behaviour: The last event is out of view due to the FAB
Expected Behaviour: It should be accessible to the user.
Steps to reproduce issue: Create a list with many events and FAB will block the menu button for last event.
Does this issue need immediate attention? Yes
Are you willing to work on this issue: Yes, I am willing to work.

**Comment by pr4nshul** [comment]
if @Hrishikesh-Bhagwat  is assigned other issues , I would like to work on this @Sagar2366

**Comment by Hrishikesh-Bhagwat** [comment]
Bro actually I am dire need of issues, due to academic stuff I joined late. I have one issue assigned but it is solved just need to push it. Please don't misunderstand me as a person who creates issues to put dibs on them🤣. I am very sorry😅

**Comment by pr4nshul** [comment]
Hey , I understand. I just wanted to mention it in case mentors anyway tells you that you can't have 2 issues at the same time. Happened with me when I started. But if they allow it, I am happy that you are here and trying to contribute as much as you can. But it's not a race.

**Comment by Hrishikesh-Bhagwat** [comment]
I already fixed my previous issue. I am resolving conflicts that happened on pulling the code. It is done.

**Comment by pr4nshul** [comment]
Close this issue if solved

**Comment by Hrishikesh-Bhagwat** [comment]
No not solved. I got covid actually. I will make a PR tmrw, the code is ready.
