### ISSUE TITLE
[Bug]- Error handling after response retrieval not checking for all cases.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#673]
* **Issue Description:** <Add brief description about issue or feature you want to add.>
There are two use case when the server don't retrieve the data:
```Access Token has expired. Please refresh session.```
```User is not authenticated```
The error handling on every screen only checks for one i.e. ```User is not authenticated```
This needs to be upgraded as it causes error on some actions i found there can be more as well:
    * mark Like unlike a post
    * Remove organization
    * Joining organization
    * Creating organization
Added all these actions throw error on auto login,
Error handling currently is checked after converting the exception to string and then slicing. Which causes a lot of mess for calculating the indices of the error and then comparing.

* **Issue Severity:** <High or Medium orLow>
High, as this hinders a lot of user actions.

* **Environment Details:** <Add details about environment where this issue is found.>
    * Organization settings page
    * join organization page
    * create organization page
    * settings page

* **Observed Behaviour:** <Add details about your observation related to this issue.>
Currently many action return a error response from server on auto login in user. Due to which the user is not able to have access to those features. The response returned needs to be validated and then new token needs to be generated again followed by the action performed.

* **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Server response handling for both the server response for not providing data should be added. Plus exception need to be checked directly with the inbuilt object provided by the package itself rather than converting it to string and than slicing followed by checking the error response start index.

* **Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.>
Important this only occurs on auto login only not on fresh account or fresh logins.
Perform any of the actions stated above. If more case are found feel free to add them in comments.

* **Snapshots/Videos:** <Add snapshots or videos wherever possible.>
Liking the post:
https://thepalisadoes-dyb6419.slack.com/files/U01QZEFJSCE/F01U9TQEG22/talawa
Removing and organization:
https://thepalisadoes-dyb6419.slack.com/files/U01QZEFJSCE/F01UVA9B68Z/talawa

* **Does this issue need immediate attention?** <If yes. Please explain in detail>
Yes this issue needs to be fixed to it earliest.

* **Are you willing to work on this issue:** <Yes or No. If you are working on other issue then issue will get assigned to someone else for getting work done faster.>
Yes, I am will to work on this please assign this issue to me.

* **Other information:** <Add extra information about this PR here>
Anyone up for help can comment need to fix this to it earliest and is needed to be done every page seeking a response from server.

**Comment by StrangeNoob** [comment]
@CyberWake Do you find any other then these exceptions ?

**Comment by CyberWake** [comment]
not yet other than the one stated in new issue #687 and I feel this doesn't  need to have multiple issues we have to implement it as a whole in every page which retrieves data.

**Comment by StrangeNoob** [comment]
@CyberWake rather than checking the substring of the exception, how about we use contains() to check the exception? I think it is the more robust method? What's your take?

**Comment by CyberWake** [comment]
Yeah the contain method is being used by me. Have created a list of the two errors ```user not authenticated``` and ```access token expired```
Then check for these two errors if condition stands true generating a new token else show the particular graphql error to user if there is no graphql error check for server expections show the same two the user.

**Comment by CyberWake** [comment]
Have worked upon join,create and remove actions stated in the PR. After we fix the found actions we can updated the handling on each page fetching data from server.

**Comment by CyberWake** [comment]
Btw you found the comment action was also not working. I adding this in the discription as well. Let's fix the actions found first together and then work on other pages.

**Comment by CyberWake** [comment]
@Sagar2366 sir can you please guide us on how should we create PR as there will be a lot of files to be changed as almost every page fetches data from server.
Help us with a solution for fast reviewal of PRs for the fix.

**Comment by palisadoes** [comment]
@CyberWake  
1. Have you written successful tests for your change? 
2. If so, please make sure the code lints correctly and submit the pull request.

It looks like an important bug, so we will give it priority.

**Comment by CyberWake** [comment]
@palisadoes sir I'll make sure to update the branch with the lint before sending a PR.
