### ISSUE TITLE
Adding logging with Flog in whole app to catch error effciently

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#675]
ENHANCEMENT 

Adding logs for the warnings and errors coming is really important we can add them with the help of Flog library in the flutter

**Comment by yasharth291** [comment]
I would love if someone can work on it as I have been already assigned some other issues :)

**Comment by StrangeNoob** [comment]
Hey, @yasharth291 I would love to work on this. I do have a similar issue opened in #427. So I don't have a problem working on it. @Sagar2366 Can you assign this to me?

**Comment by yasharth291** [comment]
sure brother you can work on it if mentors allow you
