### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by abhishekak048** [PalisadoesFoundation/talawa#678]
Describe the bug
I can't able to Create account in Talawa app.

Error 
RangeError (Range Error : value not in range : 16)

![Screenshot_2021-04-18-17-01-29-07_b0d79c17f76dc7231206b6364e70b267](https://user-images.githubusercontent.com/54079908/115143994-d88b1000-a067-11eb-9883-8b55c80d3010.jpg)
 

![Uploading Screenshot_2021-04-18-17-01-29-07_b0d79c17f76dc7231206b6364e70b267.jpg…]()

![Screenshot 2021-04-18 at 4 32 31 PM](https://user-images.githubusercontent.com/54079908/115143747-c9579280-a066-11eb-8b70-1d23232c1e10.png)

**Comment by arteevraina** [comment]
Hi @abhishekak048 ! Are you using org url as https://talawa-graphql-api.herokuapp.com/graphql ?

**Comment by abhishekak048** [comment]
> Hi @abhishekak048 ! Are you using org url as https://talawa-graphql-api.herokuapp.com/graphql ?
No
Thanks for helping ☺️
