### ISSUE TITLE
Draggable Scrollable Sheet in Event tab doesn't have smooth animations

### ISSUE THREAD

**Issue by Enigma04** [PalisadoesFoundation/talawa#682]
Issue Description:
No smooth animations when dragging up and down the Draggable Scrollable Sheet in the Events tab

Expected Behaviour:
Animations should be smooth

Snapshots/Videos:

https://user-images.githubusercontent.com/32870564/115367961-41979280-a1e4-11eb-8516-c260474b6dec.mp4

Are you willing to work on this issue:
Yes

**Comment by saraljain12** [comment]
hey, I wanna work on this issue. kindly assign it to me

**Comment by sumitra19jha** [comment]
Hi,

Our new ui is different from this and we are not using this ui anymore.
