### ISSUE TITLE
Shifting the routes and its declaration to another file from "main.dart"

### ISSUE THREAD

**Issue by nayakastha** [PalisadoesFoundation/talawa#684]
-Issue Description: 
Organizing routing in large applications is very important so that it's easy to find and maintain in the future.
It would be highly beneficial for the app to move the lines of code related to coding to a new file rather than the main.dart

-Issue Severity: low

-Does this issue need immediate attention? It can be a good step to enhance the efficiency of routing the large app.

-Are you willing to work on this issue: Yes

Not Applicable Parameters -
-Environment Details: 
-Observed Behaviour: 
-Expected Behaviour:
-Steps to reproduce the issue:
-Snapshots/Videos:

**Comment by palisadoes** [comment]
@nayakastha are you on our slack channel? Ritik Kumar Srivastava is working on something similar and is thinking of streamlining the file structure.

Are you on our slack channel? The link is: https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-oz2w954k-xMjzQ4Q3zfEIEJcOF6KdmQ

**Comment by nayakastha** [comment]
Hey! I will surely join the slack channel. I discovered about Pallisadoes through Github Externship Org List. 
I Will surely catch up on the latest discussions and try to contribute as well.
Thank You

**Comment by Sagar2366** [comment]
Create child issue under https://github.com/PalisadoesFoundation/talawa/issues/715 if anything missing, should get fixed as part of the parent issue there.
