### ISSUE TITLE
[bug] task deadline is null

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#686]
**Issue Description**
    when the users task deadline is null it show the error
   **Observed Behaviour**
      when the user tries to check his or her task lists the application crashes
    **Expected Behaviour**
     The user should be able to view there tasks list without any problem
   ** Steps to reproduce issue**
     1. Go to members screen
     2. click on the list of user which task deadline is null
     

   **Does this issue need immediate attention?**
    Yes
   **Are you willing to work on this issue**
   Yes
    **Other information**

**Comment by OnyemaAnthony** [comment]
![Screenshot_20210422-100258](https://user-images.githubusercontent.com/50530242/115706638-c9f17100-a365-11eb-845c-3713db1042c9.png)

**Comment by Anikets08** [comment]
hey is this issue solved ??

**Comment by arq0017** [comment]
Is it solved ?

**Comment by OnyemaAnthony** [comment]
Yes it's fixed
