### ISSUE TITLE
[bug] display circle loader in switch organization

### ISSUE THREAD

**Issue by OnyemaAnthony** [PalisadoesFoundation/talawa#692]
**Issue Description:**

   i want to add a circle loader when the list of organization is being fetched from the database in switch organization screen

**Issue Severity:** low

**Observed Behaviour:** 

   when users go to switch organization screen before the list of items are displayed the screen is blank

**Expected Behaviour:**

   when you go to switch organization before the list of organization is displayed there should be a loader to show that its still 
loading 

 **Steps to reproduce issue:**
  1. go to profile screen
  2. click on switch organization
 **Does this issue need immediate attention?** 
  Yes
 **Are you willing to work on this issue:**
    Yes

**Comment by OnyemaAnthony** [comment]
https://user-images.githubusercontent.com/50530242/115811190-2b0d5900-a3e7-11eb-97a4-398ea106a2b8.mp4

**Comment by CyberWake** [comment]
I think making another call to server to fetch the joined organizations would be costly. We already have the list of user joined organizations on profile page so passing them to switch organization page would be much more optimized and there won't be a need of circular progress indicator.

**Comment by OnyemaAnthony** [comment]
@Sagar2366 please assign this to me let me fix it asap

**Comment by Sagar2366** [comment]
> I think making another call to server to fetch the joined organizations would be costly. We already have the list of user joined organizations on profile page so passing them to switch organization page would be much more optimized and there won't be a need of circular progress indicator.

@OnyemaAnthony check input from @CyberWake .

**Comment by OnyemaAnthony** [comment]
@CyberWake so I guess I have to close the issue ?
