### ISSUE TITLE
GitHub action to flag large Dart files when submitted in PRs

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#700]
We have a situation where some `.dart` files in the repository are too big. Components are not created in separate files to make code easily reusable.

1. One way to prevent this inefficient practice from entering all branches is to flag large `.dart` files when submitted. 
1. This should be a separate PR check that fails when files are longer than `X` lines. You can discuss how long `X` is with a mentor.

**Comment by StrangeNoob** [comment]
@palisadoes I need to clarify a little bit. What about the business logic and queries?  All these files gonna a big. Dividing them will be a bit odd. But I am ready to work on this issue if its free.

**Comment by palisadoes** [comment]
This is primarily aimed at making the screen related component files more reusable. If you feel that a that the business logic and queries should be excluded, then those files would need to be placed in directories / folders that would be configured to be ignored.

**Comment by StrangeNoob** [comment]
Thanks for the input @palisadoes. I will discuss with @DeltaHarbinger,  @Sagar2366, and @heyjordn about the file length size.

**Comment by StrangeNoob** [comment]
@palisadoes Issues like  #716  #718  #719  #720 will decrease the size of the code as discussed by us in the Slack. Should create a PR  now or after there are merged ?

**Comment by palisadoes** [comment]
@StrangeNoob There will never be a good time to implement this. We can ask contributors to refactor, referring them to #715 when their PR submission fails.  @Sagar2366 may have some suggestions.

@StrangeNoob you were thinking of a 400 line limit correct?

**Comment by StrangeNoob** [comment]
Actually, I made a bash file that takes argument for the line limit and can be changed in the near future. With 400 lines of code, 86 files are cover out of 95. I think Its a great number. I do have [spreadsheet](https://docs.google.com/spreadsheets/d/1pESR5kl7sdqx8rD3qnhzVc5t4VLYKzMr-lcGkV3jS4s/edit?usp=sharing) for other mentor to have statical view.
