### ISSUE TITLE
[Bug] -  Build fail due to use of compatible file_picker version fetched with any with other dependency

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#701]
- **Issue Description:**
Due to the use of any version in the ```pubspec.yaml``` it fetches the version compatible with other dependencies. Resulting in fetching the previous versions which are compatible with the other dependencies of ```path_provider```,```graphql_flutter``` and ```http``` etc.

- **Issue Severity:** <High or Medium orLow>
High, this causes build fail and hinders other issues to be solved.

- **Environment Details:** <Add details about environment where this issue is found.>
```create_organization.dart``` ,```update_organization.dart``` and ```generated_plugin_registrant.dart```

- **Observed Behaviour:** <Add details about your observation related to this issue.>
Build fail due to the functions used are not found in the previous version of dependency fetched due to any keyword

- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
```image_picker``` dependency used is capable of picking images from gallery itself then we can reduce our dependency on the ```file_picker``` plugin just to only fetch a image from gallery. Though if we need to use the ```file_picker``` then we can update the conflicting dependency stated above in a separate issue.

- **Steps to reproduce issue:** <Provide detailed steps to reproduce the issue.>
Rebase your fork and let the dart analyser run or build the project after pub get.

- **Does this issue need immediate attention?** <If yes. Please explain in detail>
Yes, this help in fixing the build fail of the project.

- **Are you willing to work on this issue:** <Yes or No. If you are working on other issue then issue will get assigned to someone else for getting work done faster.>
Yes, I would like to work on the issue.

- **Other information:** <Add extra information about this PR here>
Dependencies  ```path_provider```,```graphql_flutter``` and ```http``` etc. need to be updated in new issue.

**Comment by palisadoes** [comment]
@CyberWake  This may not be a bug. Please check @sumitra19jha both here an on the slack channel to verify if this is so.

**Comment by sumitra19jha** [comment]
This is not causing any linting problem. I verified this.
Major problem might be due to the code formatter. I request you to make sure your run for `flutter format .` is successful. 

I also pushed a PR#704 resolving an issue and if you want you can check the `pubspec.yaml` of that PR. The use of `any` is not causing any conflict.
