### ISSUE TITLE
Remove The Creation of Organizations in The App

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#710]
This will require coordination with the person [working on talawa-admin installation](https://github.com/PalisadoesFoundation/talawa-admin/issues/18)

1. The ability for any user to create new organizations in the mobile app must be removed. This removes the centralized control that many organizations want.
1. Until further notice we want the creation of new organizations to be completely managed in the talawa-admin management portal.

This feature needs to be removed. The features below need to be added as part of this issue.

1. The API will need to present all the organizations created by the Super Administrator
1. The mobile app user must be able to browse and easily select any available organization presented in the API

Related Issues:

1. [Issue 236 - Talawa API](https://github.com/PalisadoesFoundation/talawa-api/issues/236)
2. [Issue 19 - Talawa Admin](https://github.com/PalisadoesFoundation/talawa-admin/issues/19)
3. [Issue 710 - Talawa](https://github.com/PalisadoesFoundation/talawa/issues/710)

**Comment by sumitra19jha** [comment]
I want to work on this

**Comment by sumitra19jha** [comment]
I have few ideas which need Talawa-Backend modification. In the user data model, we can add a new boolean parameter called orgCreationAllowed. If admin set the field value of that parameter to `true`. Then only user can create the organisation.

**Comment by palisadoes** [comment]
@sumitra19jha Are you still working on this? If not, we should let someone else get a chance

**Comment by sumitra19jha** [comment]
Sure @palisadoes. I am not currently working on this, anyone interested can take up this issue.

**Comment by rutvik11062000** [comment]
@palisadoes  please assign it to me.
