### ISSUE TITLE
UI/UX Login page does not match the look and feel of the rest of the app

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#711]
The app generally uses either a plain white or black background depending on whether light / dark mode is deployed. 
The home screen with the clouds does not match this look.

![image](https://user-images.githubusercontent.com/16875803/115974832-7bcea000-a514-11eb-9233-231bbc9b7360.png)

We need a look similar to that of global apps like Instagram or WhatsApp where there is a small app logo on a plain background above the login information boxes.

**Comment by nayakastha** [comment]
I want to work on this issue.  Since the entire UI is supposed to be revamped, I feel we should choose a palette and keep it consistent starting from the login screen.

Neutral whites and Pastel colours might be a good option, considering the colours in the logo of Palisadoes.

**Comment by utkarshshendge** [comment]
@palisadoes the UI design is a part of the GSOC program right?
Please correct me if I am wrong.

**Comment by palisadoes** [comment]
@utkarshshendge  The UI really needs to be fixed. I opened an issue #712 about this. We have the UI/UX mentioned in our ideas page, but the GSoC and GitHub externship programs focus on coding ability. We need someone with a UI/UX focus to do a comprehensive review. 

Using a lightly modified stock Figma design won't be enough. We need an original look.

**Comment by utkarshshendge** [comment]
@palisadoes I have created the UI design for Talawa. Your opinion on it will be of great help.
There is no need to build the Code as I have Included Screenshots in the Readme file.
Here is the link: https://github.com/utkarshshendge/t-sample-ui

**Comment by ishandeveloper** [comment]
I'd like to work on revamping the whole UI for the app as a part of github externship, as It's such a great app for managing communities, but I feel that we can do a much better job with the UI of the app to make it much more usable and seamless for onboarding different kinds of users.

I've developed & designed few similar apps before and on the basis of user-feedback and analysis I received, I've got a ton of different ideas on how we can improve this. I wanted to ask whether screenshots of an XD or Figma design would be sufficient for the proposal, and I can work on implementing that UI in flutter, during the externship.

Kindly, let me know if I can start working on this : )

**Comment by palisadoes** [comment]
@ishandeveloper @nayakastha We are evaluating all our GSoC proposals, Some of these students have suggested revamping the Talawa UI. We are pausing this until the formal GSoC announcements are made. Whether or not we select a GSoC UI/UX proposal, we will reopen this and other issues at that time. I'm certain we'll need more, not less assistance to get this done.

**Comment by palisadoes** [comment]
An accepted GSoC proposal covers a wide range of UI modifications including this one. I'll close the issue.
