### ISSUE TITLE
 Migration of all toasts to a common widget

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#716]
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Migration of all the success and error toast to a common widget in` success_toast.dart`
The widget here needs some modifications to make it universal. Like it needs two required parameters `message` and` isSuccess `with an option parameter duration. After which this widget needs to be used at all the places in the project by just passing the `message`, `isSuccess`, and` duration` if needed. After successfully accomplishing the task the file `toast_tile.dart` can be deleted with the file `success_toast.dart` renamed to something more appropriate like` toast.dart `etc.
- **Issue Severity:** <High or Medium orLow>
Low
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level
- **Observed Behaviour:** <Add details about your observation related to this issue.>
Toasts are coded multiple times, can be moved to single file
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Removal of unused widgets, unused files. Generation of reusable widgets
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue.**

**Comment by utkarshshendge** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.
