### ISSUE TITLE
Remove unused organization controller

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#717]
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Currently, in the codebase, there are two controllers named` OrgController `in two different files named `org_controller.dart` and `organization_controller.dart`. Where the` OrgControllerdefined` in `organization_controller.dart` is not used in the project this file needs to be deleted.

- **Issue Severity:** <High or Medium orLow>
Low
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level
- **Observed Behaviour:** <Add details about your observation related to this issue.>
 unused organization controller
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Removal of unused widgets, unused files. Generation of reusable widgets
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue**

**Comment by palisadoes** [comment]
Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.
