### ISSUE TITLE
 Reduce unnecessary wrapping of child widgets.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#718]
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Reducing unnecessary wrapping of child widgets in all the files when not needed and when the desired output could be achieved with the child property itself eg: Container wrapped in Align or Padding widget, Nested Row, and Columns``` etc.
- **Issue Severity:** <High or Medium orLow>
Low
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Removal of unused widgets, unused files. Generation of reusable widgets
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue.**

**Comment by nayakastha** [comment]
@palisadoes I wish to work on this issue.

**Comment by palisadoes** [comment]
Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.

**Comment by palisadoes** [comment]
@nayakastha Are you still working on this?

**Comment by nayakastha** [comment]
Yes sir, I am working on this. I will send a PR by tomorrow. I was a bit caught up with health issues. Sorry for the delay
