### ISSUE TITLE
Modification of Loading widget to make it a universal loading widget

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#719]
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Modification of widget declared in` loading.dart` to make it a universal loading widget. This widget can be provided with properties like` isCurrentOrgNull` resulting in asking the user to join an organization, `isNetworkError` resulting in showing an error image and appropriate text, refresh function, and message resulting in text displaying the message provided (like 'no post to show create one', 'no events to show create one', etc) and a refresh button which calls the refresh function again to fetch the data if other users add data to the server.

- **Issue Severity:** <High or Medium orLow>
Low
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level : [loading.dart](https://github.com/PalisadoesFoundation/talawa/blob/master/lib/views/widgets/loading.dart)
- **Observed Behaviour:** <Add details about your observation related to this issue.>
 Loading stateful widget with few parameters.
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Make the [Loading](https://github.com/PalisadoesFoundation/talawa/blob/99dc5dd27e49e4ae8a3d164b36ec2329567e160f/lib/views/widgets/loading.dart#L6) widget as universal loading widget. 
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue.**

**Comment by Raunakk02** [comment]
Can I work on this issue @Sagar2366 sir?

**Comment by palisadoes** [comment]
Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.

**Comment by Raunakk02** [comment]
> Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.

Sure @palisadoes !
