### ISSUE TITLE
user should be allowed to search for the organization first thing upon opening the app

### ISSUE THREAD

**Issue by Deandrew007** [PalisadoesFoundation/talawa#72]

**Comment by Bhavay192** [comment]
Hey @Laurell876 , I would like to work on this issue , Can u please help me with it .

**Comment by pr4nshul** [comment]
I would also like to contribute in it , we can give users the option whether they want to checkout the organizations or login. That can act like a anonymous login .

**Comment by Sagar2366** [comment]
@Bhavay192 are you working on it ? If not, @pr4nshul you can raise PR for this issue.

**Comment by pr4nshul** [comment]
Ok, I am going to wait for @Bhavay192 to respond within 12 hours, else I will start with it. Although @Sagar2366 do you want me to work from branch master or 2020-Q4. As I should mention right now the code on the master branch has a lot of errors and can't be compiled. It's expected to be resolved by 14th March.

**Comment by Bhavay192** [comment]
@Sagar2366 and @pr4nshul  I'm surely working on this issue to make it work properly :)

**Comment by CyberWake** [comment]
@Bhavay192 and @pr4nshul can you please update us on this issue, what is the current progress. Please respond we may need to fix this issue on the GSoC branch as the whole re-write of the codebase.

**Comment by pr4nshul** [comment]
I never worked on it as @Bhavay192  said he was. So you have a go ahead from me👍
