### ISSUE TITLE
Create classes to store the response map.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#720]
- Parent issue : #715 
- **Issue Description:** <Add brief description about issue or feature you want to add.>
Need to modify data modal classes in the project for easy conversion of JSON maps to class objects enabling easy traversal and retrieval of response data accessibility. As currently everywhere the response map is directly iterated to the search key which doesn't come in handy at every place. And the removal of` user_info.dart `not used in the project and the user data model is much bigger than the one defined. Better to create a new one. Currently, declared models are less efficient, and some are not even used. The model should look like the models declared in the [API](https://github.com/PalisadoesFoundation/talawa-api/tree/master/models). We also need to have its implementation done on getting successful response data from the server. 

- **Issue Severity:** <High or Medium orLow>
Medium
- **Environment Details:** <Add details about environment where this issue is found.>
Project Level
- **Observed Behaviour:** <Add details about your observation related to this issue.>
The response map is directly iterated to the search key. 
- **Expected Behaviour:** <Add what would like to see once this is issue is fixed.>
Use of classes to store the response.
- **Does this issue need immediate attention?** <If yes. Please explain in detail>
No
- **Please ask mentors/maintainers to assign if you are willing to work on this issue.**

**Comment by StrangeNoob** [comment]
@Sagar2366 I am free I can work on this.

**Comment by palisadoes** [comment]
Issue #700 has now been integrated into the pull request process. It will flag all Dart files that are longer than 300 lines to help with readability. Please make sure your contribution reduces file sizes to within this limit.

**Comment by StrangeNoob** [comment]
Sure @palisadoes I will keep this in mind while sending PR.

**Comment by StrangeNoob** [comment]
@palisadoes As This will add more class in the model. I was thinking of changing the directory structure. It will look something like this.
```
+-- lib/
|     +-- models/
|      |    +-- responses/
|      |    |    +-- fetchUserInfo.dart
|      |    |    +-- fetchOrgById.dart
|      |    +-- comments.dart
```
@Sagar2366, @palisadoes Can you share your views? @utkarshshendge & @sumitra19jha  I will love to take your suggestion on this.

**Comment by utkarshshendge** [comment]
@StrangeNoob your approach looks fine. It will make the code more readable and it will be easy to add tests.

**Comment by sumitra19jha** [comment]
@StrangeNoob Can you elaborate a little what you mean
Like the data model are to be build keeping the backend responses in mind. For example: Comment data model will contain `comment text` and `post id`. The same is the case with user information which will contain `first name`, `last name`, `email` etc. They both are build keeping backend response in mind.

Also, is it good to name a model `fetchUserInfo` or should we name them as `User` model and `Organization` model

**Comment by StrangeNoob** [comment]
@sumitra19jha  At a glance, New developer won't be having idea out the response of the every API Call. Converting the response JSON to a class will help it. 
Right now,  I am not concerned with the name of the files but its directory structure?

**Comment by sumitra19jha** [comment]
It's more about organizing codebase than anything else. 

What is the purpose of data model?
It will make sure organized structure is followed throughout the project just like a data type. Currently, we make a request to server and use the response in crude form in the code itself. This is creating a log of confusion.

For example: 
Let suppose I am a new developer going through codebase, somewhere I see a query result called user info. If the result is converted into a data model, I will get to know that the results contain name, email, image etc. But if it's left in its crude form, first I need to visit the query file see the response body and then again visit widget file and use it accordingly.

It's better to implement data models for those responses. It will structure the codebase and also help the developers work more effectively.

**Comment by sumitra19jha** [comment]
@CyberWake On our work on sepration of bussiness logic from UI, this creation of data model will help us in coming with great solution. 

During refactoring, we can make sure all the logics are very well implemented using this data model rather than current response map.

**Comment by StrangeNoob** [comment]
@sumitra19jha Thanks for the input. I will put it model directory only.
