### ISSUE TITLE
Convert Dart GitHub "Line Counting" action to Python3

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#725]
**Is your feature request related to a problem? Please describe.**

Issue #700 was created to help improve Dart file code quality by limiting the size of files submitted in pull requests. This issue was closed with pull request #724

PR #724 created these two files:
1. [countline.sh](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countline.sh)
1. [countlines.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countlines.yml)

**Describe the solution you'd like**
1. We need the [countline.sh](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countline.sh) script converted to `python3`. It's a more universally taught language and will make future support easier.
1. We need [countlines.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countlines.yml) to reference the new python3 file.
1. The code must:
    1. comply with the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) which is heavily based on passing the `pylint`  checks.
    1. Pass the `pydocstyle`, `pycodestyle` and `pep8` tests that can be installed using `pip3`. Most commonly used IDEs (atom.io) support including these packages and `pylint`. The IDE will alert you to non compliance
1. Delete the [countline.sh](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countline.sh) script
1. The `python3` script must:
     1. exit with a code 0 when successful and code 1 when it fails
     1. have identical text output to the current script.
     1. be proven to work as a GitHub action as part of the PR process
   
**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

See section above

**Additional context**

Kudos to @StrangeNoob for working on the original issue, who may be able to provide some guidance.

**Comment by sumitra19jha** [comment]
@palisadoes I have previously worked in Python 3 but I have never implemented this work in any of the previous flutter projects I have worked on. But still, I would like to take up this issue and resolve it. It will increase my knowledge.

**Comment by palisadoes** [comment]
1. [Use os.walk](https://docs.python.org/3/library/os.html)
1. [Here's an example](https://www.tutorialspoint.com/python/os_walk.htm]

Please focus on readability and compliance with the pip3 packages mentioned.

**Comment by sumitra19jha** [comment]
Sure @palisadoes

**Comment by palisadoes** [comment]
@sumitra19jha Also use [Argparse](https://docs.python.org/3/library/argparse.html) instead of getting the argument using $1

**Comment by sumitra19jha** [comment]
> @sumitra19jha Also use [Argparse](https://docs.python.org/3/library/argparse.html) instead of getting the argument using $1

Ok I will do that
