### ISSUE TITLE
Adding Trailing Comma in the Dart File.

### ISSUE THREAD

**Issue by StrangeNoob** [PalisadoesFoundation/talawa#735]
**Issue Description**
As we are in refactor mode, Adding trailing commas will increase the readability of the code. It will help us auto-format the code and auto-comment the ending widget. 
| Before | After |
| --- | --- |
| ![Without Trailing Commas](https://user-images.githubusercontent.com/42904343/116110881-ba5e8900-a6d3-11eb-83d2-486dc4fe86cb.png ) | ![With Trailing Commas]( https://user-images.githubusercontent.com/42904343/116110950-c9ddd200-a6d3-11eb-80b7-435751d98d62.png ) |

**Pros:** 
1. Makes the code more readable 
1. With Bracket colorizer, figuring out the widget and all will be easy.
1. Helps to auto-format the code and auto-comment about the ending widget.

**Cons:** 
1. As we have line restriction, It may be a problem as it increase the line. We can do something about this @Sagar2366,  @palisadoes and @DeltaHarbinger.

**Other Information**   
Instead of using print() to debug and view the output, the use of debugPrint() will be better than it won't show in the production. 

**Please ask mentors/maintainers to assign if you are willing to work on this issue.**
I would to work on this but I have my exams starting tomorrow :grimacing:. Let new member work on this.

**Comment by palisadoes** [comment]
Yes, this will increase the size of files, but the increase will be marginal in general. We need to stick with a limit. Let's see how the 300 line maximum works.

**Comment by StrangeNoob** [comment]
I don't have an idea about automating it. @sumitra19jha can we tweak analysis_options so it can help us?

**Comment by sumitra19jha** [comment]
I don't think so.
Plus adding trailing comma and then sticking with 300 lines will be a hurdle

**Comment by StrangeNoob** [comment]
But with issue like #716 , #718 , #720 #721 may decrease the line of code significantly. Thats What I think.

**Comment by sumitra19jha** [comment]
Still, when creating a single file to handle the business logic of a particular page like:
1. Getter
2. Setter
3. Request functin
4.  then Comments

This will take space

**Comment by StrangeNoob** [comment]
@sumitra19jha Sorry to disturb you, I came across `part` and `part_of` of splitting files. Look at this https://stackoverflow.com/questions/49594307/how-to-split-dart-class-in-flutter.  It might help.

**Comment by sumitra19jha** [comment]
Hi @StrangeNoob,
I hope you are good and healthy. I am not at all disturbed.

To the best of my knowledge, when we are talking about restricting code to 300 lines, we are doing so too make codebase more organized and structured.  For example: we want to shift logic into one controller file, and widgets into other file. In case of controller we further want to create a separate data model file. If widget file is long we want to take a part of it, like the tile section and use it in another file. Now if more than one file needs that tile, then duplicate code can be avoided.

So as you can see, these work are organizing the codebase. Simply splitting the dart class into two files using `extend` would destroy this whole purpose of refactoring. I am not saying we cannot do it, I am just saying the reason in my opinion doesn't fit our purpose.

**Comment by nayakastha** [comment]
Hey @palisadoes. I have partially worked on this issue that is changing all the print statements into debugPrint for reducing the production junk in PR #744. It would be great if I could complete this issue. Can you assign it to me?

**Comment by palisadoes** [comment]
@nayakastha Done.
