### ISSUE TITLE
Prioritize Ordering of GitHub Actions

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#738]
We have an issue with the approval process of pull requests where our GitHub actions are being run in an incorrect sequence. This can be fixed using the [GitHub Actions jobs feature](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs)

Requirements:

1. All GitHub actions must be defined in a single `.yml` file named `actions.yml` which will give us complete control over all sequencing
1. The [greetings.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/greetings.yml) workflow must always be run **first** when `pull requests` or `issues` are created
1. The [countlines.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countlines.yml) workflow must be run after the [linter.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/linter.yml) workflow. 
1. The [issue.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/issue.yml) workflow currently has no dependencies, but must be included in `actions.yml` 
1. All other `.yml` files in the [GitHub Actions directory](https://github.com/PalisadoesFoundation/talawa/tree/master/.github/workflows) in must be removed.

**Comment by palisadoes** [comment]
@sumitra19jha Please comment on this so I can assign it to you as we discussed in our slack channel

**Comment by sumitra19jha** [comment]
Yes please assign me this issue
