### ISSUE TITLE
Documentation updates for recent changes

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#747]
**Describe the bug**
Recently we have done a lot of changes and some are going on, for the developers to easily contribute and stay updated the documentation needs to be updated.

**To Reproduce**
Following things either needs to be added or elaborated more:
1. Go to README.md
2. Go to Contributing.md

**Expected behavior**
A clear and concise description of what you expected to happen:
1. File Size limited to 300 lines
2. Linting should be followed
3. Separation of business logic form UI
4. Use SizeConfig file to scale the UI, rather than constant value
5. Use Data Models

**Actual behaviour**
These are either missing or need more elaboration

**Additional details**
After the changes it would be easier for new and existing developers o stay updated.

**Comment by sumitra19jha** [comment]
@palisadoes Please assign this issue to me

**Comment by palisadoes** [comment]
@sumitra19jha I noticed that the GitHub automation that makes all new issues have the `unapproved` does not work. You'll need to review this. It is important that we have that.

**Comment by sumitra19jha** [comment]
> @sumitra19jha I noticed that the GitHub automation that makes all new issues have the `unapproved` does not work. You'll need to review this. It is important that we have that.

Ok. I am working on it

**Comment by sumitra19jha** [comment]
@palisadoes @Sagar2366 
- The `services` folder contains files that should be the part of `controller` and `utils` folder. There is no need to have this separate `services` folder. 
- The `view_models` folder contains files that should be part of `model` and `controller` folder. There is no need for this separate folder.

Should I remove both of this folder and move their files ?
