### ISSUE TITLE
New issues not given the `unapproved` label in GitHub automations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#749]
**Describe the bug**
New issues are no longer given the `unapproved` label in GitHub automations

**To Reproduce**

1. Create an issue.
2. Wait 5 minutes.
3. Label is not applied

**Expected behavior**
The `unapproved` label must be applied.

**Actual behavior**
The `unapproved` label is not applied.

**Screenshots**

**Additional details**
1. This was working until #738 was implemented
1. The [issues.yml](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/issues.yml) probably needs to be modified

**Comment by sumitra19jha** [comment]
I will fix this as soon as possible
