### ISSUE TITLE
Migrate packages and refactor code for flutter 2

### ISSUE THREAD

**Issue by pratikbaid3** [PalisadoesFoundation/talawa#76]
Currently some of the packages do not support null safety and also flutter has deprecated the use of RaisedButton. I'd like to work on fixing these issues so the it is compatible with flutter 2.

**Comment by jordanliu** [comment]
Hey @pratikbaid3, we definitely do plan on migrating to v2 but we first need to get talawa's current state stable enough before an upgrade.

**Comment by DeltaHarbinger** [comment]
Hey @pratikbaid3, all necessary stability changes have been made in #151. Not all packages have been made up-to-date yet, but we have other contributors working on compatibility upgrades.

**Comment by palisadoes** [comment]
@pratikbaid3 We have reopened the code freeze. Please proceed with this under the guidance of @jordanliu and @DeltaHarbinger

**Comment by CyberWake** [comment]
@pratikbaid3 we are working on it #834 hence closing the issue. If we need help we'll ask.

**Comment by CyberWake** [comment]
@palisadoes sir we can close this issue #834 already there labelled GSoC
