### ISSUE TITLE
MVVM implementation for Add Event Page (add_event_page.dart).

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#762]
**Is your feature request related to a problem? Please describe.**
This is the child issue of #758 
To implement MVVM architecture on add_event_page.dart file.

**Describe the solution you'd like**
See #760 for in-depth details about the implementation.
For Sample see the PR changes #759 

**Additional context**
Other things to take into consideration:
1. Make sure all the files that you are either updating or creating must be under 300 lines.
2. If there are multiple same widget with only few modification extract it as a method and give only change variable as a parameter.
3. Make the code as concise as possible.
4. Kindly add setup locator in the add_post_test.dart otherwise travis build will fail.

**Comment by CoderMayhem** [comment]
This page is built on top of events page having common endpoints and functions. I guess this can be handled along with the `events.dart` page. I guess you can close this issue and update it in the issue description in events page MVVM implementation issue. @rutvik11062000
