### ISSUE TITLE
MVVM implementation for Create Organization page (create_organization.dart).

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#765]
**Is your feature request related to a problem? Please describe.**
This is the child issue of #758 
To implement MVVM architecture on create_organization.dart file.

**Describe the solution you'd like**
See #760 for in-depth details about the implementation.
For Sample see the PR changes #759 

**Additional context**
Other things to take into consideration:
1. Make sure all the files that you are either updating or creating must be under 300 lines.
2. If there are multiple same widget with only few modification extract it as a method and give only change variable as a parameter.
3. Make the code as concise as possible.
4. Kindly create the test file if it is not created and write tests.

**Comment by sumitra19jha** [comment]
This is being handled in #721

**Comment by rutvik11062000** [comment]
@Sagar2366  @palisadoes I would like to work on this.
