### ISSUE TITLE
App has Depreciated member 'showSnackBar' and Non Responsive API . 

### ISSUE THREAD

**Issue by i-anuragmishra** [PalisadoesFoundation/talawa#77]
The app contains many **Depreciated members and API** which needs to be replaced as they are depreciated and no longer supported in flutter. i would like to work on this @palisadoes @Deandrew007 . Can you assign me this issue.

**Comment by i-anuragmishra** [comment]
The issue also mentions the Dedicated and non responsive API. which  #78 does not resolve so i think still need to wait for maintainers to comment.

**Comment by i-anuragmishra** [comment]
Hey @jordanliu since i opened it and **the PR mentioned doesn't fixes it properly or is not made according to open source contribution guidelines. **
**can this issue be please assigned to me?**

**Comment by Raunakk02** [comment]
Hey! I would like to work on this issue. Can you please assign this issue to me?

**Comment by i-anuragmishra** [comment]
hey @Raunakk02  please look at the above comments and follow guidelines for contribution. This issue has been created by me and the as regular SOP i have already asked the maintainers for assignment . Please look into #94 for the Contributing Guideline. Also there is a existing PR regarding this.

**Comment by Raunakk02** [comment]
Sure @i-anuragmishra, I asked it to assign this issue to me because I was working on this earlier. But I think I will now wait for the PR to be merged first.

**Comment by DeltaHarbinger** [comment]
@i-anuragmishra sorry for the long wait. this issue has now been assigned to you

**Comment by DeltaHarbinger** [comment]
I see that you made some PRs related to this issue @i-anuragmishra, but they have merge conflicts with other PRs that were merged. Please pull the new changes in master and reimplement yours so they can be merged

**Comment by i-anuragmishra** [comment]
> @i-anuragmishra sorry for the long wait. this issue has now been assigned to you

Thanks a lot @DeltaHarbinger  and no issues 😄...

**Comment by i-anuragmishra** [comment]
> I see that you made some PRs related to this issue @i-anuragmishra, but they have merge conflicts with other PRs that were merged. Please pull the new changes in master and reimplement yours so they can be merged

Okay @DeltaHarbinger  will do... 👍

**Comment by DeltaHarbinger** [comment]
Hey @i-anuragmishra, #76 also references this issue. I'll be redirecting the creator to this thread for further discussion on the topic

**Comment by palisadoes** [comment]
@i-anuragmishra The code freeze has been lifted please proceed with this. We have refactored the code, so you will need to fetch and merge with the upstream repo

**Comment by i-anuragmishra** [comment]
Okay @palisadoes will do.

**Comment by CyberWake** [comment]
@i-anuragmishra thanks for showing your concern as we are already migrating the codebase to flutter 2.0 and upgrading the dependencies this issue needs to be closed #834 .
@palisadoes sir we can close this issue as well
