### ISSUE TITLE
Future Builder for Startup Logic

### ISSUE THREAD

**Issue by rutvik11062000** [PalisadoesFoundation/talawa#774]
**Is your feature request related to a problem? Please describe.**
We are awaiting userId in the main.dart, then checking if user is null or not, based on that navigating to UrlPage / HomePage.
![image](https://user-images.githubusercontent.com/47498552/117687923-eb5fb300-b1d5-11eb-9ea8-45787a38ca80.png)
![image](https://user-images.githubusercontent.com/47498552/117687639-9cb21900-b1d5-11eb-85ea-60ed1c99056d.png)

**Describe the solution you'd like**
A more logical logic is to use futureBuilder to get the user detail and navigate to pages

**Approach to be followed (optional)**
One can implement something like this:
![image](https://user-images.githubusercontent.com/47498552/117687691-a6d41780-b1d5-11eb-92c7-cc714649d212.png)

After this remove the unused `userID` variable.

**Additional context**
This is a **Good First Issue** so someone with no contribution can take this.

**Comment by leoshrey** [comment]
Hey, I would like to work on this issue.

**Comment by rutvik11062000** [comment]
@leoshrey That's good😄, @Sagar2366 sir will assign it to you.
