### ISSUE TITLE
Couldn't signup with profile picture 

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#777]
**Describe the bug**
When trying to signup with a profile picture, a message true` is shown, but the user is not signed up.

**To Reproduce**
1.Try signing up without a profile picture.
2. A message true will be displayed, and you won't be taken to ` join organization` page.

**Expected behavior**
User should be able to signup with profile picture, just as he/she is able to signup without a profile picture. 

**Additional details**
Please ask mentors/maintainers to assign this issue if you are interested in working on it.

**Comment by palisadoes** [comment]
@utkarshshendge  most applications make you sign up. Then you add your profile picture afterwards. This reduces the risk of any possible flaws in the code could allow an unauthorized person to upload data. I'd suggest that you remove this feature if it exists and only allow profile picture uploads after registration is complete

**Comment by utkarshshendge** [comment]
Completely agree with you @palisadoes. Adding profile pictures later also makes signup seamless. I have addressed this issue in my proposal, I don't know if my proposal gets accepted. But I think makes sense to start working on this issue right now. 
Should I change the description of the issue and start working on it or wait for some time?

**Comment by palisadoes** [comment]
We have been respecting pausing of any issues that may be covered under GSoC proposals when alerted by students. Please wait.
