### ISSUE TITLE
[Bug] Comment count is not updated on newsfeed page.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#778]
**Describe the bug**
After adding a comment to a post the comment count is not updated on the newsfeed page. We need to pull to refresh in order for the comment count to get updated. This functionality existed before, look like a recent merge introduced this breaking change.

**To Reproduce**

1. Add a comment(s) on a post.
2. Go back to the newsfeed page.
3. The comment count on that particular post won't be updated.

**Expected behavior**
The comment count should be updated on the newsfeed page after adding a comment.

**Additional details**
If you are interested in working on this issue please ask mentors/maintainers to assign this issue to you.

**Comment by Raunakk02** [comment]
If no one is working on this issue then I would like to take it up @Sagar2366 @dellyjm @heyjordn.
