### ISSUE TITLE
[Refractor] Remove unused files and add theme related data to a single file.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#780]
**Refractor**
`toast_container.dart` is used only in the file` join_organization_view_model.dart` and can be replaced by `custom_toast.dart` (which is used at many places).` snackbar.dart` is not used and can be removed.
We can move relevant theme-related data (colors,text styles,etc) to a single file (`theme.dart`). This will help us to apply theme-related changes globally instead of going through multiple files and changing the data.

If you are interested to work on this issue, please ask, mentors/maintainers to assign it.

**Comment by nayakastha** [comment]
Hey! I am interested to work on this.

**Comment by utkarshshendge** [comment]
The data in `lib\utils\uidata.dart `contains only colors.
@nayakastha lets take an example of [register_form.dart](https://github.com/PalisadoesFoundation/talawa/blob/master/lib/views/pages/login_signup/register_form.dart) .  At some places the colors are not used from` uidata.dart` . The decoration property of` Container` , `TextFormField`  is used multiple times and can be added in a single file.

**Comment by nayakastha** [comment]
Got it. Thanks for giving an instance. I will get on working with it.
