### ISSUE TITLE
[Bug] Event list shows wrong data after deleting an event

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#781]
**Describe the bug**
After deleting events marked as _Today_ the event list updates normally, but the timeline does not change from _Today_ to _All_

**To Reproduce**
1. Delete an event that comes under the _Today_ list. 
2. You can observe that the 

timeline does not change from _Today_ to _All_

**Expected behavior**
The timeline should change from _Today_ to _All_ after the event list is updated.

**Screenshots**

https://user-images.githubusercontent.com/57677520/118015202-a6708380-b371-11eb-963c-413585bb1a9e.mp4

**Additional details**
If you are interested in working on this issue, please ask mentors/maintainers to assign this issue to you.

**Comment by Raunakk02** [comment]
@palisadoes, I would like to work on this issue If no one is working on it already.

**Comment by Raunakk02** [comment]
@palisadoes @utkarshshendge Please close this issue as the PR has been merged. If this remains open then it would just increase the number of issues.

**Comment by utkarshshendge** [comment]
Thanks for pointing it out @Raunakk02
