### ISSUE TITLE
[BUG] Data is not updated automatically after joining a new organization.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#782]
**Describe the bug**
The data on the _newsfeed page_, _events page_, _members page_ is not automatically updated after joining a new organization, we have to restart the app in order to see the updated data, However, when you switch organizations the data updated. 

**To Reproduce**

1. Go to the profile page,  join a different organization(join, don't switch).
2. After joining successfully, you can observe that the data on various pages is of the previous organization,its not updated.

**Expected behavior**
The behavior should be similar to what we observe when we switch to an organization. After joining the new organization data should be updated.

**Additional details**
If you are interested in working on this issue please ask mentors/maintainers to assign this issue to you.

**Comment by afaanshariff** [comment]
16-05_AFF633_tfa_262
@palisadoes Sir can I work on this issue.

**Comment by afaanshariff** [comment]
@palisadoes PR #703 might resolve this issue also. Shall I wait until that PR is merged or shall I submit my PR to this issue??

**Comment by palisadoes** [comment]
Wait until #703 is merged to see if the bug remains.

**Comment by afaanshariff** [comment]
@palisadoes ok sir.

**Comment by afaanshariff** [comment]
@palisadoes PR #703 did not fix this issue, shall I start working on this issue.

**Comment by palisadoes** [comment]
Yes, go ahead and this is a bug.

**Comment by afaanshariff** [comment]
@palisadoes ok Sir.
