### ISSUE TITLE
Dropdown menu(http/https) on the landing page is not working.

### ISSUE THREAD

**Issue by muskan399** [PalisadoesFoundation/talawa#784]
**Issue Description**
Dropdown menu(http/https) on the landing page(where organization URL is entered) of the page is not working. Actually a hardcoded value of HTTP is stored in the code.
So even if an user select https then also it will use http.

**To Reproduce**

1. Start the application, where the URL of the organzation is entered.
2. Go to the Dropdown menu(http/https).

**![Screenshot (720)](https://user-images.githubusercontent.com/63671368/118019560-bf2f6800-b376-11eb-9c07-78dc19d2d6fe.png)**
![WhatsApp Image 2021-05-12 at 23 10 52](https://user-images.githubusercontent.com/63671368/118020244-7e841e80-b377-11eb-9a60-dc32f984819f.jpeg)

Protocol(http/https) selected by the user must be used.
Not the hardcoded value.

**Additional details**
Application no. (For the Externship): 28-04_Mus695_tfa_262
I'm willing to work on this issue.

**Comment by afaanshariff** [comment]
@Sagar2366 @palisadoes I would like to work on this issue.
