### ISSUE TITLE
While registration using image, information is passed to wrong API URL.

### ISSUE THREAD

**Issue by muskan399** [PalisadoesFoundation/talawa#785]
**Describe the bug**
Whenever an user sign up with image, it passes the user information in a wrong API URL.
For e.g  If user have entered **talawa-graphql-api.herokuapp.com/graphql** then it will send information to **talawa-graphql-api.herokuapp.com/graphql/talawa/graphql** that's why user is not able to register.

1. Enter the organization URL on the landing page.
2. Go to sign up option
3. Fill the details and click on sign up button.

**Expected behavior**
After filling the details, sign up should be successful and user should be logged in.
Information should pass to right URL: talawa-graphql-api.herokuapp.com/graphql

**Actual behavior**
Sign up is not successful.
Information is passed to wrong URL: talawa-graphql-api.herokuapp.com/graphql/talawa/graphql

**Screenshots**
![Screenshot (721)](https://user-images.githubusercontent.com/63671368/118027916-1554d900-b380-11eb-8e42-7b8e397256e1.png)

**Additional details**
Application no.(For the Externship): 28-04_Mus695_tfa_262
I would like to work on this issue.

**Comment by palisadoes** [comment]
@muskan399 This is related to #777? We should only allow profile images to be updated for registered users.

**Comment by muskan399** [comment]
> 
> 
> @muskan399 This is related to #777? We should only allow profile images to be updated for registered users.
Yes, but issues are somewhat same.
So should I close this issue?

**Comment by palisadoes** [comment]
Yes. They are very similar.
