### ISSUE TITLE
Add Multilingual Support to the Talawa App

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#798]
### Parent Issue

**Is your feature request related to a problem? Please describe.**
Talawa Needs to have multilingual support to make it internationally acceptable.

**Describe the solution you'd like**
We need a way for users to easily select their language of choice which would immediately and permanently change the text to the new language until the language selection is changed.

### Child Issues:

The following are child issues for this parent:

1. #799 
2. #808
2. #800
3. #801
3. #802
4. #803
5. #804
6. #805
7. #806
8. #807

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue
