### ISSUE TITLE
Refactor Hard Coded strings

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#800]
**Is your feature request related to a problem? Please describe.**
This is a child issue of #798

**Describe the solution you'd like**
1. Refactor all widgets in the Talawa app which have hardcoded strings.
2. Update the Talawa GitHub action workflow to automatically reject any hard coded strings outside of the language translation files.

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by sumitra19jha** [comment]
@palisadoes Please close this issue
