### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#801]
**Is your feature request related to a problem? Please describe.**
This is a child issue of #798

**Describe the solution you'd like**
1. Develop language selection page & create change language widgets on certain specific pages to allow users to easily switch language within the app.
2. We prefer to have language selection upon registration. Future changes would occur in the user settings screen

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by sumitra19jha** [comment]
@palisadoes Please close this issue
