### ISSUE TITLE
Create Testing Mechanism for Language Selection

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#802]
**Is your feature request related to a problem? Please describe.**
This is a child of #798

**Describe the solution you'd like**
Update & develop the test code suite for all the changes that will be introduced by the feature option to switch languages in the app

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by sumitra19jha** [comment]
@palisadoes Please close this issue
test/widget_tests/select_language_page_test.dart is added for testing language specific changes
