### ISSUE TITLE
Update Profile Screens for Multilingual Support

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#806]
**Is your feature request related to a problem? Please describe.**
This is a child of #798

**Describe the solution you'd like**
1. Update the profile & chat screens to enable users of different languages to communicate & use language features effectively. 
2. Update the required documentation accordingly for both frontend and backend.

**Comment by sumitra19jha** [comment]
@palisadoes Please assign me this issue

**Comment by sumitra19jha** [comment]
Please close this issue
