### ISSUE TITLE
Flutter red screen error when events and profile page is opened while the device is offline.

### ISSUE THREAD

**Issue by afaanshariff** [PalisadoesFoundation/talawa#809]
**Describe the bug**
When the device doesn't have proper internet connection or when the device is offline, flutter red error screen is displayed.

**To Reproduce**

1.Turn off the data.
2.Open events tab. You'll get red screen there.
3. Also open profile tab. You'll get red screen there too.

**Expected behavior**
It should display internet connection not available.

**Actual behavior**
Red error screen.

**Screenshots**
![Screenshot_2021-05-18-15-24-39-366_com example talawa](https://user-images.githubusercontent.com/57586853/118633289-f1195200-b7ee-11eb-99c6-01ff746c81d8.jpg)
![Screenshot_2021-05-18-15-24-16-160_com example talawa](https://user-images.githubusercontent.com/57586853/118633323-faa2ba00-b7ee-11eb-84f5-d60ed670dafd.jpg)

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by palisadoes** [comment]
@kenkirito Any progress?

**Comment by palisadoes** [comment]
@kenkirito A similar issue #819 has also been opened. Are you still working on this?

**Comment by kenkirito** [comment]
Yeap i am looking into the issue

**Comment by kenkirito** [comment]
sorry but I am new to flutter so it is taking some time in understanding the stuff

**Comment by afaanshariff** [comment]
@kenkirito if you want any help let me know.

**Comment by kenkirito** [comment]
sure

**Comment by kenkirito** [comment]
I wanna ask one more question I am applying for Github externship this year is there any community chat where I can get reviews on my proposal

**Comment by afaanshariff** [comment]
join the slack channel

**Comment by afaanshariff** [comment]
But you won't get a review of your proposal in those channels.

**Comment by kenkirito** [comment]
how can i join the slack channel

**Comment by palisadoes** [comment]
> how can i join the slack channel

https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-qa1hbp06-GJrilN35oIYfddC9Vf0kRA

**Comment by afaanshariff** [comment]
@Atharva-Vijay-Khade did you follow the steps which I had mentioned.
If yes I'll check and let you know

**Comment by Atharva-Vijay-Khade** [comment]
@afaanshariff  Yes, firstly I opened the app with the net connection as active, then I closed the net connection and opened the events tab, then it displayed the circular Progress Indicator for a while and then this above display came.

**Comment by Sagar2366** [comment]
@afaanshariff @Atharva-Vijay-Khade please share the video recording for this.

**Comment by Atharva-Vijay-Khade** [comment]
@Sagar2366 

https://user-images.githubusercontent.com/58695354/120645906-99d5db80-c496-11eb-88c6-a58abb98d187.mp4

**Comment by afaanshariff** [comment]
https://user-images.githubusercontent.com/57586853/120763705-1b7c4680-c535-11eb-98a8-3519042fa50f.mp4


https://user-images.githubusercontent.com/57586853/120763718-1f0fcd80-c535-11eb-8ec3-625cfb77e341.mp4

@Sagar2366 @Atharva-Vijay-Khade 
Maybe the recent merges have caused these changes, but still, there are errors.

**Comment by Raunakk02** [comment]
@Atharva-Vijay-Khade and @afaanshariff, which branch of the repository are you using currently? Because I worked on the issue for creating a universal error widget and the video shared by @Atharva-Vijay-Khade shows the changes that I implemented but the videos shared by @afaanshariff show the behavior of the app before those changes were merged into the master branch. I think this error is occurring in the develop branch only. Can you please confirm this @afaanshariff and @Atharva-Vijay-Khade?

**Comment by Atharva-Vijay-Khade** [comment]
Hi @Raunakk02 , 
I am currently a beginner in contributing towards this project, I saw this error and tried to recreate it on the app which is on master branch, but I couldn't see this error coming up again.
Please could you confirm that master is the branch on which we should be looking up for bugs ?
