### ISSUE TITLE
Add workflow for CI / CD using Github Actions.

### ISSUE THREAD

**Issue by arteevraina** [PalisadoesFoundation/talawa#81]
Adding CI / CD workflow will help to improve the code quality in the future and will help to keep the code consistent.
If this issue is approved, I would like to work on this.

**Comment by arteevraina** [comment]
@jordanliu Cool ! Sending a patch for this one :)

**Comment by YashJipkate** [comment]
Hey @arteevraina are you still working on this?

**Comment by arteevraina** [comment]
Hi @YashJipkate ! I have already started working on this. I will send a patch soon. Thank you :)

**Comment by DeltaHarbinger** [comment]
Hey @arteevraina, thanks for recommending this change. Please go ahead and add an appropriate pipeline. remember to link this with any PR you create

**Comment by arteevraina** [comment]
Hi @DeltaHarbinger! Since there are analysis issues in the code. I think after my PR is merged probably, most of the PRs will fail the checks due to these analysis issues.
