### ISSUE TITLE
OTP Feature while signing-up.

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa#812]
Is your feature request related to a problem? Please describe.
It will be great if an OTP can verify the user's email ID whether it is legit or not. This can be done by using some libraries like Sendmail(for sending OTP), OTP generator(for generation different OTP).

When the user will send signup data, the mutation that will be called should be generatOTP which will send OTP to the user's email and if this OTP is correct, the signup mutation will be called and user data get saved.

This task requires work with a frontend contributor.

I have been assigned to work on this enhancement in talawa-api  [,](https://github.com/PalisadoesFoundation/talawa-api/issues/245) I need one more contributor who can help me in the frontend part of the application (for verifying OTP).

**Comment by ahluwaliatikant** [comment]
I would like to work on the frontend part.

**Comment by XshubhamX** [comment]
@palisadoes sir please assign @ahluwaliatikant so that we can start work on this issue.

**Comment by XshubhamX** [comment]
@ahluwaliatikant plz join the slack channel and let's discuss the further approach.

**Comment by ahluwaliatikant** [comment]
How do I get the invitation to join the slack channel?

**Comment by palisadoes** [comment]
@XshubhamX  As I haven't heard back from you. I'm going to close PR #248 and #245. We prefer to go with an email service for the reasons stated previously.

**Comment by XshubhamX** [comment]
@palisadoes sir I am trying to find a way to provide more than 3 ways for the user to authenticate . I am on it and will explain my approach in few days. I was not available today that's why I just saw your message
