### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by ahluwaliatikant** [PalisadoesFoundation/talawa#814]
**Is your feature request related to a problem? Please describe.**
Currently when the user opens the app the user sees a blank white screen for a few seconds before the News Feed Screen is visible.

**Describe the solution you'd like**
We should add a splash screen with the talawa logo.

**Would you like to work on this?**
Yes I am working on this issue.

**Comment by ahluwaliatikant** [comment]
@palisadoes Sir is a white background with centered talawa logo fine for the splash screen ?

**Comment by palisadoes** [comment]
@ahluwaliatikant yes
