### ISSUE TITLE
Bug : Not able to close pop up in Join Organization Screen

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa#815]
**Describe the bug**
We are not able to close pop up in Join Organization Screen & we navigate to previous screen without closing popup.

**To Reproduce**

1. Switch to Profile Screen
2. Click on 'Join or Create New Organization'
3. Chose any organization & click on 'JOIN' button
4. Popup appears. Now Click on 'Close'

**Expected behavior**
Popup should disappear & we should stay on same page.

**Actual behavior**
Popup is not disappearing even after clicking on 'close' & we are navigate to previous screen without closing popup.

**Screenshots**
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/43909309/118877235-cffa5380-b90b-11eb-990e-0583d70ac60b.gif)

**Additional details**
Github Externship Appication No. : ````20-05_Adi500_tfa_262````

**Comment by AdityaBirangal** [comment]
@palisadoes 
I would like to work on this issue.
I'm Github Externship candidate :)

**Comment by palisadoes** [comment]
@AdityaBirangal Please include your Externship ID in the issue comments.

**Comment by AdityaBirangal** [comment]
I have updated issue comment.
My Github Externship Application No. : ````20-05_Adi500_tfa_262````
Thanks!
