### ISSUE TITLE
Pixel overflow at the bottom of the screen in members detail page.

### ISSUE THREAD

**Issue by afaanshariff** [PalisadoesFoundation/talawa#819]
**Describe the bug**
When the device's internet connection is low, at that time if we try to view members detail, there's a pixel overflow at the bottom of screen.
**To Reproduce**

1.Open members tab.
2. Select any of the members in the list. It will lead to members detail page.
3. After that turn off your WiFi/data.
4.Then you can notice the pixel overflow.

**Expected behavior**
Only pixel overflow should not be shown on the screen.
**Actual behavior**
Pixel overflow by 9.7 pixels is displayed.
**Screenshots**
![Screenshot_2021-05-20-14-29-22-306_com example talawa](https://user-images.githubusercontent.com/57586853/119026083-68530f80-b9c2-11eb-86ad-7ddfca04b703.jpg)

**Additional details**

**Comment by afaanshariff** [comment]
Since there's already issue #809 which occurs while the device is offline, these two issues can be solved and merged at a time.

**Comment by bayush-9** [comment]
This error is fixed. This issue can be closed! @palisadoes @afaanshariff
