### ISSUE TITLE
Red screen error while updating image.

### ISSUE THREAD

**Issue by muskan399** [PalisadoesFoundation/talawa#820]
**Describe the bug**
A red screen error is shown when we update the profile using a zoomed image.

**To Reproduce**

1. Go to the update profile page.
2. Take a zoomed photo using the camera.

**Expected behavior**
After clicking on the update profile button, an updated profile msg should be shown.

**Actual behavior**
A red screen error is shown on the screen.

![Screenshot (723)](https://user-images.githubusercontent.com/63671368/119074884-767a4d80-ba0d-11eb-9d15-99b53ecca0c9.png)
![Screenshot (724)](https://user-images.githubusercontent.com/63671368/119074896-7e39f200-ba0d-11eb-8859-5e0e1110162a.png)

I uploaded a zoomed black photo and it started showing an error when I clicked on the update button.

**Additional details**
I'm a Github Extern.
Please assign this issue to me.

**Comment by muskan399** [comment]
Sir,
I rebased my branch with the upstream branch and got to know that the
update profile option is also giving red screen error.
So for resolving the issue #820 first the issue #824 should get resolved.
Please approve the 824 issue.

**Comment by bayush-9** [comment]
@palisadoes Please close this issue. The bug is resolved.
