### ISSUE TITLE
Profile is not updating.

### ISSUE THREAD

**Issue by muskan399** [PalisadoesFoundation/talawa#822]
**Describe the bug**
Details are not getting updated using update profile page.

**To Reproduce**

1. Go to the update profile page.
2. Fill up the details.
3. Click on update profile.

**Expected behavior**
Details should get updated.

**Actual behavior**
Details are not getting updated because data is sent to the wrong API.
Correct API should be : talawa-graphql-api.herokuapp.com/graphql

![Screenshot (725)](https://user-images.githubusercontent.com/63671368/119077396-d8d54d00-ba11-11eb-83d0-b5c2ba96d226.png)

**Additional details**
I'm a Github extern.
Assign this issue to me.

**Comment by sumitra19jha** [comment]
The Api's are correct. It's currently is in develop branch and not merged to master. After they both are compare and merged, the issue will be resolved.

**Comment by muskan399** [comment]
Ok.
