### ISSUE TITLE
Place Picker For Selecting Event Location

### ISSUE THREAD

**Issue by leoshrey** [PalisadoesFoundation/talawa#823]
**Is your feature request related to a problem? Please describe.**

Currently, while entering the event location on Add Event page, user have to type complete location in the field with no autocomplete feature. Due to which following problems are faced:

- User can either type the wrong location or the incomplete one.
- User cannot remember the exact location but he may remember the Landmark of that particular area.
- User may want to pinpoint a location using map.
- User may want to get the distance from his location to where the event is being organised.
- Event Attendees may not understand and can reach the wrong location.

Typing complete location consumes time of the user and leads to imperfect user experience.

**Describe the solution you'd like**

Whenever user taps on the location field, a new place picker screen should arrive, having:

- A Search Bar with autocomplete suggestions feature.
- A Map should be displayed having real time pinpointing.
- Nearby Places list.
- Select location button for returning the selected location back to the Location field on Add Event page.
- A button redirecting to google maps application.
This will improve the experience by speeding up the process and will give an appealing interface.

**Screenshots** 

**Case A:** User is selecting the location by just searching a word "hawa" instead of writing complete location as "Hawa Mahal Rd, Badi Choupad, J.D.A. Market, Pink City, Jaipur, Rajasthan 302002"

https://user-images.githubusercontent.com/53581274/119172568-c1cf4300-ba83-11eb-83ed-9c57a3fe92f1.mp4

**Case B:** User doesn’t remember the exact location, but he is known to a nearby location "Raj Mandir". 
In this case he is using a map picker for pinpointing the exact location, which earlier was not known to him.

https://user-images.githubusercontent.com/53581274/119172800-fd6a0d00-ba83-11eb-8efb-3f4b6c0efbd2.mp4

This is a demo of this feature I have implemented locally.

**Approach to be followed**
For achieving this I will be using Flutter Place Picker library.
I'll have to specify the dependencies, for using this library in both Android(build.gradle) as well as iOS(AppDelegate), with API keys.
For implementation, I'll be writing the code inside add_event_page.dart by using onTap callback on the inputField widget.

**Additional Information**
For implementation, enabling of Places API, Maps SDK for Android, Maps SDK for iOS and Geocoding API is needed for the generated API key on Google Cloud Platform. 
Please let me know, if this is feasible. 
And if yes, can I get the key for development purpose or may be we should just use the variable without API_KEY Value for now and get an API_KEY later?

**Github Externship Application ID**
18-05_Shr843_tfa_262

**Comment by palisadoes** [comment]
@leoshrey The original thought was that the `talawa-admin` administrator would create a list of locations to choose from. The mobile app would then download those for selection. Locations would include those the organization controlled:

1. rooms
1. halls
1. fields (soccer, cricket pitches etc.)

That way it would not be possible to double-book the location to create issues. It's an administrative feature.

How do you propose to include this functionality with your idea?

**Comment by leoshrey** [comment]
@palisadoes, what do you mean by creating list of locations by the admin?
If I am not wrong, you mean sending an API response to the mobile app containing locations list.
Then, We have to write a custom implementation with Maps flutter plugin and it can be achieved:

- by returning the exact lat long of the place searched by the user in the API response and add a pin to the map on the returned location coordinates.
- by extracting the data which we'll be getting  from the api (of json/xml/csv format) with the location values (specifically name) that we will eventually display in the list as user types in the keyword in UI for achieving the autocomplete functionality.

This will take little more time, but yes it can be achieved.

**Comment by leoshrey** [comment]
Until then, If you agree can we just use the above implementation without the location restrictions as of now 
OR we should just continue using the current way of entering locations?
