### ISSUE TITLE
Multiple registrations for same event by a user and event card not updated.

### ISSUE THREAD

**Issue by ahluwaliatikant** [PalisadoesFoundation/talawa#827]
**Describe the bug**
When a user registers for an event, the users name gets added in the registrants list. But in the event card it still shows "You are not registered".
If the user taps on Register for the event more than once. The name gets added more than once in the registrants list.

**To Reproduce**

1. Go to Events Page.
2. In event card tap on the three dots (more) icon.
3. Tap on Register For Even Multiple Times.

**Expected behavior**
When user taps on Register For The Event , the event card also must get updated and display that the user is registered.
When user tries to register for same event more than once the user name should not be added multiple times in the registrants list. Instead user should be shown a Toast / Alert Dialog saying "You are already registered for this event".

https://user-images.githubusercontent.com/52076751/119218804-ef59d200-baff-11eb-8925-1aaeb9a376cf.mp4

**Comment by AdityaBirangal** [comment]
Can I fix this issue ? 
@ahluwaliatikant @palisadoes

**Comment by palisadoes** [comment]
This will need to be fixed in the API also. Work with Sumitra. He'll show you what to do.
