### ISSUE TITLE
Not able to login in app

### ISSUE THREAD

**Issue by sssash18** [PalisadoesFoundation/talawa#83]
While completing the registration process in a correct manner , a unhandled exception toast appears.Here is the video:

https://user-images.githubusercontent.com/57896905/110587420-ad282200-8199-11eb-96e1-890b9706c1af.mp4

**Comment by i-anuragmishra** [comment]
hey @sssash18  does the flutter version you are using >2.0.1 . Coz some people might have error even in the build. Also , i guess this could be dues to some problem with the API(#77  ) that app uses.

**Comment by Swayam221** [comment]
I would like to work on this issue.

**Comment by utkarshshendge** [comment]
@i-anuragmishra exactly, few files are missing. @sssash18 Could you please mention your flutter version.

**Comment by sssash18** [comment]
> @i-anuragmishra exactly, few files are missing. @sssash18 Could you please mention your flutter version.

Its 1.22.6

**Comment by i-anuragmishra** [comment]
> > @i-anuragmishra exactly, few files are missing. @sssash18 Could you please mention your flutter version.
> 
> Its 1.22.6

yeah. i guessed so. Because app as some deprecated features which prevents it from building with flutter current stable SDK version (2.0.1). I request you ( @sssash18 ) to update your Flutter SDK to the same.

**Comment by sssash18** [comment]
> > > @i-anuragmishra exactly, few files are missing. @sssash18 Could you please mention your flutter version.
> > 
> > 
> > Its 1.22.6
> 
> yeah. i guessed so. Because app as some deprecated features which prevents it from building with flutter current stable SDK version (2.0.1). I request you ( @sssash18 ) to update your Flutter SDK to the same.

Yeah sure, So that means first we have to resolve the depreciated features and also the exception occuring to something wrong from API side . Am I correct ?

**Comment by DeltaHarbinger** [comment]
Hey @sssash18, we recently updated master to include a lot of stability changes in #151. The backend was also   offline until yesterday, so Registering and Signing In were problematic. you should now be able to register and sign in normally
