### ISSUE TITLE
Reduce DART file sizes to make the PR automated checks work.

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#830]
**Describe the bug**

1. One of our pull request checks is to ensure that Dart files have under 300 lines of code. This is because we found many instances of duplicated code and felt that adding a 300 line limit would encourage people to create reusable code.
2. We have 9 files in the repository that are over 300 lines long.
3. These need to be reduced in size by using efficiently elegant coding techniques.
4. We need this fixed so that contributors can have all their checks pass.

**To Reproduce**

1. Submit a PR with over 300 lines of code.
2. Look at the failed checks. It shows the files in the `Actual Behavior` section to be too large

**Expected behavior**
Pull requests passing all GitHub action tests

**Actual behavior**

The files below are consistently flagged as being too large.

```
Line count:   482 File: /home/runner/work/talawa/talawa/lib/views/pages/events/edit_event_dialog.dart
Line count:   371 File: /home/runner/work/talawa/talawa/lib/views/pages/organization/organization_members.dart
Line count:   547 File: /home/runner/work/talawa/talawa/lib/views/pages/organization/update_profile_page.dart
Line count:   320 File: /home/runner/work/talawa/talawa/lib/views/pages/organization/update_organization.dart
Line count:   355 File: /home/runner/work/talawa/talawa/lib/views/pages/organization/organization_settings.dart
Line count:   308 File: /home/runner/work/talawa/talawa/lib/views/pages/login_signup/register_form.dart
Line count:   542 File: /home/runner/work/talawa/talawa/lib/views/pages/login_signup/set_url_page.dart
Line count:   973 File: /home/runner/work/talawa/talawa/lib/services/queries_.dart
Line count:   312 File: /home/runner/work/talawa/talawa/test/widget_tests/register_form_test.dart

```

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/119232636-bb1fea80-bada-11eb-8113-5866e25ea933.png)

![image](https://user-images.githubusercontent.com/16875803/119232654-d985e600-bada-11eb-848c-b4628ad9be04.png)

**Additional details**
None

**Comment by anand-aman** [comment]
Can I work on this issue? @palisadoes

**Comment by palisadoes** [comment]
@anand-aman you can verify the file sizes by running the countline.py][(https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countline.py) script.

**Comment by anand-aman** [comment]
> @anand-aman you can verify the file sizes by running the [countline.py](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/countline.py) script.

Ok will check it. Thanks

**Comment by palisadoes** [comment]
@anand-aman how's progress?

**Comment by anand-aman** [comment]
@palisadoes  I am working on it. While working on this issue I came across this bug #833.

**Comment by anand-aman** [comment]
@palisadoes 
Sir, I have reduced the size of all files (except **[queries_.dart](https://github.com/PalisadoesFoundation/talawa/blob/master/lib/services/queries_.dart)** which is 973 lines) and tested it.
Can we keep queries_.dart as an exception till the new UI is implemented?

Thank You
Aman Anand

**Comment by palisadoes** [comment]
@anand-aman yes that is OK
