### ISSUE TITLE
Add functionality to upload images and videos as posts.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#831]
**Is your feature request related to a problem? Please describe.**

While adding posts from the app, only the Title and Description of posts are taken as input, while a dummy image is added from the assets to give the feel of the post item (image). Videos and images should also be added as a part of posts. Queries and mutations need to be updated once the backend is configured for this functionality.

**Additional context**
Linked issues:
Talawa Api-[ issue #251](https://github.com/PalisadoesFoundation/talawa-api/issues/251)

**Comment by palisadoes** [comment]
@utkarshshendge I'm assigning this to you so we don't forget. It can be reassigned in future. This should not impact your current tasks.
