### ISSUE TITLE
[Security Bug] User can delete any event (Front-end)

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa#832]
**Describe the bug**
Normal user can delete events created by other user/admin

**To Reproduce**
1. Switch to Events Screen
2. Tap on Event (which is created by other user) 
3. Click on menu (3 dot) & Tap delete.

**Expected behavior**
User should not able to delete event created by others.

**Actual behavior**
User is able to delete others event

**Screenshots**

**Additional details**
Github Externship Appication No. : `20-05_Adi500_tfa_262`

Backed : Issue for API PalisadoesFoundation/talawa-api#261

**Comment by AdityaBirangal** [comment]
@palisadoes 
Can I work on this issue ?

**Comment by palisadoes** [comment]
This will need to be fixed in the API also. Sumitra should he able to guide you on how to do this

**Comment by AdityaBirangal** [comment]
Yes. I was thinking to add checks points in both the sides client & server

1) In app we can add check
if (creator == user) then call delete query
else Display 'You can't delete others event'

2) At Server side
if query is from creator then delete & else not

Is my approach right ? 

First part (Flutter) I can do 👍🏻
How we can do this in API ? @sumitra19jha

**Comment by sumitra19jha** [comment]
In general, checks like these are handled by the Backend rather than the frontend. You can use `(creator == user)` in the frontend but it is not considered as a correct (and secure) way to do it as the API still have the capability to delete event (Non-Creators can use Postman or other services).

![Untitled (1)](https://user-images.githubusercontent.com/35868598/119254781-f5ba7d80-bbd5-11eb-9f85-f8b6007831a7.png)

**Comment by sumitra19jha** [comment]
For the denied case, the backend throws error message which will be displayed by snackbar

**Comment by AdityaBirangal** [comment]
Okay. Got it.
I will Handle error message in Front end 👍🏻
Can you please do the backend part ?

**Comment by sumitra19jha** [comment]
@AdityaBirangal Sure, I can work on this. But if anyone else is interested, then they can take this issue forward (as currently, I already have few issues in my bucket). If no one volunteers, then surely I will create PR myself

**Comment by AdityaBirangal** [comment]
Okay. Thank You :)
Actually I know flutter well but not familiar with javascript yet. So, won't be able to do server side API part. :(

@palisadoes 
Can I post this issue in [talawa-api](https://github.com/PalisadoesFoundation/talawa-api) repo ? 
So, somebody who knows server side languages well can work on it.

& till then Can I handle this issue in flutter (front-end) ?

**Comment by palisadoes** [comment]
@AdityaBirangal go ahead. Link back to this issue and vice versa so both of you can track progress.
