### ISSUE TITLE
Deep Linking Service

### ISSUE THREAD

**Issue by Sagar2366** [PalisadoesFoundation/talawa#836]
Description : Deep Linking Service

**Describe the solution you'd like**
I would prefer to first implement app links as they provide the ground work for all the other kind of applinking opeing methods.
Find in details over [here](https://simonmarquis.github.io/Android-App-Linking/)

**Describe alternatives you've considered**
[Here](https://simonmarquis.github.io/Android-App-Linking/#market-scheme) is the alternative documentation that actually will help us as working for a non-profitable, hence firebase-dynamic links cannot be a options.

**Approach to be followed (optional)**
[here](https://pub.dev/packages/uni_links) is the package that would help us in implementing the feature

**Additional context**
This feature is going to be for the invitation links from the participants within the organization sent to a person currently not signed up to the application, reset password links that open inside the application.

Sub issue links -
- [x] Implement service class.
- [X] Configure for invitation links navigation.
- [ ] Configure for reset password links navigation.

**Comment by CyberWake** [comment]
@Sagar2366 sir please assign the issue. I have updated the issue based on the progress.

**Comment by CyberWake** [comment]
@palisadoes can be have this issue closed somehow this was not closed after GSoC.
