### ISSUE TITLE
Add Test Coverage Check for Pull Requests as a GitHub Action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#840]
**Is your feature request related to a problem? Please describe.**

1. The code base is insufficiently testable.
1. We need all code to be tested as part of each pull request.

**Describe the solution you'd like**

1. We need a way to add a GitHub action that automatically checks the codebase for the percentage coverage by tests.
1. The check should error out when the percentage is below a predefined level
1. The aim is that we’ll set increasingly higher percentage coverage for June, July, August and subsequent months until the codebase is 100% covered
1. We also want to ensure and verify that all tests in the repo are automatically run as part of each pull request as a GitHub action.

**Describe alternatives you've considered**

1. Analysis of the output of the `flutter test –coverage` command may be suitable for Dart.
1. [Dart Test coverage](https://pub.dev/packages/test_coverage)

**Approach to be followed (optional)**

This must be added as a [GitHub action in the repository’s issues.yml file](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) 

**Additional context**

None

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by muskan399** [comment]
I would like to work on this issue.

**Comment by muskan399** [comment]
Just wanted to be sure changes need to be done in pull-request.yml, not in issue.yml. Right?

**Comment by palisadoes** [comment]
Yes `pull-request.yml` Use python3 if you need to write a script to run multiple CLI commands to get this done. There are examples of what that code python should look like and a style guide README.md file there. The percentage compliance we desire should be a `--percent` flag in the script using `argparse` as seen in the existing scripts.

**Comment by muskan399** [comment]
I was thinking of using: https://github.com/marketplace/actions/report-lcov
As flutter test --coverage creates a lcov.info file.
Is this fine?

**Comment by palisadoes** [comment]
@muskan399 Yes this should be OK. It fails if the minimum isn't met.

**Comment by muskan399** [comment]
What should be the acceptable % for test coverage?

**Comment by palisadoes** [comment]
What is it at now? We should add 5% to the current value rounded to the nearest 5%.

**Comment by muskan399** [comment]
Currently, it is about 23%
@palisadoes 
![Screenshot (728)](https://user-images.githubusercontent.com/63671368/119481277-23d3c500-bd70-11eb-8981-ce7426057324.png)
