### ISSUE TITLE
[Bug] After joining new organization, still old organization's data is displayed.

### ISSUE THREAD

**Issue by afaanshariff** [PalisadoesFoundation/talawa#841]
**Describe the bug**
After joining a new organization, the newsfeed, events, and messages tabs should be updated and display joined organizations' newsfeed, events, and messages. But it is still showing old organizations events even after joining a new organization.

**To Reproduce**

1.Open profile page.
2.Click Join or Create New Organization option.
3.Join any organization from the list.
4.Now come back to events, messages, and the newsfeed tab. Old organization's data is displayed.

**Expected behavior**
Events, messages, and the newsfeed tab should be updated with the new organization's data.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.
Events, messages, and the newsfeed tab is displaying old organization's data.

**Screenshots**

**Additional details**
16-05_AFF633_tfa_262. 
I would like to work on this issue.

**Comment by ahluwaliatikant** [comment]
@afaanshariff  I think this is similar to issue #782.

**Comment by afaanshariff** [comment]
@ahluwaliatikant thanks for letting me know bro.
