### ISSUE TITLE
[Bug] Error on "Edit this event" button

### ISSUE THREAD

**Issue by anand-aman** [PalisadoesFoundation/talawa#844]
**Describe the bug**
The app crashes and shows the error page when the "Edit this event" button from the drop-down is tapped.

**To Reproduce**

1.  Go to the Events page (Center button of Bottom Navigation Bar)
2. Create an event if it's empty
3. Tap on the 3-dot button to open the drop-down
4. Click on the "Edit this event" button

**Expected behavior**
The event editing page should open up

**Actual behavior**
Throws an error and shows the error screen (screenshot)

**Screenshots**
<img src="https://i.ibb.co/1Zgwg0b/Edit-event-bug.png" height=40% width=40%>

**Additional details**
GitHub Externship candidate

**Comment by anand-aman** [comment]
@palisadoes Please assign this issue to me.

**Comment by palisadoes** [comment]
Make sure you include tests to verify the bug is fixed.

**Comment by anand-aman** [comment]
> Make sure you include tests to verify the bug is fixed.

Yes sure. Thanks.

**Comment by anand-aman** [comment]
Bug fixed and merged with PR #875
