### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vivekdusad** [PalisadoesFoundation/talawa#849]
no feedback is given to the user on pressing login and create account button when URL field is empty
we can show a snackbar to fill URL field first

or we can show error on text field 

A clear and concise description of approach to be followed.
either showing snackbar through scaffold messenger or showing validation error by using formKey

**Comment by vivekdusad** [comment]
@palisadoes can I work on this feature?

**Comment by rutvik11062000** [comment]
@vivekdusad Thank you for pointing that out, we are already discussing these changes They'll be covered in the GSOC redesign.
You can close this issue for now😊.

**Comment by rutvik11062000** [comment]
@vivekdusad Please join #talawa-design channel on slack.

**Comment by vivekdusad** [comment]
@rutvik11062000 ok
