### ISSUE TITLE
Create Slack/discord etc. Channels for the repository

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#85]
Slack/discord channels etc. (on other platforms) for this repo can be created where fellow contributors and mentors can discuss ideas and interact about anything related to the project.

**Comment by MohitPatni0731** [comment]
What will be the name of Discord Server or Slack Channel

**Comment by cyber-venom003** [comment]
@MohitPatni0731 I guess Palisadoes Foundation would work well.

**Comment by MohitPatni0731** [comment]
I have created the Discord Server . Let me know if you want to add any more channels.
Here is the link - https://discord.gg/6XjNFurP

**Comment by MohitPatni0731** [comment]
Hey
I am not able to join the mailing list I don't know why, So can you send the invite link in the mailing list.
https://discord.gg/JUgwyeqQ

**Comment by cyber-venom003** [comment]
> 
> 
> Hey
> I am not able to join the mailing list I don't know why, So can you send the invite link in the mailing list.

https://www.freelists.org/list/palisadoes

**Comment by cyber-venom003** [comment]
> 
> 
> After registration where I have to login?

Your email account which you have used during registration.

**Comment by jordanliu** [comment]
Hey @MohitPatni0731 @cyber-venom003 @Swayam221- we have a slack channel for Palisadoes, here's the invite link: https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-nk79xxlg-OxTdlrD7RLaswu8EO_Q5rg
