### ISSUE TITLE
The Talawa Mobile App Should Periodically Query the API for New Translation JSON Files

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#859]
**Is your feature request related to a problem? Please describe.**

1. The mobile app currently has a set of pre-defined JSON files used for translating menu items
1. The API will store: 
     1. Updated versions of existing files 
     1. New files for previously unsupported languages

**Describe the solution you'd like**

1. The mobile app must periodically query the API server for the latest JSON files. Possibly when the app is started.
2. Newly discovered language files must be added to the language selection menu for the mobile app.

**Describe alternatives you've considered**

None

**Approach to be followed (optional)**

See above

**Additional context**

1. Refer to the comments in this pull request for context https://github.com/PalisadoesFoundation/talawa-api/pull/281

**Comment by sumitra19jha** [comment]
@palisadoes Please assign this to me
