### ISSUE TITLE
Feature request --- Biometrics login

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa#877]
**Is your feature request related to a problem? Please describe.**
This is a new feature that we can add on talawa mobile application.

**Describe the solution you'd like**
For now a user needs to manually login to the app, but this feature should allow biometrics login (fingerprint recognition)

@palisadoes

**Comment by palisadoes** [comment]
Thanks @ssaumyaa7

1. How do you propose this would integrate with registration?
2. How would you add a fingerprint after regular registration with email?
3. How would you propose the login would work if registered with a finger print?
4. Fingerprints are [PII](https://en.wikipedia.org/wiki/Personal_data). How would you encrypt this data reliably within the application, when the data is transferred over networks and when it's stored in the API?

Please take a look at the [latest Talawa design video on YouTube](https://www.youtube.com/watch?v=TvukxeeGnf8). That will help you figure out where to put it in the design.
