### ISSUE TITLE
Test For pre-auth screens

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#882]
**Issue Description**
Writing test for pre-auth screens.
- [x] Test for splash screen
- [x] Test for select language screen
- [x] Test for set url screen
- [ ] Test for select organisation screen
- [ ] Test for signup details screen
- [x] Test for waiting screen
- [ ] Test for login screen
- [x] Test for forget password screen
- [x] Test for reset password screen

**Issue for**
Branch GSoC

**Issue Severity**
High

**Summary**
Adding test to the new pre-auth flow in the GSoC revamp for UI/UX.

**Comment by TiwariKin** [comment]
I would like to work on this issue .can you please assign this work  to me

**Comment by dhanagopu** [comment]
@TiwariKin  Sorry, this issue is a closed issue.
