### ISSUE TITLE
Missing Dependency lipsum in pubspec.yaml file.

### ISSUE THREAD

**Issue by Swayam221** [PalisadoesFoundation/talawa#90]
The file file views/pages/newsArticle.dart has imported lipsum as 
import 'package:lipsum/lipsum.dart' as lipsum;
but the dependency for the same is missing in pubspec.yaml

**Comment by Sagar2366** [comment]
Closing this issue as fixed in https://github.com/PalisadoesFoundation/talawa/pull/151
