### ISSUE TITLE
Volunteer and Attendee Check-ins

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa#901]
An organization may rely on volunteers to manage events. It would be good to have a simple system for users to be able to let the event coordinators know that they are on site and available.

The system could also be used to have attendees confirm that they are actually at the event. This would help with capacity planning.

**Comment by AdityaBirangal** [comment]
@xsh2047 assign this issue to me :)

**Comment by AdityaBirangal** [comment]
- Every user will have it’s own unique QR code. (that can be generated from existing ID)
- Event Admin/Creator will scan that QR code & see if he/she is registered or not & give entry(check in) at event.
- Admin will also have an option to manually check-in/check-out any attendee

**Comment by xsh2047** [comment]
Could you provide an option that isn't so manual for the Admin/Creator?

**Comment by AdityaBirangal** [comment]
I think if we given option to **self check in** then attendees can check-in themselves even they didn't attended event.
It would be good if check-in/identity verification done from Admin/Creator.

**Comment by AdityaBirangal** [comment]
I have one another idea
- Every Event will have one check in code/QR code.
- Creater/Admin will print it & display nearby entry gate.
- Attendees will scan it & will show success message to watchman & do self check-in

We can implement both 
- Admin/Creator side check-in (default)
- Self check-in (optional) (Admin will enable it if required)

**Comment by xsh2047** [comment]
Okay sounds good. No objections at all.

**Comment by palisadoes** [comment]
> I have one another idea
> 
> * Every Event will have one check in code/QR code.
> * Creater/Admin will print it & display nearby entry gate.
> * Attendees will scan it & will show success message to watchman & do self check-in
> 
> We can implement both
> 
> * Admin/Creator side check-in (default)
> * Self check-in (optional) (Admin will enable it if required)

@AdityaBirangal Consider the case of no printer availability first. The QR code should scannable on organizers' phones too. This would probably include anyone assigned a task in the event.

@xsh2047 What do you think?

**Comment by AdityaBirangal** [comment]
@palisadoes 
We are thinking to implementing to two ways
- Admin/Creator side check-in (default) 
- Self check-in (optional) (Admin will enable it if required)

Second way is optional
If organiser intervention is required then **First way** will be more secure or authentic  

although Event specific QR code would be available in Digital formate with organiser.

**Comment by AdityaBirangal** [comment]
Check-in Flow
![Talawa Event Check-ins-2](https://user-images.githubusercontent.com/43909309/123554709-e0b9a700-d79e-11eb-8f3c-5c877a57281e.png)

**Comment by palisadoes** [comment]
@adithyaakrishna 

1. With the second way, the scanned code should also be available on the organizers' phone, not just printed. 
1. Some types of events will have optional checkins, without prior registration. For example,
     1. parents visiting a gym with their children and want to leave their children in the care of a volunteer station in a game room.
     1. parents going to a place of worship for weekly prayers who want to leave young children in a religious classroom until prayers are complete

How would you approach the second optional checking scenario?

**Comment by AdityaBirangal** [comment]
1. Noted 👍🏻
2. I guess Second way won't be feasible in such cases

**Comment by palisadoes** [comment]
Try to make it flexible with mandatory and optional checkins as part of event creation. Child daycare for events is fairly common in community organizations.

**Comment by AdityaBirangal** [comment]
I will keep this in mind while designing. mandatory/optional

**Comment by AdityaBirangal** [comment]
I'm seeing future scope in First way. as it can we used to **verify identity** in future.
1. Volunteer at game station will scan parent's id code. Volunteer will make entry/note in app like 2 children or belonging's left there like bag kept in rack no 6 etc. & after parent come back he again Volunteer will scan parent's id code if match with previous one. Volunteer will make entry/note that children & bag from rack no 6 were returned 
2. This can be used to **avoid duplicacy** in some cases
-- let's say at TEDx Event some takeaway gift need to be distribute & only one unit per attendee.
-- volunteer will scan user's code & will give gift. if someone tries to take double he/she can be identify

**Comment by AdityaBirangal** [comment]
@palisadoes 
This check-in functionality also need to be develop in Talawa Admin Portal.
Can I create issue on that repo to keep Admin Portal team in loop ?

**Comment by palisadoes** [comment]
Sure. 

Keep the features simple. Just focus on people check in for now.

**Comment by AdityaBirangal** [comment]
Flow with dummy data
https://user-images.githubusercontent.com/43909309/125846677-cff2a845-2d3f-4bc1-88b2-5cbc44f8180b.mp4

**Comment by palisadoes** [comment]
Well done.

**Comment by Sagar2366** [comment]
Good work @AdityaBirangal
