### ISSUE TITLE
Add functionality to edit and delete an event .

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#906]
**Is your feature request related to a problem? Please describe.**
This is for the code rewrite. App with the new UI does not have the functionality to edit and delete the event. There should be functions for the same.

**Describe the solution you'd like**
In the old UI, the options to delete and edit the event were shown to all the users. But only the event creators are able to perform the actions. The option should be visible to event creators only.

**Comment by utkarshshendge** [comment]
@palisadoes  @DeltaHarbinger please assign this issue to me.

**Comment by DeltaHarbinger** [comment]
Hey Utkarsh, the task has been assigned to you
