### ISSUE TITLE
[Feature request] Allow administrators to moderate the newsfeed

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa#921]
Administrators should be able to:
    * Mute people
    * Enable/ disable commenting on posts
    * Enable/disable Thumbs up/down on posts

**Comment by cAmartya** [comment]
@palisadoes I want to work on this issue. Can you assign it to me?

**Comment by palisadoes** [comment]
We don't want any administration functionally in the mobile app. Closing
