### ISSUE TITLE
[Feature request] Allow members to create group chats

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa#922]
Any user should be able to create a group chat.

**Comment by smil-thakur** [comment]
hey I would love to work on this issue

**Comment by smil-thakur** [comment]
@rutvik11062000 @palisadoes how can i get started with this issue?

**Comment by palisadoes** [comment]
@smil-thakur join the slack channel for a faster responses. [slack.palisadoes.org](http://slack.palisadoes.org)

This is going to require both the regular and group chat features to be created and supported. Do you have ideas for an architecture we could use?
