### ISSUE TITLE
[Feature request] Event Grouping

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa#926]
**Problem**
All events in the organisation is currently displayed ungrouped : Ideally, the user should be able to toggle between their subscribed events or all events in the organization
**Goals**
Provide a more streamlined event display : This should allow modularity for feature development in event management
**Out of Scope**
The following are aspects of this feature which have been considered but are outside of the scope for the current project:

Tag events : This will eventually allow a user to subscribe to, toggle display of and get notifications for specific types of events
Toggle personal event view, co-ordinator, organization and all views on calendar : This will allow the user to switch between the different views based on their roles.

**Proposal/Solution (User Experience)**
From the home screen users should be presented with a button to view events.
This view defaults to display all events for which the user is subscribed.
The user should be presented with the option to toggle between viewing all events, only their subscribed events and only their coordinated events.

**Comment by utkarshshendge** [comment]
Hi, @xsh2047 created events, and registered events can be grouped as in #965.  So does it solve the problem as expected?
