### ISSUE TITLE
Bug : once code detected scanning should stop

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa#936]
**Describe the bug**
in set api url using QR code feature  
scanning is being done continuously after code detected 

**To Reproduce**
Steps to reproduce the behaviour:

Try to set api URL using QR code & see logs in terminal

**Expected behavior**
once code detected scanning should stop

**Actual behavior**
scanning is being done continuously after code detected

**Screenshots**

**Additional details**
This can be easily fixed by doing minor modifications in set_url_view_model.dart

**Comment by CyberWake** [comment]
Can you exactly specify the logs.
Because the qr scan will only we considered successful if it's a valid qr in terms of talawa.

**Comment by CyberWake** [comment]
Until the same is achieved it will continue to scan once a talawa generated qr is scanned it will automatically stop.

**Comment by Sagar2366** [comment]
@AdityaBirangal  please add video reproducing the issue.

**Comment by AdityaBirangal** [comment]
@CyberWake Got it 
Accutly I scanned QR of url (our heroku api).
Can you share formate of valid QR code or demo code ?
It keeps scanning it & logs are being generated in terminal.
within fraction on time it scan same code multiple times.

This can be fixed using ```controller.scannedDataStream.first``` instead of just stream

It would be good if we add pop-up 'you scan wrong code' if user scan invalid code.
Whats your opinion @CyberWake  ?

**Comment by CyberWake** [comment]
You need to scan a qr from invite feature exclusive to talawa app from the one of the user who is already logged in and has access to dashboard

**Comment by CyberWake** [comment]
Logs printed are from the package itself and talking of the poping of the context it does that If you scan a qr from the way I told. QR contains data other than url of the server.

**Comment by AdityaBirangal** [comment]
Everything works fine if valid code is provided 👍🏻

**Comment by AdityaBirangal** [comment]
Can we add pop-up message for invalid code too ?

**Comment by CyberWake** [comment]
> Can we add pop-up message for invalid code too ?

I Will have to look in to that your concern seems to be obvious.
