### ISSUE TITLE
Everyone please maintain contributing etiquette.

### ISSUE THREAD

**Issue by sudo-vergil** [PalisadoesFoundation/talawa#94]
#### Support each other, contribution taken as competition will not do any benefit to the organization as well as to contributors.

I can see that there are 2-3 similar pull requests, it makes the task of merging difficult. So I request you to please close the PR is something similar exists. 
For instance,
issue #77 and PR #78 (issuer of #77 was requesting to be assigned)
PR  #87 and PR #88 (Similarity in flutter logo, #87 was already present)

Happy Coding!!

**Comment by utkarshshendge** [comment]
Thanks for mentioning #87 @sudo-vergil .

**Comment by sumitra19jha** [comment]
Sure @sudo-vergil. Will take care of that, from next time. I was more focused onDaySelected function in the PR but i will close this PR for now.
