### ISSUE TITLE
Add functionality to search Event 

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#942]
**Is your feature request related to a problem? Please describe.**
Currently, the search button icon is not functional, we should be able to use it.

**Describe the solution you'd like**
Add functionality to search Event.

**Describe alternatives you've considered**

**Additional context**
`search delegate` will be used for the implementation

**Comment by palisadoes** [comment]
@ utkarshshendge  should we assign this to you?

**Comment by utkarshshendge** [comment]
@palisadoes yes please assign it to me.
