### ISSUE TITLE
PlatformException (camera_access_denied) 

### ISSUE THREAD

**Issue by tosif91** [PalisadoesFoundation/talawa#950]
**Describe the bug**
When user deny the  camera permission it will get permanently denied, after if user try to pick image then their is no response from the app side.

**To Reproduce**

1. Install App
2. Navigate To Profile Screen
3. Update profile pic 
4. Deny the runtime permission 
5. Once its get permanently denied retry to update profile pic
6. No response from the application

**Expected behavior**
Once the permission is permanently denied , alert dialog should raise with the message for permission and  
option to visit app setting to give permission .

**Actual behavior**
When the permission denied exception is thrown , no action is taken to alert the user

**Screenshots**
NO

**Additional details**
NO

**Comment by tosif91** [comment]
Please assign this issue to me

**Comment by palisadoes** [comment]
@tosif91  Are you still working on this?

**Comment by tosif91** [comment]
Am not able to give time in it ,  please assign it to someone else .
