### ISSUE TITLE
Introduction Slides

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa#966]
**Is your feature request related to a problem? Please describe.**
Introduction slides can be added at startup for first-time users to
provide a quick introduction of the app & its features.

**Describe the solution you'd like**
We can add 3-4 screens to introduce app &  it's feature. with some text & graphics 
also will provide skip option to directly jump to login page.

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
1. Design UI & graphics images 
2. Code UI in flutter 

**Additional context**
GitHub Externship

**Comment by AdityaBirangal** [comment]
@palisadoes Please assign me.

**Comment by CyberWake** [comment]
this feature exists on default branch, need to have some more enhancements as a room for upgrade is still visible and is being worked upon considering the global standards to keep it minimilistic.

**Comment by palisadoes** [comment]
@AdityaBirangal Please do a mock up in figma before you start. The screens will need to support multi-lingual capabilities of the app.

**Comment by AdityaBirangal** [comment]
This feature is not yet implemented 
@CyberWake Are you taking about in app guide ? (which introduce functionality one by one)
I was thinking to implement small intro at starting to give glimpses of our app

example : 
<img src="https://user-images.githubusercontent.com/43909309/130500930-b6759994-38b4-4f29-af03-ad2894ae7492.gif" alt="example" width="360"/>


@palisadoes okay sir I will keep in mind multi-lingual thing
