### ISSUE TITLE
GitHub Actions Failing 

### ISSUE THREAD

**Issue by DeltaHarbinger** [PalisadoesFoundation/talawa#977]
**Describe the bug**
GitHub Action pipelines are currently failing during the flutter analysis stage

**To Reproduce**

1. Create a PR
2. Wait for the pipeline to be executed
3. See that the pipeline has failed due to an issue in the flutter analysis section
    a. Flutter analysis should not fail as a result of the GitHub pipeline being faulty. It should fail in the event of there being an error on the code

**Expected behavior**
Flutter analyze should fail only in cases of there being an issue with the code

**Actual behavior**
Flutter analysis is failing through no fault of the PR.

**Comment by CyberWake** [comment]
@DeltaHarbinger sir this is already fixed in the PR #972.

**Comment by DeltaHarbinger** [comment]
Thanks @CyberWake, I will close this
