### ISSUE TITLE
[Bug report] Renderflex overflow in custom_drawer

### ISSUE THREAD

**Issue by bayush-9** [PalisadoesFoundation/talawa#979]
Issue Description:  Renderflex overflow in custom_drawer at bottom
Observed behaviour: Option to exit or join new organization is inaccessible
Expected behaviour: It should be accessible to the user.
Steps to fix issue: Rearrange the spacing between sister and parent widgets

I am willing to work on this issue!!

![Screenshot_16302605782](https://user-images.githubusercontent.com/81760629/131260949-c0c1035f-a40c-490d-a7c9-77e704c744cf.png)

**Comment by bayush-9** [comment]
@palisadoes Please assign me this issue!

**Comment by CyberWake** [comment]
@bayush-9 you may start working on this I'll make sure this is assigned to you.
p.s. make sure this is fixed with dynamic sizing used for the above listview in the drawer over the last to options at the buttom.

**Comment by bayush-9** [comment]
Okay @CyberWake . I'll keep it in mind.

**Comment by bayush-9** [comment]
@CyberWake The issue is fixed. Have a look in pull request! #980
