### ISSUE TITLE
Insecure HTTP not allowed by App

### ISSUE THREAD

**Issue by infiniteoverflow** [PalisadoesFoundation/talawa#98]
Since we are using the URL: http://calico.palisadoes.org/talawa/, which uses an HTTP Connection, by default the app prevents using its services.

It returns an exception : 
`ClientException: Unhandled Failure Bad state: Insecure HTTP is not allowed by platform: http://calico.palisadoes.org/talawa/`

I have a workaround for this using which we can ignore this error and use its services until we migrate the API to HTTPS.

@jordanliu Kindly express your views on this. Thank you.

**Comment by yasharth291** [comment]
@jordanliu  may be i can help you with this by making a ssl certificate by openssl and converting the http server to https server

**Comment by jordanliu** [comment]
@infiniteoverflow @yasharth291 we're working on this, the ssl cert should be up by tonight
