### ISSUE TITLE
Feature request: Private Events

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#983]
**Is your feature request related to a problem? Please describe.**
The participants in all events are publicly visible to everyone. There needs to be options for more privacy.

**Describe the solution you'd like**
1. The ability to make events private where only participants can see who is attending
1. The optional ability to make private events invisible to persons not attending

**Describe alternatives you've considered**
N/A

**Approach to be followed (optional)**
N/A

**Additional context**
Tied to Issue https://github.com/PalisadoesFoundation/talawa-api/issues/354

**Comment by akshatgarg12** [comment]
@palisadoes There exists a property **isPublic** in event schema, should we use that to change the behaviour of the API.

**Comment by palisadoes** [comment]
> @palisadoes There exists a property **isPublic** in event schema, should we use that to change the behaviour of the API.

It should be. Please check with @sumitra19jha, @CyberWake and/or @utkarshshendge to be certain. They are all on our slack channel.
