### ISSUE TITLE
[Feature] User is unable to exit an organisation from drawer.

### ISSUE THREAD

**Issue by bayush-9** [PalisadoesFoundation/talawa#984]
**Describe the bug**
User is unable to exit an organization from drawer.

**To Reproduce**
Visit the drawer in the app.

**Expected behavior**
Organization should get removed from the list and user should exit from same.

**Actual behavior**
The exit org. button is inactive.

**Additional details**
An alert dialogue box could be added before exit to improve UX.

I am willing to work on this issue with discussing features of API for proper functioning with the heads!

**Comment by CyberWake** [comment]
@bayush-9 please do look in the `talawa-api` if this is working properly last time we checked it was not working in a desired manner and we encountered some errors from the server.

**Comment by bayush-9** [comment]
ohh okay!! I'll look into it. I hope I can open a discussion for this there.

**Comment by bayush-9** [comment]
@CyberWake I think there is work going on backend for this as this will need lot of interactions with the whole data. Hence I have just added an alert dialog box for now, which pops up before exiting the organization. The logic and backend integrations can't be added as of know.

**Comment by bayush-9** [comment]
The PR workflow issues are in other files that I haven't touched. I think it is checking the whole code base for the pr. All of them seem depreciation warnings.
