### ISSUE TITLE
Talawa App must work with older & newer versions of the API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#987]
**Is your feature request related to a problem? Please describe.**

1. It is very likely that Talawa administrators will not upgrade their servers to match the latest version of the mobile app that is downloadable from an app store or the GitHub repository. The users' mobile app will need to adapt and function appropriately when communicating with a version of the API that may not support all the features the latest version of the mobile app expects.
2. It is also likely that the mobile app installed on another user's phone may be older than the API it is communicating with. The user's mobile app will need to adapt and function appropriately. In this case the user should also be prompted to upgrade their mobile app.

**Describe the solution you'd like**

We need a way for:

1. The Talawa mobile app to disable features not supported by the API it is communicating with.
2. The Talawa mobile app to ignore extra data that may be sent to it by a newer version of the API.

**Describe alternatives you've considered**

This needs to be researched. We are looking for suggestions.

**Approach to be followed (optional)**

N/A

**Additional context**

None

**Comment by palisadoes** [comment]
@xsh2047 Here is the starter issue we discussed.

**Comment by jassi-singh** [comment]
Hi @palisadoes I am interested in working on this issue, can you provide me more info on the issue as I am new to talwa.

**Comment by palisadoes** [comment]
@ jassi-singh  I've updated the explanation of the issue to make it clearer. Please review and let me know what further clarity you would require.
