### ISSUE TITLE
Code Documentation for Chat, Organisation, Events and User #SWEN3130

### ISSUE THREAD

**Issue by MariaMckenzie** [PalisadoesFoundation/talawa#989]
Expected Documentation: Adding code documentation to the certain parts of the App (Chat, Events, Organisation and User)
Current Documentation: Lack of documentation within the code of the app.
Possible Solution: Add documentation to code to enhance readability.
Steps to Reproduce: N/A
Context (Environment): The development of code
Detailed Description:   N/A
Possible Implementation: N/A

**Comment by Mich-moon** [comment]
I would like to be assigned to this issue.
