### ISSUE TITLE
The UI of the app is great but needs some changes

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#99]
will you please consider me to so this and contribute for the talawa projects. i will change some minor differences in the app UI

**Comment by yasharth291** [comment]
i want to eagerly work on this

**Comment by sumitra19jha** [comment]
Hi @yasharth291
I agree with you that the app Ui can be optimised further. Even I am also very excited in optimising the app. We can enhance both user interface and user experience. If it's ok with you, we can discuss here. Do let me know!!!

**Comment by cyber-venom003** [comment]
Hi @sumitra19jha and @yasharth291 . I'm also experienced in UI/UX optimisation, if it is okay, we can discuss this collaboratively over slack channels.

**Comment by yasharth291** [comment]
yeah we can but there is no response from the owners

**Comment by sumitra19jha** [comment]
> Hi @sumitra19jha and @yasharth291 . I'm also experienced in UI/UX optimisation, if it is okay, we can discuss this collaboratively over slack channels.

Hi, thats great.

As others members are not currently active on slack channel, i think it will be much better if we can discuss it here. Maybe some of the other fellow contributes mite also be interested in it and can put their thoughts here.

One of the thing that can be change is Create account and login button. I think that either we should make them invisible or use light colour button while the input url has not been provided.

**Comment by sumitra19jha** [comment]
> yeah we can but there is no response from the owners

We can come up with a solution and then can ask them to put their suggestions.

**Comment by yasharth291** [comment]
but the project is not working because some files are missing

**Comment by sumitra19jha** [comment]
@yasharth291 
You can start working on the optimisation of login Page.
You might be facing issue with the opening of app because of the flutter logo issue.
You can refer to the PR of issue #86 to fix this

**Comment by yasharth291** [comment]
ok i will see it

**Comment by yasharth291** [comment]
we should connect on some of the platform

**Comment by cyber-venom003** [comment]
> 
> 
> we should connect on some of the platform

I guess, that discord server made by a contributor would work well?? Or we can connect together on a Slack group in same server.

**Comment by yasharth291** [comment]
yeah lets connect on slack

**Comment by jordanliu** [comment]
@yasharth291 @sumitra19jha @cyber-venom003 For all those who are interested, please join our Slack - https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-nk79xxlg-OxTdlrD7RLaswu8EO_Q5rg and join the #talawa-design channel to contribute to the UI/UX of the app
