### ISSUE TITLE
Assignment Error in User Model (user_info.dart)

### ISSUE THREAD

**Issue by MariaMckenzie** [PalisadoesFoundation/talawa#995]
**Expected Documentation:** Correct assignment of variables and attributes.
![image](https://user-images.githubusercontent.com/68311077/138479406-3cacc93d-8ae4-4940-8d2c-7d79eb08cd63.png)
**Current Documentation:** Error in variable assignments. (`details.firstname` is assigned to `this.lastName`, `this.email` and `this.image`)
![image](https://user-images.githubusercontent.com/68311077/138479218-cbe2803d-8aaa-4986-bc4b-dcd303a71c52.png)
**Possible Solution:** Change the variables being assigned. 
**Steps to Reproduce:** N/A
**Context (Environment):** The development of code  
**Detailed Description:** N/A
**Possible Implementation:** N/A

**Comment by M-A-D-A-R-A** [comment]
Is this issue solved? if not i would like to work on it. thanks!

**Comment by palisadoes** [comment]
@ayush-mahawar26  Are you still working on this?

**Comment by ayush-mahawar26** [comment]
@palisadoes  I resolved this issue , waiting for @utkarshshendge  to review it , BTW it is reviewed by CyberWake and he approoved it

**Comment by palisadoes** [comment]
@ayush-mahawar26 Is there a pull request for this? Please submit one if not.

**Comment by ayush-mahawar26** [comment]
@palisadoes  Yes , submittes the pull request
